### ISSUE TITLE
`NumpyArray::getitem_next_jagged` is undefined for `ndim == 2`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1026]
### Version of Awkward Array

1.4.0

### Description and code to reproduce

I think we should support this given that it works if the `NumpyArray` is converted into a `RegularArray`:
```python3
array = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.r_[0, 4, 4, 6]),
        ak.layout.NumpyArray(np.arange(4 * 6).reshape(6, 4)),
    )
)
ix = ak.Array([
    [[0], [1], [2], [3]],
    [],
    [[3], [2]]
])
```
This fails:
```python3
array[ix]
```

This succeeds:
```python3
ak.to_regular(array, axis=-1)[ix]
```

I would expect the result of jagged indexing into a `NumpyArray` to produce a jagged result (i.e. behave as it currently does for `RegularArray`).

The simplest solution would be to re-use the `RegularArray` code here, i.e. `toRegularArray()->getitem_XXX` but I don't know what the protocol on this is vs doing less work by implementing a solution specifically for NumpyArrays. I suspect here it's not unreasonable because the conversion to `RegularArray` is cheap (?)

**Comment by jpivarski** [comment]
I had thought this was related to #1022, but it's not.

Yes, we can do `toRegularArray` for this (that's what PR #1029 does), as `toRegularArray` is pretty cheap. If the NumpyArray is not contiguous, it will need to be rewritten, but otherwise it will not. ListArrays have been converted `toListOffsetArray64` (more expensive) with less motivation!
