### ISSUE TITLE
Extend the array-class syntax in `ak.behavior`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1038]
### Description of new feature

As discussed on Gitter, it may be useful for some people to be able to specify lower bounds on the dimensionality required for array classes to be chosen by their `behavior` name. 

# Syntax
## Option A
The `"+"` token was mused to reflect "one dimension":

* `ak.behavior["+", "point"]` would denote a one dimensional array of points.
* `ak.behavior["*", "point"]` would denote a one-plus dimensional array of points.
* `ak.behavior["*", "+", "point"]` would denote a two-plus dimensional array of points.

## Option B
A cleaner approach might instead use only `"*"`, and would allow users only to specify `ndim >= k` instead of `ndim == k`. This would look like:

* `ak.behavior["*", "point"]` would denote a one-plus dimensional array of points.
* `ak.behavior["*", "*", "point"]` would denote a two-plus dimensional array of points.

## Option C
Seeing as we already use `"."` to mean a single dimension array, the same behaviour in A could be implemented with `"."`:

* `ak.behavior[".", "point"]` would denote a one dimensional array of points.
* `ak.behavior["*", "point"]` would denote a one-plus dimensional array of points.
* `ak.behavior["*", ".", "point"]` would denote a two-plus dimensional array of points.

# Observations
One problem that I can see with option A is that it uses regular expressions qualifiers, but whose behaviours are inverted (`"*"` is 0+ in regex, and `"+"` is 1+).

**Comment by agoose77** [comment]
I took a brief look at the `arrayclass` function to gauge what would need to be done here. It looks like this might require a little bit of thought, because we currently do not seem to expose a means to determine the depth at which a `__record__` parameter was found. For this reason, it might be prudent to wait until v2 is done.

**Comment by jpivarski** [comment]
I guess it's not quite like regular expressions.

Since `"."` already means "one level" and `"*"` means "any number of levels," how about

   * `".", "."` for "two levels"
   * `".", ".", "."` for "three levels"
   * `"*", "."` for "two or more levels"
   * `"*", ".", "."` for "three or more levels"

? I don't think it would be necessary to introduce a number here, to simplify the problem of asking for "57 levels," since that kind of thing is very unlikely. I can't imagine requirements needing to specify anything bigger than 3.

**Comment by agoose77** [comment]
> I guess it's not quite like regular expressions.

@jpivarski yes, I don't mean that we should copy regex, rather that if we have similar syntax, it's going to confuse "some" people (myself included ;))

I was originally in favour of using `.` to mean additional levels, so that suggestion here has a +1 from me. I thought you disproved of this syntax, but perhaps I misunderstood you. I'll add the suggestion to the issue description.

>  I don't think it would be necessary to introduce a number here

Anything with >5 dimensions is probably getting silly!

**Comment by agoose77** [comment]
I'm not working on this at the moment, but I had some more thoughts syntax-wise: why not repurpose `:` and `...`? They already have meaning to developers that is compatible:

* `:, :` for "two levels"
* `:, :, :` for "three levels"
* `..., :, :` for "two or more levels"
* `..., :, :, :` for "three or more levels"

The only configurations that don't make sense hold for the `"."`, `"*"` syntax:

- `:, ...` vs `".", "*"`
- `:, ..., :` vs `".", "*", "."`

I think we could decide to raise an Exception for any non-standard usage (i.e. `...` is always the left-most token, or missing).

~~The benefit of this is that it would also not break compatibility, whereas the `"*"` syntax necessarily changes `"."` from "arrays to "array". We could introduce it through a deprecation cycle, maintaining both for a small period of time.~~

**Comment by jpivarski** [comment]
That's fine, although `"."` and `"*"` were an attempt to use existing syntax—from regular expressions. (By extension, `"+"` would mean "at least one.) I was thinking about regular expressions because this is a kind of expression-match.

`":"` and `"..."` also make sense, and seem more relevant because these are arrays (though `ak.behavior` isn't slicing an array... but I see the connection).

Even though we're allowed to break API from v1 to v2, replacing `"."` → `":"` and `"*"` → `"..."` would be a pretty subtle change, since missing behaviors (because something that used to match no longer matches) are not always caught, or are caught much later than the assignment. If we're going to introduce `":"` and `"..."`, it would have to be in addition to `"."` and `"*"`, and having too many synonyms becomes an organizational problem.

Although I _like_ the choice of `":"` and `"..."`, it may be too late to switch to them, primarily because I don't see the urgency outweighing the problems that a switch would cause. (Am I missing something? Is this anything more than a different choice of symbols, which would be used the same way with `":", ":", ":"` meaning 3 levels just like `".", ".", "."`?)

**Comment by agoose77** [comment]
> were an attempt to use existing syntax—from regular expression
Yes, I should have touched on this (thanks for the reminder). 

My thought here is that we're talking about dimensions, so let's use the same syntax that we do for slicing. This uses the actual sentinel objects / slicing mechanism, rather than strings, i.e.
```python
ak.behavior[:, :, "Vector3D"] = Vector3DArray
ak.behavior[..., "Vector3D"] = Vector3DArray
```

> though ak.behavior isn't slicing an array

Absolutely, we're in syntactic sugar territory now!

> Am I missing something? Is this anything more than a different choice of symbols

Er, actually _I'm_ missing something here - I managed to confuse `"."` and `"*"`. I've struck it through!

**Comment by jpivarski** [comment]
We are talking about dimensions, and in retrospect, I should have thought of `":"` and `"..."`, but I didn't. (I just wasn't thinking about it that way!)

**Comment by jpivarski** [comment]
I don't think anyone has ever needed this. Let's just close it.
