### ISSUE TITLE
Empty slicing behaviour before and after `ak.to_numpy` is different

### ISSUE THREAD

**Issue by pfackeldey** [scikit-hep/awkward#1046]
### Version of Awkward Array

'1.4.0'

### Description and code to reproduce

Dear awkward developers,

we noticed an unexpected behaviour in fancy indexing empty dimensions before and after `ak.to_numpy` call.
I think the following snippet makes it a bit more clear:

```python
# before
ak.to_numpy(ak.Array([[1], [2]])[[]])
>> array([], shape=(0, 0), dtype=int64)

# after
ak.to_numpy(ak.Array([[1], [2]]))[[]]
>> array([], shape=(0, 1), dtype=int64) # <-- this is what we expected
```
The shape discrepancy is unexpected for us. 
What is your take, is this behaviour intended?

Best, Peter

**Comment by jpivarski** [comment]
It's because `ak.Array([[1], [2]])` is an array of variable-length lists and `np.array([[1], [2]])` is an array of fixed-length lists:

```python
>>> ak.Array([[1], [2]])                   # note the "var"
<Array [[1], [2]] type='2 * var * int64'>
>>> 
>>> ak.Array(np.array([[1], [2]]))         # now it's regular
<Array [[1], [2]] type='2 * 1 * int64'>
```

The empty slice maintains var on the var-type array and the regular length of the regular array:

```python
>>> ak.Array([[1], [2]])[[]]
<Array [] type='0 * var * int64'>
>>> 
>>> ak.Array(np.array([[1], [2]]))[[]]
<Array [] type='0 * 1 * int64'>
```

And this is preserved when converting to NumPy. Var-type arrays can only be converted to NumPy if they _happen to be regular in the instance you're trying to convert_. (Regular arrays can always be converted to NumPy.) The lengths of the inner dimensions of a var-type array are determined from what those list lengths happen to be in the particular instance. Here, they happen to be zero because they're empty.

```python
>>> ak.to_numpy(ak.Array([[1], [2]])[[]])
array([], shape=(0, 0), dtype=int64)
>>> 
>>> ak.to_numpy(ak.Array(np.array([[1], [2]]))[[]])
array([], shape=(0, 1), dtype=int64)
```

It's unfortunate that we have to have this subtlety—that you, as user, have to be aware of the distinction between var-type and regular-type nested lists, but this is because only the regular-type can perfectly correspond to NumPy's behavior; var-type is new territory.

~~Let me know if I should reopen this, but I think it answers your question.~~ Actually, no, I'm going to convert it to a Q&A discussion so that it remains visible. Others might encounter this, and I don't want to bury it by making it a closed issue.
