### ISSUE TITLE
Assigning virtual arrays as a field to an array materializes the virtual arrays

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#1052]
### Version of Awkward Array

1.4.0 (and git main) 

### Description and code to reproduce

When inserting a virtual array into an array created with `ak.from_buffers` with `lazy=True`, the generator function of the virtual array gets called right away. This however happens only for the first virtual array being inserted. I would expect the generator function not being called at all, as the virtual arrays content is not required at this point.
Code example:
```python
import numpy as np
import awkward as ak


def some_function1(length):
    print("called1")
    return np.ones(length)


def some_function2(length):
    print("called2")
    return np.ones(length)


array = ak.from_buffers(*ak.to_buffers(ak.Array({"something": [1,2,3]})), lazy=True)
array["virtual"] = ak.virtual(some_function1, (len(array),), length=len(array))
array["virtual"] = ak.virtual(some_function2, (len(array),), length=len(array))

```
This will print `called1`, even though it shouldn't. If `lazy=False` in the `ak.from_buffers` call, it doesn't print anything, like it should.

In the same context i noticed a continuous increase in memory usage, in case the array is also used as part of the `args` parameter. To me this looks a lot like something isn't being freed. Code example:
```python
import os
import psutil
import gc
import numpy as np
import awkward as ak


def some_function(length, something):
    print("called")
    return np.ones(length)


while True:
    gc.collect()
    big = ak.Array({"something": np.random.rand(100000000)})
    array = ak.from_buffers(*ak.to_buffers(big), lazy=True)
    array["virtual"] = ak.virtual(some_function, (len(array), array), length=len(array))
    array["virtual"] = ak.virtual(some_function, (len(array), array), length=len(array))
    print(psutil.Process(os.getpid()).memory_info().rss)
```
The resident set size, which is printed, will continue to increase with every loop. This does not happen (there is almost no change to the number) if `array["virtual"]` is only set once. It also does not happen if `big` instead of `array` is used in the `args` parameter.

**Comment by agoose77** [comment]
RE the lazy aspect to this question, I assume what's happening here is that `ak.with_field` is materialising the virtual array when broadcasting.

**Comment by jpivarski** [comment]
> RE the lazy aspect to this question, I assume what's happening here is that `ak.with_field` is materialising the virtual array when broadcasting.

That's right.

Assigning an array `x` as a new field of another array `y` necessarily evaluates any generators in `x` and `y` because it needs to broadcast them to see how to restructure `x` to fit `y`. That's so that something like

```python
array_of_3vectors["mass"] = 125.0
```

can set a `"mass"` field with the same value in all records in `array_of_3vectors`, regardless of whether `array_of_3vectors` is an array of records, an array of lists of records, or something deeper. Similarly,

```python
array_of_lists_of_lists["new_field"] = array_of_lists
```

will broadcast each element from the shallower `array_of_lists` into the corresponding `array_of_lists_of_lists`.

This is a fundamental problem with our design of lazy arrays: the idea is that it will be materialized when needed, but it can be hard for users to guess when it's needed. (Maybe you didn't know that field-assignment broadcasts, for instance.) There's a long history of bug-fixes for lazy arrays being materialized "too early," but without a clear definition of when _is_ "too early." In some cases, it was obvious: some code was just checking something that could be determined from type alone, such as the value of the `"__record__"` parameter. Materializing a VirtualArray node for that would be wrong, because the `"__record__"` parameter is expressed in the VirtualArray's Form, and we can search down that tree instead. Other cases have been more borderline: should a slice materialize a VirtualArray? It's a calculation on an array, but most people didn't expect it to materialize an array, especially when the slice was just picking out one field (e.g. `my_array.field`). Now a slice of a VirtualArray creates a new VirtualArray that would cascade through evaluating the slice, then evaluating the original array.

But for broadcasting, we can't delay that. To delay a calculation, we have to be able to say what its Form is going to be without actually performing the calculation. There are even some slices in which that's not possible: the Form of the output depends on the specific values of the array. (That is, if some lists are empty or well-aligned or something, the output would have a different Form than if they weren't, and in order to make a new VirtualArray, we have to predict the Form it would have upon evaluation.)

Dask solves the lazy array problem differently, and that's where we're directing new effort on this:

![](https://raw.githubusercontent.com/jpivarski-talks/2021-05-21-dasksummit-awkward-collection/main/degrees-of-transparency-2.svg)

One difference is that a Dask collection has a `.compute()` method, so you get to say when it's the right time to start a calculation. As a consequence, the Dask DAG can be a different thing from an ordinary array (i.e. `.compute()` returns a different type, mapping DAG → in-memory array), so it doesn't need to support all the same operations that an ordinary array supports. Perhaps there would be no way to ask a DAG what the array type will be without computing it, for instance. But this would relax constraints on what can go into the DAG so that any operation can be lazy.

Development of an Awkward-Dask collection is starting next month.

-----------------

As for solving your problem: are you trying to make a record array with virtual fields? Instead of assigning new fields into an existing object, you could create the array all at once by calling the `ak.Array` constructor:

```python
array = ak.Array({"field1": ak.virtual(...), "field2": ak.virtual(...)})
```

or `ak.zip`, limited to the non-virtual, list-like dimensions:

```python
array = ak.zip({"field1": ak.virtual(...), "field2": ak.virtual(...)}, depth_limit=1)
```

If the fields were _lists of virtual_ data (i.e. the list offsets are not virtual, but the contents are), then you could use `depth_limit=2` to zip those lists together without materializing the virtual data. `depth_limit=1` is equivalent to the `ak.Array` constructor.
