### ISSUE TITLE
Building arrays out of lists of arrays doesn't work

### ISSUE THREAD

**Issue by veprbl** [scikit-hep/awkward#1060]
### Version of Awkward Array

1.4.0

### Description and code to reproduce

This works:
```python
>>> import awkward; awkward.Array({"record": awkward.Array({"column": [1]})})
<Array [{record: {column: 1}}] type='1 * {"record": {"column": int64}}'>
```

This doesn't:
```python
>>> import awkward; awkward.Array([awkward.Array({"column": [1]})])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/wi2ck5llz7lv07sir0a9xia1irc974pj-python3.9-awkward-1.4.0/lib/python3.9/site-packages/awkward/highlevel.py", line 254, in __init__
    layout = ak.operations.convert.from_iter(
  File "/nix/store/wi2ck5llz7lv07sir0a9xia1irc974pj-python3.9-awkward-1.4.0/lib/python3.9/site-packages/awkward/operations/convert.py", line 886, in from_iter
    out.fromiter(x)
  File "/nix/store/wi2ck5llz7lv07sir0a9xia1irc974pj-python3.9-awkward-1.4.0/lib/python3.9/site-packages/awkward/highlevel.py", line 1763, in __getitem__
    tmp = ak._util.wrap(self.layout[where], self._behavior)
ValueError: scalar Record can only be sliced by field name (string); try "0"

(https://github.com/scikit-hep/awkward-1.0/blob/1.4.0/src/libawkward/array/Record.cpp#L198)
```

Expected result:
```
<Array [{column: [1]}] type='1 * {"column": var * int64}'>
```

**Comment by veprbl** [comment]
Probably it would be more correct to compare:
```python
awkward.Array({"record": awkward.Record({"column": [1]})})
```
and
```python
awkward.Array([awkward.Record({"column": [1]})])
```
both of which fail in the same way

**Comment by jpivarski** [comment]
This one isn't valid because passing a dict to an `ak.Array` constructor takes each key as a column name, and therefore each value should be an iterable. A record is not iterable.

```python
awkward.Array({"record": awkward.Record({"column": [1]})})
```

Perhaps this one ought to work:

```python
awkward.Array([awkward.Record({"column": [1]})])
```

However, to get to the array you're trying to make, all your have to do is this:

```python
ak.Array([{"column": [1]}])
```

`ak.Array` and `ak.Record` objects are only recognized in `ak.Array` and `ak.Record` constructors if they're the only object in the constructor, and then all it does is unwrap the old one and wrap it in a new `ak.Array` or `ak.Record`. if they're nested inside a list or dict, they're tested as generic iterables (`ak.Array`) or mappings (`ak.Record`).

I'll look into these when I get to a computer. They might need better error messages (catching invalid cases earlier to provide better feedback), and your second example looks like it should work, though there's no advantage to writing it like that. (For instance, there's no performance advantage to iterating over a list of `ak.Record` than a list of dicts. In fact, the latter is significantly faster because it's a Python built-in.)

**Comment by veprbl** [comment]
Thank you for taking a look. The examples I provide are only MRE's, I'm not looking to define the data in my code, but to build an array from existing awkward arrays. Right now I had to settle for calling `.tolist()` to be able to build the combined array.

If I'm not mistaken this issue discusses behaviour of `awkward.from_iter`, and it already appears to have "non-iter" handling of dicts (remember that iterating over a dict doesn't give the full items: `list(dict(a=1)) == ['a']`). It would make sense that it could also properly treat `awkward.Record`'s. This just from the point of API, hopefully inside it could do something more optimal with the existing arrays.

**Comment by jpivarski** [comment]
`ak.from_iter` is, roughly speaking, the opposite of `ak.to_list` in that it converts between Awkward Array data and Python data. Just the fact that it involves Python data puts both of these functions in the "inefficient" category; performance isn't going to be better if `ak.from_iter` encounters an `ak.Record` rather than a dict.

Outside of the MRE we're discussing here, if you want to build arrays out of arrays, there are efficient ways to do that in compiled code, much faster than `ak.from_iter` or `ak.to_list`, and some of them are even _O(1)_—independent of the size of the array. Like this, for instance:

```python
>>> a = ak.Array([1, 2, 3])
>>> a
<Array [1, 2, 3] type='3 * int64'>
>>> b = ak.zip({"a": a}, depth_limit=1)
>>> b
<Array [{a: 1}, {a: 2}, {a: 3}] type='3 * {"a": int64}'>
>>> c = ak.zip({"b": b}, depth_limit=1)
>>> c
<Array [{b: {a: 1}}, ... a: 2}}, {b: {a: 3}}] type='3 * {"b": {"a": int64}}'>
```

which nests every value of `a` inside a field of records in `b` inside a field of records in `c`, and that's just a rearrangement of metadata, it takes exactly as long whether the array has length 3 or 3 billion.

Although I'll look into the apparent bug in your second example (right now, I think), building arrays up by putting existing arrays into the `ak.Array` constructor (which calls `ak.from_iter` if it's nested in any kind of Python structure) is disfavored.

**Comment by jpivarski** [comment]
I've addressed the two MRE examples (in #1060) by

   1. having `ak.Record.__iter__` explicitly iterate over its fields, like dict
   2. explicitly checking for `ak.Array` and `ak.Record` in `ak.from_iter` to interpret both as their `ak.to_list` equivalents (i.e. `ak.Record` is interpreted as its equivalent dict)
   3. not changing the "Pandas-style" `ak.Array` constructor, which takes the keys and values of a given (top-level) dict as column names and columns to zip together, iterating over the columns (even though iterating over a dict/Record's fields is probably not what you want)

Following these rules, the first MRE becomes:

```python
>>> awkward.Array({"record": awkward.Record({"column": [1]})})
<Array [{record: 'column'}] type='1 * {"record": string}'>
```

because the `ak.Array` constructor is being given a (top-level) dict, so `"record"` is interpreted as a column name and it iterates over the value, `awkward.Record({"column": [1]})`, which is an iteration over one string: `["column"]`. This is exactly the same as though the `ak.Record` were a dict:

```python
>>> awkward.Array({"record": {"column": [1]}})
<Array [{record: {column: 1}}] type='1 * {"record": {"column": int64}}'>
```

Arguably, that's not what somebody would have intended if they wrote that, but putting in special cases to check for `ak.Record`, dict, Mapping, and maybe others for the sake of interpreting them differently or at least raising an error would be making the function too magical—too hard to interpret or work around if it hits some other unexpected case.

The second MRE example is more meaningful:

```python
>>> awkward.Array([awkward.Record({"column": [1]})])
<Array [{column: [1]}] type='1 * {"column": var * int64}'>
```

Now this is interpreting the `ak.Record` exactly as though it were a dict:

```python
>>> awkward.Array([{"column": [1]}])
<Array [{column: [1]}] type='1 * {"column": var * int64}'>
```

To reiterate my previous comment, this doesn't improve the performance. The `ak.Record` is actually being turned into a Python dict, which is then iterated over—it could only be faster if it was originally a dict. In large-scale computations, you don't want to manipulate these things in a row-wise/record-oriented way, but in a columnar way with broadcasting, `ak.zip`, and other array-at-a-time functions.

**Comment by veprbl** [comment]
Let's go through some of the operations present in numpy and their counterparts in Awkward

## Array concatenation

A simple operation of concatenating two arrays
```python
>>> np.concatenate([np.array([1, 2, 3]), np.array([4, 5, 6])])
array([1, 2, 3, 4, 5, 6])
```
has an obvious counterpart in Awkward
```python
>>> awkward.concatenate([awkward.Array([1, 2, 3]), awkward.Array([4, 5, 6])])
<Array [1, 2, 3, 4, 5, 6] type='6 * int64'>
```
Now in Awkward we deal not only with numerical indices, but also with record key indices, so one might want to concatenate along that dimension as well. A naive approach:
```python
>>> awkward.concatenate([awkward.Array({"a": [1], "b": [2]}), awkward.Array({"c": [3], "d": [4]})])
<Array [{a: 1, b: 2}, {c: 3, d: 4}] type='2 * union[{"a": int64, "b": int64}, {"...'>
>>> awkward.concatenate([awkward.Array({"a": [1], "b": [2]}), awkward.Array({"c": [3], "d": [4]})]).to_list()
[{'a': 1, 'b': 2}, {'c': 3, 'd': 4}]
```
does concatenation along the numerical axis. The `awkward.zip` is not quite it, as it expectedly creates an extra dimension. It seems like there is an operation missing here, or I haven't found it.

## Array stacking

Array stacking is like concatenation, but creates a new axis. A simple use in Numpy:

```python
>>> np.stack([np.array([1, 2, 3]), np.array([4, 5, 6])])
array([[1, 2, 3],
       [4, 5, 6]])
>>> np.array([[np.array([1]), np.array([2])], [np.array([3]), np.array([4])]])
array([[[1],
        [2]],

       [[3],
        [4]]])
```

The well known `zip` operation from the Python standard library is a case of stacking:

```python
zip = lambda *arrays: np.stack(arrays, axis=1)
```

There is no dedicated operation for stacking in Awkward, but the following trick apparently works:

```python
>>> awkward.concatenate([awkward.Array([1, 2, 3])[np.newaxis], awkward.Array([4, 5, 6])[np.newaxis]])
<Array [[1, 2, 3], [4, 5, 6]] type='2 * 3 * int64'>
```

Stacking along a record index requires specifying index values and is achievable with `awkward.zip`:

```python
>>> awkward.zip({"a": awkward.Array([1, 2, 3]), "b": awkward.Array([4, 5, 6])})
<Array [{a: 1, b: 4}, ... b: 5}, {a: 3, b: 6}] type='3 * {"a": int64, "b": int64}'>
>>> awkward.zip({"a": awkward.Array({"i": [1]}), "b": awkward.Array({"k": [2]})})
<Array [{a: {i: 1}, b: {k: 2}}] type='1 * {"a": {"i": int64}, "b": {"k": int64}}'>
```

the `Array` constructor works as well for this purpose
```python
>>> awkward.Array({"a": awkward.Array([1, 2, 3]), "b": awkward.Array([4, 5, 6])})
<Array [{a: 1, b: 4}, ... b: 5}, {a: 3, b: 6}] type='3 * {"a": int64, "b": int64}'>
```

Presumably there would be an operation to do stacking at a deeper level, like `awkward.zip({"a": awkward.Array({"i": [1]}), "b": awkward.Array({"k": [2]})}, axis=1)` that would return `<Array [{i: {a: 1}, k: {b: 2}}] type='1 * {"i": {"a": int64}, "k": {"b": int64}}'>`

# Array constructor

In Numpy, the array constructor allows to add arbitrary dimensions
```python
>>> np.array([[np.array([1, 2, 3])], [np.array([4, 5, 6])]])
array([[[1, 2, 3]],

       [[4, 5, 6]]])
```

Same works in Awkward for numerical dimensions:
```python
>>> awkward.Array([[awkward.Array([1, 2, 3])], [awkward.Array([4, 5, 6])]])
<Array [[[1, 2, 3]], [[4, 5, 6]]] type='2 * var * var * int64'>
```
For record dimensions:
```python
>>> awkward.Array({"i": awkward.Array({"a": [1]}), "k": awkward.Array({"b": [2]})})
<Array [{i: {a: 1}, k: {b: 2}}] type='1 * {"i": {"a": int64}, "k": {"b": int64}}'>
```
For mixed
```python
>>> awkward.Array({"i": awkward.Array([1, 2, 3]), "j": awkward.Array([4, 5, 6])})
<Array [{i: 1, j: 4}, ... j: 5}, {i: 3, j: 6}] type='3 * {"i": int64, "j": int64}'>
```
and in the master version also the opposite way
```python
>>> awkward.Array([[awkward.Array({"a": [1]})], [awkward.Array({"b": [2]})]])
<Array [[[{a: 1, b: None}, ... b: 2}]]] type='2 * var * var * {"a": ?int64, "b":...'>
```
(although the type appears to be a bit strange here, as it could have been a "union" instead)

**Comment by jpivarski** [comment]
You presented a good overview. One point that should be emphasized, though, is that there's a conceptual distinction/asymmetry between "columns" and "rows."

By "columns," I mean data in an `ak.Array` that can be accessed by slicing with a string or a list of strings—a field or fields of a record. By "rows," I mean data that can be accessed with any other kind of slice, so that includes jagged dimensions. Awkward Array is optimized for having a large number of rows: anything involving row manipulation is done in compiled code, not Python iteration, and is therefore roughly as fast as a dedicated C program. ("Roughly" because I'm not considering the effects of multiple passes over the data and RAM → CPU cache throughput, which are relevant at higher speeds than could be achieved in a pure Python program.) Anything involving column manipulation is done in Python or dynamically typed C++ (which is currently [being converted to Python](https://github.com/scikit-hep/awkward-1.0/pulls?q=is%3Apr+%22C%2B%2B+refactoring%22)), so the scales are more limited. My standard recommendation is that the number of rows can scale to however much memory you have—a computer with GBs of RAM can deal with billions of rows—but the number of columns should not be much more than thousands.

As you've noticed, the available operations have an asymmetry between columns and rows, and that reflects the fact that the library was designed for this asymptote of scaling. Thus, `ak.concatenate` concatenates rows only, though it may do so at different dimensions/depths/`axis` numbers. The `axis` numbers are themselves a row-only concept.

But suppose you want to do something like [pd.concat](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) with `axis=1`. (Pandas _does_ treat rows and columns on a similar footing, using `axis=0` to apply a function to rows and `axis=1` to apply the same function to columns. Since Pandas only deals with 2-dimensional tables, `axis=0` and `axis=1` are the only options. Awkward Array's `axis` is a lot like NumPy's `axis` and nothing like Pandas's `axis`.) That would be to take these two arrays of records, each of which has different fields:

```python
>>> one = ak.Array([[{"a": 1, "b": 1.1}], [], [{"a": 2, "b": 2.2}]])
>>> two = ak.Array([[{"c": 3, "d": 3.3}], [], [{"c": 4, "d": 4.4}]])
```

and turn them into an array of records with all four fields, `"a"`, `"b"`, `"c"`, `"d"`. The following does that in general:

```python
>>> onetwo = ak.zip(dict(zip(one.fields + two.fields, ak.unzip(one) + ak.unzip(two))))
>>> onetwo.type
3 * var * {"a": int64, "b": float64, "c": int64, "d": float64}
>>> onetwo.tolist()
[[{'a': 1, 'b': 1.1, 'c': 3, 'd': 3.3}], [], [{'a': 2, 'b': 2.2, 'c': 4, 'd': 4.4}]]
```

You could imagine scaling the number of inputs from two (`one` and `two`) to an arbitrary number, since we're just adding lists of strings (`one.fields + two.fields`) and tuples (`ak.unzip(one) + ak.unzip(two)`). If the number of row dimensions vary, it might be necessary to limit the depth of zipping: `depth_limit=min(x.layout.purelist_depth for x in (one, two))`.

If we add such a function to the library, it would have to have a different name from "concatenate," because I want to maintain this conceptual distinction between rows and columns.

I like your stacking solution. If it's sufficiently general, we could overload `np.stack` with an `ak.stack` the same way that `ak.concatenate` overloads `np.concatenate`. (We use [NEP 18](https://numpy.org/neps/nep-0018-array-function-protocol.html) to overload NumPy functions if we can write an Awkward version of them that strictly generalizes the NumPy version.)

On your last point about the `ak.Array` constructor, it's not doing anything special with records or arrays (regardless of whether they're Awkward or NumPy) that are _nested within_ Python objects. If the top-level object passed to the `ak.Array` constructor is a list, then everything inside that list is iterated over (in Python) and it doesn't matter what kind of iterable it is. So

```python
>>> ak.Array([ak.Array([{"a": 1}]), ak.Array([{"b": 2}])])
<Array [[{a: 1, b: None}], ... a: None, b: 2}]] type='2 * var * {"a": ?int64, "b...'>
```

is not any different from

```python
>>> ak.Array([[{"a": 1}], [{"b": 2}]])
<Array [[{a: 1, b: None}], ... a: None, b: 2}]] type='2 * var * {"a": ?int64, "b...'>
```

Once inside the outer list, the `ak.Array` constructor has concluded that this is a generic iterable and it iterates over `ak.Array([{"a": 1}])` in exactly the same way as it would iterate over `[{"a": 1}]`. In this "iteration," dict-like objects are interpreted as records, so yes, we're iterating over both the keys and the values to do that, but it doesn't matter whether the objects are `ak.Record` or dict after PR #1061.

Why do you get a single record with nullable fields instead of a union-type? That was a deliberate choice: when iterating through the nested data, if we encounter dicts at the same level with different sets of keys, we could either have chosen to declare them as different record types and make a union or as a single record type in which the keys not seen in one dict are taken to have a value of "None" (i.e. ignoring the distinction between `key not in some_dict` and `some_dict[key] is None`, the way that `some_dict.get` works). This choice was made because option-type data have fewer limitations than union-type data, so it's a better default.

If you make the array manually with [ak.ArrayBuilder](https://awkward-array.readthedocs.io/en/latest/_auto/ak.ArrayBuilder.html), you can opt into or out of this choice. ([ak.from_iter](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_iter.html), which is what the [ak.Array](https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html) constructor defers to in the generic iterable case, internally uses an ArrayBuilder to make its array.)

```python
>>> builder = ak.ArrayBuilder()
>>> with builder.list():
...     with builder.record():
...         builder.field("a").integer(1)
... 
>>> with builder.list():
...     with builder.record():
...         builder.field("b").integer(2)
... 
>>> array = builder.snapshot()
>>> array
<Array [[{a: 1, b: None}], ... a: None, b: 2}]] type='2 * var * {"a": ?int64, "b...'>
>>> array.type
2 * var * {"a": ?int64, "b": ?int64}
>>> array.tolist()
[[{'a': 1, 'b': None}], [{'a': None, 'b': 2}]]
```

Naming the records establishes that they are distinct, and that you want a union-type instead of two option-types.

```python
>>> builder = ak.ArrayBuilder()
>>> with builder.list():
...     with builder.record("A"):
...         builder.field("a").integer(1)
... 
>>> with builder.list():
...     with builder.record("B"):
...         builder.field("b").integer(2)
... 
>>> array = builder.snapshot()
>>> array
<Array [[{a: 1}], [{b: 2}]] type='2 * var * union[A["a": int64], B["b": int64]]'>
>>> array.type
2 * var * union[A["a": int64], B["b": int64]]
>>> array.tolist()
[[{'a': 1}], [{'b': 2}]]
```

Naming records has [other uses](https://awkward-array.readthedocs.io/en/latest/ak.behavior.html) as well.
