### ISSUE TITLE
`mask_identity=False` should never introduce option-types

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1071]
### Version of Awkward Array

1.4.0

### Description and code to reproduce

Given this array:
```python3
layout = ak.layout.ListOffsetArray64(
    ak.layout.Index64(np.r_[0, 1]),
    ak.layout.IndexedArray64(
        ak.layout.Index64(np.r_[0,1,2,3]),
        ak.layout.RegularArray(
            ak.layout.NumpyArray(np.r_[1,2,3,4]),
            4
        )
    )
)
array = ak.Array(layout)
```
the result of reducing with `mask_identity=False` is an array with an option type:
```pycon
>>> ak.argmin(array, axis=-1, mask_identity=False)
<Array [[0]] type='1 * var * ?int64'>
```

If I were to hazard a guess, I suspect it is something to do with the way we handle indexed types vs indexed option types.

**Comment by jpivarski** [comment]
Whereas `mask_identity` is optional on most functions, it really doesn't make sense to have it on `argmin` and `argmax` (any `argX`). It's only there for completeness.

In general, the node is only added if `mask_identity` (just `mask` in C++) is true:

https://github.com/scikit-hep/awkward-1.0/blob/b8c3187f48aab8618a728537d22a71b6a177c505/src/libawkward/array/NumpyArray.cpp#L3331-L3345

But you're getting an extra one because IndexedArray does a `simplify_optiontype`:

https://github.com/scikit-hep/awkward-1.0/blob/b8c3187f48aab8618a728537d22a71b6a177c505/src/libawkward/array/IndexedArray.cpp#L2265-L2272

Even if `ISOPTION` is false, it should still do the `simplify_optiontype` because this also prevents an IndexedArray from being inside an IndexedArray (double indirection is bad, even without option-type). But the result of such a merger should be an IndexedArray, not an IndexedOptionArray. The above code does not allow for that possibility because it immediately constructs an IndexedOptionArray and calls `simplify_optiontype` on it.

Fortunately, [IndexedArray::simplify_optiontype](https://github.com/scikit-hep/awkward-1.0/blob/b8c3187f48aab8618a728537d22a71b6a177c505/src/libawkward/array/IndexedArray.cpp#L653-L956) knows that IndexedArray ∘ IndexedArray = IndexedArray, so this bug could be fixed by only replacing the `IndexedOptionArray64(...).simplify_optiontype()` call in the above-quoted code with `IndexedArray64(...).simplify_optiontype()` if not `ISOPTION`: i.e. splitting the two cases of "is option" and "is not option" at this level of the tree, and `simplify_optiontype` will do the right thing if there are option or non-option types at the next level down.
