### ISSUE TITLE
`ak.from_regular` and `ak.Array` produce distinguishable Arrays

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1075]
### Version of Awkward Array

1.4.0

### Description and code to reproduce

This is a (superficially) very strange bug.

I noticed that reducing over a jagged array produced different results according to how the Array was built:

```pyconthon
>>> X = ak.from_regular(ak.from_numpy(np.array([[0,1,2],[3,2,1]])))
>>> X.layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 6]" offset="0" length="3" at="0x0000036ea7b0"/></offsets>
    <content><NumpyArray format="l" shape="6" data="0 1 2 3 2 1" at="0x0000036f4570"/></content>
</ListOffsetArray64>
>>> ak.max(X, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
```
and
```pycon
>>> Y = ak.Array([[0,1,2],[3,2,1]])
>>> Y.layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 6]" offset="0" length="3" at="0x000003728f00"/></offsets>
    <content><NumpyArray format="l" shape="6" data="0 1 2 3 2 1" at="0x0000037314d0"/></content>
</ListOffsetArray64>
>>> ak.max(Y, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>
```

I haven't dug into this too much, but it looks like a bug to me because they layout representation is identical. Clearly, they're not identical, but I suspect something internal that isn't exposed.

**Comment by jpivarski** [comment]
I can't imagine what that different thing might be. The whole reason we have this print-out is to diagnose internal stuff; if the print-out strings are identical, the data should be identical as well.

I've reproduced the above. It doesn't survive a round-trip through v2:

```python
>>> from awkward._v2.tmp_for_testing import v1_to_v2, v2_to_v1

>>> ak.max(ak.Array(v2_to_v1(v1_to_v2(X.layout))), axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>

>>> ak.max(ak.Array(v2_to_v1(v1_to_v2(Y.layout))), axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>
```

It doesn't seem to be related to the `ak.Array` high-level wrapper:

```python
>>> ak.max(ak.Array(X.layout), axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
>>> ak.max(ak.Array(Y.layout), axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>
```

It (fortunately!) doesn't appear to be time/order-dependent:

```python
>>> ak.max(X, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
>>> ak.max(Y, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>
>>> ak.max(Y, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>
>>> ak.max(X, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
```

But it seems to be in the ListOffsetArray64 node, not in the NumpyArray node:

```python
>>> XX = ak.Array(ak.layout.ListOffsetArray64(X.layout.offsets, X.layout.content))
>>> ak.max(X, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
>>> ak.max(XX, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * var * ?int64'>
```

Finding the point where the walk through `ak.max` diverges should reveal what, exactly, is different about them.

**Comment by agoose77** [comment]
Yes I noticed that it doesn't survive any kind of dump-and-serialise, so it is very likely something that isn't supposed to be stateful is in fact stateful!

**Comment by jpivarski** [comment]
Woah, it could be this suspicious looking bool:

https://github.com/scikit-hep/awkward-1.0/blob/a8e8edf8e622b5b6ca550d901c5c161649e8530d/include/awkward/array/ListOffsetArray.h#L448-L453

**Comment by jpivarski** [comment]
Yes, that's only used in reducers, only in ListOffsetArray (not even copied in `shallow_copy`, making it very volatile, since `shallow_copy` happens a lot).

It causes exactly the effect that you see:

https://github.com/scikit-hep/awkward-1.0/blob/a8e8edf8e622b5b6ca550d901c5c161649e8530d/src/libawkward/array/ListOffsetArray.cpp#L1540-L1544

I don't understand why it's there at all. It's good that we're combing through this in the v1 → v2 transition.

**Comment by jpivarski** [comment]
These tests are an indicator of what was desired: https://github.com/scikit-hep/awkward-1.0/pull/447/files#diff-722c5c30935dd4b66b7d29d94a990b10cf0d1287630f788807c6f7bf09b03234

I suspect that this hack was only intended to exist for the life of a reduce calculation, and was supposed to disappear thereafter. It's not disappearing in `X`/`ak.from_regular`.

It probably should have been a method argument, rather than a class member, to ensure its short life.

**Comment by jpivarski** [comment]
We've identified the source for this one: it's some subtle hackery in the C++ layer (I think intended for VirtualArrays, which are also going away). This aspect of v1 was not ported over to v2. Furthermore, enough of v2 has been implemented to demonstrate that the effect is gone:

```python
>>> X = ak._v2.operations.structure.from_regular(ak._v2.operations.convert.from_numpy(np.array([[0,1,2],[3,2,1]])))
>>> X.layout
<ListOffsetArray len='2'>
    <offsets><Index dtype='int64' len='3'>[0 3 6]</Index></offsets>
    <content><NumpyArray dtype='int64' len='6'>[0 1 2 3 2 1]</NumpyArray></content>
</ListOffsetArray>
```

and

```python
>>> Y = ak._v2.highlevel.Array([[0,1,2],[3,2,1]])
>>> Y.layout
<ListOffsetArray len='2'>
    <offsets><Index dtype='int64' len='3'>[0 3 6]</Index></offsets>
    <content><NumpyArray dtype='int64' len='6'>[0 1 2 3 2 1]</NumpyArray></content>
</ListOffsetArray>
```

look the same and they are the same. When they get reduced, they return identical results.

```python
>>> ak._v2.operations.reducers.max(X, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
>>> ak._v2.operations.reducers.max(Y, axis=-1, keepdims=True)
<Array [[2], [3]] type='2 * 1 * ?int64'>
```

Although this isn't actually fixed in v1, it's a minor, subtle, hard-to-fix bug that will become irrelevant as soon as v2 is out. Efforts should be directed elsewhere. I'm going to close this issue so that it doesn't look like work to be done.
