### ISSUE TITLE
Use a consistent docstring fragment for all array inputs to ak.* functions

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/awkward#1080]
### Which documentation?

Python docstrings

### What needs to be documented?

`arrays` type in `concatenate` docstring made me guess. Maybe `(iterable)` ? 

https://github.com/scikit-hep/awkward-1.0/blob/18ba84ec7101e89fbdadb63b4683ff0025e85d71/src/awkward/operations/structure.py#L1398

**Comment by jpivarski** [comment]
Some of these are vague because they're "any data that can be converted into an Array" (with `ak.to_layout`). NumPy similarly has "array-like," which also doesn't have a formal definition.

Saying "iterable" is too precise because there can be iterables containing objects that can't be converted into arrays—such as file objects, I guess. Maybe we could adopt the "array-like" terminology, though our "array-like" is broader than NumPy's.

If this is fixed, then the "array" or "arrays" argument of all of these functions should be changed to the same text (copy-paste).

**Comment by agoose77** [comment]
Closed by #1946
