### ISSUE TITLE
`argmax` and `argmin` give incorrect results on option types when `axis=None`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1106]
### Version of Awkward Array

1.5.0

### Description and code to reproduce

Consider
```python3
>>> x = ak.Array([1, 2, 3, None, 4])
>>> ak.argmax(x)
3
```

What is happening is that `ak._util.completely_flatten` is dropping the `None` values, consequently shifting the position of the elements before calling `np.argmax`.

**Comment by jpivarski** [comment]
Right. This could be fixed by having argmin/argmax with `axis=None` first apply `ak.fill_none` with `axis=-1` and a fill value that is `-np.inf` for argmax and `np.inf` for argmin, before running it through `ak._util.completely_flatten`.

```python
>>> ak.argmax(ak.fill_none(x, -np.inf, axis=-1))
4
```

This converts the numerical data into floating point numbers, which doesn't break argmin/argmax (positions of minimum/maximum are unchanged), but it's an unnecessary computation. A more sophisticated version would use `np.iinfo(dtype).min` and `.max` instead of `-np.inf` and `np.inf`, but an array could contain multiple dtypes. It's maybe best for a first fix to just use `-np.inf` and `np.inf`.

**Comment by ianna** [comment]
or by using `axis=-1`:
```python
>>> x = ak.Array([1, 2, 3, None, 4])
>>> ak.argmax(x, axis=-1)
4
```

**Comment by jpivarski** [comment]
I had forgotten about this, but it's an important bug to fix promptly. I applied the easy fix described above in both v1 and v2.
