### ISSUE TITLE
ValueError: cannot create an OBJECT array from memory buffer

### ISSUE THREAD

**Issue by VasilyFomin** [scikit-hep/awkward#1107]
### Version of Awkward Array

1.5.0

### Description and code to reproduce

Hi,

I'm trying to read a parquet file using python 3.8 with a map column and it fails with `ValueError`:

```py
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import awkward as ak

print(f"Pandas: {pd.__version__}")
print(f"Pyarrow: {pa.__version__}")
print(f"Awkward: {ak.__version__}")

df = pd.DataFrame({
        'col1': pd.Series([
            [('key', 'aaaa'), ('value', '1111')],
            [('key', 'bbbb'), ('value', '2222')],
        ]),
        'col2': pd.Series(['foo', 'bar'])
    }
)

udt = pa.map_(pa.string(), pa.string())
schema = pa.schema([pa.field('col1', udt), pa.field('col2', pa.string())])

table = pa.Table.from_pandas(df, schema)
pq.write_table(table, "/tmp/map.parquet")

ak.from_parquet("/tmp/map.parquet")
```

> Pandas: 1.3.3 
> Pyarrow: 5.0.0
> Awkward: 1.5.0
> ValueError: cannot create an OBJECT array from memory buffer

Using Pandas and Arrow directly doesn't cause the error:

```py
pd.read_parquet("/tmp/map.parquet")
pa.from_parquet("/tmp/map.parquet").to_pandas()
```

**Comment by jpivarski** [comment]
That's right: we don't accept Python objects as components within an Awkward Array. The fact that Pandas does accept Python objects forces the columns that use them to be accessed via Python iteration and not slicing. (Actually, Awkward 0.x did that, too, but it became a confusing mess that I have a list of issue numbers for.)

The data in this DataFrame could be a nested array type. Here's a general purpose converter:

```python
array = ak.Array({x: df[x].values.tolist() for x in df.columns})
```

Now if we look at `array.tolist()`, we see

```python
[{'col1': [('key', 'aaaa'), ('value', '1111')], 'col2': 'foo'}, {'col1': [('key', 'bbbb'), ('value', '2222')], 'col2': 'bar'}]
```

and if we look at `array.type`, we see

```python
2 * {"col1": var * (string, string), "col2": string}
```

It knows about the internal structure of col1, and therefore it's possible to slice into it in ways that wouldn't be possible for generic Python objects (because each object could, in principle, have a different type):

```python
>>> array["col1", "0"]
<Array [['key', 'value'], ['key', 'value']] type='2 * var * string'>
>>> array["col1", "1"]
<Array [['aaaa', '1111'], ['bbbb', '2222']] type='2 * var * string'>
```

Parquet can also know about this structure:

```python
>>> ak.to_parquet(array, "/tmp/map.parquet")
>>> array2 = ak.from_parquet("/tmp/map.parquet")
>>> array2
<Array [{col1: [, ... col2: 'bar'}] type='2 * {"col1": var * {"0": string, "1": ...'>
```

That's almost an exact round-trip: what has been lost is that `array` knows that the key-value pairs are tuples whose left and right fields can be addressed as (string) `"0"` and `"1"`, but `array2` thinks they're records whose field names are `"0"` and `"1"`. (That's metadata we ought to store in Parquet, but don't yet.)

I don't know for certain what pyarrow is doing, but I think it's writing your Python objects as a pickled bytestream, with metadata instructing it to unpickle them when read back. That's how it gets to `ak.from_parquet`'s internals as an object array (`dtype="O"`).

Awkward Array won't be changed to accept Python objects, but we could consider some other mitigation: maybe a better error message, or maybe an attempt to run `ak.from_iter` on object arrays (though that would hide a performance bottleneck—the Python objects are themselves a performance bottleneck). Let me know what you think and we'll either close this issue or change its goal.

**Comment by jpivarski** [comment]
Let me know if I'm missing something and should reopen this issue, but I think I've addressed it and will be closing it now. Thanks!
