### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xxiang4** [scikit-hep/awkward#1144]
I looked up awkward array documentation (https://awkward-array.org/quickstart.html), but many are labeled [to do]. Can someone fill it up? For example, I tried to understand how to filter array but found the corresponding documentation missing. Many thanks.

**Comment by jpivarski** [comment]
A note reminding me to write more of these documentation chapters is on the sidebar of my email everyday. `:)` At the moment, finishing up version 2.0 is on a high priority, and all of the documentation will need to be revisited when that's done, since there will be tiny differences in interface and we want to be sure that it's not misleading. As a global optimization, it will be a little better to write more of that documentation after the 2.0 release.

In the reference documentation (which is complete), under `ak.Array` → `__getitem__`, there's a detailed explanation of filtering by boolean arrays. I hope that helps you get started.
