### ISSUE TITLE
Crash from ak.any (Floating point exception)

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#1167]
### Version of Awkward Array

1.7.0

### Description and code to reproduce

The following code
```python
import awkward as ak

a = ak.layout.NumpyArray([])
b = ak.layout.ListOffsetArray64(ak.layout.Index64([0]), a)
c = ak.layout.ListOffsetArray64(ak.layout.Index64([0]), b)
ak.any(c, axis=1)
```
crashes in the `ak.any` call. It simply prints `Floating point exception` to the console without a Python backtrace.

**Comment by ianna** [comment]
@jrueb - thanks for spotting it! Indeed, I can reproduce this crash with other reducers.

**Comment by jpivarski** [comment]
Also in v2, which is a clue that it's in the kernels, rather than the Content infrastructure:

```python
>>> import awkward as ak
>>> import numpy as np
>>> a = ak._v2.contents.NumpyArray([])
>>> b = ak._v2.contents.ListOffsetArray(ak._v2.index.Index64([0]), a)
>>> c = ak._v2.contents.ListOffsetArray(ak._v2.index.Index64([0]), b)
>>> ak._v2.operations.reducers.any(c, axis=1)
Floating point exception (core dumped)
```

There are no crashes for `axis=0` or `axis=2`, or any on `b` or `a`, so I think that means that it's getting into this if statement:

https://github.com/scikit-hep/awkward-1.0/blob/40837bfb0c066d954c0858e5e48d02706252af99/src/awkward/_v2/contents/listoffsetarray.py#L1419

and not the else branch. It's what I called the "nonlocal" case, with kernels

   * `awkward_ListOffsetArray_reduce_nonlocal_maxcount_offsetscopy_64`
   * `awkward_ListOffsetArray_reduce_nonlocal_preparenext_64`
   * `awkward_ListOffsetArray_reduce_nonlocal_nextstarts_64`
   * `awkward_ListOffsetArray_reduce_nonlocal_findgaps_64`
   * `awkward_ListOffsetArray_reduce_nonlocal_outstartsstops_64`, and
   * `awkward_ListOffsetArray_reduce_nonlocal_nextshifts_64`.

(Not all of them run; some are for argmin/max only.)

It would probably be easier to debug in v2, since the turn-around time of inserting debugging code in Python is faster than the v1 C++.

**Comment by ianna** [comment]
@jpivarski - it's because of a division by 0 in a kernel function. I'm submitting a bug-fix PR - just checking if there are other cases as that.

**Comment by jpivarski** [comment]
Thanks! I had been wondering what "Floating point exception" meant—it's a process-level error message I haven't seen before. Also, I'd expect integer division by zero to halt a process, but I would have thought that floating point division by zero would just return `nan` or `inf`. That's the usual behavior for floating point arithmetic:

```c++
root [0] double x = 3.14
(double) 3.1400000
root [1] x / 0.0
(double) inf
root [2] 0.0 / 0.0
(double) nan
```

**Comment by ianna** [comment]
this PR https://github.com/scikit-hep/awkward-1.0/pull/1168 fixes it
