### ISSUE TITLE
distutils module deprecated in Python 3.10

### ISSUE THREAD

**Issue by douglasdavis** [scikit-hep/awkward#1185]
### Version of Awkward Array

1.8.0rc1

### Description and code to reproduce

Very low priority issue

```
../../../.pyenv/versions/3.10.1/envs/dask-awkward/lib/python3.10/site-packages/awkward/__init__.py:7
  /Users/ddavis/.pyenv/versions/3.10.1/envs/dask-awkward/lib/python3.10/site-packages/awkward/__init__.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    import distutils.version

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

According to PyPA docs the preferred method for version checking is [to use `packaging.version`](
https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html#prefer-setuptools).

**Comment by jpivarski** [comment]
I just looked into this. `distutils.version.LooseVersion` would be replaced by `packaging.version.Version`, and that's available in our minimally supported Python version, 3.6.

However, that means we take on another strict, package-wide dependency, _just to check version numbers?_ Why isn't this in the standard library? (I'm tempted to just split by `"."` and compare tuples, though I know I shouldn't—because of pre-releases.)

Note: Uproot also needs this.

**Comment by jpivarski** [comment]
Oh, we're already depending on `setuptools` and `packaging.version.Version` can be accessed via

```python
setuptools.extern.packaging.version.parse
```

I don't know if `setuptools` depends on `packaging` or embeds it (it seems to be the latter, since it's possible to have the above but not the `packaging` package in a fresh Conda environment), so I'll go through the above.

**Comment by jpivarski** [comment]
I guess it would be a bug in Python 3.11, but Python 3.11 doesn't exist yet. "Installation" was the closest I could find to what this is about.

**Comment by douglasdavis** [comment]
> I don't know if setuptools depends on packaging or embeds it

`setuptools` indeed vendors its dependencies (`packaging` is here: https://github.com/pypa/setuptools/tree/main/setuptools/_vendor/packaging)
