### ISSUE TITLE
ak.singletons when array has no missing value

### ISSUE THREAD

**Issue by fleble** [scikit-hep/awkward#1189]
### Version of Awkward Array

1.7.0

### Description and code to reproduce

Dear experts,

When an ak array does not have missing values, `ak.singletons` does not wrap non-missing values into a list.

```python
>>> ak_array = ak.Array([1, 2, 3])
>>> ak.singletons(ak_array)
<Array [1, 2, 3] type='3 * int64'>
```

However everything seems fine with one missing value:
```python
>>> ak_array = ak.Array([1, 2, None])
>>> ak.singletons(ak_array)
<Array [[1], [2], []] type='3 * var * int64'>
```

Is this intending or is it a bug?

**Comment by aminnj** [comment]
@fleble check out https://github.com/scikit-hep/awkward-1.0/discussions/710 . Maybe it's worth revisiting the proposal there for `ak.singletons()`

**Comment by jpivarski** [comment]
ak.singletons and ak.firsts will be kept; I just posted an update in #710.

**Comment by jpivarski** [comment]
ak.singleton had been written with the assumption that the argument has option-type (even if there are no missing values in fact). That's because it was intended for the output of `ak.argmin`/`argmax`, which always has option-type, regardless of the value.

Your first example didn't work because it has type `3 * int64`, but it would work if it had type `3 * ?int64`, even if that option-type (question mark) is added through an option-type node with no mask (no missing data):

```python
>>> oops = ak.Array([1, 2, 3])
>>> ak.singletons(ak.Array(ak.layout.UnmaskedArray(oops.layout)))
<Array [[1], [2], [3]] type='3 * var * int64'>
```

The original point of the function was to turn option-type into list-type (and `ak.firsts` does the reverse), so maybe it _should_ pass through if there is no option-type at all. (I.e. maybe the original behavior was right.) But then again, the name is "singletons," which doesn't tell you that it has anything to do with option-types—you just expect it to make singleton lists and that's reasonable. The fix will go in.
