### ISSUE TITLE
hstack using padded numpy arrays leads to infinite recursion

### ISSUE THREAD

**Issue by mlaugharn** [scikit-hep/awkward#1192]
### Version of Awkward Array

1.7.0

### Description and code to reproduce

```
first = ak.from_numpy(np.array([1,2,3]))
deltas = ak.from_numpy(np.array([[1,2],[1,2],[1,2,3]]))
deltas = ak.pad_none(deltas, 3, axis=-1)
dxs = ak.numpy.hstack((first, deltas))
```
```

<__array_function__ internals> in hstack(*args, **kwargs)

RecursionError: maximum recursion depth exceeded while calling a Python object

```

Expected it to hstack; also, a different error message comes up when you use `ak.numpy.ma.hstack` as well:

```
dxs = ak.numpy.ma.hstack((first, deltas))
ValueError: NumPy format "O" cannot be expressed as a PrimitiveType

(https://github.com/scikit-hep/awkward-1.0/blob/1.7.0/src/libawkward/array/NumpyArray.cpp#L82)

```

**Comment by jpivarski** [comment]
Thanks for reporting the infinite recursion bug: #1198 fixes it by handling non-array iterables (the tuple, `(first, deltas)`) explicitly.

Your example still won't run as-is: there's a number of things to fix. First, `ak.numpy` was not supposed to be exposed and has been removed. What you're looking at is not a special NumPy-like submodule of Awkward Array, in the sense of `jax.numpy`, it's the normal `numpy` module that was imported within Awkward Array. Instead of providing a NumPy look-alike, you should use the normal `numpy as np`, so `np.hstack`, `np.ma.hstack`, etc. When we need to override NumPy's behavior, we use NumPy's [NEP-18](https://numpy.org/neps/nep-0018-array-function-protocol.html) (`__array_function__` protocol).

Although `ak.from_numpy(np.array([1, 2, 3]))` is a good way to make one-dimensional Awkward Arrays from NumPy (it shares the memory with NumPy and avoids copying the array), you shouldn't say

```python
deltas = ak.from_numpy(np.array([[1, 2], [1, 2], [1, 2, 3]]))
```

because the `np.array` constructor is given non-rectiliear data, which it can't handle other than creating a `dtype="O"` array (which is essentially a Python list—no advantage to using NumPy at all). In fact, NumPy 1.19 will tell you it's wrong:

```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of
lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you
must specify 'dtype=object' when creating the ndarray
```

and NumPy 1.20 will raise an error. That change in NumPy's behavior is [NEP-34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html).

If you want an array like that, avoid NumPy and go straight to Awkward Array:

```python
deltas = ak.Array([[1, 2], [1, 2], [1, 2, 3]])
```

Next is that even if the array had been regular, [np.hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) requires all of the arguments in the tuple to have the same number of dimensions. They're not:

```python
>>> first
<Array [1, 2, 3] type='3 * int64'>
>>> deltas
<Array [[1, 2], [1, 2], [1, 2, 3]] type='3 * var * int64'>
```

but `first` can be made 2-dimensional by adding a `np.newaxis` regardless of whether `first` is NumPy or Awkward):

```python
>>> first[:, np.newaxis]
<Array [[1], [2], [3]] type='3 * 1 * int64'>
```

([np.hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) does not broadcast the elements of the tuple it's given.)

Now, you can pad `deltas` to make it rectangular, but you still can't use `np.hstack` or `np.ma.hstack` on it because (a) `np.hstack` doesn't deal with missing values, only pure NumPy arrays, and (b) while `np.ma.hstack` can do it, it's not a "regular NumPy function," so [NEP-18](https://numpy.org/neps/nep-0018-array-function-protocol.html) doesn't apply: we don't have the power to overload it. The only way to get this method to work is to pad _and_ fill missing values in `deltas`:

```python
>>> totally_regular = ak.fill_none(ak.pad_none(deltas, 3, axis=-1), 999)
>>> totally_regular
<Array [[1, 2, 999], ... 1, 2, 999], [1, 2, 3]] type='3 * var * int64'>
>>> np.hstack((first[:, np.newaxis], totally_regular))
<Array [[1, 1, 2, 999], ... 999], [3, 1, 2, 3]] type='3 * 4 * int64'>
```

Combining [ak.pad_none](https://awkward-array.readthedocs.io/en/latest/_auto/ak.pad_none.html) with [ak.fill_none](https://awkward-array.readthedocs.io/en/latest/_auto/ak.fill_none.html) turns `deltas` into a totally regular NumPy array—no variable-length lists and no missing values, and `np.hstack` applies.

But then, what's the point of using Awkward Array? Just for reshaping things back so that you could have used NumPy instead?

There are other ways of approaching this problem. Starting with the original `first` and `deltas`,

```python
>>> first
<Array [1, 2, 3] type='3 * int64'>
>>> deltas
<Array [[1, 2], [1, 2], [1, 2, 3]] type='3 * var * int64'>
```

You could [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html) them at `axis=1`, which interleaves them in the way you were getting at with `np.hstack`, but you don't have to make `deltas` rectilinear.

```python
>>> ak.concatenate((first[:, np.newaxis], deltas), axis=1)
<Array [[1, 1, 2], [2, 1, 2], [3, 1, 2, 3]] type='3 * var * int64'>
```

If `first` and `deltas` have some semantic difference, you might want to make them records instead, so that you can access fields by name.

```python
>>> records = ak.Array({"first": first, "deltas": deltas})

>>> records[0]
<Record {first: 1, deltas: [1, 2]} type='{"first": int64, "deltas": var * int64}'>
>>> records[1]
<Record {first: 2, deltas: [1, 2]} type='{"first": int64, "deltas": var * int64}'>
>>> records[2]
<Record {first: 3, deltas: [1, 2, 3]} type='{"first": int64, "deltas": var * int64}'>

>>> records[1:]
<Array [{first: 2, deltas: [1, 2, ... 2, 3]}] type='2 * {"first": int64, "deltas...'>
>>> records[1:].deltas
<Array [[1, 2], [1, 2, 3]] type='2 * var * int64'>
>>> records["deltas", 1:]
<Array [[1, 2], [1, 2, 3]] type='2 * var * int64'>
```

Whatever it is you want to do with the array after having put `first` and `deltas` together, you'll likely want to do it in a different way with Awkward Array than you would have in NumPy.

**Comment by mlaugharn** [comment]
Just wanted to say thank you for this thoughtful answer! You are doing great work
