### ISSUE TITLE
singletons only created when at least one element is None

### ISSUE THREAD

**Issue by dr-stringfellow** [scikit-hep/awkward#1256]
### Version of Awkward Array

1.7.0

### Description and code to reproduce

Using `ak.singletons(array)` does not produce the expected behaviour unless at least one element of `array` is `None`. Instead, it leaves `array` unchanged.

`a = ak.Array([1,5,6,2,7,None])`
`b = ak.Array([1,5,6,2,7])`

`print(ak.singletons(a))`
`print(ak.singletons(b))`

produces

> [[1], [5], [6], [2], [7], []]

> [1, 5, 6, 2, 7]

If this _is_ the desired behaviour, it should be made clear in the documentation.

**Comment by jpivarski** [comment]
It's not the desired behavior (though I wavered on that in https://github.com/scikit-hep/awkward-1.0/issues/1189#issuecomment-1005164448). It was reported in #1189 and fixed in PR #1197. There have been releases since then, but all pre-releases so far: [1.8.0rc1](https://github.com/scikit-hep/awkward-1.0/releases/tag/1.8.0rc1), [1.8.0rc2](https://github.com/scikit-hep/awkward-1.0/releases/tag/1.8.0rc2), [1.8.0rc3](https://github.com/scikit-hep/awkward-1.0/releases/tag/1.8.0rc3). The fixed version is pip-installable, but you have to ask for it:

```bash
pip install 'awkward>=1.8.0rc3'
```
