### ISSUE TITLE
float passed to awkward.zeros_like does not behave like numpy.zeros_like

### ISSUE THREAD

**Issue by maxgalli** [scikit-hep/awkward#1278]
### Version of Awkward Array

1.7.0

### Description and code to reproduce

Hi, I noticed this difference in behaviour between ```awkward.zeros_like``` and ```numpy.zeros_like```:
```python
In [26]: import numpy as np

In [27]: import awkward as ak

In [28]: np.zeros_like(1.0)
Out[28]: array(0.)

In [29]: ak.zeros_like(1.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-95cb45da8df1> in <module>
----> 1 ak.zeros_like(1.0)

/work/gallim/anaconda3/envs/higgs-dna/lib/python3.9/site-packages/awkward/operations/structure.py in zeros_like(array, highlevel, behavior, dtype)
   1062     if dtype is not None:
   1063         return full_like(array, 0, highlevel=highlevel, behavior=behavior, dtype=dtype)
-> 1064     return full_like(array, _ZEROS, highlevel=highlevel, behavior=behavior, dtype=dtype)
   1065
   1066

/work/gallim/anaconda3/envs/higgs-dna/lib/python3.9/site-packages/awkward/operations/structure.py in full_like(array, fill_value, highlevel, behavior, dtype)
   1160             fill_value = int(fill_value)
   1161
-> 1162     layout = ak.operations.convert.to_layout(
   1163         array, allow_record=True, allow_other=False
   1164     )

/work/gallim/anaconda3/envs/higgs-dna/lib/python3.9/site-packages/awkward/operations/convert.py in to_layout(array, allow_record, allow_other, numpytype)
   1936
   1937     elif not allow_other:
-> 1938         raise TypeError(
   1939             "{0} cannot be converted into an Awkward Array".format(array)
   1940             + ak._util.exception_suffix(__file__)

TypeError: 1.0 cannot be converted into an Awkward Array

(https://github.com/scikit-hep/awkward-1.0/blob/1.7.0/src/awkward/operations/convert.py#L1940)
```

is this difference intended?

Thanks,

Massimiliano

[Related issue in coffea](https://github.com/CoffeaTeam/coffea/issues/640)

**Comment by agoose77** [comment]
The reason for this error is that Awkward 1.0 doesn't implement 0-d arrays: it returns the appropriate Python scalar type instead. This means that `ak.zeros_like` _technically_ doesn't have an Array-returning equivalent. Maybe we should return a scalar Python value here, but I'm not sure; in any case, not duplicating NumPy behaviour by returning a 0-d array is a significant behavioural difference.

@jpivarski knows more of the history here. In the upcoming v2, we return NumPy scalars instead, which retain their dtype.

**Comment by jpivarski** [comment]
It's correct that Awkward version 2 will return NumPy scalars instead of Python scalars, and NumPy scalars retain their bitwidth (as well as datetimes being distinct from Python datetimes, etc.).

```python
>>> type(ak.Array([1.1, 2.2, 3.3])[0])
<class 'float'>
>>> type(ak._v2.Array([1.1, 2.2, 3.3])[0])
<class 'numpy.float64'>
```

However, this is yet another thing, coming from the fact that in addition to bitwidth-typed scalars, NumPy also has zero-dimensional arrays:

```python
>>> type(np.float64(3.14))
<class 'numpy.float64'>
>>> type(np.array(3.14))
<class 'numpy.ndarray'>
>>> np.array(3.14).shape
()
```

I've always thought zero-dimensional arrays are pretty nutty. (It's an exception to the rule that `itemsize * prod(shape)` equals the number of bytes for C-contiguous arrays—does that mean a zero-dimensional array "is not C-contiguous?" What an odd thing to say about a single integer or float: that it's not contiguous in memory!)

Consequently, Awkward Array doesn't have them. I guess it could have—this design decision wasn't put to any kind of a vote, it was just my feeling at the time. Different array systems have made different choices here: R, being even more array-oriented than NumPy, _only_ has zero-dimensional arrays, instead of numbers. So in R, there's only one type, arrays; in Awkward, there's two, arrays and scalars (Python scalars in v1 and NumPy scalars in v2); and in NumPy, there's three, arrays, zero-dimensional arrays, and scalars.

So when it comes to what the output of `ak.zeros_like(3.14)` should be,

   * we have no equivalent of `np.array(3.14)`,
   * returning `np.float64(3.14)` would be _silently_ different from NumPy, since NumPy would return `np.array(3.14)` and this difference is hard to notice,
   * continuing to raise an exception at least calls out the fact that you can't do what you were trying to do.

In the scheme of things, the last option seems the safest to me.

I'm going to close this issue; if you think I'm wrong, speak up and I'll see it. I'm open to changing my mind.

**Comment by agoose77** [comment]
> However, this is yet another thing

Oops, I've edited my post to reflect my intended meaning.

> I've always thought zero-dimensional arrays are pretty nutty.

Yes, they are also the source of *some* headaches (conversely, here's a place where _not_ having 0-d arrays is a headache... sort of!)
