### ISSUE TITLE
Don't accept record as index

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1414]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

Over in https://github.com/ContinuumIO/dask-awkward/issues/23 a user ran into the case where a record is treated as an iterable of strings. This might be fun in some cases, but I suspect most users would stumble upon this behaviour by accident when attempting. I propose that we add a special case to `__getitem__` to reject record indices.

**Comment by jpivarski** [comment]
That's because ak.Record is a Python Mapping. The idea was that ak.Array would be a Sequence and ak.Record would be a Mapping, but if that's causing confusion, then we could remove that protocol from ak.Record (in v2).

**Comment by agoose77** [comment]
I think that might be a sensible proposal. It's not a huge problem, but having `iter(ak.layout.Record)` do something fundamentally different to `iter(ak.layout.RecordArray)` is likely to confuse some people, and indeed I've run into problems with passing `ak.Record` into other Awkward functions (even if by accident) and seeing surprising results.

**Comment by jpivarski** [comment]
At the mid-level (`ak.layout.*` or `ak._v2.contents.*`/`ak._v2.record`), we can assume more expertise. But also, these mid-level objects don't need to be iterable at all, unless the `ak._v2.Array.__iter__` implementation goes through the `ak._v2.contents.Content.__iter__` implementation or something. We can definitely remove any `__iter__` on the mid-level Record.

At high-level (`ak.Array`/`ak.Record` or `ak._v2.Array`/`ak._v2.Record`), I still slightly refer having them be a Sequence and a Mapping, respectively, because ak.Array is like a list and ak.Record is like a dict. One user might be confused about `iter(record)` yielding strings and another user might be confused about not being able to duck-type a `record` in a function that expects a dict.

You're right to have labeled this "policy."

**Comment by agoose77** [comment]
Right, I'm being lazy :zzz: I am referring to the high level API here!

> You're right to have labeled this "policy."

It's tricky indeed. Sometimes I really want records to behave like atoms, other times it is useful to decompose them. Fitting that into the Pythonic protocols is not trivial. 

I've made my position known, but I'm fairly confident it may well reverse in future, so I'm not pushing anything further!

**Comment by agoose77** [comment]
I think we can close this: `Record` is no longer iterable.
