### ISSUE TITLE
`ak.to_parquet` very slow on `uproot.lazy()` output with multiple branches via HTTP

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#1436]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

I'm not 100% sure whether this is a problem with `awkward` or with `uproot`. I'm using the following example code to store a subset of TTree branches to a Parquet file, using either `.arrays()` or `uproot.lazy()` via an HTTP URL:

```python
import time

import uproot
import awkward as ak

url = 'http://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root:events'
n_branches = 1

start = time.time()
tree = uproot.open(url)
branches = tree.keys()[:n_branches]
array = tree.arrays(branches)
ak.to_parquet(array, 'array.parquet')
end = time.time()
print(f'arrays() with {n_branches=}: {round(end - start, 2)} s')

start = time.time()
lazy_array = uproot.lazy(url)
ak.to_parquet(lazy_array[branches], 'lazy_array.parquet')
end = time.time()
print(f'lazy() with {n_branches=}: {round(end - start, 2)} s')
```

With `n_branches` set to `1`, I get roughly comparable performance between these two methods, which is what I would always expect:

```
arrays() with n_branches=1: 3.9 s
lazy() with n_branches=1: 5.66 s
```

If the number of branches is increased, however, the `lazy()` path takes much longer:

```
arrays() with n_branches=10: 4.04 s
lazy() with n_branches=10: 32.09 s
```

This seems to continue to scale very close to linearly with the number of branches:

```
arrays() with n_branches=50: 5.99 s
lazy() with n_branches=50: 152.94 s
```

Notably, I don't see this behavior with local files or `root:` URLs.

**Comment by jpivarski** [comment]
Without digging into it, I would guess that this is because `lazy` has to make a separate HTTP request for each basket of each branch, whereas `arrays` can request all of the byte ranges upfront in a single request, if the server supports multi-part GETs. Even if the server doesn't support multi-part GETs, the `lazy` requests have to be sequential and the `arrays` can use the multiple workers of the fallback MultithreadedHTTPSource.

With lazy arrays fetching data "as soon as they're needed," there is no way to fix this problem: it has to discover, one by one, that each basket of each branch will be needed when `ak.to_parquet` requests it. There is no coordination between `ak.to_parquet` and Uproot, such that Uproot can know that `ak.to_parquet` is going to require all baskets of all branches, eventually. (`ak.to_parquet` walks sequentially over partitions of a partitioned virtual (i.e. lazy) array, so that only one has to be in memory at a time, writing them to separate row groups in the output file.) That's a fundamental computer science/"how much information is available at a given time" issue.

> Notably, I don't see this behavior with local files or `root:` URLs.

This effect still happens with local files and XRootD, but local files have much less latency. For XRootD, maybe it's recognizing the pattern and pre-fetching baskets? That's a guess. By the way, it's also a guess that this effect is the dominant one in your case.

Switching to Dask will fix the above problem because nothing is computed until `compute` is explicitly called, and then we can scan the Dask DAG for which branches/entry ranges are touched and fetch them all in one request, as in `arrays`. The reason this requires Dask is because of the extra information we get from the `compute` call, which we currently lack.

--------------------------

I guess the reason you're using lazy arrays at all (which aren't recommended for performance, because of the above) is to prevent the whole array from being loaded into memory at once, so that the ROOT → Parquet conversion can be done in small steps? I'll be working on a v2 `ak._v2.to_parquet` soon, which will have to have some iterator solution for writing chunks and controlling the row group size because PartitionedArray won't be there. For the time being, we could arrange to build a PartitionedArray of VirtualArray manually to take all branches in larger-than-basket chunks for this process? Or just wait for `ak._v2.to_parquet` because we can write round-trip-safe arrays in Parquet in v2?

**Comment by masonproffitt** [comment]
This came up in the context of the Uproot transformer in ServiceX, which uses `lazy` because FuncADL doesn't currently have a way to determine which branches will be needed until a query is run. For my purposes here, I don't care about row chunking (I'm always loading an entire branch); I just don't want to load every branch in the tree. In this case, the entire file is only 200 MB, so I don't think there's any chunking happening anyway. The problem seems to be that there are sequential requests for each branch. Is there a way around that?

**Comment by agoose77** [comment]
@masonproffitt could you perhaps add a little more detail with regards to 

> FuncADL doesn't currently have a way to determine which branches will be needed until a query is run

Is it that you support non-trivial methods of e.g. accessing record fields (e.g. a dynamic string) such that the AST needs to be executed in order to determine which fields are in use?

If this is the case, then it will not be trivial to predict which branches will be loaded by the routine in order to batch-load them. Most expressions that operate on a lazy array also end up materialising it, which is not what you want here! 

There is a fundamental conflict between "invisible" laziness and optimization, which is a strong motivation for Awkward-Dask. Awkward only realises that you need a particular lazy array to be materialized at the point that its data is required. There is no mechanism for optimising this whilst we are required to run sequentially and synchronously.

If one had concrete knowledge of which branches were going to be used before any of the analysis code were invoked, then one could inspect the array layout and (hackily) its virtual layouts in order to build a single call to `uproot.open`. However, I imagine if this were possible that it would also be possible to do it before the user analysis code is invoked (i.e. don't use `uproot.lazy` to begin with) which you've stated isn't possible.

If this is a UX thing, perhaps there could be a way to add metadata that would allow you to optimize the case where this information is known at an early stage?

**Comment by masonproffitt** [comment]
> Is it that you support non-trivial methods of e.g. accessing record fields (e.g. a dynamic string) such that the AST needs to be executed?

Exactly. There's no way to know exactly what needs to be loaded until the point of the `ak.to_parquet` call. In many cases, part or all of the output array has already been materialized by the query (which is perfectly fine), but this particular case is an example in which nothing has been materialized, but all of the knowledge needed to make a much more efficient `arrays()` call exists. Maybe I can just write some code to detect this case and extract the information from the PartitionedArray to do exactly that?

**Comment by agoose77** [comment]
Of the possible solutions, I'd generally argue in favour of an explicit early-as-possible solution (e.g. the metadata approach I mentioned earlier). Only special-casing `to_parquet` means that a general analysis will not benefit from this optimisation.

I don't know enough to know whether these options would work, but some possible avenues:

- Allow the user to add metadata as to which branches will be loaded. Process the lazy array and replace the known parts with their eagerly loaded contents.
- Implement a trivial optimisation pass in the AST transformer that looks for `array.field` and `array['field']` cases, and keeps track of these (then apply above optimisation)
- Special-case only the `to_parquet` as you outline above.

In all three of these, you'd need to rip apart the `uproot` lazy array, and work backwards to perform the single `uproot.open` call. This is obviously not ideal (I'm picturing looking at `virtual.generator.callable.__self__` to get the `TBranch` :vomiting_face:) but it would *work* and be hidden away from user-facing code.

**Comment by masonproffitt** [comment]
The first option isn't tenable, as it breaks one of the primary goals of the interface. Even the significant performance penalty I've seen here is preferable to that. The second option is closer to the idea I've had for a long-term solution, but it is highly non-trivial, as the array and various slices of it can be assigned to new variables within a query, and there are non-field attributes. For now the special case should be fine, although I'll certainly be interested in the v2 Dask solutions.

**Comment by jpivarski** [comment]
I think there isn't anything that can or should be done to the Awkward or Uproot codebases to address this, though there are ways of dealing with it in downstream dependencies (ServiceX). Arguably, it's complicating things to put that fix in ServiceX, but there isn't a good way to do it in the non-Dask model of laziness (no way to propagate information about what `to_parquet` needs to `uproot.lazy` because we don't have a DAG that can be examined), but all of the Awkward+Uproot code that handles PartitionedArrays and VirtualArrays will be superseded (to address exactly this issue, actually). So unfortunately, ServiceX has to be complicated to deal with the way v1 laziness is working, but it will be simpler in v2.

I'm getting long-winded, but really what I'm saying is that this issue should be closed, since we can't do anything about it that we're not already doing (the whole v2 thing).
