### ISSUE TITLE
new FillableArray option?

### ISSUE THREAD

**Issue by glass-ships** [scikit-hep/awkward#145]
It looks like the `fillable` directory is no more, which means import statements for `FillableArray` et alia must be adjusted.

What is the appropriate import given these changes?

**Comment by jpivarski** [comment]
The following names have been changed:

   * `FillableArray` → `ArrayBuilder`
   * `FillableOptions` → `ArrayBuilderOptions`
   * `fillable` (in any other context) → `builder`

It's still early days and @henryiii found the name "fillable" to suggest an already allocated array to which we're inserting values, rather than a thing that grows. I agreed. I also didn't like the way that "Array" suggests that it's the same sort of thing as "ListArray", "RecordArray", etc. It's not—you have to `snapshot` for that. That's why there was a name change.

Sorry for the lack of notice!

**Comment by glass-ships** [comment]
No worries, that makes a lot of sense. thanks the context as well!
