### ISSUE TITLE
`to_layout` lets record cases slip through to the handler for generic iterators when `allow_records=False` (v1 and v2)

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1453]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

This is an issue we technically already know about, at least off-hand. However, I wanted to track it here so that we don't forget it.

Like #1414, we should either error on `to_buffers`, or handle this case. I believe we don't implement a form for a singular record, so the logical conclusion is to raise a `TypeError` here.

In the long run, I feel like it might be useful to be able to support singular records, but adding a new form is a bit more work than raising an Exception for now.

**Comment by jpivarski** [comment]
I guess this is what you mean:

```python
>>> record = ak._v2.Record({"x": 1, "y": [1, 2, 3], "z": "three"})
>>> record
<Record {x: 1, y: [1, ..., 3], z: 'three'} type='{x: int64, y: var * int64,...'>
>>> ak._v2.from_buffers(*ak._v2.to_buffers(record))
<StringBehavior ['x', 'y', 'z'] type='3 * string'>
```

The `to_buffers` function didn't recognize the Record, iterated over it, which means its dict-like keys, and turned that into an Array to convert into buffers.

Yes, that's definitely wrong and perhaps the easiest thing to do is to prevent Record from being used in `to_buffers`.

It looks like that's supposed to happen:

https://github.com/scikit-hep/awkward-1.0/blob/2ee6e64097015d0fd343f247326e82ca10718af5/src/awkward/_v2/operations/convert/ak_to_buffers.py#L129-L131

It's actually `to_layout` that's broken:

```python
>>> ak._v2.to_layout(record, allow_record=False).tolist()
['x', 'y', 'z']
```

`allow_record=False` should mean "raise a TypeError if you get a Record."

Here's the problem:

https://github.com/scikit-hep/awkward-1.0/blob/2ee6e64097015d0fd343f247326e82ca10718af5/src/awkward/_v2/operations/convert/ak_to_layout.py#L51-L63

The low-level `ak._v2.record.Record` check is correct in saying, "if you're a Record then { if not `allow_record`, FAIL, else good things }", whereas the high-level `ak._v2.highlevel.Record` is saying, "if `allow_record` and you're a Record then { ... }". So instead of failing, it keeps going until it gets to the case that handles general iterables:

https://github.com/scikit-hep/awkward-1.0/blob/2ee6e64097015d0fd343f247326e82ca10718af5/src/awkward/_v2/operations/convert/ak_to_layout.py#L105-L111

and a Record is iterable (returning its keys, as a Mapping). The fix is to make `to_layout`'s high-level section look like its low-level section.

**Comment by jpivarski** [comment]
This same mistake was made in v1, but it was made for both the low-level and high-level records:

https://github.com/scikit-hep/awkward-1.0/blob/2ee6e64097015d0fd343f247326e82ca10718af5/src/awkward/operations/convert.py#L1885-L1886

and

https://github.com/scikit-hep/awkward-1.0/blob/2ee6e64097015d0fd343f247326e82ca10718af5/src/awkward/operations/convert.py#L1897-L1898

This issue should cover both v1 and v2, and it will be super-easy. Maybe I'll do it before I finish answering #1454.
