### ISSUE TITLE
Masking and binning awkward.highlevel.Array leads to wrong results

### ISSUE THREAD

**Issue by WenzDaniel** [scikit-hep/awkward#1459]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

Hej Jim, thanks for the nice package. 

I encountered a strange behavior when making a histogram of a masked Awkward Array. I am not sure if the issue arises from awkward or numpys masked arrays (or maybe even both). When converting the awkward.array into a numpy.masked array the entries for the masked fields change. In addition when making the histogram of the masked array it looks like that the masked values are not removed before making the histogram (while they are removed when using other numpy functions like `np.sum`).

I made a short video to illustrate the issue. 

https://user-images.githubusercontent.com/43881800/166879012-6057a1af-c379-4ac2-9889-7b2e142f401b.mp4

Below you can find the code used in the video:

```
import numpy as np
import awkward as ak
import pickle
import sys
print(sys.version, ak.__version__, np.__version__)

# Load and prepare data:
with open("test_data_awkward_numpy_bug", "rb") as fp:   # Unpickling
    list_root = pickle.load(fp)

test_data = ak.Array(list_root)
first_photon = ak.min(test_data['pmthitTime'], axis=1)
first_photon = first_photon * 10**9
test_mask = (test_data['nNVpmthits'] >= 300 ) & (test_data['nNVpmthits'] < 700)
test_mask = test_mask & (first_photon < 20)

# Bug observed in awkward arrays using numpy.ma.core.MaskedArray 
# No sure if the bug is in awkward or numpy.
t = ak.to_numpy(test_data['nNVpmthits'][test_mask])
print(t[:20])
print(t.data[:20])
a, _ = np.histogram(t, bins=100, range=(0, 1500))
b, _ = np.histogram(t.data[~t.mask], bins=100, range=(0, 1500))
print(a)
print(b)
```

I also made a pickle file of the used data:

[test_data_awkward_numpy_bug.zip](https://github.com/scikit-hep/awkward-1.0/files/8629433/test_data_awkward_numpy_bug.zip)

**Comment by WenzDaniel** [comment]
(btw sorry for the poor video quality, but I had to compress it in order to upload it)

**Comment by agoose77** [comment]
Unlike NumPy, Awkward array isn't guaranteed to preserve the original values of masked elements. 

As to the histogram results, I'm not sure that `np.histogram` supports masked arrays at the moment #832. I suspect you will want to first ravel the contents e.g. with `np.ravel`.

## Technical Explanation :microscope:  
The reason for this is that there are several representations of missing values in Awkward. Some of them (`BitMaskedArray` / `ByteMaskedArray`) _mask_ elements, meaning that `len(array) == len(mask)`, whereas others _index_ elements (`IndexedOptionArray`, where `len(array)` may not equal `len(index)`.

The consequence of having an indexed option type is that by masking an array you are _not_ guaranteed to later be able to recover the masked values.

**Comment by WenzDaniel** [comment]
Hej Angus, thank you very much for the quick reply. 

> Awkward array isn't guaranteed to preserve the original values of masked elements.

Okay, this is something I expected already.  

> I'm not sure that np.histogram supports masked arrays at the moment

Okay, thanks. Yes the current behavior is a bit funky. At least none of us expected this behavior. Okay then I will warn our collaboration about it. Thank you very much for the quick help.

**Comment by WenzDaniel** [comment]
FYI: I think you mean `ak.ravel` before converting to numpy, is not it? At least `np.ravel` is not doing anything on the masked array as my data is already flat.

**Comment by agoose77** [comment]
`np.ravel` invokes `ak.ravel`, which does two things - it flattens _and_ it drops None values. Both are generally useful when filling histograms. 

However, in your case, the array _is_ a `MaskedArray` after you call `to_numpy`, so this wouldn't happen.

In general I suggest using the NumPy API unless you need an Awkward function, but cases like this are a bit special, and have given me something to think about

**Comment by agoose77** [comment]
If you're happy with the solutions posed here, then I shall close the issue :)

**Comment by WenzDaniel** [comment]
Sure, thanks for your help. I think the issue is more related to numpy showing this unexpected behavior, Though I think it is quite a pitfall and a bit worrisome if you are doing simulations, working with uproot etc.

**Comment by jpivarski** [comment]
(Thanks @agoose77 for resolving this!)

> I think the issue is more related to numpy showing this unexpected behavior

It took me a while to figure out what, exactly, is happening here, but yes: I would call this a NumPy quirk. NumPy's MaskedArray is (in my opinion) not well thought-through, and not very widely used. This case shows that all you have to do to expose hidden/uninitialized/undefined data is to say `t.data`. MaskedArray is considering the `t.mask` as some optional "maybe you want it, maybe you don't" kind of thing, whereas a `None` in an Awkward Array means "there is no value at this index." If it happens to be implemented with a mask (BitMaskedArray or ByteMaskedArray), then the value in the data buffer behind that mask is random, uninitialized junk. You're not supposed to look behind the mask.

I just tried it out—I think this is an unreasonable thing for `np.histogram` (or possibly `np.ma.MaskedArray.__array__`) to do:

```python
>>> # This is fine: all of the values go into the histogram.
>>> x = np.ma.MaskedArray([1, 2, 3, 4, 5], None)
>>> np.histogram(x, bins=5, range=(0.5, 5.5))
(array([1, 1, 1, 1, 1]), array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5]))

>>> # Yuck! 2, 3, and 4 are supposed to be hidden/not there!
>>> y = np.ma.MaskedArray([1, 2, 3, 4, 5], [False, True, True, True, False])
>>> np.histogram(y, bins=5, range=(0.5, 5.5))
(array([1, 1, 1, 1, 1]), array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5]))
```

As a rough edge, I can see two possibilities: one is to use [hist](https://github.com/scikit-hep/hist) for histogramming, which recognizes Awkward Arrays so that you don't have to cast them as NumPy and get the weird NumPy behavior. It will also `ak.revel` it for you.

Another is that we could change `ak.to_numpy` to explicitly set uninitialized data in the output to an explicit value, perhaps the MaskedArray's `fill_value` (default is 999999). Instead of constructing it with `numpy.empty`, we'd be constructing it with `numpy.full` and give it the fill value.

Here in v1:

https://github.com/scikit-hep/awkward/blob/f00775803a5568efb0a8e2dae3b1a4f23228fa40/src/awkward/operations/convert.py#L287

And here in v2 (although I just noticed that we ought to implement [ByteMaskedArray._to_numpy](https://github.com/scikit-hep/awkward/blob/f00775803a5568efb0a8e2dae3b1a4f23228fa40/src/awkward/_v2/contents/bytemaskedarray.py#L929-L930) with directly creating the MaskedArray; going through IndexedOptionArray is pointless extra computation):

https://github.com/scikit-hep/awkward/blob/f00775803a5568efb0a8e2dae3b1a4f23228fa40/src/awkward/_v2/contents/indexedoptionarray.py#L1532
