### ISSUE TITLE
How to restructure arrays by adding fields

### ISSUE THREAD

**Issue by fstrug** [scikit-hep/awkward#1547]
Link to page: https://awkward-array.org/how-to-restructure-add-fields.html

I need some further documentation so that I can understand how to add a new "branch" to an awkward array that comes from an opened TTree using uproot. It seems that TTrees opened in uproot follow a similar structure to this example:

```
array1 = ak.zip({"x": [1, 2, 3, 4, 5], "y": [1.1, 2.2, 3.3, 4.4, 5.5]})
```
How would I go about adding a new field to this array such that it is properly indexed/formatted with the original array. If we try:
```
array1 = ak.zip({"x": [1, 2, 3, 4, 5], "y": [1.1, 2.2, 3.3, 4.4, 5.5]})
array2 = ak.zip({"z" : [6,7,8,9,10]})
print(repr(array1))
print(repr(array2))
**Output:**
<Array [{x: 1, y: 1.1}, ... {x: 5, y: 5.5}] type='5 * {"x": int64, "y": float64}'>
<Array [{z: 6}, {z: 7}, ... {z: 9}, {z: 10}] type='5 * {"z": int64}'>
```
Now if we try combine array1 and array2 together.
```
new_array = ak.zip([array1, array2])
print(repr(new_array))
```
We get this output
`<Array [({x: 1, y: 1.1}, ... {z: 10})] type='5 * ({"x": int64, "y": float64}, {"...'>`
Instead of something like:
`<Array [{x: 1, y: 1.1,z:6}, . . ., {x:5, y:5.5, z:10} ] type='5 * ({"x": int64, "y": float6...'>`
How can we add the field "z" and get the desired format?

**Comment by jpivarski** [comment]
What you're getting is nested: "tuple of (record of x and y) and (record of z)". A "tuple" is a record without field names (these two fields are `"0"` and `"1"`), so this is records-within-records because you constructed a record array out of two record arrays.

You can flatten the field structure like this:

```python
new_array = ak.zip({"x": array1.x, "y": array1.y, "z": array2.z})
```

or more automatically like this:

```python
new_array = ak.zip(dict(zip(ak.fields(array1), ak.unzip(array1))) | dict(zip(ak.fields(array2), ak.unzip(array2))))
```

using the `dict1 | dict2` [syntax from Python 3.9+](https://peps.python.org/pep-0584/), or if you have an older Python, there's `{**dict1, **dict2}`.
