### ISSUE TITLE
__enter__

### ISSUE THREAD

**Issue by philippemiron** [scikit-hep/awkward#1558]
### Description of new feature

I believe it would be useful to define the `__enter__` / `__exit__` methods so we could do:

```
with ak.from_parquet('test.parquet') as ds:
    print(ds.fields)
```
and it would take care of closing (or deleting) the dataset.

**Comment by jpivarski** [comment]
Well, the `ak.from_parquet` function opens and closes the file (using `with` blocks internally, to be sure to close the file even if there's an error), so by the time that it returns and `ds` is defined, the file is already closed. If you want this to delete `ds`, that's not what `with` blocks are normally for: they're for scoping resources _other_ than memory because memory is already scoped by functions.

That is, if we defined `__exit__` in such a way that it looked into `__locals__` and removed the `"ds"` key, that would be very unexpected behavior (and would likely get reported as a bug!).

Here are some ways that the memory used by `ds` can be scoped:

```python
try:
    ds = ak.from_parquet("test.parquet")
    ...
finally:
    del ds
```

and

```python
def tmp():
    ds = ak.from_parquet("test.parquet")
    ....

tmp()
```

This is based on the assumption that you're using `ak.from_parquet` in v2 or in v1 with `lazy=False`. Awkward v1 lazy arrays hold open a reference to the file so that they can read more data from it on demand, but lazy arrays are the part of Awkward that are being phased out with the switch to v2.

In Awkward v2 with Dask, the file would not be opened until the delayed computation is executed with `.compute()`, and then the file would be opened and closed as part of that computation. So holding a file open indefinitely is only an Awkward v1 lazy thing, which is deprecated.

I'd like to close this issue; let me know if this reasoning is sufficient. Thanks!
