### ISSUE TITLE
Consistency between __getitem__ and to_list when a Record is the top-level

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/awkward#1600]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

If you set a behavior in v2, then `to_list()` no longer returns a simple list, but instead returns Records. This is breaking https://github.com/scikit-hep/vector/pull/226.

MWE:

```python
import awkward

for ak in (awkward, awkward._v2):

    class Point(ak.Record):
        def distance(self, other):
            return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)

    ak.behavior["point"] = Point

    print(
        ak.Array(
            [[{"rho": 1, "phi": 1.0}], [], [{"rho": 2, "phi": 2.0}]], with_name="point"
        ).to_list()
    )
```

This prints:

```output
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
[[<Point {rho: 1, phi: 1} type='point[rho: int64, phi: float64]'>], [], [<Point {rho: 2, phi: 2} type='point[rho: int64, phi: float64]'>]]
```

**Comment by agoose77** [comment]
@henryiii can you confirm that this doesn't happen in a new RC (e.g. rc9)? I narrowed it down to 
- broken in 1.9.0rc2
- working in 1.9.0rc3

**Comment by Saransh-cpp** [comment]
Works fine in `rc9`!
```
In [1]: import awkward

In [2]: awkward.__version__
Out[2]: '1.9.0rc9'

In [3]: for ak in (awkward, awkward._v2):
   ...:
   ...:     class Point(ak.Record):
   ...:         def distance(self, other):
   ...:             return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)
   ...:
   ...:     ak.behavior["point"] = Point
   ...:
   ...:     print(
   ...:         ak.Array(
   ...:             [[{"rho": 1, "phi": 1.0}], [], [{"rho": 2, "phi": 2.0}]], with_name="point"
   ...:         ).to_list()
   ...:     )
   ...:
ArrayBuilder snapshot
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
ArrayBuilder to_buffers
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
```

**Comment by Saransh-cpp** [comment]
But `vector` still gives weird results (replacing all the `awkward` imports with `awkward._v2` in `vector`'s code) -
```
In [1]: import vector

In [2]: import awkward; awkward.__version__
Out[2]: '1.9.0rc9'

In [3]: array = vector.Array([[{"pt": 1, "phi": 0}], [], [{"pt": 2, "phi": 1}]])
ArrayBuilder to_buffers

In [4]: array
Out[4]: <MomentumArray2D [[{rho: 1, phi: 0}], [], [{...}]] type='3 * var * Momentum...'>

In [5]: array.tolist()
Out[5]: 
[<Array [{rho: 1, phi: 0}] type='1 * Momentum2D[rho: int64, phi: int64]'>,
 <Array [] type='0 * Momentum2D[rho: int64, phi: int64]'>,
 <Array [{rho: 2, phi: 1}] type='1 * Momentum2D[rho: int64, phi: int64]'>]

In [6]: [arr.tolist() for arr in array.tolist()]
Out[6]: [[{'rho': 1, 'phi': 0}], [], [{'rho': 2, 'phi': 1}]]
```

**Comment by agoose77** [comment]
@Saransh-cpp thanks for checking that. I've done the same, and noted that it's [this check](https://github.com/scikit-hep/awkward/blob/ead200677450ba4811d09bc69faf83738e11aac4/src/awkward/_v2/contents/content.py#L1391) that's finding [this `__getitem__`](https://github.com/scikit-hep/vector/blob/d4ad49ecf1761e3a6561498d2405b7789d53deff/src/vector/backends/awkward.py#L610-L614)

I haven't yet checked `git blame` to see why we do this, or indeed why we need this implementation on the vector side.

@jpivarski I've had a poke around, but I can't see this behavior in v1, and I can't find any information on why this was introduced. I've probably missed something, but nevertheless - can you provide any insight as to why Awkward does this? Is it  a feature waiting for an application, or does it solve an existing problem? (This sounds like a loaded question, but in my view both are fine! I'm just trying to get a handle on how to proceed).

**Comment by Saransh-cpp** [comment]
Thanks for pointing out the possibly faulty code, @agoose77! I tried testing things out after removing the [`__getitem__`](https://github.com/scikit-hep/vector/blob/d4ad49ecf1761e3a6561498d2405b7789d53deff/src/vector/backends/awkward.py#L610-L614) pointed by you (thanks to a discussion with @henryiii) -

## Works
The original issue goes away!
```
In [1]: import vector

In [2]: import awkward; awkward.__version__
Out[2]: '1.9.0rc9'

In [3]: array = vector.Array([[{"pt": 1, "phi": 0}], [], [{"pt": 2, "phi": 1}]])
ArrayBuilder to_buffers

In [4]: array.tolist()
Out[4]: [[{'rho': 1, 'phi': 0}], [], [{'rho': 2, 'phi': 1}]]
```

The `mypy` hook fails after removing `__getitem__`, but I think that can be fixed.

## Does not work
(Maybe these should be reported as new issues.)

Indexing and `tolist()`. The failing test -
https://github.com/scikit-hep/vector/blob/d4ad49ecf1761e3a6561498d2405b7789d53deff/tests/test_issues.py#L14-L24
```py
def test_issue_99():
    ak = pytest.importorskip("awkward")
    vector.register_awkward()
    vec = ak.Array([{"x": 1.0, "y": 2.0, "z": 3.0}], with_name="Vector3D")
    assert vec.to_xyz().tolist() == [{"x": 1.0, "y": 2.0, "z": 3.0}]
    assert vec[0].to_xyz().tolist() == {"x": 1.0, "y": 2.0, "z": 3.0}
    assert vec[0].to_rhophiz().tolist() == {
        "rho": 2.23606797749979,
        "phi": 1.1071487177940904,
        "z": 3.0,
    }
```
Running locally (after replacing `awkward` import with `awkward._v2` imports) -
```
In [1]: import vector

In [2]: import awkward; awkward.__version__
Out[2]: '1.9.0rc9'

In [3]: import awkward._v2 as ak

In [4]: vector.register_awkward()

In [5]: vec = ak.Array([{"x": 1.0, "y": 2.0, "z": 3.0}], with_name="Vector3D")
ArrayBuilder to_buffers

In [6]: vec
Out[6]: <VectorArray3D [{x: 1, y: 2, z: 3}] type='1 * Vector3D[x: float64, y: float...'>

In [7]: vec.to_xyz().tolist()
Out[7]: [{'x': 1.0, 'y': 2.0, 'z': 3.0}]

In [8]: vec.to_xyz()
Out[8]: <VectorArray3D [{x: 1, y: 2, z: 3}] type='1 * Vector3D[x: float64, y: float...'>

In [9]: vec[0].to_xyz()
ArrayBuilder to_buffers
ArrayBuilder to_buffers
ArrayBuilder to_buffers
Out[10]: <VectorRecord3D {x: 1, y: 2, z: 3} type='Vector3D[x: float64, y: float64, z...'>

In [10]: vec[0].to_xyz().tolist()  # -> should output a python list
ArrayBuilder to_buffers
ArrayBuilder to_buffers
ArrayBuilder to_buffers
Out[11]: <VectorRecord3D {x: 1, y: 2, z: 3} type='Vector3D[x: float64, y: float64, z...'>
```

**Comment by agoose77** [comment]
As per the Awkward meeting, the reason for https://github.com/scikit-hep/awkward/blob/ead200677450ba4811d09bc69faf83738e11aac4/src/awkward/_v2/contents/content.py#L1391 is that if users override the `__getitem__` implementation, then we can't use the (fast) normal path for list serialisation. 

In the meeting, we discussed making `to_list` overrideable by extension authors, but didn't get as far as how to do this.

**Comment by agoose77** [comment]
@jpivarski I have been thinking on this some more, and as far as I can recall, we don't have any concrete use cases for overriding `__getitem__` to return non-arrays. Given how big Awkward already is, I am inclined to suggest that we drop this `to_list` feature (it's exclusive to v2, right?) until someone actually needs it. To my mind, Arrays are at the core of what Awkward "is", so any intention to break that assumption by returning non-Awkward types at the heart of the array machinery seems misguided. If users do want to do this, they can just write a custom `def getitem(self, item)`. Otherwise, we need to figure out an extension mechanism for a use case that we don't yet understand, and that seems like a tall order.

**Comment by jpivarski** [comment]
Originally, `__array__ = "string"` used this feature to return strings, rather than arrays. Strings were intended as a first example of a behavior, the kind of Array-overriding one would want to do: "This isn't an array of lists of uint8; it's an array of strings." Strings, specifically, are now hard-coded, so they're not explicitly using this feature right now. (Strings are such a basic data type that we don't want them to be lost. Getting lists of integers when you expect strings is very unnerving.)

So overriding `__getitem__` was a basic goal with a use-case, strings, even though that use-case is implemented differently now. Other use-cases could involve, say, arrays of pickled Python objects (to get the functionality of [ObjectArray](https://github.com/scikit-hep/awkward-0.x/blob/master/awkward0/array/objects.py) from Awkward v0). Also, we can't prevent people from overriding `__getitem__` in classes that derive from `ak.Array`, and we don't want the `to_list` to disagree with the `__getitem__` (`to_list` should act as though it pulled all items from `__getitem__`, even though it's normally vectorized for speed.).

I've had this tab open since the issue was first raised; I've been meaning to get back to it. I was thinking that the `is` could be replaced by some sort of Python-friendly `issubclass`, or something that checks the `mro`. I need to find out what, exactly, is breaking here; I feel like there must be a way to make it work.

**Comment by agoose77** [comment]
Ah, that's a really good point. I had forgotten about the depth-reduction aspect of our string abstraction here. Incidentally, I think it might be useful to abstract our string-specialcasing at a later date, in case there are legitimate uses for the same mechanism down the road. Not an urgent todo, though.

The basic problem here is that `vector` implements a custom `__getitem__`. We have no way of knowing whether the author intends to use the vectorized `to_list` or not. Because of this, we currently assume that any custom `__getitem__` implementation is overloading the behaviour of `getitem`. In `vector`'s case, that's not true; they're just adding type hints. So, it's not a problem of inheritance or any such thing, we just don't have enough information to determine the behaviour author's intention.

We have some options:
- Check whether `__getitem__` returns an array with a no-op getitem call, e.g. `self[()]`, and assume that if it does, `to_list` works as expected. This makes a lot of assumptions about what kind of things the author is doing with `__getitem__`. 
- Provide a mechanism for behaviours to implement a custom `to_list`, which `vector` could use to restore the original `to_list` behaviour
- Provide a mechanism for behaviors to signal that they *don't* want the fallback `to_list` pathway

Or variations thereof.

From a type-theory perspective, we're in murky water because allowing a user to just break `__getitem__` is at odds with the Liskov Substitution Principle, but equally, we already have that problem with strings (using the string behaviour changes the dimension of an array by `-1`). That is, using the definition:
> Let Φ(x) be a property provable about objects x of type T. Then Φ(y) should be true for objects y of type S where S is a subtype of T.

Let it be known that I also don't hugely care about breaking LSP here, it's a principle not a law ;)

Ultimately, the safest thing to do is disable the fast-path `to_list` if a user overrides `__getitem__`. I feel that it's better to make this slow than just plain wrong, so users should opt-in to using the Awkward fast-path through a custom `_to_list` perhaps. For vector, that would mean:

```python
class VectorAwkward:

    def _to_list(self, ...):
        this_no_cls = ak.with_parameter(self, "__array__", None)
        return ak._v2.to_list(this_no_cls)
```

**Comment by jpivarski** [comment]
Just disabling the fast-path is exactly what the code in

https://github.com/scikit-hep/awkward/blob/8c9bf49e7656571912861b615429c411f51be039/src/awkward/_v2/contents/content.py#L1406-L1412

is supposed to do. It's supposed to be saying, "Would this node (`self`), if it were at top-level, have a custom `__getitem__`? If so, call that `__getitem__` on each `i` in `range(self.length)` to make a list of results _instead of_ using the fast-path." (The code that calls this checks for whether its return value is `None`, which is how it's supposed to communicate the fact that the fast-path is still a viable option.)

If that is not what is happening, then have a bug; something that I'm not seeing is broken in this implementation. I'd have to try it out to find out if it is broken and in what way.

@henryiii's MWE does not override `__getitem__`. This detour from the fast-path shouldn't be triggered. Without running it personally, I don't see why that's happening, but I can get to it in a moment.

-----------------------

Whether we're breaking the LSP is a matter of what you think is a provable property of type `ak.Array`. Any subclass `S` in OOP can override the base class `T`'s method `X`. The only reason you'd want to override a method is so that it can return something different: "`T.X()` returns value `Y`" but "`S.X()` returns value `Z`" with `Y` and `Z` being different values. So unless we're in a language in which methods can be declared `final` or we're talking about return _types_ `Y` and `Z` in a type-checked language, "`T.X()` returns value `Y`" can't be a _proven_ statement about `T`.

You'd be right to point out that any of the imaginable use-cases (including strings) would return different _types_ `Y` and `Z`. So `ak.Array.__getitem__` would not pass a type-checker unless it claimed to return `Any`. However, even without this ability for subclasses to override it, `ak.Array.__getitem__` can return `ak.Array`, `ak.Record`, any of the numeric types listed here:

https://github.com/scikit-hep/awkward/blob/8c9bf49e7656571912861b615429c411f51be039/src/awkward/_v2/types/numpytype.py#L66-L82

and strings (because that extension is hard-coded). Putting IP and MAC addresses in arrays was the motivating reason for Pandas to adopt an ExtensionArray mechanism, though for us, that could be an array of fixed-length bytestrings, maybe with special behaviors. The list of possible scalar types will have to be extensible.

-------------------

Making developers have to explicitly override `to_list` is something I'd like to avoid. It opens questions of "What happens if only one of the two is overridden?"

**Comment by agoose77** [comment]
> @henryiii's MWE does not override __getitem__. This detour from the fast-path shouldn't be triggered. Without running it personally, I don't see why that's happening, but I can get to it in a moment.

Right, that was because he was testing against 1.8.0, where we had a bug in `to_list`. In `main` this does not happen (and indeed, most of the pre-releases). This issue is about two separate problems.

> Just disabling the fast-path is exactly what the code in ... is supposed to do

Yes, agreed. My response is whether this is the right way for users to override `__getitem__`, or should we require them to "do more", e.g add new methods.

> Whether we're breaking the LSP is a matter of what you think is a provable property of type ak.Array

Indeed, hence why I don't place too much stock in the argument. Yet, I don't think most invocations of LSP are actually referring to provability. Particular in Python, most people are likely talking about "would my application break if you replaced `X` with `class Y(X)` for some `Y`, `X`.

> The only reason you'd want to override a method is so that it can return something different:

I disagree - logging is one case, vector's use case is another. That said, most users would not be doing either of these.

> Making developers have to explicitly override to_list is something I'd like to avoid. 

I wouldn't require them to do this. Only if they want to use the non-customised pathway, or implement some other `to_list` scheme.

My answer to
> What happens if only one of the two is overridden?

is "what we have right now".

**Comment by jpivarski** [comment]
> Right, that was because he was testing against 1.8.0, where we had a bug in `to_list`. In `main` this does not happen (and indeed, most of the pre-releases). This issue is about two separate problems.

What's the other problem? I'd like to address this, but I don't know what's wrong.

Oh, wait: is it this?

```python
>>> import awkward as ak
>>> class Point(ak._v2.Record):
...     def __getitem__(self, where):
...         return super().__getitem__(where)
... 
>>> ak._v2.behavior["point"] = Point
>>> array = ak._v2.Array(
...     [[{"rho": 1, "phi": 1.0}], [], [{"rho": 2, "phi": 2.0}]],
...      with_name="point",
... )
>>> array.tolist()
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
>>> array[0].tolist()
[{'rho': 1, 'phi': 1.0}]
>>> array[0, 0].tolist()
<Point {rho: 1, phi: 1} type='point[rho: int64, phi: float64]'>
```

That is, `ak.Record.to_list` should not return `self`? Indeed, the above is wrong.

**Comment by agoose77** [comment]
In 1.8.0, the original code sample in this issue produced the following:
```python

In [1]: import awkward
   ...:
   ...: for ak in (awkward, awkward._v2):
   ...:
   ...:     class Point(ak.Record):
   ...:         def distance(self, other):
   ...:             return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)
   ...:
   ...:     ak.behavior["point"] = Point
   ...:
   ...:     print(
   ...:         ak.Array(
   ...:             [[{"rho": 1, "phi": 1.0}], [], [{"rho": 2, "phi": 2.0}]], with_name="point"
   ...:         ).to_list()
   ...:     )
   ...:
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
[[<Point {rho: 1, phi: 1} type='point[rho: int64, phi: float64]'>], [], [<Point {rho: 2, phi: 2} type='point[rho: int64, phi: float64]'>]]
```

In `main`, we have
```python
In [1]: import awkward
   ...: 
   ...: for ak in (awkward, awkward._v2):
   ...: 
   ...:     class Point(ak.Record):
   ...:         def distance(self, other):
   ...:             return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)
   ...: 
   ...:     ak.behavior["point"] = Point
   ...: 
   ...:     print(
   ...:         ak.Array(
   ...:             [[{"rho": 1, "phi": 1.0}], [], [{"rho": 2, "phi": 2.0}]], with_name="point"
   ...:         ).to_list()
   ...:     )
   ...: 
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
[[{'rho': 1, 'phi': 1.0}], [], [{'rho': 2, 'phi': 2.0}]]
```

So the original issue seems fixed. However, you seem to have discovered another bug.  We need to fix that regardless of whether we need a "fast path" for trivially overloaded `__getitem__`s.

Closely related is the issue that's now being triggered by `vector`'s arrays with `to_list`; a slow-path is directly storing the output of `array[i]` into the output list:

https://github.com/scikit-hep/awkward/blob/ead200677450ba4811d09bc69faf83738e11aac4/src/awkward/_v2/contents/content.py#L1397

Fixing this seems a bit tricky to me - are we to assume that the user is returning something arbitrary, or an Awkward type? etc. Hence my suggestion that we look at letting users override `to_list` to correctly handle cases like this! :)
