### ISSUE TITLE
`ak.from_parquet` returns empty array when columns are specified

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1606]
### Version of Awkward Array

HEAD

### Description and code to reproduce

```python
>>> taxi = ak.from_parquet(
    "https://pivarski-princeton.s3.amazonaws.com/chicago-taxi.parquet",
    columns=["trip.km"],
)
>>> taxi.type.show()
7728 * {
    
}

```

**Comment by agoose77** [comment]
NB: the `docs` branch will need modifying after this fix to re-enable strict mode for the 10-minutes-... notebook. Right now, it's allowed to fail in order to keep builds working.

**Comment by agoose77** [comment]
@martindurant / @jpivarski I mistakenly tagged you whilst formulating a question concerning pyarrow details here. Now, however, I'll open a PR and we can discuss things there.

**Comment by jpivarski** [comment]
Does `"trip.km"` match any columns? (We need to make it easier to use the `from_parquet_metadata` to answer this question, though it's currently possible.)

Oh wait: things have been changing and I'm not up to date on the changes. `metadata_from_parquet` is now a dict, rather than a namedtuple. The `"trip.km"` is definitely one of the columns:

```python
>>> import awkward._v2 as ak
>>> ak.metadata_from_parquet(
...     "https://pivarski-princeton.s3.amazonaws.com/chicago-taxi.parquet"
... )["form"].columns()
['trip.sec', 'trip.km', 'trip.begin.lon', 'trip.begin.lat', 'trip.begin.time', 'trip.end.lon',
 'trip.end.lat', 'trip.end.time', 'trip.path.londiff', 'trip.path.latdiff', 'payment.fare', 'payment.tips',
 'payment.total', 'payment.type', 'company']
```

Getting any column by name no longer works:

```python
>>> ak.from_parquet("https://pivarski-princeton.s3.amazonaws.com/chicago-taxi.parquet", columns=["trip.km"])
<Array [{}, {}, {}, {}, {}, {}, ..., {}, {}, {}, {}, {}, {}] type='7728 * {}'>
```

which is a regression. (These features are going to need unit tests, which is a little complicated because that means making small sample files.)

**Comment by martindurant** [comment]
Aside from fixed quite how the columns are passed, we should presumably warn or error on an attempt to select columns that don't exist.
