### ISSUE TITLE
`ak._v2.values_astype` is idempotent for character arrays

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1622]
### Version of Awkward Array

HEAD

### Description and code to reproduce

In `NumpyArray.py` we deliberately return the original array in `numbers_to_type` [when the array is a character/byte array](https://github.com/scikit-hep/awkward/blob/9c33c2aa7d55766c99245a8ff21d416b9be4518f/src/awkward/_v2/contents/numpyarray.py#L651-L652).

Because of this, `ak._v2.values_astype` silently returns the same array with an unchanged dtype.

I can see an argument for not wanting to silently break strings, but I equally think that users might want to interpret strings as codepoints. Either we:
- Raise a noisy error here
- Drop the `__array__` parameter for these arrays (see https://github.com/scikit-hep/awkward/pull/1623)

I'm in favour of (2), because it gives users more agency.

**Comment by jpivarski** [comment]
The idea was that you might use this on a complex tree of numbers and strings (think of the taxi dataset) and want it to only apply to the numbers. I can see how converting the code points of characters to e.g. floating point numbers would be a relevant thing to do if the array consists only of those strings, but it would be completely undesirable if your intention was to turn all of the `float32`s into `float64`s in the taxi dataset.

Seeing the array come back to you looking just as it did before is how the communication is intended. I can't think of better way to do it: warnings are noisy because you often want to do the things they warn you about (I'm thinking of NumPy's zero-division warnings), log files don't make sense in a library, as they would have to get set up somehow, and error messages limiting you to a narrow range of behavior are restrictive.

(I'm assuming that users set up their scripts interactively—that's a hard assumption that I frequently emphasize, and it's an assumption that the whole family of APL languages have been making. I know that some people do set things up in a script and only look at the bottom line, but that is especially hard with this kind of language.)

On this point, users do have agency, to turn the strings into code points:

```python
array["path", "to", "string", "field"] = ak.without_parameters(array["path", "to", "string", "field"])
```

although that might be hard to discover and should perhaps have a convenience method.

**Comment by agoose77** [comment]
This was a use-case that I hadn't considered. I'm not 100% convinced though, because we are assuming that the entire recordarray is usefully represented as e.g. floats or integers, which has not been my experience. 

I'm actually OK with us having `without_parameters` be the canonical way to peek through the string abstraction, too. In fact, it makes me want to be more cautious about introducing more routines that break the string abstraction.

In generaI still think having a function called `do_X` sometimes _not_ do `X` might be a bad idea. The right solution to this might need some more thought. Preliminarily, I'm considering:
- By default, `values_astype` errors when it encounters char/byte arrays
- Users can opt-in to ignore these with `ak.values_astype(..., ignore_strings=True)`
- Users can convert strings to codepoints first with `without_parameters`


This way, they have to opt-in to bad behaviour.

**Comment by agoose77** [comment]
I also noticed that we have a typo in the docs that refers to `ak.numbers_astype`. Maybe this is what we wanted to do originally, and have two explicitly separate methods. If so, I'm happy to close this issue, because we're stuck with `values_astype` for the near future.

**Comment by agoose77** [comment]
Following our meeting, Jim and I discussed these two functions being orthogonal and thus it is reasonable not to error provided that the documentation is clear(er)?
