### ISSUE TITLE
Remove special-casing for strings

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1682]
### Version of Awkward Array

main

### Description and code to reproduce

The internals of Awkward have some hard-coded logic for handling strings (and categoricals). We ought to extend our behaviour system so that it is not necessary to special-case these types.

Examples:
https://github.com/scikit-hep/awkward/blob/1ebf1dbe732b6b634fab95c8406498a59b71695f/src/awkward/_v2/contents/listoffsetarray.py#L830-L840
https://github.com/scikit-hep/awkward/blob/1ebf1dbe732b6b634fab95c8406498a59b71695f/src/awkward/_v2/contents/listoffsetarray.py#L1203-L1247

etc.

**Comment by agoose77** [comment]
@jpivarski suggested adding an `is_string` helper function, which special cases string fast-paths. We can build-out a more general mechanism, which we can then disable down the road.

**Comment by jpivarski** [comment]
For name-collisions: there's a function in both Awkward and Uproot's _util called `isstr`, parallel with `isint`, which checks to see if an object is as Python `str`. `isstr` can be retired/removed, since its purpose was to handle Python 2 vs 3 strings, though that means turning a lot of `ak._util.isstr(x)` into `isinstance(x, str)` (and `x` can be complex). Incidentally, we'll still need `isint` because it standardizes _which_ integers we accept (no booleans but yes NumPy integers).

Since `is_string` always applies to things that have parameters, maybe it could be a method on the Metadata superclasses we talked about? And since we're talking about strings-via-parameters, maybe name it `parameter_is_string` (`string`, `bytestring`, `anystring`, with `anystring` being the most popular, I think).

**Comment by agoose77** [comment]
Just updating with my latest ideas.

I think about this occasionally, and I recognise that it will be tricky to implement. At present, we use the forms to test things like `purelist_depth`. Any PR that wants to make string handling less special-cased would likely need to make forms more aware of behaviours, either through an initialiser argument (harming serialisation), or remove the ability to ask a form for its depth without providing the behaviour, e.g. `form.purelist_depth(behavior)`.

I can definitely see value in someone limiting the true depth of an array via behaviours, but it seems non-trivial to get there from where we are now.

**Comment by agoose77** [comment]
Closed by #2547 (we went the other way, and made strings internal!)
