### ISSUE TITLE
Change `numba_type` objects to match `type` object interface?

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1719]
### Version of Awkward Array

main

### Description and code to reproduce

...

**Comment by jpivarski** [comment]
Numba type objects have to be distinct from `ak.types.Type` objects. Numba types are subclasses of `nb.Type` and have to be one-to-one with the concrete layouts used in lowered code, which makes them closer to Forms, but there are nagging differences with respect to Forms (no List/ListOffset distinction, no equivalent of Union).

Maybe I'm misreading this, but there can be no unification of Numba type objects (return value of `ak.Array.numba_type`) and Awkward types (return value of `ak.Array.type`). _Maybe_ the Numba type should even be private/hidden? No, downstream dependencies like Vector need to access it.

We can reopen this if you meant something else or I'm missing something.

**Comment by agoose77** [comment]
@jpivarski I am literally referring to the `NumbaType.type` vs `ArrayType.content` distinction. It's a superficial issue.

Vector _does_ use this interface during lowering: https://github.com/scikit-hep/vector/blob/8a68c9a7093d3f89291d619fe10e416aacdacd95/src/vector/backends/awkward.py#L1818-L1823

**Comment by jpivarski** [comment]
Oh, the fact that children are named "type" in NumbaType and "content" everywhere else in Awkward (and that was an intentional synchronization for Content, Form, Type in v2).

In fact, there's a potential conflict of conventions, since these are also Numba types. Numba tends to call children of lists "`dtype`". But since those aren't NumPy dtypes, we probably shouldn't continue with that convention.

I'd rather not rock the boat in the Numba implementation, and the Numba types aren't parallel enough with Content/Form/Type that I feel the need to synchronize them. My preference would be to ignore this, as we have a lot of other issues to consider.

**Comment by agoose77** [comment]
That's fine. I'm just trying to create more work for us, because I'm worried that we're slacking /s ;)
