### ISSUE TITLE
`ak.argcartesian` doesn't support negative values of `axis`

### ISSUE THREAD

**Issue by veprbl** [scikit-hep/awkward#1875]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

I'm looking to implement a lookup by index needed to process `TRefArray`s.

For example, if we have two arrays:
```python
obj = ak.Array([[46, 77], [], [123], []])
tref = ak.Array([[77], [], [123], []])
```
And need to look up the indices of `tref` values in `obj`, one can check the matching pairs:
```python
c = ak.cartesian([obj, tref], axis=1)
c.slot0 == c.slot1
```
```output
<Array [[False, True], [], [True], []] type='4 * var * bool'>
```
Then `argcartesian` can be used to get the indices and perform a lookup:
```python
ac = ak.argcartesian([obj, tref], axis=1)
obj[ac[c.slot0 == c.slot1].slot0]
```
```output
<Array [[77], [], [123], []] type='4 * var * int64'>
```
However this only works if obj and tref have the same level of juggedness (specified by `axis=1`). It would help to use `axis=-1`, but `ak.argcartesian` doesn't support this: https://github.com/scikit-hep/awkward/blob/v1.10.2/src/awkward/operations/structure.py#L3640-L3644

**Comment by ianna** [comment]
@veprbl - Thanks for bringing it up. The `axis` parameter is the dimension at which an operation is applied. The outermost dimension is `0`, followed by `1`, etc., and negative values count backward from the innermost: `-1` is the innermost dimension, `-2` is the next level up, etc. Some operations wrap the `axis` if a negative value is given.

As a workaround (and if it takes sense) you can check how deep your array is by asking its layout `depth`, the innermost axis is usually `depth - 1`:
`
obj.layout.minmax_depth
`

**Comment by agoose77** [comment]
As @ianna says, you can determine what a negative axis might be by using the depth of the array.

In this case, we likely don't provide support for negative axes in `argcartesian` because the result would not work properly with our indexing routines when the arrays have different dimensions; the resulting record array of indices would have dimensions given by the broadcasting result. Looking at the source, we do something like
```
1 * var
1 * 2 * var
---- becomes ----
1 * 1 * var           ] introduce new axes before the final dimension
1 * 2 * var           
---- becomes ----
1 * 2 * var           ] broadcast
1 * 2 * var           
----   result    ---- 
1 * 2 * var * (int64, int64)
```
@ianna / @jpivarski can you confirm this guess?

This would mean that the `argcartesian` result field corresponding to the first array (originally `1 * var`) no longer indexes into it; the dimensions don't match. This doesn't mean that `argcartesian` is useless in this case, however; you might want to use the "arg" in a non-indexing case. Nevertheless, if that's the case, you could just manually broadcast the results yourself with some additional work:
```python
left = ak.Array([1, 2, 3, 4])
right = ak.Array([[46, 77], [], [123], []])
assert left.ndim == right.ndim - 1

i = ak.local_index(left)
j = ak.local_index(right)

# Broadcast `i` to `j` after inserting padding dimensions
# Stop at axis=-1 so that the final dimension doesn't need the same length
k, _ = ak.broadcast_arrays(i[..., np.newaxis, :], j, depth_limit=j.ndim-1)

index = ak.cartesian((i, j), axis=-1)
```

My gut feeling is that `argcartesian` shouldn't try and handle this `axis=-1` case because to do so fundamentally requires us to broadcast the array, at which point the `arg` part is disconnected from the original array. Though this might sometimes be useful, in general it might be better to have a more predictable API that just doesn't permit this.

**Comment by jpivarski** [comment]
I'm completely perplexed about why negative `axis` is not supported in `argcartesian`. Even if the result wouldn't be useful as an index, it should still be implemented.

But also, if a non-negative `axis` is valid here, a negative one should be valid as well because it's just a translation. As @ianna said, it's a strict function of the given `axis` and the depth. In fact, if the depth has no branching (no records or unions), negative `axis` values are also useless: it's just another way of saying the non-negative `axis` (maybe a mild convenience, which allows you to avoid having to know how deep an array is, and calculate it yourself). With branching, negative `axis` allows one to specify different depths in different branches, which is useful for some functions, but might not be possible to use with `cartesian` and `argcartesian`.

The equivalent for `cartesian` attempts to convert the negative `axis` into a non-negative axis, but if there's branching, it gives up:

https://github.com/scikit-hep/awkward/blob/80bbef0738a6b7928333d7c705ee1b359991de5b/src/awkward/operations/structure.py#L3359-L3362

That's probably what should happen here, too: have negative `axis` be converted into the corresponding non-negative `axis`, using the depth of the array, but only if there is no branching.

I think, @agoose77, you're saying that the branching case (the only case in which it's more than a convenience) is not possible? If so, I think you're right about that.

By the way, all the code samples we're pointing to here are v1. The v2 `argcartesian` is defined in terms of `cartesian`:

https://github.com/scikit-hep/awkward/blob/3d93692be9b06843aa6b0051023f235fe406cad5/src/awkward/operations/ak_argcartesian.py#L114-L121

and the v2 `cartesian` attempts to convert negative `axis` into a non-negative `axis`:

https://github.com/scikit-hep/awkward/blob/3d93692be9b06843aa6b0051023f235fe406cad5/src/awkward/operations/ak_cartesian.py#L264-L266

which would mean nothing to do, for v2. (And the v1 problem can be worked around, so it's not a big enough problem to require a fix.)

**Comment by agoose77** [comment]
@jpivarski it might be worth choosing a reference frame when we talk about branching. My argument is that `argcartesian` is less meaningful in the case that the two arrays have different dimensions. This is like branching, but obviously we're talking about two distinct layouts, rather than e.g. two fields in a `RecordArray`. I think that's what you mean by branching too, because you make the point that if the arrays have the same dimension, it would make sense to support negative axes as a convenience. 

We could support a negative axis even for arrays of differing dimensionality, but the result would be less interpretable. My vote is in favour of allowing negative axes for non "branching" arrays, as you suggest :)

**Comment by jpivarski** [comment]
Right—in addition to a single array having multiple depths (due to records or unions), the Cartesian functions also take multiple arrays, and they could have different depths. I hadn't thought about that, but that is an important consideration.

The [current ak.cartesian implementation](https://github.com/scikit-hep/awkward/blob/3d93692be9b06843aa6b0051023f235fe406cad5/src/awkward/operations/ak_cartesian.py#L264-L266) gets a non-negative `axis` from the _first_ array; it's the `new_arrays_values[0]` that gets `axis_wrap_if_negative`. So that's the current policy.

Let's see... is there any guidance from NumPy? What does it do if a negative `axis` is applied to a function of multiple array arguments? `np.concatenate` takes multiple arguments, but they can't have different numbers of dimensions, so that's not a guide: we need a NumPy function of multiple array arguments in which the arrays may have different numbers of dimensions.

![image](https://user-images.githubusercontent.com/1852447/201423829-bf42928b-9a33-4133-87d0-72ee7dcbbdca.png)

I opened all the sections of the NumPy User Guide into tabs and searched for `axis` to see all the examples, and the closest I found to the case I'm looking for here is [np.cross](https://numpy.org/doc/stable/reference/generated/numpy.cross.html), which takes `axisa`, `axisb`, `axisc` arguments to deal with the fact that you might want to pick out different axes in the input arguments. In principle, maybe the Cartesian functions could follow suit by allowing the `axis` argument to be an integer (as it is now) _or_ a list of integers, one for each input array. But that's expanding the Cartesian functionality more than we should consider right now.

So, at the moment, the v2 Cartesian functions allow negative `axis`, and if they differ in dimension, the difference is resolved in favor of the first array. Is there any reason to change that? The one alternative that I can think of is to refuse input arrays with different numbers of dimensions, but I can see legitimate reasons why one would want to compute Cartesian products on different numbers of dimensions.

**Comment by agoose77** [comment]
Yes, I think the existing logic for `ak.cartesian` is sensible unless we start adding multiple axis values, which might be a nice feature, but it's a bigger change that we need to justify.

Whereas, for `ak.argcartesian`, there's an argument to be made against allowing negative axes for different dimension arrays on the basis that the result field corresponding to the padded array won't index into the original non-padded array. Usually I'm in favour of letting users do things even if seem a bit daft, and this might be such a case. I've thought about it some more this afternoon, and perhaps we should allow this (negative axis for non-branching arrays of different dimensions).

**Comment by agoose77** [comment]
OK, so I actually checked this out in v2, and we also forbid negative axes when arrays have different dimensions in both `ak.argcartesian` and `ak.cartesian`. So, in v2 the behavior is consistent between the two, but not as permissive as you describe it @jpivarski  (I also made this assumption).

I think that we should probably leave things as they are; you can still compute a negative axis using `purelist_depth / ndim`, and I think we want negative axes to be predictable and understandable. In particular, it would be nice to avoid introducing argument-order specific behavior (i.e. which array is first in the cartesian product), as that is semantically important outside of the axis choice.

**Comment by jpivarski** [comment]
I only found the part where the first array was used, not the part where if other arrays have different negative `axis` interpretations, an exception is raised, but I guess I didn't look far enough. It's different from what I thought, but this is also an acceptable behavior. In fact, more so, because it's always easier to turn error states into new interpretations than the reverse.

I'll close this issue, because everything is fine as-is (in v2).
