### ISSUE TITLE
Move `NumpyArray.ptr` body to `NumpyLike`.

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1926]
### Version of Awkward Array

main

### Description and code to reproduce

See title.

**Comment by jpivarski** [comment]
I'm not really sure what this is. Do you remember what you intended by this issue title?

**Comment by jpivarski** [comment]
If you remember what this means, go ahead and reopen it with an explanation.

Right now, I'm paraphrasing every open issue for a Statement of Work and building a tidy priority list. That's why I'm coming across these old issues. For this one, I don't know how to paraphrase it because I don't know what it means. As long as that's the case, we won't be able to address it. (For now, I can't include it on the list.)

**Comment by agoose77** [comment]
I've not had much time to look at this today, but I think it can be closed
permanently!
