### ISSUE TITLE
ak.is_none should have an axis parameter

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#193]
And it should probably become a C++ method. It was only implemented in Python because we needed it right away to support Pandas. (That's also why it doesn't have an `axis` parameter—it's a bare minimum.)

Also, none of the "na" functions recognize floating-point `nan` as the same thing as `None`. Pandas seems to be trying to get away from that misidentification, but maybe there are specialized needs for it—in that case, there should be a function that turns floating-point `nan` into None. (There's already one for the other direction: `ak.fillna` can be used to turn None into any value, such as `nan`.)

**Comment by jpivarski** [comment]
This would be a "good first issue" for developers who want to delve into C++. This function has a straightforward output—booleans at some level of depth—but more importantly, it only involves one input array and therefore avoids broadcasting.

There are a number of rules to follow when adding an operation in C++, such as never accessing a buffer's data directly—it has to go into a new cpu-kernels function to keep the structure organization code separate from the numeric computation code, which will eventually be have a gpu-kernels backend as well. If anyone starts on this issue, it will force me to write a CONTRIBUTING.md to spell out what's allowed and what isn't.

**Comment by Ellipse0934** [comment]
I have begin working on this and have a few thoughts which might need corrections and/or suggestions.

We'll have a `is_none` function with the arguments `axis` and `depth`. Till `axis != depth` we recursively call `is_none` on `contents` incrementing `depth` until `axis = depth` similar to many other functions.
When `axis = depth` if we are currently an `IndexedOptionArray` we return `NumpyArray(bytemask())` otherwise we return a `NumpyArray` of the same length filled with `False`.

Now the issue is that there is no `NumpyArray` constructor for boolean values ([here](https://github.com/scikit-hep/awkward-1.0/blob/master/src/libawkward/array/NumpyArray.cpp#L27)). There is a constructor right below which can allow us to do something like `NumpyArray(bytemask(), "Bool")`. I can't think of anything with the same convenience. Can this be added ? If so, then what should be it's name as "b" is reserved for `int8` right now.

Currently, calling `ak.is_none(ak.Array([None, 1, 2, 3])).dtype` returns `dtype('bool')`. I am assuming this behavior needs to be maintained. 

As far as the `CONTRIBUTING.md` is concerned maybe you can start writing the `How-it-works tutorials for developers` section, a main outline of the architecture along with an explanation of the various Array types can at least give potential contributors a head start before this section is fully written. The previous readme page([here](https://github.com/scikit-hep/awkward-1.0/blob/0.2.5/README.md)) was helpful compared to right now where it would be a nightmare for a newcomer to figure things out independently.

**Comment by jpivarski** [comment]
If the NumpyArray constructor is given a NumPy array with `np.bool` dtype, the NumpyArray will have boolean type. There's no reason to express that separately.

Giving this function depth would go through `awkward1._util.recursively_apply`. That takes a function that tells `recursively_apply` whether it should keep descending or to compute something on the current level and return. The full set of array nodes with option type are in `awkward1._util.optiontype`, and they all have `boolmask` methods.

Doing so would turn the output of this function from a NumPy array (which can have dtype `np.bool` or `np.bool_`) into an Awkward Array (which can have depth, and its dtype is a dummy to satisfy Pandas). I think that would be okay because the circumstances that require NumPy output, such as Pandas, ask for `axis=0`, which makes an Awkward Array that is immediately convertible into a NumPy array (i.e. its `__array__` method doesn't complain).

I agree that I need documentation, but I'm also on the hook for updating the Uproot project to output Awkward Arrays. That's supposed to be done by the end of April, which isn't going to happen because the two new array node types it needs, PartitionedArray and VirtualArray, are still in progress (well, the latter one is). I know that writing documentation enables contributors, but updating Uproot enables users, since it's the primary way physicists obtain arrays. Right now, Awkward1 has quite a lot developed, but few users because they're still getting Awkward0 arrays from Uproot.

I'll help you with spot problems and can probably manage to write that CONTRIBUTING.md, but such a file would be about coding practice, not an explanation of how the library works.

**Comment by jpivarski** [comment]
This issue keeps popping up, so I'm moving it to the November project. As per the discussion on #226, it will have a Python implementation. The `awkward1._util.recursively_apply` utility would make short work of it.

**Comment by jpivarski** [comment]
This one will be next, following up on PR #582.
