### ISSUE TITLE
Introduce `kernel_nplike` 

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1933]
### Description

We should enforce the idea that kernels are distinct from `nplikes` by having a third `kernel_nplike`, and try to convert all `Index` objects to this nplike before execution. This will ensure that JAX fails if we try to operate on JAX buffer _values_. It's a design decision that we don't support non-differentiable operations on JAX arrays, which means any place that _values_ go through a NumPy kernel.

### Motivation

The `nplike` mechanism is closely related, yet distinct from, the kernel dispatch mechanism. At present we require (implicitly) that the inputs to kernels all have the same nplike. Most kernels operate exclusively on index values, with the notable exception of reducers and a few kernels (IIRC) look at both index and content. In these latter cases, we do not want backends that mix the index and content `nplike`s to be able to invoke the kernel. A simple way to do this is to explicitly define the `nplike` of the kernel, and try to convert the raw pointers to this nplike.

**Comment by agoose77** [comment]
To add some follow up thoughts to this issue:

The only reason that we need a `backend` abstract is because we can't (easily) write kernels for JAX. In future, JAX may gain interop support for CUDA, and perhaps might add some mechanism for us to be able to write kernels that target JAX. Then it might be useful to switch between CuPy and NumPy for the index nplike, and use their reducer mechanisms. For now, we're CPU-only with JAX.

**Comment by jpivarski** [comment]
I'm going to close this because it sounds like a large project, intended to target a different design, one in which kernel invocation is decoupled from nplike functions. We've been running for a long time with the idea that kernels are just functions we'd like to have in each nplike, but have to implement ourselves because our backend libraries don't support them.

It's an interesting idea, but not a project that I would want to take on at this stage.
