### ISSUE TITLE
`ak.without_field`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1961]
### Description of new feature

It is not possible to remove a field from an `RecordArray` without rebuilding the layout manually e.g. with `ak.zip`. 

I think a natural extension of `with_field` and `__setitem__` would be `without_field` and `__delitem__`. Unlike `with_parameter`, where `None` has special meaning, `None` values are supported as array values, so we need a distinct function

**Comment by jpivarski** [comment]
~~We have a protocol, used and assumed throughout the codebase, that a missing parameter is exactly equivalent to a parameter whose value is `None`. The idea was that you can remove a parameter by assigning `None`.~~

~~Adding an `ak.without_parameter` function is still a good idea because users might not know this fact about parameters and may be looking for `ak.with_parameter`'s opposite.~~

**Comment by jpivarski** [comment]
My comment above is totally batty: I thought this was about layout `parameters`, when it's about record `fields`!

> Unlike `with_parameter`, where `None` has special meaning
