### ISSUE TITLE
`ak._connect.numexpr` is not exported under `ak.numexpr`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2000]
### Version of Awkward Array

main

### Description and code to reproduce

```
import awkward as ak
ak.numexpr.evaluate(...)
```

**Comment by agoose77** [comment]
Clearly, we also need numexpr docs / tests

**Comment by jpivarski** [comment]
Yes, but I want to check over at NumExpr to see if there's a way to do this, now (3 years later):

```python
>>> import awkward as ak, numexpr as ne
>>> one = ak.Array([[1, 2, 3], [], [4, 5]])
>>> two = ak.Array([100, 200, 300])
>>> three = ne.evaluate("one + two")
<Array [[101, 102, 103], [], [304, 305]] type='3 * var * int64'>
```

If NumExpr now supports something like a NEP13 overload (NEP13 because all NumExprs are ufunc-like), then we'd want to take advantage of it to make the user experience simpler. We'd need to have our code called in the above, to be able to do the broadcasting (like `__array_ufunc__`).

When I last talked with the author of NumExpr, we talked about this but he was busy in the transition from NumExpr 2 to NumExpr 3. That must be long-past by now.

**Comment by jpivarski** [comment]
Or... maybe not. https://github.com/pydata/numexpr/issues/350

Then I'll need to look into whether NumExpr 2 has anything like this. (Or you—go ahead if you're interested.)

**Comment by agoose77** [comment]
Closing this for now, due to #2011
