### ISSUE TITLE
ListOffsetArray type tracers (from form) raise exception when printing

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2042]
### Version of Awkward Array

2.0.4

### Description and code to reproduce

requires dask_awkward
```python3
import dask_awkward as dak
import awkward as ak

form = ak.forms.ListOffsetForm("i64", ak.forms.NumpyForm("float32", inner_shape=(2,)))
tt = dak.typetracer_from_form(form)
print(tt)
```

results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 1192, in __str__
    return awkward._prettyprint.valuestr(self, 1, 80)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 232, in valuestr
    _, strs = valuestr_horiz(data, limit_cols)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_prettyprint.py", line 99, in valuestr_horiz
    if len(data) == 0:
TypeError: 'UnknownLengthType' object cannot be interpreted as an integer
```

Strangely, `tt.__repr__()` executes just fine but when going through `tt.__str__()` I get the error!
This seems to have some knock-on problems elsewhere in dask_awkward when automatically determining typetracer metadata.

**Comment by jpivarski** [comment]
> Strangely, `tt.__repr__()` executes just fine but when going through `tt.__str__()` I get the error!

That's a good clue. `__str__` goes straight into `ak._prettyprint.valuestr`:

https://github.com/scikit-hep/awkward/blob/6efa28727e2877daa9369f1efb265b5a630588fb/src/awkward/highlevel.py#L1934-L1937

which immediately touches the data:

https://github.com/scikit-hep/awkward/blob/6efa28727e2877daa9369f1efb265b5a630588fb/src/awkward/_prettyprint.py#L224-L229

but `__repr__` has a special code-path for typetracers:

https://github.com/scikit-hep/awkward/blob/6efa28727e2877daa9369f1efb265b5a630588fb/src/awkward/highlevel.py#L1942-L1971

which also touches the data... Aha! The problem is that the `ak._prettyprint.valuestr` touches the data _and does not exit_. It should not attempt to extract data from the `TypeTracerArray`, which will fail. It should probably return a string like `"[...]"` immediately after declaring all of the data touched.
