### ISSUE TITLE
`ak.ArrayBuilder.type` contains non-canonical union

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2054]
### Version of Awkward Array

main

### Description and code to reproduce

In the following example, the `ak.ArrayBuilder()._layout.form()` contains a union that is ultimately simplified. However, the `type` attribute looks at this form, and so includes the union.

```python
import awkward as ak
from numba import njit


@njit
def func(builder):
    builder.begin_record("x")
    builder.field("time").real(2.0)
    builder.end_record()
    return builder


builder = ak.ArrayBuilder()
builder.begin_record("x")
builder.field("time").real(0.0)
builder.end_record()

func(builder)

print(builder.type)
print(builder.snapshot().type)

```

### Observations
This seems to require the same conditions as #2053

**Comment by agoose77** [comment]
I *think* what's happening is that the union is being introduced in the second call to `builder.begin_record()`, which invokes `RecordBuilder::beginrecord`. The first `begin_record()` stores the pointer to the cast result of the C string.

By the time of the second call to `begin_record()`, the contents of this C string are no longer valid, and it seems that the object allocated for the `name` argument has a different pointer.

I think it's reasonable that the original `nameptr_` contents appear to change; the lifetime of the Python `name` argument is never explicitly tied to the `ArrayBuilder` in `content.cpp`. However, the fact that the pointer itself is different suggests that we're perhaps seeing a case where interning is not happening.

In fact, that is likely what's happening — we explicitly allocate a C string in `src/awkward/_connect/numba/builder.py`. So, it might be that this fix just requires us to be a bit more clever here. The reason that this test is failing is because we're using `beginrecord_fast` which explicitly does not check the field name contents for performance. Maybe this should be a Numba-only feature, because in Python the other overheads are likely just as problematic as the string comparison? i.e. `beginrecord` invalidates the `beginrecord_fast` optimisation pointer?

**Comment by jpivarski** [comment]
You're right: there is this distinction between beginrecord_check and beginrecord_fast, and it's very likely that Numba is set to use beginrecord_fast. Python must use beginrecord_check, since there's no notion of a string pointer.

The fact that they get union-simplified is a good change. It was an accident-an unintended consequence of adding simplification to ArrayBuilder snapshots—but a good one.

The only issue here, then, is that the Form doesn't get passed through the same simplification routine. Forms have the same simplification constructors as Contents, so it should be possible to mirror it.

The UnionForm simplification takes an easy, slow-ish, but safe route of making a length-zero array, simplifying that, and then taking the Form (instead of trying to reproduce the Content's logic).

(And happy new year!)

**Comment by agoose77** [comment]
Happy new year!

Right, after reading this code _again_, although this code-path should probably be updated to explicitly invalidate the pointer when crossing the Numba boundary, it currently "works". It explains why we have a Union with Numba + Python, but not with Numba + Numba, or Python + Python, but this should be simplified away anyway.

So, as you say, the course of action is to ensure that the form gets simplified.
