### ISSUE TITLE
TypeError in ak.to_packed with UnionType

### ISSUE THREAD

**Issue by grst** [scikit-hep/awkward#2058]
### Version of Awkward Array

2.0.5

### Description and code to reproduce

I'm getting a TypeError when calling `ak.to_packed` on a UnionType of two RegularTypes with different dimensions. 

Context: this is a unit test case from https://github.com/scverse/anndata/pull/647 that failed after upgrading to v2.x. 

```python
arr = ak.concatenate([ak.Array(np.ones((2, 2))), ak.Array(np.ones((2, 3)))])
ak.to_packed(arr)
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sturm/anaconda3/envs/anndata_dev/lib/python3.9/site-packages/awkward/operations/ak_to_packed.py", line 70, in to_packed
    return _impl(array, highlevel, behavior)
  File "/home/sturm/anaconda3/envs/anndata_dev/lib/python3.9/site-packages/awkward/operations/ak_to_packed.py", line 75, in _impl
    out = layout.to_packed()
  File "/home/sturm/anaconda3/envs/anndata_dev/lib/python3.9/site-packages/awkward/contents/unionarray.py", line 1550, in to_packed
    return UnionArray(
  File "/home/sturm/anaconda3/envs/anndata_dev/lib/python3.9/site-packages/awkward/contents/unionarray.py", line 81, in __init__
    raise ak._errors.wrap_error(
TypeError: while calling

    ak.to_packed(
        array = <Array [[1, 1], [...], ..., [1, 1, 1]] type='4 * union[2 * ...'>
        highlevel = True
        behavior = None
    )

Error details: UnionArray cannot contain mergeable 'contents' (RegularArray of '2 * float64' and RegularArray of '3 * float64'); try UnionArray.simplified instead
```

**Comment by jpivarski** [comment]
There are two steps: the first merges everything with equivalent types (e.g. "list of floats" and "list of ints" are mergeable); everything that is not mergeable becomes a UnionArray. The second step is in the UnionArray constructor, which complains if it gets mergeable data.

Evidently, these two steps disagree on what is mergeable and what is not.

There are two possible choices we could make about this:

  * We could say that the first step is right, and `2 * float64` is not mergeable with `3 * float64`. The result should be a union of two regular list dimensions. (The `size` of regular lists is part of their type.)
  * Alternatively, we could say that the second step is right: the concatenation of `2 * float64` with `3 * float64` should be variable-length lists: `var * float64`. This preserves less information than the first policy, but non-union types are generally more useful than union types, so it may be a more practical choice.

@grst, since you're using this in an application, what would you _want_ the answer to be? I doubt anyone has considered this case before.

**Comment by grst** [comment]
We are using this for writing awkward arrays to disk. I would have expected the type of an array to be preserved and only the underlying layouts to be changed by this `ak.to_packed`, so the first of the two options.

**Comment by agoose77** [comment]
@grst to elaborate on Jim's point; the bug is in the discrepancy between our simplification tests and our simplification implementation. However, we can pick one of Jim's options, so we could choose for `ak.concatenate` to coerce incompatible regular dimensions to a ragged dimension.

That said, @jpivarski is there any nice way to recover the union if we made option (2) the default? For option (1) we can just to `ak.from_regular()` which drops the union, but there's no obvious way to do the same for (2). My feeling, if this is the case, is that the regular/ragged distinction is really important, so we should preserve it with the union. Many operations, I would assume, will erase the union naturally anyway.

**Comment by jpivarski** [comment]
Choosing option (2) would mean declaring `union[2 * float64, 3 * float64]` to be _invalid_, just as, say, `union[int32, float64]` is invalid (since numbers are mergeable). Even though this is information-losing, I think it's the way we want to go—I suspect that we want to pick option (2), not option (1)—because unions are so hard to deal with.

But just to be clear about what the consequences are: not only do we lose information, turning the above into `var * float64` (only knowing that the lists have different lengths, not the fact that the lengths can only be `2` or `3`), but it would also be impossible to construct `union[2 * float64, 3 * float64]` if you knew you wanted that (if we go with option (2)). That sounds like a dire warning—that we won't even be able to express something—but I _still_ think it's the right way to go. How useful is it to be able to say "the lengths of these lists differ, but they're all drawn from the set `{2, 3}`"? It doesn't help with slicing, which is a runtime check, anyway.

If you had an array of lists with type `var * float64`, but you happened to know more than the type system: you happened to know that some lists have length `2` and some have length `3`, and you want to use that fact, you could still impose it like this:

```python
length_2 = ak.to_regular(array[ak.num(array) == 2])
length_3 = ak.to_regular(array[ak.num(array) == 3])
```

which involves some runtime checks. (I'm using the word "runtime" to mean something that can't be determined from the types, but running the code would fail if the invariant isn't true. For instance, dask-awkward would build the graph, and any failures would happen while executing the graph on a Dask worker.)

------------------

Some more context for @grst: this has to do with a new constraint that we're applying to union-type and option-type arrays, starting in #1910/#1928/#1939. It used to be that there were some constructions, like

```
option[option[float64]]
```

or

```
union[int64, int64]
```

that were not considered valid, but also not rejected by the constructors because we needed to be able to make arrays like this temporarily in some of our implementations. When code accepts arrays from a user, I said it didn't have to handle these invalid cases, which can be pretty complicated. However, that's not a good situation for multiple developers and long-term maintainability, since the code wouldn't tell you whether a construction is valid or not and whether the case can be ignored.

So #1910/#1928/#1939 made these dubious cases actually invalid: the layout constructors check for them and raise errors, and there's a work-around for our code to express these things temporarily, but always return valid constructs.

The new restrictions on union-type and option-type layouts are listed here: https://github.com/scikit-hep/awkward/pull/1939#issuecomment-1336057331, and specifically for unions:

> A union type must:
> 
> * never contain another union type
> * contain at least two `contents`
> * none of those `contents` may be `mergeable` with any of the other `contents` (mergeability is an equivalence relation)

What happened in your case is that two parts of the code are apparently disagreeing on what "mergeable" means. One says that `2 * float64` and `3 * float64` are mergeable (into `var * float64`) and the other says that they are not. To be clear, this is _our_ bug (in Awkward), and we need to fix it. But the question is, fix it which way?

Above, I'm campaigning for saying that `2 * float64` and `3 * float64` should be mergeable, so that concatenating different-shape regular arrays at `axis=0` (which NumPy would not allow) would result in a ragged array, rather than a union array (both of which are beyond NumPy). We want to think about this before committing to it, though, to be sure that this doesn't lead to any unintended consequences. I'm thinking about it and I don't foresee any. @agoose77? @ioanaif? @ianna?

**Comment by agoose77** [comment]
Not disagreeing with you, but this discussion always makes me ask the question "what purpose do unions satisfy?". In fact, disagreeing with you, I would argue that we introduce unions for more clear-cut cases like `(str, int)` or `(var * int, int)`, so why not `(2 * var, 3 * var)`?

This is to say; making a decision on what `ak.concatenate` should do here is implicitly making a statement about the purpose and function of `Union`, which I'm not sure about.

**Comment by jpivarski** [comment]
Unions have limited usefulness. For instance, suppose that data comes from a JSON source that involves heterogeneity, such as GeoJSON. (2D points and polyline regions are in the same collection, distinguished by a string value, but one has deeper nestedness than the other.) To use it in Awkward Array, you'd want to read the JSON into a union array, select the different-type objects with slices (`array.coordinates[array.data_type == "Point"]`), and then work with non-union arrays. If we couldn't represent unions at all, users wouldn't be able to get through the data-cleaning stage.

**Comment by agoose77** [comment]
So, with this proposal, we'd be constraining unions to be a mechanism for representing otherwise irrepresentable types, instead of accurately preserving type information. 

As I write this, I think of `int`-`float`, or `int`-`bool` (for `mergebool=True`). These are distinct types but have coercion rules. With the above lens, I'd be happy to extend this to merging distinct regular dimensions.

**Comment by jpivarski** [comment]
We've already been merging `int` and `float`, and have long considered `union[int, float]` to be invalid, though only recently are we enforcing that. Booleans are still distinct from integers (`mergebool=False` in the UnionArray constructor).

If nobody has any objections, we can adopt a policy of regular-N ⊕ regular-N = regular-N, but regular-N ⊕ regular-M = irregular (instead of union(regular-N, regular-M)) in the `mergeable` and `mergemany` functions (where ⊕ means "merge arrays"). Fixing this issue would amount to enforcing that rule consistently.

**Comment by agoose77** [comment]
Fab, we're on the same page. In fact, @jpivarski, so are you and @ioanaif — the following example _already_ does this:
```python
x = ak.from_numpy(np.arange(4 * 3).reshape(4, 3), regulararray=True)
y = ak.from_numpy(np.arange(4 * 2).reshape(4, 2), regulararray=True)

ak.concatenate((x, y))
```

However, because we special-case `NumpyArray`s, our implementation differs for the non-regulararray case:
```python
x = ak.from_numpy(np.arange(4 * 3).reshape(4, 3), regulararray=False)
y = ak.from_numpy(np.arange(4 * 2).reshape(4, 2), regulararray=False)

ak.concatenate((x, y))
```

**Comment by agoose77** [comment]
Notes to self - the planned fix here will do the simplest thing of converting NumpyArray to RegularArray eagerly using a strided view, avoiding a copy for non contiguous-arrays. JAX will incur a copy penalty, however.
