### ISSUE TITLE
`ak.to_layout(str)` does not throw exception

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2070]
### Version of Awkward Array

main

### Description and code to reproduce

If `string` is a primitive type, then `to_layout` should not succeed; we don't support `to_layout(10)`, but `to_layout("10")` returns a length-one array of strings. This is seen in `ak.type("string")`, which returns `1 * string` instead of erroring, whilst `ak.type(10)` returns `int64`. 

It's not immediately obvious what we should do here. I am leaning towards suggesting that `ak.type()` should not support the leaf types (int64, string, etc), because it should operate on arrays.

**Comment by jpivarski** [comment]
The main purpose of `ak.to_layout` is to prepare array-like arguments for other functions, so it should be designed for that. For that purpose, `ak.to_layout("10")` returning a length-one array of strings sounds right, since we'd want

```python
ak.something_or_other("one")
```

to work like

```python
ak.something_or_other(ak.Array(["one"]))
```

By that argument, `ak.to_layout(10)` should return a length-one array of integers, though.

What `ak.type` does can be brought into line with `ak.to_layout`, though it may just be better to deprecate `ak.type`. It's now redundant with `ak.Array.type`, `ak.Record.type`, and `Content.form.type`.

Well, no, we still need `ak.type` in case someone overloads that method in an `ak.Array`/`ak.Record` subclass. The word "type" is pretty general. But anyway, after getting `ak.to_layout` to do the right thing for function arguments, `ak.type` can be brought into agreement with it; it can return the type of array that `ak.to_layout` would have created.

Keep in mind, though, that `ak.to_layout` creates layouts, whose types differ from the corresponding `ak.Array` by not including the `ak.types.ArrayType` wrapper (which has the array length):

```python
>>> array = ak.Array([[1, 2, 3], [], [4, 5]])

>>> ak.type(array)
ArrayType(ListType(NumpyType('int64')), 3)
>>> print(ak.type(array))
3 * var * int64

>>> ak.type(array.layout)
ListType(NumpyType('int64'))
>>> print(ak.type(array.layout))
var * int64

```

**Comment by agoose77** [comment]
@jpivarski I'd be strongly in favour of simplifying `ak.type` to return
```python
return ak.types.ArrayType(
            self._layout.form.type_from_behavior(self._behavior), self._layout.length
        )
```
with the suitable case for non-layout arguments?

IIRC we rely on `ak.to_layout` leaving scalars intact elsewhere in the program, so I'd consider it sensible to do the same for strings. But equally, we're probably relying on the current behaviour for strings. Fundamentally, `ak.type("string")` and `ak.type(["string"])` should return different results, but I'm not decided upon what I think the best path to this is yet :)

**Comment by jpivarski** [comment]
Layouts need to be nestable/self-similar, including the `ArrayType` wrapper would break that. Certainly `layout.form.type` shouldn't include the `ArrayType` wrapper; `ak.type` could, but then `ak.type` would be returning a different result than `layout.form.type`.

(Less importantly, layouts don't have a `self._behavior` to pass to `type_from_behavior`.)

It's these weirdnesses that make me want to banish `ak.type` overall, but I don't think we can do that because "type" is a common word that might be overridden in the `ak.Array` subclass namespace.

> IIRC we rely on `ak.to_layout` leaving scalars intact elsewhere in the program

Good point!

https://github.com/scikit-hep/awkward/blob/8d7a2c31f1ea24cef8a909fb12bb14eb812477ac/src/awkward/operations/ak_to_layout.py#L14

has an `allow_other` argument for passing through scalars unharmed, so the same thing should happen to string-scalars. This is still using the principle that `ak.to_layout` should do what `ak.*` argument-handling needs, but making the important point that it needs to pass some arguments through as scalars.

I'm in favor of making `ak.to_layout("string")` return `"string"`, without a deprecation cycle because I don't see a good way to do it.

**Comment by agoose77** [comment]
> Layouts need to be nestable/self-similar, including the ArrayType wrapper would break that. Certainly layout.form.type shouldn't include the ArrayType wrapper; ak.type could, but then ak.type would be returning a different result than layout.form.type.

What I'm proposing is that the high-level function directly replicates the high-level `Array.type` logic. And, I'd go as far as to say that it should always wrap with the `ArrayType` wrapper, even if a low-level layout is passed in. But, you make a case for replicating the high/low-level distinction, so we could also use a simple switch

```python
layout = ak.to_layout(array, ...)
layout_type = layout.form.type_from_behavior(behavior)
if is_high_level(array):
    return ak.types.ArrayType(
	    layout_type, layout.length
	)
else:
    return layout_type
```

> I'm in favor of making ak.to_layout("string") return "string", without a deprecation cycle because I don't see a good way to do it.

This is what I like most of the options on the table. I suspect that something like `ak.fill_none` etc might want to receive a layout here, but I think we can special case that and improve our robustness vs keeping this peculiarity.

**Comment by jpivarski** [comment]
Maybe `ak.type` should take `highlevel` and `behavior` arguments, like most other `ak.*` functions, and use them to decide whether or not the output is wrapped in `ArrayType` and what to pass to `type_from_behavior`?

Then, at least, we'd have a good explanation why

```python
isinstance(ak.Array([1, 2, 3]).type, ak.types.ArrayType)
```

is `True`,

```python
isinstance(ak.Array([1, 2, 3]).layout.form.type, ak.types.ArrayType)
```

is `False`, and

```python
ak.type(ak.Array([1, 2, 3]).layout)
```

returns something different from `layout.form.type`: "it's guided by `ak.type`'s `highlevel` and `behavior` arguments, not by the Python type of the first argument."

**Comment by agoose77** [comment]
> Maybe ak.type should take highlevel and behavior arguments, like most other ak.* functions, and use them to decide whether or not the output is wrapped in ArrayType and what to pass to type_from_behavior?

Hehe, I also had the same thought. I'm happy to choose that solution over type-dependence. It would be easier to reason about, for one thing.

**Comment by jpivarski** [comment]
It seems like a good way to go. I'm in favor of that (`highlevel` argument fully determining whether the output has an `ArrayType` or not).

The idea of the output of a function named `ak.type` depending on type doesn't sound wrong, but this "include `ArrayType` or not" is special.
