### ISSUE TITLE
`ak.merge_union_of_records` not merging `Union[var * {a: int, b:int}, var * {a: int}]`

### ISSUE THREAD

**Issue by ivirshup** [scikit-hep/awkward#2211]
### Version of Awkward Array

2.0.7

### Description and code to reproduce

I've found what I think is a bug in the recently added `merge_union_of_records`. With the following input it seems to be a no-op, when I would have expected it to result in `5 * var * {a: int: b: ?int}`

```python
>>> a = ak.Array([[{"a": 1, "b": 4}], [{"a": 2, "b": 5}, {"a": 3, "b": 6}]])
>>> b = ak.Array(
...     [
...         [{"a": 4}, {"a": 5}],
...         [{"a": 6}],
...         [{"a": 7}],
...     ]
... )
>>> a.type.show()
2 * var * {
    a: int64,
    b: int64
}
>>> b.type.show()
3 * var * {
    a: int64
}
>>> ak.concatenate([a, b]).type.show()
5 * union[
    var * {
        a: int64,
        b: int64
    },
    var * {
        a: int64
    }
]
>>> ak.merge_union_of_records(ak.concatenate([a, b])).type.show()
5 * union[
    var * {
        a: int64,
        b: int64
    },
    var * {
        a: int64
    }
]
```

**Comment by agoose77** [comment]
Yes, from a user standpoint, this is a bug; I can clearly see that the record should be made over the innermost dimension, and the `var`s should then line up. We're only seeing this because of the policy that we have `Union[var * ..., var * ...]` instead of `var * Union[..., ...]`. I've never given that much thought; I suspect @jpivarski  has, and there's a reason that we don't try to push the union as deep as possible. It might be as simple as the way we check mergeability; we ask whether a layout is mergeable, which returns a single boolean for the entire layout tree. We don't have a mechanism for saying where the union should appear in the layout, at least, I don't think.

So, what we do here depends upon what we do with unions more generally. I *think* that pushing the union as deep as possible is more useful, and if we did so, we wouldn't need to change things function. Meanwhile, if we decide not to change that behavior, `merge_union_of_records` could rewrite the records first and then simplify, with additional checks to ensure that the union disappears.

**Comment by ivirshup** [comment]
> there's a reason that we don't try to push the union as deep as possible

I would imagine that `union[var * x, var * y]` is more efficient that `var * union[x, y]`.  With `var * union[...]` you end up with large index arrays for the union, and much more frequent branching during execution.

**Comment by ivirshup** [comment]
As desired behavior, I would expect this to propagate through matching dimensions. E.g.:

* `n * Union[10 * {a: int}, 10 * {b: int}] -> n * 10 * {a: ?int, b: ?int}`

<details>
<summary> current </summary>

```python
a = ak.Array([np.repeat(np.array([{"a": 1}], dtype=object), 10)])
b = ak.Array([np.repeat(np.array([{"b": 2}], dtype=object), 10)])

res = ak.to_regular(ak.concatenate([a, b]))
# 2 * union[10 * {a: int64}, 10 * {b: int64}]

ak.merge_union_of_records(res)
# 2 * union[10 * {a: int64}, 10 * {b: int64}]
```

</details>

* `n * Union[{a: {b: int}}, {a: {c: int}}] -> n * {a: {b: ?int, c: ?int}}`

<details>
<summary> current </summary>

```python
a = ak.Array([{"a": {"b": 1}}])
b = ak.Array([{"a": {"c": 2}}])

res = ak.concatenate([a, b])
res.type.show()
# 2 * union[
#     {
#         a: {
#             b: int64
#         }
#     },
#     {
#         a: {
#             c: int64
#         }
#     }
# ]

ak.merge_union_of_records(res).type.show()
# 2 * {
#     a: union[
#         {
#             b: int64
#         },
#         {
#             c: int64
#         }
#     ]
# }
```

</details>

**Comment by jpivarski** [comment]
When a UnionArray of unknown contents is created, it goes through `UnionArray.simplified`, which checks the proposed `contents` to see if they're mergeable. If they're `var * A` and `var * B` and `A` and `B` are not mergeable, then it won't merge them.

But this is a new case, yet another different thing that could be eliminated by `UnionArray.simplified`. Before any other checks, this constructor could see if all of the given `contents` are lists. If they *all* are, it would build a new `offsets` for them all, expanding the `tags` and `index` to apply to the contents of the lists, rather than the lists themselves, and return a ListOffsetArray whose content is the result of a recursion on `UnionArray.simplified`. If any one of those original `contents` had an option-type, that would wrap the output ListOffsetArray.

It's possible, but rather complex and it might need new kernel functions. Also, maybe it should happen on a minor version boundary because it's a breaking change.

What would you (everyone) think about intending to do it and for now, just identifying the situation to add a warning about the coming change? Identifying the situation is not nearly as complex as implementing it.

**Comment by ivirshup** [comment]
> Also, maybe it should happen on a minor version boundary because it's a breaking change.

I think it could be considered a bug if the behavior was the original intent.

But this may not be the case if this isn't specific to `merge_union_of_records`, and is instead more general to unions.

----

> What would you (everyone) think about intending to do it and for now, just identifying the situation to add a warning about the coming change? Identifying the situation is not nearly as complex as implementing it.

I think a warning, possibly also in the docs, would be a good step. I agree this seems complicated to implement.

Do you think the proposed solution is more difficult than an `Array.astype(t: ak.types.Type)` method?

**Comment by jpivarski** [comment]
Well, it's not that it was unintended behavior so much as an unconsidered case. In the beginning, my idea was that all types are a free monoid of these generators:

  * primitive types (booleans, numbers, datetimes, timedeltas)
  * list types (may count as two generators if we distinguish `var *` from `## *`)
  * record types (tuples and structs; the field names are almost-irrelevant metadata)
  * option types
  * union types

You've already pointed out that option types can be implemented in terms of unions if we had a unit type primitive (`None` is the only member of `NoneType`). Even though we don't use that implementation, that fact implies that the type system we want is not a _free_ monoid; there are equivalences like

```
option[union[X, Y]] == union[option[X], Y] == union[X, option[Y]] == union[option[X], option[y]]
```

(due to a more fundamental equivalence, `union[X, union[Y, Z]] == union[X, Y, Z]`, in which `Z` is the unit type primitive).

The PRs associated with #1910 were intended to "divide through" these equivalences, replacing the members of each equivalence class with a canonical form that represents that class. So, for instance, any of the above would be replaced by

```
union[option[X], Y]
```

as the only form we construct.

What you discovered here is another equivalence class:

```
union[list[X], list[Y]] == list[union[X, Y]]
```

We're finding these now because you're evidently focusing a lot on unions. That's great—we were hoping new use-cases would reveal blind spots. HEP users do sometimes use unions, but all the cases I've seen have been unions of distinguishable records, so there was no reduction to be done.

Without unions, I'm pretty sure that the space of all types really is a free monoid:

   * primitive types
   * list types
   * record types
   * option types

Any combination of these is distinguishable. For instance,

```
list[option[X]] != option[list[X]]
```

because the left hand side is saying that the `X` values can be replaced by `None`, whereas the right hand side is saying that the _lists_ can be replaced by `None`. (Google products, like Protobuf, don't seem to make the distinction between a missing list and a list of missing elements, but I think it's important.)

I used to think there was a symmetry between records ([product types](https://en.wikipedia.org/wiki/Product_type)) and unions ([sum types](https://en.wikipedia.org/wiki/Tagged_union)) because every instance value of `record[X, Y, Z]` is an `X` and a `Y` and a `Z`, whereas every instance value of `union[X, Y, Z]` is an `X` or a `Y` or a `Z`, but the distinction between "and" and "or" is really deep. I'm pretty sure that any tree that you make of records, with or without lists and option types, has instance values that are distinguishable from another tree,

```
record[X, record[Y, Z]] != record[X, Y, Z] != ...
```

but that's not at all the case for unions:

```
union[X, union[Y, Z]] == union[X, Y, Z]
```

Since you found one more, I'm thinking we should do some sort of search to see if there aren't other equivalences. We'd like to be aware of all the algebraic simplifications that can be done because replacing each equivalence class by one canonical member means that there are a lot of type-combinations that we can ignore in our implementations.

I'm thinking about doing a brute-force search. We don't expect any type equivalence expression to be deeper than, say, three nodes deep, unless that expression is just a composition of other expressions. Maybe SymPy could be brought into this.

Or maybe there's a general theory for this stuff, and I just need to find the right computer scientist to take a look and say, "Oh yeah, that's just lasdkjhflakdfjh-theory. It's in so-and-so's textbook."

I'll look into this and come up with something. At least we can add the

```
union[list[X], list[Y]] == list[union[X, Y]]
```

that you found to our list of to-do items.

**Comment by jpivarski** [comment]
Oh, and `Array.astype(t: ak.types.Type)` is a bigger project than adding this one equivalence to union-building. Since an `astype` function would construct a new tree, it would be _using_ what we do here, and inherit all the equivalences that the constructors implement.

**Comment by jpivarski** [comment]
I'm working with that brute-force approach and discovered something: if we rewrite

```
union[list[X], list[Y]] → list[union[X, Y]]
```

then we can get into situations in which

```
union[list[union[X, Y]], Z]
```

is not considered equivalent to

```
union[list[X], list[Y], Z]
```

It would generally be better to have fewer unions than more, so maybe the canonical form should actually be

```
list[union[X, Y]] → union[list[X], list[Y]]
```

(i.e. prefer moving unions outside of lists, rather than the other way).

**Comment by jpivarski** [comment]
Here's the result of the brute-force approach: https://gist.github.com/jpivarski/ea00b9269fc77b0c9b8aa7da6111ed62

The final set of rules that merges all equivalent types down to depth 3 (depth 2 for unions of 3 contents) is:

  1. Apply the canonization rules recursively to lists and unions.
  2. Rewrite `list[union[X, Y, ...]] → union[list[X], list[Y], ...]` (unions always go outside of lists).
  3. Rewrite `union[X, union[Y, Z, ...], ...] → union[X, Y, Z, ...]` (flatten unions of unions).
  4. Rewrite `union[X] → X` (no single-content unions).

We're already applying 1, 3, and 4. The new rule would be 2, which is the only one that has any interaction between lists and unions. And unlike what I said above, it would move the union _outside_ of any lists, rather than inside.

If we moved the union _inside_ of lists, then we would have to add additional rules to handle cases like

```
union[list[union[X, Y]], Z]
```

(i.e. a rule that would have to look at 3 levels). I wouldn't have noticed that without doing the brute-force search, so even though it's not a mathematical proof, it was useful to do.

I _think_ it would also be easier to implement in Awkward Array, too. Also, @ivirshup's point is a good one,

> I would imagine that `union[var * x, var * y]` is more efficient that `var * union[x, y]`. With `var * union[...]` you end up with large index arrays for the union, and much more frequent branching during execution.

we would generally get smaller `UnionArray.index` buffers this way, as long as the average list length is greater than 1.

-----------------------------

Thinking about how this would be implemented, I realize now that it's a big change. We wouldn't need to touch `ak.merge_union_of_records` or `UnionArray.simplified`, but we would need to _add_ a `ListArray.simplified` (for all the list types), which check to see if the `content` is a `UnionArray` and would return a union of lists instead.

The hard part is that all of the list-constructors of unknown `content` would have to be replaced by this `simplified` constructor, and subsequent code couldn't assume that it has a list-type. We did that for all of the `UnionArray` constructors, but lists are much more widespread.

So for instance, the list-constructor in

```python
>>> ak.from_regular(ak.Array([1, 2, 3, "a", "b"])[np.newaxis], axis=1)
<Array [[1, 2, 3, 'a', 'b']] type='1 * var * union[int64, string]'>
```

would have to be sensitive to the fact that the new list could contain a union and have to bubble the union out, to make type `1 * union[var * int64, var * string]`.

In fact,

```python
>>> ak.unflatten([1, 2, 3, "a", "b"], [3, 0, 2])
<Array [[1, 2, 3], [], ['a', 'b']] type='3 * var * union[int64, string]'>
```

Oh, wait a minute—

```python
>>> ak.unflatten([1, 2, 3, "a", "b"], [2, 0, 3])
<Array [[1, 2], [], [3, 'a', 'b']] type='3 * var * union[int64, string]'>
```

This _can't_ be converted into a `3 * union[var * int64, var * string]` because that assumes that no list contains both integers and strings. And that's a value-dependent distinction—a type-tracer could never know whether it can do that or not.

So unions _can't_ (in general) be bubbled out of lists. It _has to_ go the other way.

Back to the drawing board...

**Comment by jpivarski** [comment]
Okay, so this has been a long, strange trip, but in the end, I think there's _nothing that needs to be changed_ (in `UnionArray.simplified`, at least; we'll come back to `ak.merge_union_of_records` later, which is what this issue was originally about).

Suppose that we have this type:

```
union[list[X], list[Y]]
```

_If_ we were to convert it into `list[union[X, Y]]`, that that would be _losing_ information. A union of list-types is saying that the contents of each (instance value) list can't be mixed, but a list of union-type is saying that each (instance value) list could be mixed.

Suppose that we have this type:

```
list[union[X, Y]]
```

We can't convert it into `union[list[X], list[Y]]` at all because the list boundaries might not line up to give homogeneous `X` in some lists and homogeneous `Y` in other lists. Even if that's possible, it would be an instance value-dependent question, not something that can be applied to arrays in general (it would be impossible for typetracers and therefore Dask).

So at the very least, a user needs to be involved in deciding to do the information-losing operation (just as `ak.merge_union_of_records` exists to perform an information-losing operation). I don't think it should be the same function because the word "list" isn't anywhere in its name.

So if this is really needed, it can only go in one direction, and it would need to be yet another library function. Since it's invoked by a user, it doesn't need any deprecation cycle.

Sorry about the run-around! In the end, it has an objective answer—it just took me a long time to see it.

**Comment by ivirshup** [comment]
Interesting to see the process here! But yeah, it makes a ton of sense that you can't do:

> `list[union[X, Y]] → union[list[X], list[Y]]`

But is this what you're referring to here: 

> So if this is really needed, it can only go in one direction, and it would need to be yet another library function. Since it's invoked by a user, it doesn't need any deprecation cycle.

or was it `ak.merge_union_of_records`? Since to me this is going in the opposite direction of `ak.merge_union_of_records`.

------------

> We're finding these now because you're evidently focusing a lot on unions.

I'm really focussing a lot on concatenation. It's just that concatenation is giving us unions and we're trying to eliminate them.

**Comment by agoose77** [comment]
@jpivarski another option is that rewriting
```
union[list[X], list[Y]] → list[union[X, Y]]
```
support non-list types, e.g.
```
union[list[X], U, list[Y], V] → union[list[X], list[Y], U, V] → union[list[union[X, Y]], U, V]
```

I don't initially think it's better; yes, we identify an equivalence relation, but we now have two unions. It's also possible that this introduces a new equivalence somehow; I haven't given it much thought.

So, with that said, @ivirshup I think Jim's suggestion is that we have a _separate_ function that performs `union[list[X], list[Y]] → list[union[X, Y]]` such that a subsequent application of `merge_union_of_records` would work in your example.
```
1) Union[List[Record[a: ..., b: ...]], List[Record[a: ...]]]
# `merge_union_of_lists`
2) List[Union[Record[a: ..., b: ...], Record[a: ...]]]
# `merge_union_of_records`
3) List[Record[a: ..., b: ?...]]
```

**Comment by agoose77** [comment]
I'm working on this feature [here](https://github.com/scikit-hep/awkward/pull/2235).

**Comment by jpivarski** [comment]
That's right. If this is really needed, it should be a separate function from `ak.merge_union_as_records`. As you pointed it, it's seemingly going in the other direction, but perhaps more importantly, the name "merge union as records" doesn't mention lists, and here we're talking about an interaction between unions and lists.

Let's move this discussion to #2235.

**Comment by agoose77** [comment]
@ivirshup I wanted to follow up on #2267 here; we will be performing a final patch release of the `awkward==2.0.*` series soon. It would be useful to know whether your use case is addressed sufficiently by this new function in conjunction with `ak.concatenate`. 

An example usage is:
```python3
x, y, z = ak.broadcast_fields(x, y, z)
w = ak.concatenate([x, y, z], axis=0)
```

Do let me know if you get a chance to try it out; I would love to hear your findings! :)

**Comment by ivirshup** [comment]
I think I can take a look in ~a week or so. Is this feature going to be in that release by then or on the main branch?

**Comment by jpivarski** [comment]
It will be in a release by a week from now. In fact, maybe I should make a patch release now.

**Comment by jpivarski** [comment]
https://github.com/scikit-hep/awkward/releases/tag/v2.0.9
