### ISSUE TITLE
`ak.from_buffers` does not accept `with_name` argument

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#2262]
### Version of Awkward Array

master branch

### Description and code to reproduce

`with_name` (None or str): Gives tuples and records a name that can be
            used to override their behaviour

```python
contents[col] = ak.from_buffers(
                form,
                length,
                buffers,
                byteorder=ak._util.native_byteorder,
                highlevel=highlevel,
                behavior=behavior,
                # FIXME: with_name=with_name,
            )
```

**Comment by agoose77** [comment]
@ianna is this a feature request, or is it something that we're already supposed to support e.g. because the documentation / code samples say so?

**Comment by ianna** [comment]
> @ianna is this a feature request, or is it something that we're already supposed to support e.g. because the documentation / code samples say so?

I think it's an issue to discuss: when a new behaviour is assigned it may need a `with_name` argument.

**Comment by jpivarski** [comment]
This is a feature request. The `ak.from_buffers` function doesn't have a `with_name` argument because it had never been proposed. `ak.zip` and `ak.Array` have a `with_name` argument (which just calls `ak.with_name` or its `_impl`) for user-convenience.

In terms of the 4 levels of privateness:

  * L1: public, intended for data analysts, most of the `ak.*` namespace
  * L2: public, intended for downstream developers, layouts, Forms, and such
  * L3: private, starts with an underscore, but accessible throughout the Awkward codebase
  * L4: private, starts with an underscore, accessible only within a narrow context (single file or a class's private methods, etc.)

the `ak.from_buffers` is more of an L2 function than an L1 function. Using it means passing it a Form, which is generally an L2 thing.

`ak.zip` and `ak.Array` are definitely L1 and we want to make things convenient in interactive environments (Jupyter) for them, and adding a name to a newly created record is something that needs to be easy, to encourage people to use behaviors. But with `ak.from_buffers` being L2... developers tend to prefer building-block architectures over shorter-to-type—I think they'd rather just call the `ak.with_name` function directly, rather than have to know that the `with_name` argument is equivalent to it (and then be forced to pick a style, which one to prefer, since they do the same thing).

For this reason, I'd lean toward not adding `with_name` as an argument to `ak.from_buffers`.

**Comment by ianna** [comment]
Thanks, @jpivarski ! Yes, it make sense - I'm closing the issue.
