### ISSUE TITLE
Memory leak when using array of strings

### ISSUE THREAD

**Issue by skr0x1c0** [scikit-hep/awkward#2330]
### Version of Awkward Array

2.1.1

### Description and code to reproduce

Unbounded memory growth when using arrays with strings. Running the following code will demonstrate the issue. In each loop iteration, memory usage keeps on increasing

``` python
import awkward as ak

from tqdm.cli import tqdm

def f(arr):
    result = 0
    for i in range(len(arr)):
        result += (arr[i] == "mov")
    return result


for i in tqdm(range(100)):
    arr = ak.Array(['aaaaa' * 100 * 1024] * 1024)
    f(arr)
```

**Comment by jpivarski** [comment]
(In my tests, and presumably in your case as well...) It keeps increasing because it hasn't reached the limit of what the Python process is allowed, so the garbage collector doesn't get invoked. You can test that (I just did) by inserting `gc.collect()` between each iteration:

```python
import awkward as ak
import gc

def f(arr):
    result = 0
    for i in range(len(arr)):
        result += (arr[i] == "mov")
    return result


for i in range(100):
    arr = ak.Array(['aaaaa' * 100 * 1024] * 1024)
    f(arr)
    gc.collect()
```

This code produces a lot of little strings. (I can follow up with a better way to do it, but maybe you know it already and this is just a demonstration of the effect.)

**Comment by jpivarski** [comment]
For what it's worth, a vectorized way to count the number of strings that are equal to `"mov"` (replacing `f`) is

```python
ak.count_nonzero(arr == "mov")
```

The default `axis=None` for [ak.count_nonzero](https://awkward-array.org/doc/main/reference/generated/ak.count_nonzero.html) gives you a scalar; if what you intended here was to apply it to a jagged array of strings and get an array, a count either along the first or second axis, then set `axis=0` or `axis=1`.

Using a vectorized expression like this is not only much faster (`ak.Array.__getitem__`, used in "`arr[i]`", is slow—much slower than a builtin Python list), it also doesn't create all of those little strings that have to get cleaned up by garbage collection. It also releases [Python's GIL](https://realpython.com/python-gil/).

**Comment by skr0x1c0** [comment]
You are right, using `gc.collect` fixes the issue in sample code. I was facing this issue while using awkward array and numba for processing a large dataset in batches. The memory usage will keep on increasing after processing each batch and eventually the process will be killed. 

The following code is correctly reproducing the issue

``` python
import awkward as ak
import numba as nb
import gc

from tqdm.cli import tqdm

@nb.njit
def f(arr):
    result = 0
    for i in range(len(arr)):
        result += (arr[i] == "mov")
    return result


for i in tqdm(range(100)):
    arr = ak.Array(['aaaaa' * 100 * 1024] * 1024)
    f(arr)
    gc.collect()
```

**Comment by jpivarski** [comment]
Indeed it is. `gc.collect()` is also returning smaller numbers, since it's finding fewer objects to free.

It also explains why you were doing an imperative loop, rather than vectorizing. Presumably, there's more to the real function `f` that requires Numba.

**Comment by jpivarski** [comment]
I jumped on this one because it looks so much like a recent (and very long-running) issue, #2311. In that issue, I was calling a Python C API function to handle strings and didn't know that it created one more reference count than I was expecting.

This is like that, but Numba is in the mix. Strings and byte objects in Numba's lowered code are actually Python strings and byte objects, so I was wrong about it releasing the GIL. It has to reacquire the GIL to call Python's C API:

https://github.com/scikit-hep/awkward/blob/c44a62280779acf199955c8632dca64b56b9fc09/src/awkward/behaviors/string.py#L235-L247

The [PyUnicode_FromKindAndData](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromKindAndData) and [PyBytes_FromStringAndSize](https://docs.python.org/3/c-api/bytes.html#c.PyBytes_FromStringAndSize) functions return a new reference, but I thought that's what Numba wanted. The data from the original array is copied into those new Python objects, but that's good because the new Python objects may outlive the original array.

The fix puts a `pyapi.decref(pystr)` right after ... !

Okay, I got it: strings and byte objects in Numba's lowered code _are not_ Python strings and byte objects ([UnicodeType](https://github.com/numba/numba/blob/4b8b176b5bdd2f93200b1eca727411c3e1657858/numba/core/types/misc.py#L530-L537) and [Bytes](https://github.com/numba/numba/blob/4b8b176b5bdd2f93200b1eca727411c3e1657858/numba/core/types/containers.py#L96-L103)), but I use Python objects to create them. After having created the Numba string or bytes object, the Numba object has a life of its own, reference-counted with Numba's Runtime (NRT), while the Python object is ignored. _That_ is why I must delete the Python object; it's not what Numba is using after all!

So this was a different issue, ultimately, than #2311, but it also came down to a misunderstanding of what the other library is doing. Actually, based on this new understanding, it ought to be possible to make Numba strings and bytes objects directly, and therefore not acquire the GIL. Maybe someday.
