### ISSUE TITLE
"NullType Arrow field must be nullable" after upgrading to newer awkward/pyarrow.

### ISSUE THREAD

**Issue by HenryDayHall** [scikit-hep/awkward#2337]
### Version of Awkward Array

2.1.1

### Description and code to reproduce

Back in awkward version 1.8.0 (pyarrow version 3.0.0) we could do;
```
import awkward as ak
to_be_saved = {"itemA": [[], [[]]]}
as_record = ak.Record(to_be_saved)
ak.to_parquet(as_record, "example.parquet")
```
However, after upgrading to awkward version 2.1.1 (pyarrow version 11.0.0) this snippet gives the error;
`NullType Arrow field must be nullable`

I think this is a bug, either in pyarrow or in awkward, but I don't see a bug report about it in either. Can this function be restored from the awkward side?

We do have some edge cases in which empty lists like this appear in some items. We also have a considerable amount of data saved in this format. There would be many workarounds involving altering the save format, but we would really like to avoid that.

**Comment by agoose77** [comment]
The minimal reproducer here is 
```python
import awkward as ak
ak.to_parquet([], "test.parquet")
```
which tries to write an `EmptyArray` to Parquet.

**Comment by HenryDayHall** [comment]
@agoose77 So actually, the reason I didn't go with that, is that this didn't work back in awkward 1.8.0 (pyarrow version 3.0.0). For example;

```

[ins] In [1]: import awkward as ak
         ...: to_be_saved = {"itemA": [[], [[]]]}
         ...: as_record = ak.Record(to_be_saved)
         ...: ak.to_parquet(as_record, "example.parquet")

[ins] In [2]: ak.to_parquet([], "example2.parquet")
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-2-2bb2c79799a9> in <module>
----> 1 ak.to_parquet([], "example2.parquet")

~/Programs/anaconda3/envs/tree/lib/python3.7/site-packages/awkward/operations/convert.py in to_parquet(array, where, explode_records, list_to32, string_to32, bytestring_to32, **options)
   3049         options["schema"] = first.schema
   3050 
-> 3051     writer = pyarrow.parquet.ParquetWriter(**options)
   3052     writer.write_table(pyarrow.Table.from_batches([first]))
   3053 

~/Programs/anaconda3/envs/tree/lib/python3.7/site-packages/pyarrow/parquet.py in __init__(self, where, schema, filesystem, flavor, version, use_dictionary, compression, write_statistics, use_deprecated_int96_timestamps, compression_level, use_byte_stream_split, writer_engine_version, data_page_version, **options)
    623             writer_engine_version=engine_version,
    624             data_page_version=data_page_version,
--> 625             **options)
    626         self.is_open = True
    627 

~/Programs/anaconda3/envs/tree/lib/python3.7/site-packages/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetWriter.__cinit__()

~/Programs/anaconda3/envs/tree/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: NullType Arrow field must be nullable

[ins] In [3]: ak.__version__
Out[3]: '1.8.0'

[ins] In [4]: import pyarrow; pyarrow.__version__
Out[4]: '3.0.0'

```

Arguably that was/is a bug too, but it can't quite be the same one.

**Comment by jpivarski** [comment]
I tried toggling a few things (including `extensionarray=False`, to turn off our new metadata-preservation), and I found that it's not a problem between Awkward and Arrow, but the Arrow → Parquet step in the pyarrow library doesn't like non-nullable unknown types.

For instance, I can run your example, replacing `ak.to_parquet` with `ak.to_arrow_table`.

```python
>>> import awkward as ak
>>> to_be_saved = {"itemA": [[], [[]]]}
>>> as_record = ak.Record(to_be_saved)
>>> ak.to_arrow_table(as_record)
pyarrow.Table
itemA: extension<awkward<AwkwardArrowType>> not null
----
itemA: [[[[],[0 nulls]]]]
```

From the way that Arrow is presenting this as a repr, it's pretty clear that they think the only purpose of this null type (equivalent of our `EmptyArray` and `UnknownType`) is to say how many missing values there are. So although it got this far, it's not too surprising why the Arrow-Parquet group didn't implement the next step of converting it to Parquet.

> We do have some edge cases in which empty lists like this appear in some items.

But you want them to be properly typed, anyway, right? If you're getting data directly from `ak.from_iter` (Python lists and dicts) and putting them in Parquet files, you won't be guaranteeing that the Parquet files have the same types, and I think you want that. This is a reminder to me that we need to create a function that would allow users to assign types to arrays, which is a tricky problem because what if the type you're trying to assign is incompatible with the array?

If these are simple fields, you can use [ak.values_astype](https://awkward-array.org/doc/main/reference/generated/ak.values_astype.html) to set leaf nodes to a given dtype. Applying this across a record with many fields is fine if you want all numeric values to have the same dtype, but it's not the right interface if you want some to be integers and others to be floating point. Also, you need to use the `including_unknown=True` flag to turn `[]` from a list of unknown type (`var * unknown`) into a list of floating point type (`var * float64`), but your data is doubly nested; what if you have `[]` and you want it to be a _list of lists_ of floating point (`var * var * float64`)? It won't be able to know that. That's why we'll need the general "assign type to array" function.

A cheesy way to do it, if you're collecting data with `ak.from_iter`, is to make a prototype of the type of data that you want, insert it as the last item in the iteration, and then slice it off (`array[:-1]`).

**Comment by jpivarski** [comment]
Note to self: the "prototype method" of assigning a type is a good hint of how to write that type-setting function. We have a way of turning a Form into a length-0 array (it's an L2 function), and if you concatenate that length-0 array onto the array with unknowns, it would give the appropriate type to those unknowns. If the types conflict, you'd get unions, which might be the right thing.

This should be turned into an issue, for brainstorming how to make that function.

**Comment by HenryDayHall** [comment]
@jpivarski 

Many thanks for taking a look at this. You are correct, ideally an empty array would retain the type that it would have possessed had it not been empty. However, given ducktyping, it's not too much of a barrier in practice.

I tried your workaround, but sadly no dice;
```
[ins] In [1]: import awkward as ak
         ...: problem_record = ak.from_iter([[], [[]], [0]])
         ...: print(problem_record)
         ...: print(problem_record[:-1])
         ...: to_be_saved = {"itemA": problem_record[:-1]}
         ...: as_record = ak.Record(to_be_saved)
         ...: out = ak.to_parquet(as_record, "example10.parquet")
[[], [[]], [0]]
[[], [[]]]
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
Cell In [1], line 7
      5 to_be_saved = {"itemA": problem_record[:-1]}
      6 as_record = ak.Record(to_be_saved)
----> 7 out = ak.to_parquet(as_record, "example10.parquet")


```

I did some tests with `to_arrow_table`, just in case that offered a work around.
In more recent versions it goes just like you say, I can make the table, but I cannot write it.

So then I started looking at `values_astype`, but that doesn't seem to effect an empty array.
```
...: my_array = ak.Array([[], [[]]])
...: my_array = ak.values_as_type(my_array, int)
...: my_array
< Array [[], [[]]] type='2 * var * var * unknown'>
```

Right now I don't have any workaround for this, but it seems vaguely possible that using the pyarrow interface directly I could construct something.

**Comment by jpivarski** [comment]
It didn't work because you had the wrong depth: the zero is supposed to be one deeper, right?

```python
>>> ak.from_iter([[], [[]], [0]]).show(type=True)
type: 3 * var * union[
    var * unknown,
    int64
]
[[],
 [[]],
 [0]]

>>> ak.from_iter([[], [[]], [[0]]]).show(type=True)
type: 3 * var * var * int64
[[],
 [[]],
 [[0]]]
```

I'm assuming that your data are not union-typed: that you don't have any data that are sometimes lists and sometimes numbers.

**Comment by HenryDayHall** [comment]
@jpivarski yes you are right, provided the dummy value is put to max depth, it fixes the issue;
```python3
import awkward as ak
def typify(my_array):
    array_type = my_array.type
    depth = 0
    # decide if the array has a proper type, and also ascertain the depth.
    while hasattr(array_type, 'content'):
        depth += 1
        array_type = array_type.content
    # If the array doesn't have a proper type
    if ak.types.UnknownType() == array_type:
        # make a dummy item to give it a type
        dummy_item = [0]
        for _ in range(depth):
            dummy_item = [dummy_item]
        as_list = my_array.to_list()
        typed_array = ak.Array(as_list + dummy_item)
        # then cut the dummy item away again
        my_array = typed_array[:-1]
    return my_array
    

my_array = ak.Array([[], [[]]])
print((my_array, typify(my_array)))
my_array = ak.Array([[], [[2.3]]])
print((my_array, typify(my_array)))

problem_record = ak.from_iter([[], [[]]])
safe_record = ak.from_iter([[], [[2.3]]])
to_be_saved = {"itemA": typify(problem_record),
               "itemB": typify(safe_record)}
as_record = ak.Record(to_be_saved)
out = ak.to_parquet(as_record, "example11.parquet")
```

**Comment by agoose77** [comment]
@jpivarski If this is a long-standing bug in PyArrow, should we add an explicit test for `EmptyArray` in Awkward's conversion routine such that we can raise an exception to inform users what this error really pertains to?

Off the top of my head, if Arrow tables can encode this information but Parquet cannot, then we should expose an option to `to_arrow_table` that is `False` by default, so that `ak.to_arrow_table` works.

**Comment by jpivarski** [comment]
There are quite a few data structures that Arrow can represent but cannot convert into Parquet. In general, I report each one in the Arrow JIRA, but I guess I didn't do this one. They eventually do get covered.

I was just trying to find the JIRA, but they've [moved to GitHub Issues](https://github.com/apache/arrow/issues) (yay)!

In trying to construct a minimal reproducer, I find that they directly forbid a null type from being non-nullable:

```python
>>> import pyarrow as pa
>>> pa.field("name", pa.null(), nullable=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/types.pxi", line 2266, in pyarrow.lib.field
ValueError: A null type field may not be non-nullable
```

In our code, we must be getting at it some other way that bypasses this check, but it's clear what their intentions are. We _do_ allow an `UnknownType` to not be inside an `OptionType`, so the problem is that we have a broader type system and a direct conversion makes something that Arrow doesn't consider legal.

So the right way to fix this is to wrap our `EmptyArray` inside `UnmaskedArray` on conversion to Arrow, but include enough metadata in the `ExtensionType` that when we convert it back, we know to remove the option-type, so that it's round-trip preserved. I'll make this an issue.
