### ISSUE TITLE
Warning in `RDataSource::Initialise` in ROOT 6.28

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#2344]
### Version of Awkward Array

2.1.1

### Description and code to reproduce

Rename legacy `RDataSource::Initialise` to `RDataSource::Initialize` when minimum required ROOT version is fixed to 6.28:
```python
Warning in <RDataSource::Initialise>: Initialise is deprecated. Please rename it to "Initialize" (with a z).
```

**Comment by ianna** [comment]
It's just a reminder - the warning comes from our generated `RDataSource`: https://github.com/scikit-hep/awkward/blob/main/src/awkward/_connect/rdataframe/to_rdataframe.py#L261
We could check the ROOT version and generate an updated `RDataSource::Initialize` with a `z`...

**Comment by jpivarski** [comment]
Are there some ROOT versions with only the U.K. spelling and some ROOT versions with only the U.S. spelling? If so, then we'd need to check to see which one we have. If we only call it from one place in our code, we could perhaps use `hasattr` (if that works for PyROOT objects; otherwise, try the spelling with "z" first and catch an AttributeError).

If, for all the ROOT versions we support, either both spellings exist or only the "z" spelling exists, we should use only the "z" spelling.

(What ROOT versions do we support? I don't know if we've answered this question yet. There's probably some RDataFrame feature we rely on, and it was introduced in some particular version.)

**Comment by ianna** [comment]
ROOT 6.26 and earlier versions use the UK spelling
ROOT 6.28 introduces the US spelling and warns about the UK one
ROOT 6.29 removes deprecated UK spelling (https://github.com/root-project/root/pull/9521)

**Comment by jpivarski** [comment]
6.26 sounds recent enough that we should support it.

This works as a way to check:

```python
>>> hasattr(ROOT.RDF.RDataSource, "Initialize")
False
>>> hasattr(ROOT.RDF.RDataSource, "Initialise")
True
```

and it's more direct and specific than checking the version. (It explains why.)
