### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [scikit-hep/awkward#2383]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by jpivarski** [comment]
Hello!

I enabled the setting, though I don't see what our project would be vulnerable _from_, since it's not a service or anything that handles our own sensitive data. It's free software that one might use to manage their own sensitive data, but if so, they need to be careful because this library doesn't provide any more or less safety guarantees than the Python language itself.

Also, some of the maintainers (myself included) have posted our email addresses on our GitHub profiles. There are ways to contact us privately. (There's also [a Gitter channel](https://matrix.to/#/#Scikit-HEP_awkward:gitter.im), which allows private messages.)

**Comment by agoose77** [comment]
@igibek did you manage to report the vulnerability that you discovered?

**Comment by agoose77** [comment]
I'm closing this issue for now, as I believe the necessary information for contacting us has been disseminated here! Feel free to re-open this if needed.
