### ISSUE TITLE
boolean arrays don't negate correctly in all cases in awkward1

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2578]
### Version of Awkward Array

1.10.3

### Description and code to reproduce

Trying to negate a component of a boolean array in awkward 1 results in:
```
>>> import awkward as ak
>>> x = ak.Array([[False, False, False], [False, False], [False, False, False]])
>>> ~x[0,0]
-1
```

however:
```
>>> ~x
<Array [[True, True, True, ... True, True]] type='3 * var * bool'>
>>> ~x[0]
<Array [True, True, True] type='3 * bool'>
```

are fine.

This is fixed in awkward2 but we have a large user base that cannot move to awkward2 due to coffea 2023 not being out yet and their analyses being ongoing.

**Comment by jpivarski** [comment]
Yeah, so the difference here is that Awkward 2 returns NumPy types:

```python
>>> ak.__version__
'2.3.1'
>>> type(x[0, 0])
<class 'numpy.bool_'>
```

and Awkward 1 returns Python types:

```python
>>> ak.__version__
'1.10.3'
>>> type(x[0, 0])
<class 'bool'>
```

(for all primitive types, including numbers and times). That's why this is only an effect when you get down to the scalar level. (You see it in `x[0, 0]` and not in `x[0]`.)

The difference in what `~` does on scalars is outside of Awkward itself.

```python
>>> ~bool(False)
-1
>>> ~np.bool_(False)
True
```

It's because Python is bad and considers booleans to be a type of number. `~` is bitwise inversion; `False` is `0`, and the bitwise inverse of `0` is `-1` (by [two's complement rules](https://en.wikipedia.org/wiki/Two%27s_complement)[^1]).

Meanwhile, NumPy is good and considers booleans to be distinct from numbers. `~` inverses the boolean.

I don't know what can be done here: returning NumPy types instead of Python types was one of the backward-compatibility breaking changes we made in the v1 → v2 transition (for reasons like the above: NumPy is right and Python is wrong about what booleans are). Making the output of `x[0, 0]` invert as a boolean under `~` would be to put that backward-incompatible change into v1, but that's what v2 was for.

I guess what I'm saying is that this isn't a bug; it's a feature of v2.

[^1]: Fun fact: for this reason, FORTH defines false to be `0` and true to be `-1`, so that they're completely closed under bitwise operations, and then they don't even define any logical operations.

**Comment by lgray** [comment]
Along this line (~x)[0,0] does what you may expect from numpy for the reasons explained here (if I read that correctly)!

**Comment by jpivarski** [comment]
Yes,

```python
>>> ak.__version__
'1.10.3'
>>> x = ak.Array([[False, False, False], [False, False], [False, False, False]])
>>> ~x[0, 0]
-1
>>> (~x)[0, 0]
True
```

is understood (though clearly that can be confusing, but that's why we changed the output type).
