### ISSUE TITLE
Missing symbol on import on Termux (Android)

### ISSUE THREAD

**Issue by mark-grimes** [scikit-hep/awkward#2605]
### Version of Awkward Array

2.3.1

### Description and code to reproduce

On termux 0.118.0, tried
```
bash$ pip install awkward
```
Everything seems fine. In a python REPL:
```
import awkward
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/awkward/__init__.py", line 31, in <module>
    import awkward.jax
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/awkward/jax.py", line 8, in <module>
    from awkward import highlevel
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/awkward/highlevel.py", line 15, in <module>
    from awkward_cpp.lib import _ext
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/awkward_cpp/lib/_ext.cpython-311.so"...
```
Investigating the library:
```
bash$ patchelf --print-needed /data/data/com.termux/files/usr/lib/python3.11/site-packages/awkward_cpp/lib/_ext.cpython-311.so
libdl.so
libc++_shared.so
libm.so
libc.so
```
Then this will fix the problem:
```
bash$ patchelf --add-needed libpython3.11.so.1.0 /data/data/com.termux/files/usr/lib/python3.11/site-packages/awkward_cpp/lib/_ext.cpython-311.so
```
...and awkward works fine.

**Comment by jpivarski** [comment]
Is Termux included in Python's `manylinux` or `musllinux` definitions? That's [what we support](https://pypi.org/project/awkward-cpp/#files), although it sounds cool to run Awkward on a phone!

I don't know whether this procedure with `patchelf` would invalidate our wheels by including .so versions that might clash with what we find on a target system. (Fixing for Termux might be breaking for other Linux systems.)

If we leave things as-is, call this not a bug, I would like to turn this Issue into a Discussion so that it remains unclosed for anyone else who encounters this problem on Termux.

**Comment by mark-grimes** [comment]
To be clear, I wasn't suggesting you do the `patchelf` hack to fix it. It's a workaround that worked for me and might help others (as you say). I also thought the information might help you diagnose the issue.
The actual problem is happening in the link step, but I don't know enough about the build system to help more than that.

Not sure about `manylinux`/`musllinux`. I'll try and find out.

**Comment by jpivarski** [comment]
It might not be an error: perhaps `manylinux`/`musllinux` are supposed to leave these libraries out (they've very fundamental: `libdl.so`, `libc++_shared.so`, `libm.so`, `libc.so`). It may be that Termux doesn't qualify as a `manylinux` or `musllinux` distribution, and so it's not supported by Python libraries that only build these wheels (like Awkward). There are other Linux distributions that don't qualify.

If that's the case, then the best thing to do, I think, is to convert this Issue into a Discussion, so that other Termux users can learn the work-around.

**Comment by agoose77** [comment]
A super brief search suggests that this is an android linker behaviour: https://github.com/android/ndk/issues/201

**Comment by agoose77** [comment]
I'm going to close this for now, as we don't target termux. It would be interesting to hear more about your use case, so please feel free to loop us in with what you're doing!
