### ISSUE TITLE
Add a "path" to ak.with_field and array["outer", "inner", "new_field"] = new_field syntax to ak.Array/Record.

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#273]
I got quite confused when i (wrongly) assumed that i can assign fields to arrays

```pycon
>>> import numpy as np
>>> offsets = np.random.randint(0, 10, size=5)
>>> x = ak.zip({k : [np.random(off) for off in offsets] for k in ["a", "b"]})
>>> d = 2 * x.a
>>> x.d = d # wrongly assumed this is equivalent to x["d"] = d
>>> x = x[x.a > 0.9] # ups, now x.d is gone
```

Would it make sense/be possible to implement `__setattr__` to do the same thing as  `__setitem__`? Or if that introduces other problems, warn users they should not do that?

**Comment by jpivarski** [comment]
I've been on the fence about this because all the other attributes that attach to an `ak.Array` have to be attached _carefully_ (by directly accessing the `__dict__` or calling the superclass's `__getattr__` or `__getattribute__` or something; I'd have to look it up and experiment).

I've asked this question when presenting Awkward, whether the argument for `x.d = d` is strong enough to warrant the potential for issues like, "Oops, now we can't add new features to `ak.Array`," or "Oops, now exceptions that happen inside the assignment (like `d` doesn't broadcast to `x`) are hidden, or a wrong error message is raised." Something very much like that happened with `__getattr__` until we found a way to navigate around all the consequences. In that case, the argument for `__getattr__` access was strong enough to do it.

Also something to consider: Pandas _used to_ have this ability and now they've deprecated it and raise warnings if users attempt it.

```python
>>> import pandas as pd
>>> df = pd.DataFrame({"x": [1, 2, 3], "y": [1.1, 2.2, 3.3]})
>>> df
   x    y
0  1  1.1
1  2  2.2
2  3  3.3
>>> df.z = [100, 200, 300]
__main__:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
>>> df
   x    y
0  1  1.1
1  2  2.2
2  3  3.3
>>> df["z"] = [100, 200, 300]
>>> df
   x    y    z
0  1  1.1  100
1  2  2.2  200
2  3  3.3  300
```

(But they do allow `df.x is df["x"]`.)

I don't know if they hit some bad design issues or something. Maybe a warning is in order? I normally don't like warnings because they tend to not do what they're supposed to do—they often get buried in a script with no one watching to see them, or when they are observed, they pertain to something so many steps away from what the user is doing that the warning doesn't make sense. But since Pandas does it, maybe we should too...

I think I'm going to label this as a "discussion" because what we have to think about goes well beyond the simple matter of implementing `__setattr__`.

**Comment by nikoladze** [comment]
A similar problem occurs when one tries to use `__setitem__` on nested structures. This is then related to where pandas gives it's `SettingWithCopy` warning which is then confusing when i actually want to use that copy. So I'm also a bit undecided if these things (both the `__setattr__` and the `__setitem__` on a copy) should show warnings, because they can indeed lead to confusion. On the other hand, if there is no perfect solution, maybe confusion is better than making unnoticed mistakes?

**Comment by jpivarski** [comment]
While working on something else, I was reminded that if you declare that Python class has `__slots__`, then attempts to assign attributes that are not in those slots is an error.

```python
>>> class Something(object):
...     __slots__ = ["only", "allowed", "members"]
... 
>>> something = Something()
AttributeError: only
>>> something.only = 1
>>> something.allowed = 2
>>> something.members = 3
>>> something.whatever = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Something' object has no attribute 'whatever'
```

Maybe this is the way forward on attribute-assignment. "'Something' object has no attribute 'whatever'" seems like a pretty clear message. I could just assign slots to ak.Array, ak.Record, and ak.ArrayBuilder (whose only real attributes, not properties, start with underscores) and then you'd get the above error message if you mistakenly try to assign to it. It would be nice, however, if the error message included an indication that you can use item-assignment instead.

Then you brought up another point:

> A similar problem occurs when one tries to use __setitem__ on nested structures. This is then related to where pandas gives it's SettingWithCopy warning which is then confusing when i actually want to use that copy.

I hadn't thought of that, but someone could do

```python
>>> array.inner.structure["x"] = new_field
```

and the new field has been added to a temporary that immediately goes away, but one might think that it is now a part of `array`. Pandas does have a `SettingWithCopy` warning—which means that they are somehow able to detect this situation, and I don't know how they do it—but that warning is one of the most googled Pandas questions out there. I've run into it a few times and found myself in good company.

One of the nice things about Python is that you can always do this—assign a deep member of a structure and have it now be attached to the main structure—and you forget how much that uncertainty plagues languages like C with both pass-by-value and pass-by-reference semantics. In Python, this intuitive situation is possible because _everything_ is pass-by-reference.

It won't work for Awkward Array because these slices might be novel objects: `array` might be nested lists of nested lists of records that have a field named `inner`, and `array.inner` projects that field to make nested lists of nested lists of just the `inner` field. NumPy's structured arrays do the same thing—you can slice with integers first to pick rows and then strings to pick columns or vice-versa—Awkward just generalizes that beyond number-labeled rows to jagged arrays and string-labeled columns to nested records. But it does mean that if you ask for `array.inner`, you might have just created a new thing that has never been seen before. Python's pass-by-reference won't work because there's no long-lived, preexisting object to reference.

Some languages (like Haskell) take the opposite tack and only allow pass-by-value. (I was introduced to it by Scala, which takes it to less of an extreme than Haskell, but it still makes the pattern apparent.) Like being purely pass-by-reference, being purely pass-by-value avoids the confusion of allowing both. In the implementation, I took a relaxed view of being mostly immutable, but discovered along the way that most of my problems were coming from the exceptions, so pretty soon the layout nodes will be purely immutable (#176 and #177). All these confusion exceptions to mutability are therefore concentrated on the top-most ak.Array layer, where I can focus on them because they're all in one place.

But maybe ak.Array should follow suit and be immutable as well? Maybe attempts to assign shouldn't just use [ak.with_field](https://awkward-array.readthedocs.io/en/latest/_auto/ak.with_field.html) but point the user to it as what they really mean. The `array.inner.structure` example illustrates an issue: building this up would require three nested `ak.with_field` calls. Perhaps the interface of `ak.with_field` should be expanded to take a `path` that assigns a field deeply and packs everything up, giving you the `array_with_x`?

But if `ak.with_field` had a `path`, I guess we could use it in the `__setitem__` interface like this:

```python
array["inner", "structure", "x"] = new_field
```

and include all sorts of warnings in the documentation that

```python
array["inner"]["structure"]["x"] = new_field
```

won't work?

**Comment by nikoladze** [comment]
> Maybe this is the way forward on attribute-assignment. "'Something' object has no attribute 'whatever'" seems like a pretty clear message. I could just assign slots to ak.Array, ak.Record, and ak.ArrayBuilder (whose only real attributes, not properties, start with underscores) and then you'd get the above error message if you mistakenly try to assign to it. It would be nice, however, if the error message included an indication that you can use item-assignment instead.

This sounds good and clear.

I also like the idea that `ak.with_field` gets a `path` argument and that assigning to inner elements can work with `__setitem__` with multiple arguments. Also i agree it probably is better to warn that `array["inner"]["structure"]["x"] = new_field` is not working in the documentation rather than with a confusing warning like in pandas.

**Comment by jpivarski** [comment]
I changed the title to be clear about what this feature request is requesting. I'm also going to add "good first issue" because this can be implemented with only a little Python meddling, not deep changes to the C++.
