### ISSUE TITLE
If `form_key` is None, we should not interpolate it to build a buffer key

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2731]
### Version of Awkward Array

main

### Description and code to reproduce

This would remove the patch in dask-awkward requiring `if buffer_key == "None"`

**Comment by agoose77** [comment]
@jpivarski This comes up in the context of calling `typetracer_with_report` upon a (partially) unlabelled form. I wonder if that should just be an error; what is the point of associating a report with a form if that relationship is many to one (`None`)?

**Comment by jpivarski** [comment]
It was a convenient way to implement `Form.length_zero_array`. All of the nodes need at most 8 bytes of zeros (`b"\x00\x00\x00\x00\x00\x00\x00\x00"`). By setting `buffer_key` to produce constant lookups in the `container`, we only had to make a `container` with one key and don't have to care about what the `form_keys` of the Form are.

If `buffer_key` were forced to be one-to-one, then we'd have to make many keys in the `container`, one for each node, and create or replace `form_keys` in the Form. All of the values of the `container` could point to one object, but setting that up would be more lines of code than what we have.

That might be regarded as a hack. (I don't think so, because it conforms to the rules about how the abstraction works—there's nothing in the rules that say the mapping has to be one-to-one.) There are also legitimate cases in which multiple Form nodes would point to the same `container` keys, such as if someone does `ak.cartesian([array, array])`; the buffers of `array` are going to be referenced twice in the array returned by `ak.cartesian`.

**Comment by agoose77** [comment]
I agree about the convenience for `typetracer_from_form`, which definitely falls into this category. I'm rather thinking about `typetracer_with_report`, which uses the above but also introduces the `TypeTracerReport`. It's _that_ part of our API that I think effectively mandates meaningful form keys, and that I'd like to change.

**Comment by agoose77** [comment]
I'm closing this for now, as I can't see mention in dask-awkward any more.
