### ISSUE TITLE
`ak.softmax` with `axis=0` fails

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2760]
### Version of Awkward Array

main

### Description and code to reproduce

I suspect this is a general bug with reducers implemented through multiple-step operations, i.e. not just `axis=0`.

The problem arises when reducing a ragged array e.g.
```python
import awkward as ak

assert isinstance(
    ak.softmax([[1, 2, 3, 4], [5], [10]], axis=0, highlevel=True), ak.Array
)
```

**Comment by jpivarski** [comment]
I want to fix this issue because pytest shows xfailed tests in red, and I keep thinking that it's an unexpected error, rather than an expected error.

The commentary on #2918 says that this might be similar to an error that was fixed in `ak.std` and `ak.var`. In that error, we noticed that only reduction along `axis=-1` (or `axis=None`, trivially) kept an array broadcastable with its original self; other `axis` values change the shape in ways that are no longer broadcastable. It could be _accidentally_ broadcastable, and that's even worse: it would be the wrong broadcasting for the operation.

The underlying issue is the same as in #2918, but the fix can't be the same. For `ak.std` and `ak.var`, we could replace $E[(x - E(x))^2]$ with $E[x^2] - E[x]^2$. The first expression has the broadcasting problem, but the second doesn't. Both expectation values sum along the same axis, producing the same shape independently, but $x - E[x]$ has to broadcast the original shape, $x$, with a reduced shape, $E[x]$.

However, softmax is $\exp(x)/\Sigma\exp(x)$, so the original shape, $\exp(x)$, has to be broadcasted against the reduced shape, $\Sigma\exp(x)$ in the division operation. I don't think this expression can be rewritten in a way that avoids that.

For the specific test case in question,

```python
>>> x = ak.Array([[1, 2, 3, 4], [5], [10]])
```

the `axis=-1` case that passes is

```python
>>> np.exp(x) / ak.sum(np.exp(x), axis=1)
<Array [[0.0321, 0.0871, 0.237, 0.644], [1], [1]] type='3 * var * float64'>
```

and the `axis=0` case that fails is

```python
>>> np.exp(x) / ak.sum(np.exp(x), axis=0)
...
ValueError: cannot broadcast RegularArray of size 3 with RegularArray of size 4 in divide

This error occurred while calling

    numpy.divide.__call__(
        <Array [[2.72, 7.39, 20.1, 54.6], ...] type='3 * var * float64'>
        <Array [2.22e+04, 7.39, 20.1, 54.6] type='4 * float64'>
    )
```

The original shape, `np.exp(x)`, has length 3 and the `axis=0` reduced shape, `ak.sum(np.exp(x), axis=0)`, has length 4. If it accidentally had length 3, then the operation wouldn't have failed but it would be the wrong answer: those 4 items in the denominator correspond to the maximum length of the inner lists—that is,

* the first of the 4 items should be the denominator of `[np.exp(1), np.exp(5), np.exp(10)]`,
* the second of the 4 items should be the denominator of `[np.exp(2)]`,
* the third of the 4 items should be the denominator of `[np.exp(3)]`, and
* the fourth of the 4 items should be the denominator of `[np.exp(4)]`

but that's not what division of `np.exp(x)` and `ak.sum(np.exp(x), axis=0)` would do if they happened to have the same length.

A correct calculation of the softmax for this 2-D ragged array at `axis=0` would be

```python
>>> denom = ak.sum(np.exp(x), axis=0, keepdims=True)
>>> denom
<Array [[2.22e+04, 7.39, 20.1, 54.6]] type='1 * var * float64'>
>>> denom[np.zeros(len(x), dtype=int)].show()
[[2.22e+04, 7.39, 20.1, 54.6],
 [2.22e+04, 7.39, 20.1, 54.6],
 [2.22e+04, 7.39, 20.1, 54.6]]
>>> denom[np.zeros(len(x), dtype=int)][ak.local_index(x)].show()
[[2.22e+04, 7.39, 20.1, 54.6],
 [2.22e+04],
 [2.22e+04]]
>>> np.exp(x) / denom[np.zeros(len(x), dtype=int)][ak.local_index(x)]
<Array [[0.000123, 1, 1, 1], [0.00669], [0.993]] type='3 * var * float64'>
```

but I don't know how to generalize that for arbitrary ragged dimension and arbitrary `axis`.

So in the ensuing PR, I won't. I'll just exclude `axis != -1` from `ak.softmax` and include this comment in the code. If anyone really needs softmax with arbitrary dimension and `axis` reduction, it's a fun challenge!
