### ISSUE TITLE
Dasky thoughts for awkward

### ISSUE THREAD

**Issue by martindurant** [scikit-hep/awkward#284]
Following #263, it's now possible to pull big data into awkward of a form that outsiders from the project will appreciate and allow, for instance, parquet and orc reading (this may already exist). This raises the interesting question of how people in the wider community (i.e., non-root) might interact with awkward for nested dataset processing, especially where that data is big enough to need parallel and/or out-of-core processing with dask. This is different from the original question me and @jpivarski talked about, how to make use of Dask within awkward.

Firstly, in my opinion, an awkward array is best seen as a one-dimensional array of things, where those things have structure (whether variable-length components, structs or maps), and so maps best into existing python-land as a pandas series or column. I understand that much of the current coding style is numpy-like, and it may seem that of the dask collections, it most resembles the dask-array codebase. However, usage, to my mind, will be along the lines of

```python
df = ak.read_parquet(awkward_columns=[...])  # other columns are simple pandas types; or we expose columns for extraction
df[filter_multi_column]
df.col1.map(numba_func)
df.col1.agg(numba_iterating_func)
```
where the `map` could be written `df.map_partitions(lambda d: d.map(numba_func)` but the aggregation required the same combination logic as any dataframe combinations currently do. The filter step would require the ability to iterate over the awkward array(s) as well as ordinary pandas series, together.

A few notes:
- the pandas codebase and indeed the dask.dataframe one respects the numpy protocol, so that (g)ufuncs are sensibly dealt with, and f(akarray)->akarray should work fine
- wrapping awkwards arrays, or indeed seeing the whole arrow structure as a top-level record in awkward, is a very light-weight process
- to enable the conversion to dask.dataframe, you would need simply to run arrow->awkward extension array on each piece, and not have to worry about chunks in awkward at all
- conversely, if you happen to be starting with a chunked akarray (from root?), then one chunk becomes one partition, and, again, none of the partitions themselves are chunked; the only information you would currently loose is the row-count of each piece
- caching of virtual arrays would not be handled in the first instance, but it would not be hard to do something sensible at the dask worker level; the scheduler will tend to keep tasks where an array piece was previously loaded into memory and round-robin pieces that have no dependencies on each other

--

In addition, to kick off this conversation of awkward integration, I was confused in trying to build examples, so I have a couple of gists to share:
- https://gist.github.com/martindurant/6a95e20bce620471462062083d1ac1ff#file-time1-py shows that although `len` mapped on a awkward pandas series is a few times faster than when mapped on a list-of-lists series; but only as fast as a python comprehension on the original lists, and *much* slower than it should be with numpy
- https://gist.github.com/martindurant/6a95e20bce620471462062083d1ac1ff#file-ak-ipynb I couldn't actually get complex numba-jit functions to run, perhaps due to confusion over map and struc-like things when converting from python/json. I would have thought you could process maps too by iterating on the keys or key/value tuples.

**Comment by jpivarski** [comment]
This is a good line of thought, and I agree that the best way to think of these things is as one-dimensional arrays, like they way they're represented in Pandas.

I added some comments to the gists.

**Comment by jpivarski** [comment]
This will still be searchable, but I don't see any action items in it, so I'm going to close it.

**Comment by nsmith-** [comment]
I spent some time thinking about this and playing, and I believe ultimately `awkward` arrays should be a new collection type in Dask. Here is why the existing ones won't work out:

- *DataFrame*: the conclusion of #350 is that it is inappropriate to make awkward arrays a special Pandas column dtype, and anyway as I understand, there was some issue with conflicts in the awkward extension of pandas and the dask extension of pandas. Certainly the fact that pandas is extensible is enough of a feat to engineer that having two separate packages extend it without conflict is even harder. (c.f. also jax extensions of numpy vs. awkward)
- *Array*: Dask makes great use of the fact that the full shape is known to design partitions and chunk work appropriately. We immediately have to toss all of this out since only the first dimension shape is known. (an exception is when all nodes are Record or RegularArray, so maybe those can be made compatible)
- *Bag*: This is the first collection type that awkward could conceivably extend, because it is conceptually very similar to the awkward *PartitionedArray* albeit with no knowledge of partition sizes. The downside is that all bag operations are geared towards the assumption that both an outer loop over partitions and an inner loop over entries in partitions is carried out in pure python. There is an escape valve via `map_partitions` but clearly we are not able to use most of the *Bag* functions (such as max, mean, repartition, etc.) in an efficient manner out of the box.

I sketched a simple bag extension:
```python
import numbers
from operator import getitem, add
from numpy.lib.mixins import NDArrayOperatorsMixin
from dask.bag import Bag, map_partitions, from_delayed



class AwkwardBag(Bag, NDArrayOperatorsMixin):
    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
        if "out" in kwargs:
            raise ValueError("awkward dask ufuncs cannot use 'out'")

        if method != "__call__":
            raise ValueError("awkward1 only supports ufunc call method")

        for x in inputs:
            if not isinstance(x, (numbers.Number, AwkwardBag)):
                return NotImplemented

        return map_partitions(ufunc, *inputs, **kwargs)

    def __getitem__(self, key):
        if isinstance(key, tuple):
            if isinstance(key[0], numbers.Number):
                raise NotImplementedError("We need to know partition sizes to find the right position")
            elif isinstance(key[0], slice):
                if key[0] == slice(None):
                    pass  # We can do this
                else:
                    raise NotImplementedError("We need to know partition sizes to correctly slice")
            else:
                raise NotImplementedError("Maybe its an array? we could handle that if we partition it to match")
        return map_partitions(getitem, self, key)

    def __getattr__(self, key):
        if key in dir(type(self)):
            return super(DaskAwkwardArray, self).__getattribute__(key)
        # it would be nice to have the Form to check an item is available
        return map_partitions(getattr, self, key)

    @classmethod
    def from_bag(cls, bag):
        """Convert a bag of json-like python objects to awkward arrays"""
        return bag.map_partitions(ak.from_iter)
    
    @classmethod
    def from_delayed(cls, items):
        out = from_delayed(items)
        out.__class__ = cls
        return out
```

with an example of use:
```python
import random
import numpy as np
import awkward1 as ak
from dask import delayed

@delayed
def gen_partition(i):
    return ak.zip({
        "x": i * np.ones(100),
        "y": ak.from_iter([range(random.randint(0, 6)) for _ in range(100)])
    })

abag = AwkwardBag.from_delayed(map(gen_partition, range(10)))
(abag.y[:, :2] + 3).reduction(lambda x: x, ak.concatenate).compute()
```
where once the partitions of the bag are generated, any broadcastable operation (such as the `add` ufunc here) are going to be computed in the fast path for each partition. Then to bring the results back I have to concatenate the arrays, resulting in:
```
<Array [[3, 4], [3, 4], ... [3, 4], [3], []] type='1000 * var * int64'>
```

Since this seemed promising, I went further and implemented a [custom collection](https://docs.dask.org/en/latest/custom-collections.html) that tracked partition sizes, and am looking into saving the [awkward Form](https://awkward-array.readthedocs.io/en/latest/ak.forms.Form.html) (which is known ahead of time for my use case, but could be inferred when loading a dataset similar to how columns would be inferred when reading many csv files). The Form would allow checking that fields exist during the graph construction, and maybe could validate certain structure operations as well.

Many of the `ak.*` namespace functions that we would want to work with these arrays (think `ak.mean(abag, axis=None)`, etc.) in principle have already been written for [PartitionedArray](https://github.com/scikit-hep/awkward-1.0/blob/master/src/awkward1/partition.py#L100) (which is, conveniently, pure python) but the assumption there is that all operations are eager (e.g. the general [reduce](https://github.com/scikit-hep/awkward-1.0/blob/master/src/awkward1/partition.py#L262-L272)). Perhaps something as simple as wrapping each such eager op with `dask.delayed()` is all that's needed.

**Comment by martindurant** [comment]
Please see also https://github.com/martindurant/awkward_extras/issues/1 for discussion on the pandas extension array path - I'd say it certainly can be done for dask-dataframe. Whether it is the right or best model is another matter,
