### ISSUE TITLE
Export `remove_structure` and `prettyprint` for dask-awkward

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2856]
### Description of new feature

Dask-awkward currently imports this private name.

**Comment by jpivarski** [comment]
Here:

https://github.com/dask-contrib/dask-awkward/blob/816eebaba6765e390c483a212d3fd3b37ec65d97/src/dask_awkward/lib/core.py#L19

The [Ragged](https://github.com/jpivarski/ragged) library _almost_ had to do this, but I found a work-around. However, Ragged does use `_prettyprint`:

https://github.com/jpivarski/ragged/blob/444aa0f7016688ce0e9a8fa828c73cc7ac2a3210/src/ragged/_spec_array_object.py#L239-L267

Both of these should be exported as L2 "semipublic". They shouldn't be `ak.*` functions, but hidden in some nested submodule, though without an underscore.

This issue mentions both of them because it's as easy to do both as it is to do either one of them. We just need to decide on what their API paths will be.
