### ISSUE TITLE
`array.layout.form` touches shape

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#3018]
### Version of Awkward Array

2.6.1

### Description and code to reproduce

```python3
import awkward as ak

a = ak.Array([1, 2, 3, 4, 5])

layout, report = ak.typetracer.typetracer_with_report(a.layout.form_with_key())

b = ak.Array(layout)

print(report.data_touched, report.shape_touched)

b.layout.form

print(report.data_touched, report.shape_touched)
```
results in:
```
[] []
[] ['node0']
```

Asking for the form shouldn't touch shape.

**Comment by lgray** [comment]
This is what is needed in addition to #3017 to avoid problems with dask's deterministic keys project https://github.com/dask/dask/issues/10905.


Also related: https://github.com/dask/dask/pull/10918 (partial fix that doesn't quite hold)

**Comment by agoose77** [comment]
Technically this does require shape because it's a NumpyArray, and NumpyArray's have shapes as part of their type signature. In this case, it's asking for `shape[1:]`, because the outermost length can be unknown. We don't have a way of saying `touch_inner_shape`, so we have to touch the whole thing.

**Comment by agoose77** [comment]
Well, saying that, we could introduce a "fast path" that checks `self.data.ndim`. This is defined as non-touching because it's "valueless metadata". I think it's the only example of such an operation that doesn't even touch shape; I remember us discussing it recently (and we could `git blame` that line in `_nplikes/typetracer.py` to find more discussion if needs be).

e.g.
```python
if self._data.ndim == 1:
    ...
else:
    do_something_with(
        self._data.shape[1:]
    )
```
