### ISSUE TITLE
Non-monotonic `offsets` in ListOffsetArray, causes segfault in reducer

### ISSUE THREAD

**Issue by gipert** [scikit-hep/awkward#3062]
### Version of Awkward Array

2.6.2

### Description and code to reproduce

I'm seeing segfaults when applying Awkward routines to large arrays. This is the layout of the array:
```pycon
In [9]: data.layout
Out[9]: 
<ListOffsetArray len='12182595'>
    <offsets><Index dtype='int64' len='12182596'>
        [    0     0     0 ... 44617 44617 44624]
    </Index></offsets>
    <content><ListOffsetArray len='44624'>
        <offsets><Index dtype='int64' len='44625'>
            [   0    1    5 ... 8451 8453 8456]
        </Index></offsets>
        <content><NumpyArray dtype='float64' len='8456'>
            [0.98749351 0.88292027 0.6609051  ... 1.07222264 6.76291445
             2.08533864]
        </NumpyArray></content>
    </ListOffsetArray></content>
</ListOffsetArray>
```
The typical length of arrays at the innermost axis is ~3. I read offsets and contents from disk and build the array in memory with them. Once the data is loaded, I can for example apply `ak.count()` without specifying an axis:
```pycon
In [16]: ak.count(data)
Out[16]: 8456
```
An this works fine, but I get a segfault when I do specify the axis:
```pycon
In [17]: ak.count(data, axis=-1)
malloc(): invalid next size (unsorted)
zsh: IOT instruction (core dumped)  ipython
```
I see the same behavior on e.g. `ak.full_like(data, 42)`. I cannot provide the actual data file, unfortunately.

Let me know if I should provide more details about my Linux environment or version of libraries.

**Comment by agoose77** [comment]
Hi @gipert,

It's very hard to debug this kind of crashes without looking at the data because ultimately this is likely because of data and faulty assumptions. We should avoid segfaults at runtime by checking error conditions, but this isn't always comprehensive.

One thing to try would be to pull out the inner list, as the outer list itself should not be all that useful for `ak.count(..., axis=-1)` (though it is involved in the codepath for reduction). Does it segfault with
```python
ak.count(data.layout.content, axis=-1)
```
?

**Comment by gipert** [comment]
Yes!
```
malloc(): mismatching next->prev_size (unsorted)
zsh: IOT instruction (core dumped)  python mwe.py
```
Also note that this is related to the size of the array. It does not segfault on chunks of the same array which are small enough.

**Comment by gipert** [comment]
I can share the data in private under a non-disclosure agreement ;)

**Comment by jpivarski** [comment]
Actually, if you do

```python
pickle.dump(ak.to_buffers(data.layout.content), open("filename.pkl, "wb"))
```

and share `filename.pkl`, that's the minimum amount of information that we would need to diagnose the problem. The contents of that pickle file would be

1. the data type, which we already know (ListOffsetArray of NumpyArray, since the outer ListOffsetArray has been stripped off with `data.layout.content`)
2. the length, which we already know (44624)
3. two arrays,

```python
[   0    1    5 ... 8451 8453 8456]
```

and

```python
[0.98749351 0.88292027 0.6609051  ... 1.07222264 6.76291445 2.08533864]
```

The first reveals the lengths of the inner lists that you're trying to count as a monotonically increasing sequence (mostly around 3—4) and the second reveals some floating point numbers (of order 0.5‒5).

Is there anything in the distribution or sequence of these two arrays that would give away something that should be kept confidential? I think it would be hard to gain any knowledge from these two arrays, but I'll leave that up to you because you know the context better.

**Comment by gipert** [comment]
[Here you are](https://github.com/scikit-hep/awkward/files/14744405/issue3062.pkl.tgz)! This is actually `ak.full_like(data, 42).layout.content`, not the original data.

Thanks a lot for the prompt support!

**Comment by jpivarski** [comment]
Reproduced:

```python
>>> import pickle
>>> import awkward as ak
>>> data = pickle.load(open("issue3062.pkl", "rb"))
>>> array = ak.from_buffers(*data)
>>> array
<Array [[42], [42, ..., 42], ..., [42, 42, 42]] type='44624 * var * float64'>
>>> array.layout
<ListOffsetArray len='44624'>
    <offsets><Index dtype='int64' len='44625'>
        [   0    1    5 ... 8451 8453 8456]
    </Index></offsets>
    <content><NumpyArray dtype='float64' len='8456'>[42. 42. 42. ... 42. 42. 42.]</NumpyArray></content>
</ListOffsetArray>
>>> ak.count(array.layout, axis=-1)
Segmentation fault (core dumped)
```

Replacing the `content` with 42 was a good idea: it blanked out the most information-rich part while preserving the part that's responsible for the segfault. If I had thought of it, I would have suggested it: `ak.count` doesn't do anything with the `content`; it depends entirely on the `offsets` array.

**Comment by jpivarski** [comment]
It's in

https://github.com/scikit-hep/awkward/blob/958deb9f07c2c6f62594ae88683eadf589edcf12/awkward-cpp/src/cpu-kernels/awkward_ListOffsetArray_reduce_local_nextparents_64.cpp#L7-L21

**Comment by jpivarski** [comment]
The `awkward_ListOffsetArray_reduce_local_nextparents_64` looks correct, but the offsets are inconsistent: there are two places in the array where they are not monotonically increasing: at indexes 46 and 39828.

```python
>>> starts, stops = array.layout.offsets.data[:-1], array.layout.offsets.data[1:]
>>> np.nonzero(stops - starts < 0)
(array([   46, 39828]),)
>>> starts[46], stops[46]
(106, 2)
>>> starts[39828], stops[39828]
(70761, 2)
```

So now the question is, how did it get that way? The Awkward codebase doesn't check for inconsistencies like this at every step because that would be a $\mathcal{O}(n)$ operation everywhere, even if it would be in compiled code.

There are two functions that manually opt-in to this kind of test: [ak.is_valid](https://awkward-array.org/doc/main/reference/generated/ak.is_valid.html) (returns a boolean) and [ak.validity_error](https://awkward-array.org/doc/main/reference/generated/ak.validity_error.html) (returns an error message as a string or `None`), as well as the `check_valid` boolean argument of the [ak.Array constructor](https://awkward-array.org/doc/main/reference/generated/ak.Array.html). Applying this to the above `array`,

```python
>>> print(ak.validity_error(array))
at highlevel ("<class 'awkward.contents.listoffsetarray.ListOffsetArray'>"): start[i] > stop[i] at i=46 (in compiled code: https://github.com/scikit-hep/awkward/blob/awkward-cpp-30/awkward-cpp/src/cpu-kernels/awkward_ListArray_validity.cpp#L18)
```

However, you want to know where this first happens, to identify the Awkward (or other) function that is producing the wrong `offsets`, so add these validity checks to your code, at least temporarily to narrow in on the offending function call.

On our side, we could add an inline check for this kind of validity error in this kernel. It's not supposed to be given wrong `offsets`, but at this point, the neighboring `offsets` are in CPU cache and it wouldn't be a memory-fetching cost to verify in-place that they're monotonically increasing. It might spoil vectorization, though.

**Comment by gipert** [comment]
Thanks a lot for identifying the problem! I was indeed constructing arrays with invalid offsets.
