### ISSUE TITLE
`Form.select_columns` needs a way to distinguish structural dots from dots in the names of record fields

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#3088]
### Version of Awkward Array

HEAD

### Description and code to reproduce

Suppose you have an array like

```python
>>> array = ak.Array([{"outer": {"crazy.dot": {"inner_a": 12.3, "inner_b": 123}}}])
>>> array.show(type=True)
type: 1 * {
    outer: {
        "crazy.dot": {
            inner_a: float64,
            inner_b: int64
        }
    }
}
[{outer: {'crazy.dot': {inner_a: 12.3, inner_b: 123}}}]
```

If you want to Form-select `inner_a` and not `inner_b`, you can't:

```python
>>> array.layout.form.select_columns("outer.crazy.dot.inner_a")
RecordForm([], [])
```

When this problem is encountered in Spark, they use backticks. To do the same, we'd want

```python
>>> array.layout.form.select_columns("outer.`crazy.dot`.inner_a")
RecordForm([], [])
```

to result in

```python
RecordForm([RecordForm([RecordForm([NumpyForm('float64')], ['inner_a'])], ['crazy.dot'])], ['outer'])
```

which means a bit more parsing of the specifier.

**Comment by tcawlfield** [comment]
Spark's use of backticks seems convenient, apparently borrowing from Markdown. But it brings up a number of related issues and a host of complexities that would be time-consuming to document and test. How do you handle column names that have backticks in them? Do we fully support some version of [inline code spans from some version of the CommonMark spec](https://spec.commonmark.org/0.31.2/#inlines)? That doesn't seem like an appropriately-sized solution to me.

A related issue is how to handle column names that have a literal asterisk in them, as we use globbing rules. Shell-style globbing has its own means of escaping such as `[*]` being a literal asterisk, and it looks to me like we support this correctly.

I'm leaning toward the following approach for `select_columns`: If `specifier` is a sequence of lists or tuples, then consider elements of that inner list to be column names (or patterns). Otherwise if specifier is a `str` or iterable of `str`s, split the columns on periods as usual.

Spark is Java-based, where there is more encouragement to use rigid typing. That's a possible reason they chose to go with backticks.

**Comment by jpivarski** [comment]
If we can fall back on a list/tuple of (non-wildcard) strings, then the strings can be unquoted and we don't care what special characters they use in them.

For wildcards in the single dotted-string case, I think we use a standard library (`fnmatch.fnmatch`?), so escaped wildcards ought to work. I don't think I've tried it.

**Comment by tcawlfield** [comment]
Okay, I like the idea that if we provide a list of lists of strings, the user is being explicit and not using patterns. Patterns are a convenience only, and in the super-rare cases that we're dealing with, convenience gets outvoted by the need for something simple and direct.

Yes, looks to me like fnmatch is used. I wondered "why not glob.glob?" After reading up, looks like glob.glob relies on the filesystem and also treats path separator characters in a special way. So fnmatchcase is used instead. `glob.escape` is used in a clever way, just to distinguish between patterns and non-patterns. If you want to match the column named `x * y` you can use `x [*] y`. glob.escape will modify it which flags this as a pattern, and fnmatchcase will interpret the pattern as only matching the literal string `x * y`. You could also just use `x*y` here too, and the glob probably matches what you're looking for anyway unless you have another column like `x + y`. If anyone actually has record names like these, well, they brought this upon themselves.

**Comment by tcawlfield** [comment]
Working on the code, I found that it would take a much larger change to insist that column-names-as-a-tuple (or list) will not use pattern-matching. Although I prefer that approach from a user perspective, it would require a deep reworking of the `_SpecifierMatcher` class. The PR submitted allows glob-style patterns for all column/field names, even when provided as a list.

**Comment by agoose77** [comment]
I'm only dropping in at a highlevel - the rework that introduced the specifier matcher was just an attempt to encapsulate some of the matching logic.

Would it be possible to introduce escapes into the search string? So `foo\.bar` matches 'foo.bar' columns.

**Comment by tcawlfield** [comment]
About escapes: Yes, I think that's another valid approach. Special characters `.*?[]{}\` could all be escaped, or maybe even all punctuation a-la Markdown. I suppose that's easy to do with a regex. Backslashes not matching the pattern would be literal, so `\\\a` -> `\\a`.

I don't really have enough perspective on how forms are used. What are some of the use cases? Are these common? Would ergonomics be helpful in these cases?

Hmm... Even with this very simple approach, I'd have to re-work `_SpecifierMatcher`. The basic idea is that both patterns and literal strings are used as keys and list elements in `_match_to_next_specifiers`. Upon iteration to the next level deep, the strings are again tested for whether or not they are patterns or literals, and then put into either a list of patterns or a set of literals. (The set type is used because its big-O time is logN vs N, although in practice I'd bet that N is so small the list would be faster.)

Anyway, the test for is-a-pattern, `if escape_glob(parent) == parent`, is performed multiple times on the same string. If we introduce this escape mechanism, we have to arrange it so that the test (and escape) is only performed once, which probably means that we make classes like ColumnNameLiteral and ColumnNamePattern. Even the first time it's not very simple. Probably have to transform characters `[]?*` into some super-special reserved characters, then test with `glob.escape`, then swap original glob special characters with the reserved ones, actually run `glob.escape` and store that result, and then transform the reserved chars back into their original pattern-meaningful `?*[]`. Yeah, the more I think about it, the more I feel like this is a big change. We also have to do a similar dance when `expand_braces` is True, which is the default. I guess adding escapes would make `expand_braces` a deprecated argument.

A big change like that is fine. I'm happy to do it, and it's not difficult or even really time-consuming to code up. Very self-contained. But all code has an associated cost of maintenance. If the use case for this kind of thing is almost nonexistent, then it would be better strategy to defer this kind of change until some future time.
