### ISSUE TITLE
CI test to check if documentation is generated correctly

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/awkward#318]
It would be nice to have a CI test that checks if the generated readthedocs documentation breaks.

**Comment by jpivarski** [comment]
See the new test here:

https://dev.azure.com/jpivarski/Scikit-HEP/_build?definitionId=5

The [YAML for this test](https://github.com/scikit-hep/awkward-1.0/blob/master/.ci/azure-doctest-awkward.yml) doesn't actually run the documentation workflow; you'll have to add that. And you might want to remove the compilation, too (now that I think about it), because the documentation needs to be buildable without compilation (so that it works on ReadTheDocs). That will take the running time from 2 minutes down to almost nothing.
