### ISSUE TITLE
Can numba functions accept layouts?

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#332]
Although rare, sometimes its easier to do certain operations on the awkward1 layouts than their wrapped arrays. It would be convenient if numba functions could be called interchangeably, e.g.
```
import awkward1
import numba

@numba.njit
def dostuff(x):
    return x[0]

a = awkward1.Array([1, 2, 3])
dostuff(a.layout)
```
crashes, seemingly unnecessarily since wrapping any layout with `awkwrad1.Array` passes it through.

**Comment by jpivarski** [comment]
Numba function don't accept layouts. I don't know if that's something that should change. (Layouts also can't do NumPy ufuncs and various other things.)

It might seem like allowing layouts in Numba would be easy, since they are the "lower level" items, anyway—it would seem like allowing `ak.Array` in Numba functions would be implemented in terms of layouts. Actually, it isn't. Entering a Numba-JITed function means turning an array into an `ArrayView`, which has a `Lookup` consisting of arrays that are pointers into the original arrays, posing as integers. It's these pointers to arrays that are traversed through Numba, not any facsimile of the C++ hierarchy, to avoid performance bottlenecks due to Numba's pass-by-value semantics.

`ak.Array`'s "wrapper oriented" perspective is actually helpful in this; the "composable nodes" go against the grain. So it wouldn't be an easy thing to do to make layout objects accessible in Numba, and it's also not strongly motivated, since the `ak.Array` works.

Actually, the cheap solution to this might be to give all of the layout classes Numba box/unbox functions that wrap/unwrap an `ak.Array` and then use `ak.Array`'s solution. It sounds perverse, wrapping with a high-level interface in order to generate a low-level Numba model, but that's the situation. Personally, I think it makes more sense to just document it somewhere: a list of all the things that bare layout objects can't do, but `ak.Array` can.

**Comment by nsmith-** [comment]
Ok, that's fine. I brought it up since most `ak.*` methods seem to be happy with either (since they are often _un_-wrapping)

**Comment by nsmith-** [comment]
Call it documentation issue then?

**Comment by jpivarski** [comment]
Yes. That makes more sense.

**Comment by jpivarski** [comment]
I had half a thought to make layouts wrap themselves as `ak.Array` before entering a Numbafied function, but that would be confusing because if they are passed _through_, they'll be changed, and their semantics inside the Numbafied function would be as high-level, not low-level arrays.

Instead, I should identify layouts on their way in and have them raise an error there. The in-situ notification will be a lot more useful than documentation hidden in a corner of the website.

**Comment by jpivarski** [comment]
I was just about to do this when i found that I've already done it:

https://github.com/scikit-hep/awkward-1.0/blob/e023cfc7a95c90ea980b7c348049ceb10fdca807/src/awkward/_connect/_numba/layout.py#L16-L49

For example,

```python
>>> import awkward as ak
>>> import numba as nb
>>> @nb.njit
... def f(array):
...     return array
... 
>>> f(ak.Array([[1, 2, 3], [], [4, 5]]))
<Array [[1, 2, 3], [], [4, 5]] type='3 * var * int64'>
```

but

```python
>>> f(ak.Array([[1, 2, 3], [], [4, 5]]).layout)
TypeError: ListOffsetArray64 objects cannot be passed directly into Numba-compiled functions; construct a high-level ak.Array or ak.Record instead
```
