### ISSUE TITLE
Decorators for making new mixins

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#355]
This is a tracking issue for migrating https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/methods/mixin.py into awkward. The decorators allow a more concise declaration of mixin classes, e.g.:
```python
from awkward1 import mixin_class, mixin_class_method


@mixin_class(ak.behavior)
class Point:
    def distance(self, other):
        return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)

    @mixin_class_method(np.equal, {"Point"})
    def point_equal(self, other):
        return np.logical_and(self.x == other.x, self.y == other.y)

    @mixin_class_method(np.abs)
    def point_abs(self):
        return np.sqrt(self.x ** 2 + self.y ** 2)
```
reproduces the functionality outlined in the `ak.behavior` introductory documents.

**Comment by nsmith-** [comment]
I wonder if we can make these decorators attempt automatic lowering into numba?
For most properties and things like `abs` it should be straightforward, although I am not sure what it would look like for functions where you have to zip up into a new record. Is there a way to lower ak.zip so that it forms a record with the correct type when called from a numba-ized function?

**Comment by jpivarski** [comment]
I've never attempted it, and it would take some thought. The Numba implementation works with scalars, which might be feasible for making new types of records (since they're metadata-only: no new indexes like `starts` and `stops`). Before solving the problem at the decorator level, it would have to be solved at the bare function level, where it's never been done before.

It runs counter to the general stance I've taken toward Numba: not to try to reimplement the whole environment you have outside of Numba, but for iterating with for loops as you shouldn't outside of Numba (so that inside and outside of Numba each have their strengths). There is an open issue to add `enumerate` to Awkward-Numba, and `zip` (the ordinary Python version) would also be important. These would iterate over Python-tuples-in-Numba, rather than Awkward records. That's probably closer to what a user would want, if they're using Numba as an imperative alternative to array-at-a-time interfaces.
