### ISSUE TITLE
Argmin gives negative values

### ISSUE THREAD

**Issue by dteague** [scikit-hep/awkward#408]
# Overview
When running `ak.argmin()` over certain arrays, the indices are negative.

## Reproduce
Here is an excerpt of an array i am using that caused the bug:
```
tester = ak.Array([[[10.249728202819824, 8.437639236450195, 7.679991722106934, 1.2447497844696045, 9.229813575744629, 0.005525465123355389], [None, None, None, None, None, None]], 
    [[None , None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None]], 
    [[9.047218322753906, 2.489292621612549, 13.802090644836426, 0.040674030780792236, 0.6052520275115967, 12.557860374450684, 24.019344329833984, 2.9109175205230713, 0.9435217380523682], [None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None], [None, None, None, None, None, None, None, None, None]]])       
ak.argmin(tester, axis=-1)  
# [[5, None], [None, None], [-19, None, None, None]]   
# Should be [[5, None], [None, None], [3, None, None, None]]
```
If there are a block of nones ahead of subarray that has numbers that need to be actually minimized, the value becomes negative. Also, the indices get more and more negative farther in the list, as if the indexing problem cascades to the next block.

Not sure if this helps either, but the other axes fail as well in the same way.
```
ak.argmin(tester, axis=-2)
#  [[0, -6, -12, -18, -24, -30],
#   [None, None, None, None, None, None, None, None],
#   [-3, -9, -15, -21, -27, -33, -38, -43, -46]]
```

**Comment by jpivarski** [comment]
Actually, it's not a full block of Nones, it's _any_ Nones!

```python
>>> ak.argmin(ak.Array([[2.2, 1.1], [3.3], [2.2, 1.1]]), axis=-1)
<Array [1, 0, 1] type='3 * ?int64'>
>>> ak.argmin(ak.Array([[2.2, 1.1], [None, 3.3], [2.2, 1.1]]), axis=-1)
<Array [1, 0, 0] type='3 * ?int64'>
>>> ak.argmin(ak.Array([[2.2, 1.1], [None, None, 3.3], [2.2, 1.1]]), axis=-1)
<Array [1, 0, -1] type='3 * ?int64'>
>>> ak.argmin(ak.Array([[2.2, 1.1], [None, None, None, 3.3], [2.2, 1.1]]), axis=-1)
<Array [1, 0, -2] type='3 * ?int64'>
```

I'm going to take a look now. I have an idea of what's going on—the Nones have to be removed; it looks like the index shift represented by removing them has to be put back in.

Thanks for reporting!

**Comment by jpivarski** [comment]
In fact, it can be very simple:

```python
>>> ak.argmin(ak.Array([3.3, 2.2, 1.1]), axis=0)
2
>>> ak.argmin(ak.Array([3.3, 2.2, None, 1.1]), axis=0)
2
>>> ak.argmin(ak.Array([3.3, 2.2, None, None, 1.1]), axis=0)
2
>>> ak.argmin(ak.Array([3.3, 2.2, None, None, None, 1.1]), axis=0)
2
```

**Comment by jpivarski** [comment]
It's because the following case wasn't tested and needs a correction for the index offset caused by removing None values:

https://github.com/scikit-hep/awkward-1.0/blob/e4932ec4c5c57b5731e609f1d6fbfdc4a439e7ea/src/libawkward/array/IndexedArray.cpp#L1926-L1928

(A code coverage tool wouldn't have caught it because it _was_ tested for another reducer, `ak.prod`, but this bug is particular to `ak.argmin` and `ak.argmax` because these are the only two that return index positions.)

The other branch (the `else` just below the `if` quoted above) is tested and correct. That other branch applies to Nones from missing lists, rather than missing values in lists, as your case illustrates.

**Comment by jpivarski** [comment]
Actually, it's more than just that. Here's an example without any Nones:

```python
>>> ak.min(ak.Array([[1.1, 5.5], [4.4], [2.2, 3.3, 0.0, -10]]), axis=0)
<Array [1.1, 3.3, 0, -10] type='4 * ?float64'>
>>> ak.argmin(ak.Array([[1.1, 5.5], [4.4], [2.2, 3.3, 0.0, -10]]), axis=0)
<Array [0, 1, 0, 0] type='4 * ?int64'>
```

`ak.min` does the right thing for `axis=0`: it takes `1.1` from the first list (it's smaller than `4.4` and `2.2`), it takes `3.3` from the second list (it's smaller than `5.5`), and it takes `0.0` and `-10` from the second list (nothing to compare).

By the same logic, `ak.argmin` should be `[0, 2, 2, 2]`. It's not getting the message that non-existent values in the earlier lists shift the baseline: the result for the first slot, `0`, is okay but the result for the second slot, `1`, is wrong because it's not counting the `[4.4]` list, which doesn't have a second slot, and the results for the third and forth slots, `0, 0`, are wrong because it's not counting the `[1.1, 5.5]` and `[4.4]` lists, which both don't have third and fourth slots.

So this is a more fundamental thing about adjusting index positions for missing values (due to lists being too short) than Nones specifically. I'm going to fix the more fundamental bug first because the one you noticed with Nones might just be a byproduct of that. Even if not, it's better to start adjusting from a correct baseline.

**Comment by jpivarski** [comment]
Although this was a bug—wrong behavior—fixing it was something like adding a new feature: both the error you identified (with Nones) and the error I identified (with variable-length lists) were due to it missing a correction for index positions. All reducers have None and variable-length list aware placement of output, but argmin/argmax additionally needs to have its values updated because they refer to positions, which are affected by Nones/jaggedness.

That's done in #410 (I'll be merging soon), and your example works now (among other things).

**Comment by dteague** [comment]
Oh wow, I didn't know the error went so deep! Thanks for the super speedy reply and fix, especially since it was nastier of a bug than expected!

**Comment by jpivarski** [comment]
It was more along the lines of an incomplete implementation. I had tests with jagged arrays and missing values, but this error snaked through the cracks between them. I didn't realize how much there was left to do.

But argmin and max are important—I couldn't leave it wrong. This is being deployed as version 0.2.33 right now.
