### ISSUE TITLE
Multi dimensional indexing goes wrong for ListOffsetArray with numpy array content that is in fortran order

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#418]
Not sure if this is supported, but if i manually construct a `ListOffsetArray` that uses a numpy array in fortran order as content (happened to me accidentally since the output of some np operations return fortran ordered arrays) then things go wrong when i try multidimensional indexing:

```pycon
>>> import awkward1 as ak
>>> import numpy as np
>>> offsets = ak.layout.Index64(np.arange(0, 1010, 10))
>>> np_content = np.asfortranarray(np.arange(0, 3000).reshape(-1, 3))
>>> content = ak.layout.NumpyArray(np_content)
>>> loa = ak.Array(ak.layout.ListOffsetArray64(offsets, content))
>>> loa[0][0] # this is fine
<Array [0, 1, 2] type='3 * int64'>
>>> np_content[0]
array([0, 1, 2])
>>> loa[0, 0] # this goes wrong
<Array [0, 0, 140236515206304] type='3 * int64'>
```

The underlying `NumpyArray` seems to be aware of the fortran order strides and indexing it works as expected:

```pycon
>>> content
<NumpyArray format="l" shape="1000 3" strides="8, 8000" data="0x 00000000 00000000 03000000 00000000 ... b20b0000 00000000 b50b0000 00000000" at="0x56001c85b610"/>
>>> content[0]
<NumpyArray format="l" shape="3" strides="8000" data="0 1 2" at="0x56001c85b610"/>
>>> content[0][1]
1
>>> content[0, 1]
1
```

**Comment by jpivarski** [comment]
Thanks for catching this! Fortran-order NumpyArrays are supported, since they come for free with NumPy's `shape`, `strides` mechanism, which is needed for any sliced NumPy arrays. (This `shape`, `strides` thing is very clever! Worth reading about if you don't already know about it.)

As seen in PR #420, there were two errors: the calculation of `NumpyArray::bytelength`

```diff
@@ -422,7 +422,11 @@ namespace awkward {
       return itemsize_;
     }
     else {
-      return shape_[0]*strides_[0];
+      ssize_t out = itemsize_;
+      for (size_t i = 0;  i < shape_.size();  i++) {
+        out += (shape_[i] - 1)*strides_[i];
+      }
+      return out;
     }
   }
```

which showed up in print-outs of the NumpyArray layout, and `NumpyArray::carry`, which is used to propagate slices down in `__getitem__`. Handling the full non-contiguous case in `carry` would be complicated; I decided to punt for now and just ensure that the array is C-contiguous.

There are quite a few spots like that, in which non-contiguous arrays are allowed as inputs, but they aren't handled efficiently: they're first converted to contiguous and then the operation proceeds. The plan is to get everything working first and optimize hotspots later (i.e. not this year, unless they're particularly egregious). Therefore, if you're using Fortran-order arrays for efficiency, that's not a good strategy with Awkward Array.

---------------

**Before:**

```python
>>> import awkward1 as ak
>>> import numpy as np
>>> np_content = np.asfortranarray(np.arange(15).reshape(3, 5))
>>> np_content
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> ak_content = ak.layout.NumpyArray(np_content)
>>> ak_content
<NumpyArray format="l" shape="3 5" strides="8 24" data="0x 00000000 00000000 05000000 00000000 0a000000 00000000" at="0x55ff9abd35b0"/>
>>> offsets = ak.layout.Index64(np.array([0, 0, 1, 1, 2, 2, 3, 3]))
>>> listoffsetarray = ak.layout.ListOffsetArray64(offsets, ak_content)
>>> listoffsetarray[1, 0]
<NumpyArray format="l" shape="5" strides="24" data="0 33 94556304121488 94556298227728 3" at="0x55ff9aeb1e90"/>
>>> ak.to_list(listoffsetarray[1, 0])
[0, 33, 94556304513392, 94556298227728, 94556301333088]
```

**After:**

```python
>>> import awkward1 as ak
>>> import numpy as np
>>> np_content = np.asfortranarray(np.arange(15).reshape(3, 5))
>>> np_content
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> ak_content = ak.layout.NumpyArray(np_content)
>>> ak_content
<NumpyArray format="l" shape="3 5" strides="8 24" data="0x 00000000 00000000 05000000 00000000 ... 09000000 00000000 0e000000 00000000" at="0x55570d3eab20"/>
>>> offsets = ak.layout.Index64(np.array([0, 0, 1, 1, 2, 2, 3, 3]))
>>> listoffsetarray = ak.layout.ListOffsetArray64(offsets, ak_content)
>>> listoffsetarray[1, 0]
<NumpyArray format="l" shape="5" data="0 1 2 3 4" at="0x55570d401e50"/>
>>> ak.to_list(listoffsetarray[1, 0])
[0, 1, 2, 3, 4]
>>> listoffsetarray[3, 0]
<NumpyArray format="l" shape="5" data="5 6 7 8 9" at="0x55570d3fe2f0"/>
>>> ak.to_list(listoffsetarray[3, 0])
[5, 6, 7, 8, 9]
```

**Comment by jpivarski** [comment]
Interestingly, I noticed along the way that NumPy's `nbytes` doesn't really describe how many bytes a sliced array covers, either:

```python
>>> import numpy as np
>>> import ctypes
>>> a = np.arange(15, dtype="i2").reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int16)
>>> b = a[:, :-1]
>>> b
array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]], dtype=int16)
>>> b.shape
(3, 4)
>>> b.strides
(10, 2)
>>> b.itemsize
2
```

Using the algorithm I implemented for `NumpyArray::bytelength`, the length of the buffer is `(shape[0] - 1)*strides[0] + (shape[1] - 1)*strides[1] + itemsize`:

```python
>>> (3 - 1)*10 + (4 - 1)*2 + 2
28
```

but `ndarray.nbytes` says

```python
>>> b.nbytes
24
```

(which is `shape[0]*shape[1]*itemsize`). If you look at 28 bytes in memory, starting at the data pointer,

```python
>>> np.ctypeslib.as_array((ctypes.c_int16 * int(28/2)).from_address(b.ctypes.data))
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
      dtype=int16)
```

you do need to go 28 bytes out to see everything in `b`. Internally, NumPy must be calculating the right length in order to copy array slices, but the `nbytes` they provide is rather naive. (It's the size the array would be if you copied it into a contiguous buffer, not the size that it is currently occupying in memory.)

**Comment by nikoladze** [comment]
Thanks a lot for the quick fix! I didn't have a use case in mind where fortran ordering would be used for efficiency - i just didn't notice that i was using fortran ordered arrays as they came out of a numpy operation (`np.argwhere`). So returning a C-contiguous copy after `__getitem__`  is perfectly fine.

Indeed the `strides`, `shape` logic is quite interesting!
