### ISSUE TITLE
argmin/max with keepdims=True returns regulararray

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#434]
If I run
```
In [3]: a = ak.Array([[0, 1, 2], [3, 4], [5]])

In [5]: ak.argmin(a, axis=1, keepdims=True)
Out[5]: <Array [[0], [0], [0]] type='3 * 1 * ?int64'>
```
the output is of fixed size in the last axis, and as such it cannot be used in a slice:
```
In [6]: a[ak.argmin(a, axis=1, keepdims=True)]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-83ba94cb4af4> in <module>
----> 1 a[ak.argmin(a, axis=1, keepdims=True)]

~/src/awkward-1.0/awkward1/highlevel.py in __getitem__(self, where)
    939         """
    940         return awkward1._util.wrap(
--> 941             self._layout[where], self._behavior, cache=self._cache
    942         )
    943

ValueError: slice items can have all fixed-size dimensions (to follow NumPy's slice rules) or they can have all var-sized dimensions (for jagged indexing), but not both in the same slice item

(https://github.com/scikit-hep/awkward-1.0/blob/0.2.36/src/libawkward/array/RegularArray.cpp#L846)
```

A workaround is to use `ak.singletons`:
```
In [7]: ak.singletons(ak.argmin(a, axis=1))
Out[7]: <Array [[0], [0], [0]] type='3 * var * int64'>

In [8]: a[_7]
Out[8]: <Array [[0], [3], [5]] type='3 * var * int64'>
```

**Comment by jpivarski** [comment]
Actually, "singletons" was created (along with "firsts") because I hadn't thought of using `keepdims=True`!

The original rationale for having `keepdims=True` return regular-typed lists was because I knew the length was always equal to 1. However, it makes more sense to keep it the same as whatever the dimension used to be.

Additionally, regular-typed lists should remain regular-typed when reducing (with or without `keepdims=True`) unless there are any None values (because they can change the lengths of the outputs). That all has to be decided based on the types, not whether the lists happen to have the same number of items in each. For example, UnmaskedArray counts the same as ByteMaskedArray or any other option-type, even though it doesn't have any Nones.

Everything has been implemented and tested in PR #447 (exhaustively tested: all combinations of variable and regular-typed lists three levels deep, with `axis=-1`, `-2`, `-3`...)

So this should be ready for use as maxby/minby. I guess you don't need to use [ak.firsts](https://awkward-array.readthedocs.io/en/latest/_auto/ak.firsts.html) if the lists were created with `keepdims=True`, since there won't ever be any empty lists. I'm going to start recommending `keepdims=True` for maxby/minby type problems.

(#203 was an idea about adding specialized functions for maxby/minby because the [ak.singletons](https://awkward-array.readthedocs.io/en/latest/_auto/ak.singletons.html)/[ak.firsts](https://awkward-array.readthedocs.io/en/latest/_auto/ak.firsts.html) method is so cumbersome. But maybe that's not needed?)
