### ISSUE TITLE
Handle stream-of-many-JSON files? Options for `"NaN"` strings as NaN floats?

### ISSUE THREAD

**Issue by blipblipgo** [scikit-hep/awkward#437]
This is my first time using awkward and json. I was analyzing the data related to the paper by Guest, Collado, Baldi, Hsu, Urban, Whiteson                                                                                                           
viz. “Jet Flavor Classification in High-Energy Physics with Deep Neural Networks” . Each time I was trying to do the conversion from json to ak array : **ak.from_json('dataset.json'),**  I was getting the error "**ValueError: JSON error at char 2453: The document root must not be followed by other values**."

```
import json
import awkward1 as ak
ak.from_json('dataset.json')
```

Here is the dataset - http://mlphysics.ics.uci.edu/data/hb_jet_flavor_2016/dataset.json.gz
and the details - http://mlphysics.ics.uci.edu/data/hb_jet_flavor_2016/readme.txt

@reikdas @jpivarski

**Comment by jpivarski** [comment]
The problem is that this file technically isn't JSON: it's a stream of many JSON objects. Applied to the same data (taking care because the file is huge), Python's `json.loads` says,

```
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 2453)
```

Python gives a little more information: the beginning of the second object is on the beginning of the second line of text. Though not satisfying the JSON specification, this file fits a widely used format that I like to call "JSONS": a complete JSON object on each line of text. The best way to parse such files is to split them at the line breaks (which are faster to find than balancing JSON curly brackets) and then running a JSON parser on each string.

For your case, this would be

```python
>>> import json
>>> import time
>>> import awkward1 as ak
>>> import numpy as np
>>> 
>>> builder = ak.ArrayBuilder()
>>> for lineno, line in enumerate(open("dataset.json")):
...     if lineno % 114919 == 0:
...         print(time.strftime("%H:%M:%S"), ":", lineno/114919, "percent complete")
...     builder.append(json.loads(line))
... 
08:47:16 : 0.0 percent complete
08:47:23 : 1.0 percent complete
08:47:29 : 2.0 percent complete
...
>>> array = builder.snapshot()
```

I got the total number of lines in this file, 11491971, by running `wc -l dataset.json` on the terminal. It took `wc` 6 seconds to find all the line breaks and count the number of lines; Python's JSON parsing + Awkward's rowwise-to-columnar translation would take 648 seconds if I had the memory for it.

I ran out of memory trying to read this 16 GB JSON file; my computer has 15.5 GB of real memory and 4 GB of swap space. That's close. The text representation of each floating point number uses 9‒13 characters (9‒13 bytes), each of which becomes 8 bytes as a double precision floating point number. Add to that the indexing of the variable-length lists and the tags to build a union-type from the fact that this file mixes lists of different depths (i.e. different data types) in the same array, and the in-memory representation will be larger than this particular text representation. (If it had more or fewer digits, it would be a different story.)

I changed the title of your issue into a feature request because my first thought was that you'd want the handling of JSONS format to be automatic. For future reference, that involves turning on RapidJSON's `kParseStopWhenDoneFlag` (see [Parsing documentation](http://miloyip.github.io/rapidjson/md_doc_dom.html#Parsing)) and setting up tests to make sure that Awkward's JSON SAX → ArrayBuilder does the right thing with the structure that RapidJSON serves in such a case.

Having that capability built in would mean that you wouldn't have to write a for loop to handle each line of text separately. (And it would be more capable: if the JSON objects didn't have line breaks between them, RapidJSON's SAX parser would separate them correctly.) However, if you have a file as large as this one, you'd still have to write a for loop or split it up in appropriate places if you don't have enough memory to hold the whole thing as an array.

In addition, this file has strings mixed in with the numbers: `"NaN"`, `"inf"`, and `"-inf"`. There is no JSON standard for the three "non-finite" floating point values, so the author of this file decided to make them strings. Awkward Array will read those in as strings; dealing with them after the fact means some manipulations. Maybe `ak.from_json` should have some options for interpreting these strings (or different spellings of them, like `"nan"` and `"Infinity"`, since there isn't a standard) as the appropriate floating point values instead of strings.

Naively reading them in and doing

```python
>>> tonan = (array == "NaN")
```

on a 10% sample used up a lot of memory—the string-equality has been implemented in NumPy, rather than low-level C++, so it has some inefficiencies due to storing intermediate arrays. Also, I don't know if [ak.where](https://awkward-array.readthedocs.io/en/latest/_auto/ak.where.html) is currnetly up to the task of deeply replacing data with union-type (unions are the most complex type; that part might not have been implemented _yet_).

Replacing these strings while reading makes the reading step take about twice as long:

```python
>>> def fix(x):
...     if isinstance(x, list):
...         return [fix(y) for y in x]
...     elif x == "NaN" or x == "-NaN":
...         return np.nan
...     elif x == "inf":
...         return np.inf
...     elif x == "-inf":
...         return -np.inf
...     elif isinstance(x, str):
...         raise Exception("unhandled string: " + repr(x))
...     else:
...         return x
... 
>>> builder = ak.ArrayBuilder()
>>> for lineno, line in enumerate(open("dataset.json")):
...     if lineno % 114919 == 0:
...         print(time.strftime("%H:%M:%S"), ":", lineno/114919, "percent complete")
...     builder.append(fix(json.loads(line)))
... 
09:29:12 : 0.0 percent complete
09:29:22 : 1.0 percent complete
09:29:32 : 2.0 percent complete
09:29:42 : 3.0 percent complete
09:29:52 : 4.0 percent complete
09:30:02 : 5.0 percent complete
09:30:12 : 6.0 percent complete
09:30:21 : 7.0 percent complete
09:30:31 : 8.0 percent complete
09:30:41 : 9.0 percent complete
09:30:51 : 10.0 percent complete
^CTraceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "<stdin>", line 3, in fix
  File "<stdin>", line 3, in <listcomp>
  File "<stdin>", line 3, in fix
  File "<stdin>", line 3, in <listcomp>
  File "<stdin>", line 3, in fix
  File "<stdin>", line 3, in <listcomp>
  File "<stdin>", line 3, in fix
  File "<stdin>", line 3, in <listcomp>
  File "<stdin>", line 4, in fix
KeyboardInterrupt
>>> array = builder.snapshot()
>>> ak.type(array)
1156435 * var * union[float64, var * union[float64, var * var * float64]]
```

But at least now you're only dealing with

   * list of numbers (`var * float64`)
   * lists of lists of numbers (`var * var * float64`)
   * lists of lists of lists of lists of numbers (`var * var * var * var * float64`).

Awkward Array can load union-type data, but this type is more limited in operations. In your dataset, it looks like each outer list has exactly 6 elements and each of these has a different depth of structure. Putting even more intelligence into the reading process,

```python
>>> b1 = ak.ArrayBuilder()
>>> b2 = ak.ArrayBuilder()
>>> b3 = ak.ArrayBuilder()
>>> b4 = ak.ArrayBuilder()
>>> b5 = ak.ArrayBuilder()
>>> b6 = ak.ArrayBuilder()
>>> for lineno, line in enumerate(open("dataset.json")):
...     if lineno % 114919 == 0:
...         print(time.strftime("%H:%M:%S"), ":", lineno/114919, "percent complete")
...     l1, l2, l3, l4, l5, l6 = fix(json.loads(line))
...     b1.append(l1)
...     b2.append(l2)
...     b3.append(l3)
...     b4.append(l4)
...     b5.append(l5)
...     b6.append(l6)
... 
09:41:48 : 0.0 percent complete
09:41:58 : 1.0 percent complete
09:42:07 : 2.0 percent complete
09:42:16 : 3.0 percent complete
09:42:25 : 4.0 percent complete
09:42:34 : 5.0 percent complete
09:42:44 : 6.0 percent complete
09:42:53 : 7.0 percent complete
09:43:02 : 8.0 percent complete
09:43:11 : 9.0 percent complete
09:43:20 : 10.0 percent complete
^CTraceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/jpivarski/miniconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/jpivarski/miniconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jpivarski/miniconda3/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
KeyboardInterrupt
>>> a1 = b1.snapshot()
>>> a2 = b2.snapshot()
>>> a3 = b3.snapshot()
>>> a4 = b4.snapshot()
>>> a5 = b5.snapshot()
>>> a6 = b6.snapshot()
>>> ak.type(a1)
1155960 * float64
>>> ak.type(a2)
1155960 * float64
>>> ak.type(a3)
1155960 * int64
>>> ak.type(a4)
1155960 * var * float64
>>> ak.type(a5)
1155960 * var * float64
>>> ak.type(a6)
1155960 * var * var * var * float64
```

which would be a lot easier to deal with if each of these 6 arrays have different meanings. In fact, it's a little faster to read than the union case (fewer cases to handle in ArrayBuilder) and might even fit into memory now that we don't need to store a bunch of tags to represent the union structure.

So to summarize this long-winded answer (which I spent too much time on because it piqued my interest), automatically recognizing JSONS format would be a nice feature, as would automatically substituting strings for the non-finite floating point values. However, in your case, you'd _still_ want to iterate over these data manually to make their structure easier to use later in the analysis. Perhaps, ultimately, the ideal is to include yet more features: better memory handling in expressions like `array == "NaN"` and better ways to deal with union-typed data. But on the timescale of this year, you're better off writing a Python loop to ingest the data, "fixing" it as you go.

One last comment: I tried loading the whole thing as 6 separate arrays and ran out of memory at 74%. This technique uses _less_ memory, but the file still needs to be split into at least two parts for a computer with 15.5 GB of RAM. Be sure to split it on a line boundary. Or if you don't need all 6 of those differently typed arrays, dropping the ones you won't use before loading them into ArrayBuilders will use a lot less memory. (Watch it in `htop`: the memory use jumps up and down because everything that's not being accumulated into arrays gets garbage collected by Python.)

Another "last" comment: once you've read these arrays into columnar form, save them as Parquet files: [ak.to_parquet](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_parquet.html). Parquet is a numerical format that stores lists of lists of lists in a _columnar_ way, like Awkward and unlike JSON/JSONS. With an exact 10% sample (1149197 lines from the original JSONS file):

```python
>>> array = ak.Array({"a1": a1, "a2": a2, "a3": a3, "a4": a4, "a5": a5, "a6": a6})
>>> ak.type(array)
1149197 * {"a1": float64, "a2": float64, "a3": int64, "a4": var * float64, "a5": var * float64, "a6": var * var * var * float64}
>>> array.a1
<Array [47.9, 35, 26.6, ... 67.3, 23.9, 32.3] type='1149197 * float64'>
>>> array.a2
<Array [1.89, 0.61, -0.53, ... 0.569, 0.655] type='1149197 * float64'>
>>> array.a3
<Array [5, 5, 5, 5, 5, 5, ... 0, 5, 5, 5, 5, 0] type='1149197 * int64'>
>>> array.a4
<Array [[21.2, 8.37, 29, ... -1, -inf, -inf]] type='1149197 * var * float64'>
>>> array.a5
<Array [[32.9, 3, 7, 0.162, ... inf, -1, -inf]] type='1149197 * var * float64'>
>>> array.a6
<Array [[[[0.0312, 0.082, ... 1, 0.644]]]] type='1149197 * var * var * var * flo...'>
>>> ak.to_parquet(array, "array.parquet")
```

created a file that is 30× smaller, so 3× smaller per datum (remember that this is a 10% sample) and took 3.3 seconds to load:

```python
>>> import awkward1 as ak
>>> starttime = time.time(); array = ak.from_parquet("array.parquet"); print(time.time() - starttime)
3.3123741149902344
>>> array.a1
<Array [47.9, 35, 26.6, ... 67.3, 23.9, 32.3] type='1149197 * ?float64'>
>>> array.a2
<Array [1.89, 0.61, -0.53, ... 0.569, 0.655] type='1149197 * ?float64'>
>>> array.a3
<Array [5, 5, 5, 5, 5, 5, ... 0, 5, 5, 5, 5, 0] type='1149197 * ?int64'>
>>> array.a4
<Array [[21.2, 8.37, 29, ... -1, -inf, -inf]] type='1149197 * option[var * ?floa...'>
>>> array.a5
<Array [[32.9, 3, 7, 0.162, ... inf, -1, -inf]] type='1149197 * option[var * ?fl...'>
>>> array.a6
<Array [[[[0.0312, 0.082, ... 1, 0.644]]]] type='1149197 * option[var * option[v...'>
```

which is 28× faster than parsing the JSONS (93 seconds vs 3.3 seconds). It still doesn't solve the problem of memory overhead—I can't, for instance, load 10 of these into the same Python process.

Now I'm going to delete this 16 GB file and I'm not going to download it again. Good luck!

**Comment by blipblipgo** [comment]
Thanks Jim for your time and effort. I just skimmed through your reply, lemme work through it.

**Comment by jpivarski** [comment]
Done (in #568): both multi-JSON and nan/inf/-inf strings.
