### ISSUE TITLE
Can "cmake" be removed from pyproject.toml?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#466]
@henryiii Is this a relic of our original attempt to base Awkward's compilation on Scikit-Build?

https://github.com/scikit-hep/awkward-1.0/blob/e4932ec4c5c57b5731e609f1d6fbfdc4a439e7ea/pyproject.toml#L5

It might be causing #430 because the cmake pip package depends on Scikit-Build and Scikit-Build doesn't support Windows (in Cygwin).

Do the dependencies declared in pyproject.toml get installed in all cases or only those involving the source distribution? If someone's getting this from a wheel, they shouldn't need CMake. If they're getting it from the source distribution, we're already in desperation mode—it might be better to allow users in this mode the flexibility to use their own CMake. (That option would be better for @kpedro88.)

I can try removing it and setting up an Azure node to try to install from a wheel to test it, but that will take some time. I'm wondering if you have want thoughts first. Thanks!

**Comment by jpivarski** [comment]
This is the case in the latest release (though I think the source tarball hasn't been deployed yet).

**Comment by henryiii** [comment]
I mentioned this on slack because I have not had full internet until today. If a user can't get the Windows wheel, they can manually set up a build environment (including putting CMake in the path), then they can build with `--no-build-isolation`. Or they can manually install Scikit-Build, which will enable them to install CMake from the CMake SDist, as long as they have the requirements to build CMake.

**Comment by jpivarski** [comment]
I'm putting that back in #470. I remembered at the last minute that this was an issue, but I didn't remember how it wasn't resolved. There are too many things in-flight, I think I opened 6 one-line PRs yesterday.
