### ISSUE TITLE
Build with external PyBind11

### ISSUE THREAD

**Issue by vvolkl** [scikit-hep/awkward#476]
As far as I can tell, the CMakeLists.txt of this project makes it fairly hard to use an existing install of pybind11. I'd like to request an option to use either the builtin/submodule or external. Can prepare a PR if needed.

**Comment by jpivarski** [comment]
Sure, I'm interested, though I don't understand how that would be a good thing. What's the use-case?

The reason I'm asking so bluntly is because I've found that if two Python extension modules are compiled with very different versions of pybind11, they can't share objects in each others' function arguments. I can see this becoming a problem for C++ projects that produce or consume Awkward Arrays through a Python interface (like [dependent-project](https://github.com/scikit-hep/awkward-1.0/tree/master/dependent-project)). I think then we'd have to be very clear about which version of pybind11 a given version of Awkward Array is compiled with so that dependent projects can use this interface. (Like, a table mapping major/minor Awkward version numbers, X.Y for all .z, to specific pybind11 version numbers.)

If it's easy to change the pybind11 version, won't there be a "version hell" problem trying to get the right one? Wouldn't making the compilation more flexible make interoperability more difficult?

Also, I'm trying to make sure that the vast majority of users can get a wheel for their system. What's the specific reason you're compiling?

**Comment by vvolkl** [comment]
Of course, the use-case is to include awkward in the software stack of an experiment design study. Not as big as the LHC experiments, but still, it's not desirable to have three separate packages ship their own pybind11. At this scale, "version hell" is a known problem anyway, and software librarians have tooling to get consistent installs. But packages that treat dependencies in a clear and uniform way do help a lot here!

In particular, I'm evaluating the spack build manager, which is very effective at dealing with problem like the one you describe. For now I'm fine with installing a patched version of uproot4
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-awkward1/pybind11.patch
But I do think that treating dependencies as such instead of hiding them to reduce the complexity for users is a good idea (especially since this can be optional) -- just mention the required version(s) of pybind11 in the CMakeList.

Also, it seems to me that for the problem you describe, it would be worse anyway to have different packages set up their own pybind11 instead of using one external one?

**Comment by jpivarski** [comment]
If it were a shared library with externally visible symbols, then definitely it would be worse for packages to bring their own. In fact, I've seen this become an issue between ROOT and Julia: the LLVM symbols clashed.

But I think a header-only library is different. At least, as an extreme, the embedding of RapidJSON is 100% safe because this dependency isn't even visible—it's only used in Awkward implementations, never any header files, and only objects defined in Awkward's header files are exposed (visibility=false with explicit exceptions). If two libraries had different versions of RapidJSON, they wouldn't even find out. You might say that one is a waste of disk space, but that's not what we usually care about.

But pybind11 is a different case. It's visible—it literally is the interface—but it's not presenting a suite of pybind11 symbols to the dynamic loader, it's making PyCapsules for the Python C API out of Awkward objects. Mixing pybind11 versions would prevent packages that depend on Awkward for being able to pass their data into each other's functions in Python, but it wouldn't affect unrelated libraries using pybind11 for types that are incompatible anyway. In fact, it was to prevent accidental collisions of intermediate symbols that pybind11 requires projects to be compiled with visibility=false.

If your software stack has Awkward compiled with a different version of pybind11 than a matrix claims, then dependent packages that are supposed to work with that version won't work with that version.

I understand the point that sharing libraries usually makes a collection of packages more maintainable because you can avoid symbol clashes, but here there are no symbols to clash and introducing uncertainty about which version of Awkward uses which version of pybind11 will make it impossible to know if a dependent library is going to work. (Unless, of course, the dependent library is compiled in the same package library you're developing—but do you want to say that users can't bring in their own packages from elsewhere? That's a valid option—what conda does—but then you have to be prepared to include everything every user wants in the distribution. Maybe this isn't for users? Is it a reconstruction workflow?)

**Comment by jpivarski** [comment]
Actually, what happens when you try compiling the normal way? I assume that everything builds as expected, the tests run, and if there are any issues, they're possible/future issues.

It also wouldn't be a difficult thing, technically, to add a CMake build variable to opt into a different pybind11 directory location, which changes this line:

https://github.com/scikit-hep/awkward-1.0/blob/820a2b0ba655fa17e19042f5b32b6c5996347d3c/CMakeLists.txt#L110

The "version hell" I was talking about was one that would fall on the shoulders of scientists attempting to use the library, which is a much bigger issue than a software librarian dealing with them. ("At this scale, "version hell" is a known problem anyway, and software librarians have tooling to get consistent installs.") But, as is evident in the parenthetical sentence at the end of my last message, I'm just now realizing that the software stack you're building might not be intended for individual scientists to use. It might be supporting a reconstruction pipeline whose application is known ahead of time. The example I'm familiar with, CMSSW, is used both ways: to support the large-scale reconstruction and to set up an environment in which individual scientists work on projects whose dependencies aren't known in advance.

So if you're building a pipeline that will run one application and 100% of the dependencies will always be supplied through the software stack, then let's add that line to the Awkward CMakeLists so that you can use whichever pybind11 you prefer. (It's still not clear to me that this is necessary, but in this case, it doesn't hurt.)

But if you're building an environment for individual scientists to use ad-hoc, individuals who might bring in Python packages from other sources like pip, conda, homebrew, ... etc., then I'm going to want to force particular versions of Awkward to use particular versions of pybind11 so that this will be deterministic. Otherwise, _they'll_ be the ones trapped in version hell, and they won't have the expertise or the tooling to fix it.

**Comment by vvolkl** [comment]
> Actually, what happens when you try compiling the normal way? I assume that everything builds as expected, the tests run, and if  there are any issues, they're possible/future issues.

Ah, right my bad, I was compiling from the github release tarball, not the pypi downloads. This doesn't include the submodules, and the error prompted me to open the issue. 

I'm not that familiar with pybind11, and from your comment it seems indeed to be less clear cut. For individual ad-hoc use, I fully subscribe to bundlining it. Our usecase is similar to CMSSW - awkward is not directly used in reconstruction, but we want to be able to run also common analysis script with the central software installation (for reproducibility etc.). In this case there is much less potentials for errors due to version mismatches. And while it may not "cost" much to bundle pybind11, it does remind me of this comment I read somewhere:

>By my count, the unreal engine source tree only has 3 full copies of boost inside it. In my opinion, any real engine should easily have 4 or 5 copies of boost to really deliver on quality.

But this verges on the philosophical, so I'm fine with closing this issue.

**Comment by jpivarski** [comment]
Okay, thanks for clarifying! Since this is a case in which a downstream library depending on Awkward might come from a different compilation, let's stick with the embedded pybind11.

Since the GitHub release tarball doesn't include submodules, perhaps I should look into a way of removing that link. When cloning the repository, there's the `--recursive` flag, but that doesn't apply to the tarball.

PyPI is a better source anyway; it's the distribution you'd get with

```bash
pip install awkward1 --no-binary
```

which ought to compile Awkward using only the files shipped as part of that version. (I hope I didn't get the `--no-binary` flag wrong; you'd want it to take the NumPy wheel but compile Awkward. NumPy is Awkward's only pip dependency.)
