### ISSUE TITLE
Returning ak.zip() of lazy arrays loses "its weak reference to mapping"

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#479]
Apparently an `ak.zip()` of lazy arrays cannot be evaluated after it has been returned from a function:

```python
>>> import awkward1 as ak
>>> import uproot4
>>> def func():
...     tree = uproot4.lazy('tests/scalars_tree_file.root')
...     return ak.zip([tree['int_branch'], tree['long_branch']])
... 
>>> print(func())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/awkward1/highlevel.py", line 1253, in __str__
    return self._str()
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/awkward1/highlevel.py", line 1273, in _str
    return awkward1._util.minimally_touching_string(
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/awkward1/_util.py", line 1486, in minimally_touching_string
    lft = next(leftgen)
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/awkward1/_util.py", line 1473, in forever
    for token in iterable:
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/awkward1/_util.py", line 1367, in forward
    for token in forward(x[i], sp):
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/awkward1/_util.py", line 1377, in forward
    for token in forward(x[str(i)], ""):
RuntimeError: PyArrayCache has lost its weak reference to mapping

(https://github.com/scikit-hep/awkward-1.0/blob/0.3.1/src/python/virtual.cpp#L334)
```

whereas returning a plain `list` works just fine:

```python
>>> def func():
...     tree = uproot4.lazy('tests/scalars_tree_file.root')
...     return [tree['int_branch'], tree['long_branch']]
... 
>>> print(func())
[<Array [0, -1] type='2 * int32'>, <Array [0, -2] type='2 * int64'>]
```

**Comment by jpivarski** [comment]
@nsmith- Just thinking... below are notes.

Something to think about: the cache was attached to the `ak.Array` with the understanding that any transformations of that array would lose the original `ak.Array` and therefore also lose the cache, but since the array has been transformed, the original isn't needed, anyway.

But here's a case where the cache should be retained but the `ak.Array` goes away. `ak.zip` combines many arrays, so the output `ak.Array` has to have a cache that holds all of the old ones, but doesn't necessarily add to them, like this:

```python
class MergedCaches(MutableMapping):
    def __init__(self, *arrays):
        self._old_caches = [x.cache for x in arrays
                            if isinstance(x, awkward1.highlevel.Array) and x.cache is not None]
    def __getitem__(self, where):
        for cache in self._old_caches:
            try:
                return cache[where]
            except KeyError:
                pass
        else:
            raise KeyError(where)
    def __setitem__(self, where, what):
        pass
```

And just as every operation calls `awkward1._util.behavior_of(*input_arrays)` to get a merged behavior for the output, they'd have to create a `MergedCaches(*input_arrays)` to pass to the `cache` argument of

https://github.com/scikit-hep/awkward-1.0/blob/c314dfe6c907609114a6d53a7ccee2fbaf10174f/src/awkward1/_util.py#L375-L391

so that old caches are not forgotten, but the new cache object is not usable as a place to put things. (Perhaps the caches attached to `ak.Array` need to be Mappings, not MutableMappings. The cache passed to `ArrayCache` must be a MutableMapping, but for the sake of attaching it to an `ak.Array`, it doesn't need to be mutable.

Also, the `ak.Array` cache would have to be updated to take on any new caches attached through `ak.Array.__setitem__`.

**Comment by nsmith-** [comment]
Shoot. My first reaction was that I thought `ak.zip` would materialize the arrays. I think merging caches is reasonable, and indeed ~all of these are `Mapping` instances at this interface~ literally the only purpose of tracking `Array.cache` is to hold a reference, we don't need any of the functionality in theory. One tweak I would suggest is to make a set of the array caches, since often (and indeed in this example) the actual cache object will be the same for both high-level arrays being passed to `ak.zip`.

**Comment by jpivarski** [comment]
I was thinking that, too, while writing the code. Maybe the list comprehension in the `MergedCaches.__init__` should be

```python
list({
    id(x.cache): x.cache
    for x in arrays
    if isinstance(x, awkward1.highlevel.Array) and x.cache is not None
}.values())
```

(Caches won't, in general, be hashable.)

**Comment by nsmith-** [comment]
I think, similar to behavior, there should be a function that returns the original object if it is useable, and an instance of this merged cache object if otherwise

**Comment by jpivarski** [comment]
And also keeps it flat, rather than making MergedCaches of MergedCaches (which could be viewed as part of what you described above: 0 caches → None, 1 cache → that cache, 2 or more → a MergedCache of the caches, but no nesting).

**Comment by jpivarski** [comment]
What I did in #512 is a more complete solution than what is described above. Instead of `ak.Array.cache` being a user-settable property of an `ak.Array`, a read-only property `ak.Array.caches` is a tuple of all distinct caches used in the layout. When an `ak.Array` is first built, it collects references to the caches the layout contains and puts them in this tuple to maintain their references.

There's still a potential for gaps, in which old references might be lost before the new reference is made, but these necessarily happen in low-level functions; it's never a high-level user's responsibility to keep track of them. For instance, the following implementation of `do_something` can lose cache references, leading to the RuntimeError:

```python
def do_something(array):
    layout = array.layout
    del array
    return ak.Array(layout)
```

but the following will not lose cache references/no RuntimeError:

```python
def do_something(array):
    layout = array.layout
    return ak.Array(layout)
```

Real bugs are unlikely to be that simple, but this is the essence: a low-level function that extracts a layout from an `ak.Array` and does something with it must keep the original `ak.Array` around long enough for the new, output `ak.Array` to be returned.

Another way it could fail is if a new cache is not held before making the output:

```python
def do_something(func):
    layout = ak.layout.VirtualArray(func, ak.layout.ArrayCache(ak._util.MappingProxy({})))
    return ak.Array(layout)
```

would fail because the reference to `ak._util.MappingProxy({})` is lost but

```python
def do_something(func):
    hold_cache = ak._util.MappingProxy({})
    layout = ak.layout.VirtualArray(func, ak.layout.ArrayCache(hold_cache))
    return ak.Array(layout)
```

would succeed because `hold_cache` stays in scope until the `ak.Array` can be made.

So it's not foolproof, but it is out of most users' way—something only framework developers need to think about—and this solution doesn't depend on every operation passing cache references on to the next operation: all caches are collected from the entire layout whenever an `ak.Array` is made; none would be missed.

The changes in interface are now marked with DeprecationWarnings. @nsmith-, you should test this with NanoEvents. (I'll be pushing a new release because the interface changes also need to be coordinated with Uproot.)
