### ISSUE TITLE
How to slice array with a list or ndarray

### ISSUE THREAD

**Issue by jtang10** [scikit-hep/awkward#480]
This is for requesting new documentation or corrections/modifications/additions to existing documentation.

If you have a problem without an answer in the [How do I…?](https://awkward-array.org/how-to.html) tutorials, ask it here and we will answer it as a new tutorial that will benefit everybody.

If your problem is too specific for that or it isn't exclusively related to Awkward Array, it might be more appropriate to ask on [StackOverflow with the [awkward-array] tag](https://stackoverflow.com/questions/tagged/awkward-array), instead of here. Be sure to include tags for any other libraries that you use, such as Pandas or PyTorch.

Here are some additional links that might help you find what you're looking for. It would be helpful if requests to change existing documentation includes a link.

   * [The tutorials site](https://scikit-hep.org/awkward-1.0/index.html)
   * [The C++ API](https://awkward-array.readthedocs.io/en/latest/_static/index.html)
   * [The Python API](https://awkward-array.readthedocs.io/en/latest/index.html)

Given I have a 2d np.ndarray, e.g. with shape (512, 128) and called arr, and I have a list or 1d np.ndarray with shape (512) and values indicating the indices for each row in arr, I want to create ak array (terminology might be wrong since I just noticed your amazing package) that takes the first k elements for each row, with k as each element in indices array. The following code shows the intended behavior.
```
arr = np.random.rand(512, 128)
arr = ak.from_numpy(arr)
ind = np.random.randint(0, 10, 512).tolist()
sub = arr[:, :ind]
```
I believe [How to filter lists within arrays using jagged slicing](https://awkward-array.org/how-to-filter-jagged.html) is related to this topic but there is no documentation yet. Would anyone be generously pointing me to the right location to look into this? Or write this doc? Thank you very much!

**Comment by jpivarski** [comment]
Noted: this will be the next section I write.

In particular, I'll update #409 (where I was _starting_ to write docs again, but it fell by the wayside because of other work), write the page you requested, and then finish that PR so that it updates on the web.

However, I think I can give you some quick pointers to help you now.

   * If your arrays all have fixed-size dimensions (as in your example), you can use NumPy directly. Awkward Array's syntax is the same as NumPy's, and Awkward Array can be as fast as but no faster than NumPy, so the reason you'd use Awkward is to get generality. If your problem is not more general than NumPy, I don't see a reason to use it.
   * I'm not sure what you're intending to do with `sub = arr[:, :ind]` because `ind` is a list of numbers. Python only allows scalar numbers as the start, stop, or step of a slice (the `:` syntax inside square brackets).

For example, if you have

```python
>>> arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
>>> arr
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
```

(It's always good to use small, non-random examples, so that you can see what's going on.)

Getting the first `k` (e.g. `2`) of each row is

```python
>>> arr[:, :2]
array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])
```

[NumPy's advanced indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html) lets you rearrange, duplicate, and/or drop elements from each row:

```python
>>> arr[:, [2, 0, 0, 1]]
array([[ 3,  1,  1,  2],
       [ 6,  4,  4,  5],
       [ 9,  7,  7,  8],
       [12, 10, 10, 11]])
```

As a special case, boolean indexing lets you drop elements only:

```python
>>> arr[:, [True, False, True]]
array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])
```

All of the above is equally true of an Awkward Array:

```python
>>> arr = ak.from_numpy(arr)
>>> arr
<Array [[1, 2, 3], [4, 5, ... 9], [10, 11, 12]] type='4 * 3 * int64'>
>>> arr[:, :2]
<Array [[1, 2], [4, 5], [7, 8], [10, 11]] type='4 * 2 * int64'>
>>> arr[:, [2, 0, 0, 1]]
<Array [[3, 1, 1, 2], ... [12, 10, 10, 11]] type='4 * 4 * int64'>
>>> arr[:, [True, False, True]]
<Array [[1, 3], [4, 6], [7, 9], [10, 12]] type='4 * 2 * int64'>
```

But Awkward Arrays also work on irregular shapes:

```python
>>> arr = ak.Array([[1, 2, 3], [4], [5, 6]])   # these lists have different lengths; not allowed in NumPy
>>> arr
<Array [[1, 2, 3], [4], [5, 6]] type='3 * var * int64'>
>>> arr[:, :2]
<Array [[1, 2], [4], [5, 6]] type='3 * var * int64'>
>>> arr[:, :1]
<Array [[1], [4], [5]] type='3 * var * int64'>
>>> arr[:, [0, -1]]
<Array [[1, 3], [4, 4], [5, 6]] type='3 * 2 * int64'>
```

and using an Awkward Array _as a slice_ has no analogue in NumPy, but it lets you pick out different numbers of elements from each row.

```python
>>> arr[ak.Array([[1, 1, 0], [0, -1], []])]
<Array [[2, 2, 1], [4, 4], []] type='3 * var * int64'>
>>> arr[ak.Array([[True, False, True], [False], [True, True]])]
<Array [[1, 3], [], [5, 6]] type='3 * var * int64'>
```

I hope this helps you get started!

**Comment by jtang10** [comment]
Hello Jim, thank you for your reply. It looks like the last two examples are related to the scenario I'm dealing with. What I am looking for is that given the original array has regular shape, and I have a list which contains varying number denoted as ls[i] = k, denoted as take the first k element in row i of the regular array, i.e.
```
>>> arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
>>> arr
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
>>> ls = [0, 3, 1 ,2]
>>> arr[:, :ls]
array([[],
       [4, 5, 6],
       [7],
       [10, 11]])
```
Numpy supports it well if you slice each row with the same number of elements but not if you want to slice each row with different number of elements. I see awkward array can do something similar to what I described above shown in the last example, but more a np.take style rather than slicing. 

Maybe I'm asking too much for this and need to rethink the strategy of my code. All I need to do is taking the argmin or min of the first k element in each row of a np.ndarray, with k varying. I have fair experience vectorizing my code but in this work I don't see any strategies to optimize it other than parallelizing the for-loop or use numba.jit to automate the optimization so far.

**Comment by jpivarski** [comment]
Oh, so it is an Awkward problem, after all.

Since you want to select everything up to N, you need to make a list of integers from 0 to N, like what `range` does. The slice syntax (`:` character) is not involved.

```python
>>> import numpy as np
>>> import awkward1 as ak
>>> arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
>>> lengths = [0, 3, 1, 2]
>>> ak.from_numpy(arr)[[range(length) for length in lengths]]
<Array [[], [4, 5, 6], [7], [10, 11]] type='4 * var * int64'>
```

The slowest part of that is creating the slice: `[range(length) for length in lengths]` is a collection of Python objects that have to be implicitly converted into an Awkward array to use it as a slice. The structure has to be like the following, and I don't know of any functions that will make it for you:

```python
>>> ak.Array([[], [0, 1, 2], [0], [0, 1]])
```

so it has to be created by hand. Creating it by hand in Numba is faster; you could use

```python
>>> import numba as nb
>>> @nb.jit
... def make_index(lengths, builder):
...     for length in lengths:
...         builder.begin_list()
...         for x in range(length):
...             builder.append(x)
...         builder.end_list()
...     return builder
... 
>>> lengths = np.array([0, 3, 1, 2])
>>> make_index(lengths, ak.ArrayBuilder()).snapshot()
<Array [[], [0, 1, 2], [0], [0, 1]] type='4 * var * int64'>
```

Knowing that this is an interesting case, I can include it in the documentation on slicing. Mixing Numba's ability to speed up for-loops with Awkward's for-loopless interface can be powerful.

-------------------------

Although... I guess you could also take a more direct approach using Numba only:

```python
>>> arr = ak.from_numpy(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]))
>>> @nb.jit
... def make_direct(input, lengths, builder):
...     for row, length in zip(input, lengths):
...         builder.append(row[:length])
...     return builder
... 
>>> make_direct(arr, lengths, ak.ArrayBuilder()).snapshot()
<Array [[], [4, 5, 6], [7], [10, 11]] type='4 * var * int64'>
```

Whatever seems more natural to you. (There might also be a performance difference for large arrays, since the two techniques are doing rather different things with the data you have in memory. The resulting arrays would also have different performance characteristics, but which is better depends on how it's used _after_ creation. But for performance questions, try one and if it's fine for your needs, no reason to change it!)
