### ISSUE TITLE
removing none from awkward array 1

### ISSUE THREAD

**Issue by ramankhurana** [scikit-hep/awkward#490]
Hello 

I have an awkward array (1) which I obtained post-processing.

An array look like (with some of the elements as None):

>>> a=ak.Array([96., 99., 67., 13.,  3.,  None, 1.,  1.,None])

I want to remove the None elements from this array. I tried following but it does not give expected result: 
>>> b=a[a!=None]
>>> b
<Array [96, 99, 67, 13, ... None, 1, 1, None] type='9 * ?float64'>

 I could remove them using loop and worked, but I want to avoid it to save some computing time. Or writing a function and compiling using Numba is only option?

Thanks.

**Comment by ramankhurana** [comment]
I just realised that is_none exist and work like charm, 

a[~ak.is_none(a)]

**Comment by Superharz** [comment]
> 
> 
> I just realised that is_none exist and work like charm,
> 
> a[~ak.is_none(a)]

I agree with your solution. 
However, it doesn't seem to work for nested arrays, like:
```
a = [[1, None], [3]   , [] , [4, None, 6]]
a = ak.from_iter(a)
ak.is_none(a)
#<Array [False, False, False, False] type='4 * bool'>
``` 
It would be nice if an ```axis``` parameter could be added to ```ak.is_none()```

**Comment by jpivarski** [comment]
I agree. That's #193.

**Comment by ramankhurana** [comment]
I agree, i end up in a situation where I have the nested arrays. I would wait for the feature to be in the awkward array in future.

**Comment by Superharz** [comment]
I haven't been aware of #193. Thanks for bringing it up.

**Comment by jpivarski** [comment]
Also, someone contacted me on Slack about this—the natural-looking syntax

```python
a[a != None]
```

won't work because `np.equal` and `np.not_equal` have not been overridden to interpret missing value `==` missing value as True and missing value `==` anything else as False. (More likely, they'd be overridden to call `ak.is_none`.)

(If "None" were "NaN," then things would be even more complicated, semantically, because `NaN == NaN` is always _supposed to be_ False. By spelling it "None," we've committed to a user expectation that `None == None` is True, which is more palatable.)

And another thing, which has bothered me but apparently nobody else yet, is that using a slice to remove None values keeps the type of the array as option-type, potentially missing values, even though all of the actually missing values have been removed. Since the result of `~ak.is_none(a)` has lost its connection to `a`, passing it to `a[·]` can't tell it, "Yes, this eliminates every last None; you can simplify your type." If it's desirable to have such a feature, we'd probably want to create `ak.drop_none`. Doing it in one step allows us to know enough to change the type. Also, an operation like `ak.drop_none` on missing values would have parallels with an operation to project a union onto only one of its possibilities and simplify _its_ type, which is important because unions can't be used everywhere (for example, Numba).

**Comment by Superharz** [comment]
```ak.drop_none``` sounds like a nice thing to have.

About the Slack: is there a way to join it myself?

**Comment by jpivarski** [comment]
> About the Slack: is there a way to join it myself?

This is the [IRIS-HEP](https://iris-hep.org/) Slack, though there are also non-IRIS-HEP members of the particle physics community on it. (It's not specifically an Awkward Array Slack or anything; for that, I have a [Gitter channel](https://gitter.im/Scikit-HEP/awkward-array)). It's not restricted, and if you think it makes sense to join, send me your email address by email (I'm pivarski at princeton.edu) and I'll send you an invite.

Actually, I'd prefer these sorts of requests to be on GitHub Issues, anyway. Getting them on a different platform makes it less likely that I'll remember to do them and a private message on Slack has zero chance of anyone else stepping in to do it, since they don't even know about it. In fact, it's lucky that the above discussion reminded me about the `a[a != None]` thing long enough to write it down here. Without that reminder, it probably would have just died in my memory.

**Comment by ramankhurana** [comment]
I also tried a[a!=None] but did not work, but could not understand why? 
I also asked the same question on stackoverflow a week ago and due to no response I posted directly here :) 

https://stackoverflow.com/questions/64308530/removing-none-from-an-awkward-array/64419535#64419535

we can update it, one a[a!=None] is working

**Comment by jpivarski** [comment]
I have no idea why I didn't get an alert about the StackOverflow question. I'm signed up for email alerts for everything tagged `[awkward-array]`. There's something about StackOverflow's "watching" system that I don't understand...

-----

As it stands, `a != None` is evaluated just like any other `np.not_equal`: any None values are set aside, everything else is compared using NumPy (for which all the non-None values in `a` all return False—they're not equal to None by definition), and then the True/False values (all False) are mixed in with the None values that have been set aside. For

```python
>>> a = ak.Array([96, 99, 67, None, 1, None])
>>> a
<Array [96, 99, 67, None, 1, None] type='6 * ?int64'>
```

the result of `a != None` is the same as the result of `a != 5`:

```python
>>> a != None
<Array [True, True, True, None, True, None] type='6 * ?bool'>
>>> a != 5      # notice that the outputs are True, False, or None; the type is not bool but ?bool
<Array [True, True, True, None, True, None] type='6 * ?bool'>
```

because "missing" is a special value that is not checked for equality like everything else. As I said in a parenthetical statement above, defining the equality of missing values has had a long, strange history. At least if we're spelling it "None" and not "NaN", Python has a tradition of interpreting None as an ordinary object that can be equal or not equal to things—specifically, it's not equal to anything except another None. To make Awkward Array more familiar to newcomers from Python, we should make `!= None` mean False for missing values, True otherwise.

Getting `a == None` and `a != None` to return non-option-type booleans (i.e. type `bool`, not `?bool`) from `ak.is_none` would require modification to this function

https://github.com/scikit-hep/awkward-1.0/blob/e1fe6f2497ae007bdddcdbd60a08f7bbec4e1029/src/awkward1/_connect/_numpy.py#L71-L105

to recognize that (a) the `ufunc` is `numpy.equal` or `numpy.not_equal`, (b) one of the `inputs` is `None`, and (c) that the other of the `inputs` (there can only be two) has option-type:

https://github.com/scikit-hep/awkward-1.0/blob/e1fe6f2497ae007bdddcdbd60a08f7bbec4e1029/src/awkward1/_util.py#L70-L76

and then return a lambda that calls `awkward1.operations.structure.is_none` with `highlevel=False`, rather than the default of returning no lambda (None), letting the recursion continue to the next level of depth (after which, the missing values have already been set aside and it's too late).

But doing this, formally recognizing that missing values are equal to None (instead of just presenting them on the screen that way and converting them to None in `ak.to_list`), we'd be obliged to also say that

```python
ak.Array([1, None, 2]) == ak.Array([3, None, None])
```

should return

```python
ak.Array([False, True, False])
```

which is to say, the intersection of `ak.is_none` (which checks to see where the two arrays both have missing values) and the normal definition of `np.equal` (one step further in the recursion, after the None values have already been set aside). This is totally doable, but it's more complicated than the above, and both must be implemented together for consistency. That's why it's in the "should be done, hasn't been done" category.
