### ISSUE TITLE
add function similar to np.add

### ISSUE THREAD

**Issue by ramankhurana** [scikit-hep/awkward#491]
Dear Experts 

Since stackoverflow sometime does not behave good so I am just posting the issue here, 

https://stackoverflow.com/questions/64436398/ak-add-function-similar-to-np-add

**Comment by jpivarski** [comment]
I've answered it on StackOverflow, and I'm looking into why I didn't get an email about the use of the `[awkward-array]` tag. According to StackOverflow, it's one of my watched tags.

**Comment by jpivarski** [comment]
It turned out that StackOverflow had confirmed my email address for watching the `[uproot]` tag, but it hadn't confirmed my email address for watching the `[awkward-array]` tag. Since most of the questions had previously been tagged with both `[uproot]` and `[awkward-array]` (because Awkward is still growing into recognition as a library on its own), I hadn't realized that I was missing questions marked with `[awkward-array]` only.

That's fixed now. Sorry I missed your question!
