### ISSUE TITLE
Provide access to localindex

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#496]
`localindex` is a very useful feature in awkward0 that seems to be present in various places in the source of awkward1, but isn't exposed through the `Array` interface as far as I can tell. That is, it would be nice to be able to get the awkward1 equivalent of:

```python
>>> import awkward 
>>> awkward.fromiter([[1], [2, 3]]).localindex
<JaggedArray [[0] [0 1]] at 0x7ff85f9beac0>
```

**Comment by jpivarski** [comment]
Yes, this needs to become a high-level function in src/awkward1/operations/structure.py.

The implementation exists and is even accessible to Python at the "layout" level, but it isn't a high-level function recommended for users with documentation and everything. That is, you can do this:

```python
>>> import awkward1 as ak
>>> array = ak.Array([[1.1, 2.2, 3.3], [], [4.4, 5.5]])
>>> ak.Array(array.layout.localindex())
<Array [[0, 1, 2], [], [0, 1]] type='3 * var * int64'>
```

But you'd really want to be able to do that without having to manually unwrap with `.layout` and re-wrap with `ak.Array(·)`.

I think the main thing waiting on this is, what's a good name? We don't use words joined without an underscore at high-level (non-layout) anymore, so at least it would have to be `ak.local_index(·)`. Is that a guessable name? If someone wanted this feature and didn't know what it was called, would seeing that name in the list make them think, "Yes, that's it!" Are there any NumPy parallels that would make sense here, such as a variation on `arange`?

Should this function have an `axis` parameter? I think that could be implemented through `awkward1._util.recursively_apply` (i.e. descend to the right depth, then call `localindex` on the layout at that depth). Clearly the default should be like the code snippet above, but is that default `axis=1` or `axis=0`? To me, it looks like `axis=1`, where `axis=0` might be `np.arange(len(array))`.

**Comment by jpivarski** [comment]
@nsmith- might want to weigh in. I know you use this function, too.

**Comment by nsmith-** [comment]
Personally I'd say default `axis=-1` but its not so critical. I wonder if there is any relationship between localindex and the eventual Identities feature that is worth thinking about at this point.

**Comment by jpivarski** [comment]
The default could be `axis=-1`, which would also make the above example work by default. Mainly, I'm trying to work out what `axis=0` and `axis=1` should mean, so that it doesn't get defined off-by-one from what it should naturally be.

You're right that localindex and an initial set of `Identities` are numerically equal. They're "colored differently" (think "red functions and green functions") because `Identities` are carried around as part of an array, manipulated by every operation on that array, whereas the output of localindex simply is an array.

**Comment by masonproffitt** [comment]
Right, I think `axis=-1` is the correct default. The closest simple numpy parallel that I can think of is `np.indices(array.shape)[axis]`, although that seems less like a "localindex" for `axis != -1` than `np.indices(array.shape[:(len(array.shape) + axis if axis < 0 else axis) + 1])[-1]` does (which would preserve `np.arange(len(array))` for `axis=0`).

**Comment by jpivarski** [comment]
Since NumPy's `np.indices` is close to this functionality, using a word like `ak.local_index` or `ak.local_indices` isn't too far, mentally. (It can't be exactly `ak.indices` because it does a different thing.)

It seems that `np.indices` does both of what JaggedArray's `parents` and `localindex` did. There's value to a `parents` equivalent; perhaps `ak.global_index`/`ak.global_indices`? There's definitely a symmetry between `parents` and `localindex`.

(I've never liked pluralizing a word like "indices" because sometimes it's legitimately "indexes," and I can never guess which it's going to be. I also don't like "axes," even though "axises" is not a legal spelling. As I type this, there's red under "axises" but not the other three.)

**Comment by jpivarski** [comment]
From the documentation,

```python
>>> array = ak.Array([
    [[0.0, 1.1, 2.2], []],
    [[3.3, 4.4]],
    [],
    [[5.5], [], [6.6, 7.7, 8.8, 9.9]]])
>>> ak.local_index(array, axis=0)
<Array [0, 1, 2, 3] type='4 * int64'>
>>> ak.local_index(array, axis=1)
<Array [[0, 1], [0], [], [0, 1, 2]] type='4 * var * int64'>
>>> ak.local_index(array, axis=2)
<Array [[[0, 1, 2], []], ... [], [0, 1, 2, 3]]] type='4 * var * var * int64'>
```

Note that you can make a Pandas-style MultiIndex by calling this function on every axis.

```python
>>> multiindex = ak.zip([ak.local_index(array, i) for i in range(array.ndim)])
>>> multiindex
<Array [[[(0, 0, 0), (0, 0, ... ), (3, 2, 3)]]] type='4 * var * var * (int64, in...'>
>>> ak.to_list(multiindex)
[[[(0, 0, 0), (0, 0, 1), (0, 0, 2)], []],
 [[(1, 0, 0), (1, 0, 1)]],
 [],
 [[(3, 0, 0)], [], [(3, 2, 0), (3, 2, 1), (3, 2, 2), (3, 2, 3)]]]
>>> ak.to_list(ak.flatten(ak.flatten(multiindex)))
[(0, 0, 0),
 (0, 0, 1),
 (0, 0, 2),
 (1, 0, 0),
 (1, 0, 1),
 (3, 0, 0),
 (3, 2, 0),
 (3, 2, 1),
 (3, 2, 2),
 (3, 2, 3)]
```
