### ISSUE TITLE
Cannot assign Virtual Regular (or equivalent Numpy) Array - fails with broadcasting error

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#541]
Below is not minimal but reflects where I first found the bug (NumpyArray), which seems to also extend to regular arrays?

Below produces an error on the master branch.

```python3
import awkward1 as ak
import numpy as np

FORM1 = {
    "class": "RegularArray",
    "content": "float32",
    "size": 3
}

FORM2 = {
    "class": "NumpyArray",
    "inner_shape": [
        3
    ],
    "itemsize": 4,
    "format": "f",
    "primitive": "float32"
}

rcd_array = ak.Array([{'x': 1.0} for i in range(100)])

length = len(rcd_array)
x1 = ak.virtual(lambda length: np.ones((length, 3), dtype=np.float32),
                args=(length, ),
                length=length,
                form=FORM1)
x2 = ak.virtual(lambda length: ak.layout.NumpyArray(np.ones((length, 3), dtype=np.float32)),
                args=(length, ),
                length=length,
                form=FORM2)

rcd_array['test1'] = x1
rcd_array['test2'] = x2
```

fails with:
```
Traceback (most recent call last):
  File "more_bugs.py", line 32, in <module>
    rcd_array['test1'] = x1
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/highlevel.py", line 1026, in __setitem__
    self._layout, what, where
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/operations/structure.py", line 560, in with_field
    [base, what], getfunction, behavior
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 996, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 572, in apply
    return apply(nextinputs, depth)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 759, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 586, in apply
    depth,
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 754, in apply
    + exception_suffix(__file__)
ValueError: cannot broadcast RegularArray of size 3 with RegularArray of size 100
```

**Comment by jpivarski** [comment]
This is a "gotcha," rather than a "bug," in that it's the intended behavior but may be surprising.

Assignment uses broadcasting, and there's a subtlety about left-broadcasting versus right-broadcasting that is [documented here](https://awkward-array.readthedocs.io/en/latest/_auto/ak.broadcast_arrays.html) (though it could get a more prominent tutorial on [awkward-array.org](https://awkward-array.org/)).

In short, NumPy does right-broadcasting, but left-broadcasting is much more natural for general data structures. (I don't know whether NumPy had a reason to choose right-broadcasting, but the choice is more arbitrary for rectilinear data.)

Here's the essence of what you want to do as an assignment, written as an addition (since NumPy can't add fields to an existing structured array for an exact analogy). You _want_

```
[1, 2, 3, 4, 5] +
        [[10, 100], [20, 200], [30, 300], [40, 400], [50, 500]] →
                                                      [[11, 101], [22, 202], [33, 303], [44, 404], [55, 505]]
```

but this is what NumPy says:

```python
>>> (
...     np.array([1, 2, 3, 4, 5]) +
...     np.array([[10, 100], [20, 200], [30, 300], [40, 400], [50, 500]]
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (5,) (5,2) 
```

For consistency with NumPy, Awkward Array does the same thing if the list types have _regular lengths_ (i.e. if they're numbers in the type string, not "`var`").

```python
>>> (
...     ak.Array(np.array([1, 2, 3, 4, 5])) +
...     ak.Array(np.array([[10, 100], [20, 200], [30, 300], [40, 400], [50, 500]])
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
ValueError: operands could not be broadcast together with shapes (1,1,5) (1,5,2) 
```

If they are _irregular lengths_, Awkward Array left-broadcasts, which is what you want to do. (We're allowed to deviate from NumPy's behavior for irregular lengths because there are no irregular lengths in NumPy.)

```python
>>> (
...     ak.Array([1, 2, 3, 4, 5]) +
...     ak.Array([[10, 100], [20, 200], [30, 300], [40, 400], [50, 500]]
... )
<Array [[11, 101], [22, ... 404], [55, 505]] type='5 * var * int64'>
```

Applying this to assignment, it means that you can do this if the thing you're assigning has irregular length.

```python
>>> rcd_array = ak.Array([{"x": i} for i in range(10)])
>>> x1 = ak.Array([[i*10, i*100] for i in range(10)])
>>> x2 = ak.Array([[i*0.1, i*0.01] for i in range(10)])
>>> rcd_array["x1"] = x1
>>> rcd_array["x2"] = x2
>>> rcd_array
<Array [{x: 0, x1: [0, 0, ... x2: [0.9, 0.09]}] type='10 * {"x": int64, "x1": va...'>
```

It does _not_ work if the thing you're assigning has regular length, just as with addition.

```python
>>> rcd_array = ak.Array([{"x": i} for i in range(10)])
>>> x1 = ak.Array(np.array([[i*10, i*100] for i in range(10)]))
>>> x2 = ak.Array(np.array([[i*0.1, i*0.01] for i in range(10)]))
>>> rcd_array["x1"] = x1
Traceback (most recent call last):
...
ValueError: cannot broadcast RegularArray of size 2 with RegularArray of size 10
```

This actually doesn't have anything to do with virtualness.

**Comment by lgray** [comment]
Yeah I just noticed this wasn't working in 0.4.3 either. The much more complex example it's derived from was working in 0.4.3 but now no longer does either... Though the progression of versions has been non-linear recently, maybe my history is a bit corrupted.

**Comment by jpivarski** [comment]
If a Form wasn't specified, it might have allowed you to attach the VirtualArray, though it would have been wrong as soon as it was evaluated. Maybe that's the difference?

**Comment by lgray** [comment]
No, it was evaluating all the way through just fine, there was no error thrown (the CI for it in the coffea PR completed).
I'll keep hacking at it.

Just really odd that it completely stopped working. Maybe a type was getting coerced before that's not now? If possible.

**Comment by jpivarski** [comment]
As for broadcasting, turning the regular dimension into a `var` dimension is sufficient:

```python
>>> data = ak.Array([{"x": 1}, {"x": 2}, {"x": 3}])
>>> y = ak.Array(np.array([[1, 2], [3, 4], [5, 6]]))
>>> data["y"] = y
Traceback (most recent call last):
...
ValueError: cannot broadcast RegularArray of size 2 with RegularArray of size 3
>>> data["y"] = ak.Array(y.tolist())
>>> print(data)
[{x: 1, y: [1, 2]}, {x: 2, y: [3, 4]}, {x: 3, y: [5, 6]}]
```

The thing is, we need a fast alternative for `ak.Array(y.tolist())`. There should be a function that turns a RegularArray into a ListOffsetArray at a given `axis` by inserting an `np.cumsum`. Actually, there are already low-level functions for this; it's just a matter of making the high-level function and documenting it: issue #551.
