### ISSUE TITLE
Missing keyword arguments for np.amax(awkward1.Array)

### ISSUE THREAD

**Issue by kreczko** [scikit-hep/awkward#557]
Using numpy 1.19.4 and awkward1 0.4.4 I get the following issue:

```python
import awkward1 as ak
import numpy as np

sample = ak.Array(np.arange(10))
np_array = ak.to_numpy(sample)

print(np.amax(np_array)) # prints 9
print(np.amax(sample)) # prints 9

print(np.amax(np_array, initial=10))  # prints 10
print(np.amax(sample, initial=10))  # TypeError: max() got an unexpected keyword argument 'initial'
```

Not sure what goes wrong internally, but `initial` is a valid (and useful) keyword argument:
https://numpy.org/doc/stable/reference/generated/numpy.amax.html#numpy.amax

Unfortunately, I do not know enough awkward1 to attempt a fix, any pointers would be helpful.

### Full trace
```bash
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    print(np.amax(sample, initial=10))  # prints 9
  File "<__array_function__ internals>", line 6, in amax
  File "/software/miniconda/envs/hep/lib/python3.7/site-packages/awkward1/highlevel.py", line 1388, in __array_function__
    return awkward1._connect._numpy.array_function(func, types, args, kwargs)
  File "/software/miniconda/envs/hep/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 31, in array_function
    return function(*args, **kwargs)
TypeError: max() got an unexpected keyword argument 'initial'
```

**Comment by jpivarski** [comment]
We haven't implemented all of NumPy's functions or all of NumPy's function arguments, and this is one of them. (Actually, it was added in NumPy 1.15, so it's relatively new.)

My first thought was that implementing this would be rather involved—passing down a new argument through every `Content::reduce_next` (which is used for _all_ reducers, including sum, count, argmin, etc.) and that everything but min/max would have to pass down a dummy value. But as it turns out, we're luckier than that: the `Content::reducer_next` methods already pass down a `Reducer` object, which is used to say whether this reduction is "sum," "count," "argmin," etc., since this information is only needed at the end of a recursive descent. Since this is an object, we could extend the ReducerMin and ReducerMax objects to take an optional `initial` argument, and the object would carry that down to the kernel function where it's actually used. Then when "min" or "max" is called in Python,

https://github.com/scikit-hep/awkward-1.0/blob/af774dee5efa3ced4c478e2172f4cb71057ace33/src/python/content.cpp#L1341-L1348

passing an optional `initial` argument would set that argument on the ReducerMin/ReducerMax and then set `mask` to `false`.

The `mask` argument (only accessible in the low-level layout nodes, not the high-level `ak.min` or `np.min`/`np.amin`) is what directs min/max to cover `initial` values with None:

```python
>>> np.amin(ak.Array([[3.3, 2.2, 1.1], [], [4.4, 5.5]]), axis=1)
<Array [1.1, None, 4.4] type='3 * ?float64'>
>>> ak.Array(ak.Array([[3.3, 2.2, 1.1], [], [4.4, 5.5]]).layout.min(axis=1, mask=False))
<Array [1.1, inf, 4.4] type='3 * float64'>
```

To get what you want now (before `initial` is implemented), you can do a `fill_none` to replace those None values with the `initial` that you want:

```python
>>> ak.fill_none(np.amin(ak.Array([[3.3, 2.2, 1.1], [], [4.4, 5.5]]), axis=1), 0)
<Array [1.1, 0, 4.4] type='3 * float64'>
```

but that's not quite the same thing because `initial` will replace any values larger than it (for `np.amin`), not just any empty lists:

```python
>>> np.amin([[3.3, 2.2, 1.1], [4.4, 5.5, 6.6]], axis=1, initial=3)
array([1.1, 3. ])
```

So actually implementing this `initial` argument does something that `fill_none` doesn't do. (...Unless you first cut with that value:

```python
>>> array = ak.Array([[3.3, 2.2, 1.1], [], [4.4, 5.5]])
>>> array[array < 3]
<Array [[2.2, 1.1], [], []] type='3 * var * float64'>
>>> np.amin(array[array < 3], axis=1)
<Array [1.1, None, None] type='3 * ?float64'>
>>> ak.fill_none(np.amin(array[array < 3], axis=1), 3)
<Array [1.1, 3, 3] type='3 * float64'>
```

which uses the `initial` value in two places: in the cut and in the `fill_none`, to get the same effect.)

**Comment by jpivarski** [comment]
```python
    data = ak.Array([[1, 3, 5, 4, 2], [], [2, 3, 1], [5]])
    assert ak.min(data, axis=1, initial=4).tolist() == [1, None, 1, 4]
    assert ak.max(data, axis=1, initial=4).tolist() == [5, None, 4, 5]

    data = ak.Array([[1.1, 3.3, 5.5, 4.4, 2.2], [], [2.2, 3.3, 1.1], [5.5]])
    assert ak.min(data, axis=1, initial=4).tolist() == [1.1, None, 1.1, 4]
    assert ak.max(data, axis=1, initial=4).tolist() == [5.5, None, 4, 5.5]
```

in PR #566.

**Comment by kreczko** [comment]
Awesome! Thank you!
