### ISSUE TITLE
docstring oddity: behavior is a bool?

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/awkward#594]
I noticed that PyCharm actually picks up the NumPy style docstrings's type definitions, which is really quite impressive. But, it picks up that behavior is a bool, well, because it is documented as such:

https://github.com/scikit-hep/awkward-1.0/blob/518232b1c6758e3d9bf94fae91a72696d2d3e6ce/src/awkward/operations/convert.py#L638-L639

That even by definition should be at least an `Optional[bool]`, but better yet, I think it's a `Optional[dict]`?  Also, I'd highly recommend actual typing, with `typing; python_version<"3.5"` in the `install_requires` and Python 2-style `# type:` comments. It looks like you've already thought through all the allowed types, but making it formal and letting (other, less intelligent) IDE's and type checkers take advantage of it would be nice. :)

Unrelated, but could the standard GitHub link be added to the top right corner of the docs? Like https://boost-histogram.readthedocs.io/en/latest/ 's top corner.

Okay, back to work, just noticed that PyCharm was insisting that behavior was supposed to be a bool...

<img width="717" alt="Screen Shot 2020-12-11 at 4 21 04 PM" src="https://user-images.githubusercontent.com/4616906/101956083-ff729a80-3bcc-11eb-9548-917f04b50317.png">

**Comment by jpivarski** [comment]
It should be `Optional[dict]`. I'll do a search through the codebase to find all the places where this happened.

Adding type annotations everywhere is an option, though I'd have to do Python 2 style for compatibility (yuck).

I removed the GitHub link from the corner because it was wrong. These are auto-generated files that have no source in GitHub to point to. The closest thing we have is the "Defined in" link below the class/function name:

![image](https://user-images.githubusercontent.com/1852447/101957018-3beec800-3bc6-11eb-949b-9da46b1c6575.png)

The "line" link goes right to the definition, which has the docstring. It also goes to the right commit.

**Comment by jpivarski** [comment]
Since this is a documentation-only fix and I want to release a new release candidate, I think it's okay to commit directly to main (like README and other administrative fixes): https://github.com/scikit-hep/awkward-1.0/commit/68087850eabafd39f0c0de37ed96487fa44cc69f.
