### ISSUE TITLE
PyPI source tarball does not have samples

### ISSUE THREAD

**Issue by badshah400** [scikit-hep/awkward#596]
The `tests/samples` dir is missing from the PyPI tarball, causing a couple of tests from `test_0437` to fail when it is used to build and test awkward (1.0.0):

```
[   39s] ________________________________ test_fromfile _________________________________
[   39s] 
[   39s]     def test_fromfile():
[   39s]         # read multiple json fragments from a json file
[   39s] >       array = ak.from_json("tests/samples/test-record-array.json")
[   39s] 
[   39s] tests/test_0437-stream-of-many-json-files.py:357: 
[   39s] ________________________________ test_fromfile _________________________________
[   39s] 
[   39s]     def test_fromfile():
[   39s]         # read multiple json fragments from a json file
[   39s] >       array = ak.from_json("tests/samples/test-record-array.json")
[   39s] 
[   39s] tests/test_0437-stream-of-many-json-files.py:357: 
[   39s] =========================== short test summary info ============================
[   39s] FAILED tests/test_0437-stream-of-many-json-files.py::test_two_arrays - ValueE...
[   39s] FAILED tests/test_0437-stream-of-many-json-files.py::test_fromfile - ValueErr...
[   39s] ================== 2 failed, 560 passed, 7 skipped in 20.68s ===================
```

**Comment by jpivarski** [comment]
I would have thought that this line would include them:

https://github.com/scikit-hep/awkward-1.0/blob/68087850eabafd39f0c0de37ed96487fa44cc69f/MANIFEST.in#L5

but I know that the last time I checked that the source tarball is complete, I didn't check for a samples directory. The effect of it being missing may be different note because before the only tests that used it used Parquet samples _if_ pyarrow is installed (otherwise, those tests are skipped). Now there are JSON files in there that are always tested.

It may be that the MANIFEST.in line needs to include

```
tests/samples/*
```

because the `*.cpp *.py` could be qualifying the `tests` to recursively include, and the sample files don't end with these extensions.

I can test it, but I'll need to get to a computer Monday morning.

**Comment by jpivarski** [comment]
I verified that

```bash
python setup.py sdist
```

without and with `samples/*` in

```
recursive-include tests *.cpp *.py samples/*
```

determines whether the samples are in the source tarball. Today, I had planned to do a 1.0.1 non-release candidate, but I'm going to start with a release candidate to verify the full chain. (I'm applying a new policy in which release candidates—only—can be deleted from PyPI to control my quota usage. The 1.0.1 release has to be exactly right because it will live forever.

**Comment by jpivarski** [comment]
Try the source tarball in 1.0.1rc3: https://pypi.org/project/awkward/1.0.1rc3/

```bash
pip install --no-binary awkward "awkward>=1.0.1rc3"
```

I'm working on #597, so the full release is not going out just yet.

**Comment by jpivarski** [comment]
I installed it with `--no-binary` on a VM that previously had no Python installed. I don't think this actually runs the tests, but I do know from downloading the tarball directly that the samples files are included and source-installation works:

```bash
ubuntu@ip-172-31-64-157:~$ python3 -m pip install --no-binary awkward "awkward>=1.0.1rc3"
Collecting awkward>=1.0.1rc3
  Downloading awkward-1.0.1rc3.tar.gz (815 kB)
     |████████████████████████████████| 815 kB 14.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.13.1
  Downloading numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 33.0 MB/s 
Building wheels for collected packages: awkward
  Building wheel for awkward (PEP 517) ... done
  Created wheel for awkward: filename=awkward-1.0.1rc3-cp38-cp38-linux_x86_64.whl size=6303076 sha256=258dee1a13545fc78efcce9f18ebd3e3aa993137e3e97c5e4c25b917823e028c
  Stored in directory: /home/ubuntu/.cache/pip/wheels/fe/01/c7/b97ea7f5da917acfbd6ba22d0f228315675d236779760bc178
Successfully built awkward
Installing collected packages: numpy, awkward
  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed awkward-1.0.1rc3 numpy-1.19.4
```

When I download the tarball onto this machine and run pytest on the `tests` directory it contains (with `samples` within that), all pass, even with all extra dependencies. So I guess this is okay...

I'm going to release `awkward==1.0.1` (full release).

**Comment by badshah400** [comment]
@jpivarski Many thanks! I can confirm that as of version 1.0.1, the PyPI tarballs do contain the samples dir. Thanks too for the great library, btw.
