### ISSUE TITLE
`ak.from_buffers` fails in certain constellations with `lazy=True`

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#597]
I found https://awkward-array.org/how-to-convert-buffers.html which is really nice. Playing with this a bit i encountered a situation where this goes wrong with `lazy=True` (but works in non-lazy mode).

```pycon
>>> import awkward as ak
>>> ak.__version__
'1.0.1rc2'
>>> array = ak.Array([[{"a": 1, "b" : [1, 2, 3]}],
...                   [{"a": 1, "b" : [4, 5]}, {"a" : 4, "b" : [2]}]])
```

This still works,

```pycon
>>> buffers = ak.to_buffers(array)
>>> ak.from_buffers(*buffers, lazy=True)
<Array [[{a: 1, b: [1, 2, 3, ... b: [2]}]] type='2 * var * {"a": int64, "b": var...'>
```

but with the same structure where the record field under `"b"` is a `ListArray64` instead of a `ListOffsetArray64` works only without `lazy=True`:

```pycon
>>> array_new = ak.Array(
...     ak.layout.ListOffsetArray64(
...         array.layout.offsets,
...         ak.layout.RecordArray(
...             {
...                 "a" : array.layout.content["a"],
...                 "b" : ak.layout.ListArray64(
...                     array.layout.content["b"].offsets[:-1],
...                     array.layout.content["b"].offsets[1:],
...                     array.layout.content["b"].content
...                 ),
...             }
...         )
...     )
... )
>>> buffers = ak.to_buffers(array_new)
>>> ak.from_buffers(*buffers)
<Array [[{a: 1, b: [1, 2, 3, ... b: [2]}]] type='2 * var * {"a": int64, "b": var...'>
>>> buffers = ak.to_buffers(array_new)
>>> ak.from_buffers(*buffers, lazy=True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    ak.from_buffers(*buffers, lazy=True)
  File "/home/nikolai/.conda/envs/py37/lib/python3.7/site-packages/awkward/highlevel.py", line 1238, in __repr__
    return self._repr()
  File "/home/nikolai/.conda/envs/py37/lib/python3.7/site-packages/awkward/highlevel.py", line 1250, in _repr
    limit_value, self._layout, self._behavior
  File "/home/nikolai/.conda/envs/py37/lib/python3.7/site-packages/awkward/_util.py", line 1511, in minimally_touching_string
    lft = next(leftgen)
  File "/home/nikolai/.conda/envs/py37/lib/python3.7/site-packages/awkward/_util.py", line 1498, in forever
    for token in iterable:
  File "/home/nikolai/.conda/envs/py37/lib/python3.7/site-packages/awkward/_util.py", line 1396, in forward
    for token in forward(x[i], sp):
ValueError: generated array does not conform to expected form:

{
    "class": "ListOffsetArray64",
    "offsets": "i64",
    "content": {
        "class": "RecordArray",
        "contents": {
            "a": {
                "class": "VirtualArray",
...
```

(seems to affect both the old `from_arrayset` and the new `from_buffers` interface)

**Comment by jpivarski** [comment]
Since `ak.from_buffers` is the main thing I want to release in 1.0.1, I fixed this one before that release.

As it turns out, ListArray (and only ListArray) was missing a stanza that loosens the comparison between expected Form and generated Form, allowing a VirtualArray to be considered the same as the array the VirtualArray generates.

~~But looking closely at this, it also bothers me that a VirtualArray and its content have the same `form_key`. Those are supposed to be unique. A VirtualArray has nothing to store in the container, like RecordArray, so it should probably have _no_ `form_key`, like RecordArray. I'm going to check to see if that passes tests.~~

I was mistaken: that never happens.

(Since this is a format that will have to be supported indefinitely (to read pickled arrays written by any version), it's worth getting it right.)
