### ISSUE TITLE
from_buffers/from_arrayset lazyness insonsistent when concatenating

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#603]
This issue is originating from the usage of Coffea's NanoEvents. It is a RecoardArray of large RecordArrays, that really need lazy loading.

  <details>
    <summary>Example code</summary>
    

```python
import awkward as ak
import numpy as np


class Map(dict):
    def __getitem__(self, key):
        print(f"Loading {key}")
        return dict.__getitem__(self, key)

form = {
    'class': 'RecordArray',
    'contents': {
        'Electron': {
            'class': 'ListOffsetArray64',
            'content': {
                'class': 'RecordArray',
                'contents': {
                    'charge': {
                        'class': 'NumpyArray',
                        'form_key': 'loads_slowly1',
                        'format': 'i',
                        'has_identities': False,
                        'inner_shape': [],
                        'itemsize': 4,
                        'parameters': {},
                        'primitive': 'int32'}},
                'form_key': 'invalid',
                'parameters': {}},
            'form_key': 'loads_quickly1',
            'offsets': 'i64'},
        'Muon': {
            'class': 'ListOffsetArray64',
            'content': {
                'class': 'RecordArray',
                'contents': {
                    'charge': {
                        'class': 'NumpyArray',
                        'form_key': 'loads_slowly2',
                        'format': 'i',
                        'has_identities': False,
                        'inner_shape': [],
                        'itemsize': 4,
                        'parameters': {},
                        'primitive': 'int32'}},
                'form_key': 'invalid',
                'parameters': {'__record__': 'Muon'}},
            'form_key': 'loads_quickly2',
            'offsets': 'i64'}},
    'form_key': '',
    'parameters': {}}

map = Map({
    "part0-loads_quickly1-offsets": np.array([0,1,2,3]),
    "part0-loads_quickly2-offsets": np.array([0,1,2,3]),
    "part0-loads_slowly1-data": np.array([5,5,5], dtype=np.int32),
    "part0-loads_slowly2-data": np.array([5,5,5], dtype=np.int32)})

print("First concatenation")
arr = ak.from_buffers(form, 3, map, lazy=True)
con = ak.concatenate([arr["Electron"], arr["Muon"]], axis=1)
print("Second concatenation")
arr = ak.from_buffers(form, 3, map, lazy=True)
con = ak.concatenate([arr["Muon"], arr["Muon"]], axis=1)
print("Third concatenation")
del form["contents"]["Muon"]["content"]["parameters"]["__record__"]
arr = ak.from_buffers(form, 3, map, lazy=True)
con = ak.concatenate([arr["Electron"], arr["Muon"]], axis=1)

```
  </details>

If you execute above example, you will see that the first concatenation only loads the offsets. However the second and third concatenation load (in fact all) contents. This seems to be inconsistent.
Preferably I would like to have none of the concatenates load the contents, because this can take really long. It seems content loading is not necessary, as the first concatenate is not doing it.

**Comment by jrueb** [comment]
I would also like to add a case in conjunction with `ak.num`
```python
form["contents"]["Muon"]["content"]["parameters"]["__record__"] = "Muon"
arr = ak.from_buffers(form, 3, map, lazy=True)
con = ak.concatenate([arr["Electron"], arr["Muon"]], axis=1)
con["var"] = 5
print("Getting counts")
ak.num(con)
```
Here the `ak.num` call will also make all contents being loaded, which is also not desirable. This does not happen if `"var"` isn't added to the array.

**Comment by jpivarski** [comment]
This is part of defining what `ak.concatenate` is supposed to mean. There are two ways to put arrays one after another: as a partitioning ([ak.partitioned](https://awkward-array.readthedocs.io/en/latest/_auto/ak.partitioned.html)), which doesn't make the arrays contiguous in memory, it just chains them logically, mapping global indexes to local indexes, and [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html), which eagerly makes them contiguous in memory.

Creating a partitioned array scales with the number of partitions but not the size of the data in those arrays. Concatenating scales with the size of the data in the arrays because it's actually making them contiguous (by column, as everything is only ever contiguous by column). However, partitioning must be at the outermost level of a tree structure. (In Awkward 0, partitioning was allowed anywhere, and it led to numerous gotchas and bugs.)

There's a third option, but it's not a good one: a set of RecordArrays could be combined as a UnionArray with tag `0` for the first RecordArray, tag `1` for the second RecordArray, etc. That would ensure that the RecordArrays are combined lazily, but UnionArrays have some limitations, like you can't use them in Numba. So we'll discard that option.

Here's a better option: instead of having the `ak.concatenate` function merge all partitions as a first step,

https://github.com/scikit-hep/awkward-1.0/blob/e1970c0542002725b647b210f595dbd808c53565/src/awkward/operations/structure.py#L1094-L1097

if the `axis == 0` it should string partitioned data together into a bigger partitioning. For that to work consistently, `ak.from_buffers` with `lazy == True` should always return a partitioned array, even if it's only a single partition, rather than returning non-partitioned data as it does now:

https://github.com/scikit-hep/awkward-1.0/blob/e1970c0542002725b647b210f595dbd808c53565/src/awkward/operations/convert.py#L3725-L3732

Same for `ak.from_parquet`, in which single-partition outputs are currently thwarted:

https://github.com/scikit-hep/awkward-1.0/blob/e1970c0542002725b647b210f595dbd808c53565/src/awkward/operations/convert.py#L2686-L2689

**Comment by jpivarski** [comment]
I've been meaning to do this one "next" for a whole week now. There were some deeper things to fix along the way, but now this should be good.

The reason that concatenating electrons and muons did not cause the [VirtualArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.VirtualArray.html) to materialize but concatenating electrons and electrons or muons and muons did is because concatenation for `axis != 0` works by first building a [UnionArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.UnionArray.html) with the data interleaved:

```python
>>> one = ak.Array([[1, 2, 3], [], [4, 5]])
>>> two = ak.Array([[10, 20, 30], [], [40, 50]])
>>> ak.concatenate([one, two], axis=1, merge=False).layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 6 6 10]" offset="0" length="4" at="0x563b8df5cdd0"/></offsets>
    <content><UnionArray8_64>
        <tags><Index8 i="[0 0 0 1 1 1 0 0 1 1]" offset="0" length="10" at="0x563b8de1d8e0"/></tags>
        <index><Index64 i="[0 1 2 0 1 2 3 4 3 4]" offset="0" length="10" at="0x563b8d9af450"/></index>
        <content tag="0">
            <NumpyArray format="l" shape="5" data="1 2 3 4 5" at="0x563b8df849a0"/>
        </content>
        <content tag="1">
            <NumpyArray format="l" shape="5" data="10 20 30 40 50" at="0x563b8df93950"/>
        </content>
    </UnionArray8_64></content>
</ListOffsetArray64>
```

and then "simplifying" the UnionArray:

```python
>>> ak.concatenate([one, two], axis=1, merge=True).layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 6 6 10]" offset="0" length="4" at="0x563b8ddf5910"/></offsets>
    <content><NumpyArray format="l" shape="10" data="1 2 3 10 20 30 4 5 40 50" at="0x563b8dea7920"/></content>
</ListOffsetArray64>
```

but the "`Muon`" and "`Electron`" records are considered different types, so they weren't simplified/merged into the same array buffers, while the "`Muon`" and "`Muon`" and the "`Electron`" and "`Electron`" are considered the same type, so they were simplified/merged.

The first thing I did was to ensure that if you have partitioned data, which is usually the case for lazy arrays, that `axis=0` concatenation just puts the partitions one after another. Earlier, I had misread your example, thinking they were `axis=0`, which absolutely should do this, at least. If you start non-partitioned data, I do not think that [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html) should just be gluing them into partitions—that's why there's a difference between the [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html) and [ak.partitioned](https://awkward-array.readthedocs.io/en/latest/_auto/ak.partitioned.html) functions.

But you had `axis=1`, which is more subtle. _Some_ of the virtual data must be materialized to perform that operation: the [ListOffsetArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.ListOffsetArray.html) offsets, at minimum. In your example, it was also materializing all the fields of the [RecordArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.RecordArray.html), which it really didn't need to do.

As I said, it was merging "`events.Muon`" and "`events.Muon`" because it has the same type as itself. However, if you're concatenating something with itself, I think you'll want to use indirection, rather than an explicit merge, since that indirection would be an [IndexedArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedArray.html), rather than a [UnionArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.UnionArray.html). (There are reasons to avoid UnionArrays, if possible; for example, they can't be used in Numba: #174.) So now there's a new internal function that can determine if two arrays are referentially equal (like a deeply nested version of the Python `is`).

That made your examples work "out of the box," without manual intervention, because

   * "`events.Muon`" and "`events.Electron`" are different types (because they have a different `__record__` parameter)
   * "`events.Muon`" and "`events.Muon`" are referentially equal

However, if the first of these hadn't been labeled with a different `__record__` parameter, they'd be merged, causing materialization of all fields. That's not something we can avoid by default because it goes against the meaning of "concatenate". If any data, regardless of referential identity or data type, is not simplified/merged by [ak.concatenate](https://awkward-array.readthedocs.io/en/latest/_auto/ak.concatenate.html), there would be no way for a user to ask for it!

Therefore, I added `merge` as an option to `concatenate`, to prevent recursive merging if you really want to. I set it up to always eliminate UnionArray nested within UnionArray (that's bad), but if there are any different arrays with the same type `concatenate`'s intermediate step, setting `merge=False` will make them _not_ be combined.

It was also the only way I could make the first example, above, without building the UnionArrays by hand.

**Comment by jrueb** [comment]
Thank you for all the work.
Do you know why the `ak.num` call I mentioned in my second message triggers the loading and how to get around that?

**Comment by jpivarski** [comment]
The `ak.num` loads only the list offsets, not the particle attribute data, as it should:

```python
>>> # I loaded the Map, form, and map from your first message.
>>> arr = ak.from_buffers(form, 3, map, lazy=True)

>>> # Only loads the offsets, not the charge.
>>> ak.num(arr.Muon)
Loading part0-loads_quickly2-offsets
<Array [1, 1, 1] type='3 * int64'>

>>> # Do it again with concatenation.
>>> con = ak.concatenate([arr["Electron"], arr["Muon"]], axis=1)
Loading part0-loads_quickly1-offsets
Loading part0-loads_quickly2-offsets
>>> ak.num(con)
<Array [2, 2, 2] type='3 * int64'>

>>> # Just to be sure, printing it out loads the internal data that is shown in the print-out.
>>> con
Loading part0-loads_slowly1-data
Loading part0-loads_slowly2-data
<Array [[{charge: 5}, ... {charge: 5}]] type='3 * var * union[{"charge": int32},...'>
```

Determining the number of items in each list (what `ak.num` does) requires the list offsets—it has to be loaded in order to compute that quantity—but the inner data is not needed and is not loaded.

**Comment by jrueb** [comment]
I agree with you, but what is weird is that the inner data is loaded by the call if you set a field, for example
```python
con["var"] = 5
```
before the `ak.num` call.

**Comment by jpivarski** [comment]
I looked into it, and that investigation snowballed. The reason setting a variable affects the later `ak.num` call is because part of broadcasting the `5` to all elements in `con` slices all the fields in the array by a trivial slice. Because of the delayed slicing that VirtualArrays now have, that operation doesn't cause a read. (You can see that difference by looking at `con.layout` before and after assigning the new field: the other fields go from VirtualArrays with a PythonGenerator to VirtualArrays with a SliceGenerator.)

Then you'd think that calling `ak.num` with an `axis` above the RecordArray wouldn't touch the contents inside the RecordArray, but the function that determines how to convert a negative `axis` into a positive axis has to descend all the way to the leaves of the tree to find out how deep it is, and that materializes the fields of the RecordArray because the lazily sliced array has no Form. The lazily sliced array has no Form because the Form of anything but a field-slice (only slicing using strings) is hard to predict. The code the computes a slice is rather complex—writing parallel code to predict whether the result of that slice will be a ListArray or a ListOffsetArray, for instance, would at least be hard to keep in sync with the code that actually does the computation (a maintenance problem), but it might also be impossible (it might depend on details of the values in the array, which are not available in the Form).

In this case, the `axis` of `ak.num` is non-negative, so we could just check for `axis >= 0` _before_ checking the depth of the array (6d0f7639ccfc71cf6f0b82763a2364f8b0dd760c). I should have left it at that.

Instead, I looked into why the fields of the RecordArray were getting sliced. It was a trivial slice (i.e. `x[slice] == x`), and there are quite a few situations in which a slice might happen to be trivial, so I added logic that if a slice is trivial, it should not be applied. If we ever had any hope of predicting what `__getitem__` does through an array's Form, it's gone now because this makes that result depend on a value: whether the slice is trivial or not. (You have to look at all the values of the slice and whether it matches the array's length.) This can also be a performance improvement because not applying trivial slices avoids memory copies.

Once that was working (PR #643) and I had half-written this response, I started thinking that the calculation of array depth involved in `ak.num`'s handling of a (potentially) negative `axis` shouldn't ever cause a VirtualArray to materialize if it has any Form information. Perhaps we can't predict the exact Form of a sliced array, but that doesn't mean we don't know its depth. Therefore, I changed the depth calculations so that they derive from the arrays themselves, rather than creating a Form and checking that, with extra logic to compute the depth of a sliced VirtualArray from the unsliced VirtualArray (PR #644). Maybe we don't know whether it will be composed of ListArrays or ListOffsetArrays, but we do know how many such things will be nested.

The bottom line is that keeping VirtualArrays from being materialized is _inherently_ complex. Awkward Array is not a delayed evaluation formalism like Dask, which postpones every action until a `calculate()` method is called—it is an eager evaluation formalism in which every action returns as much information as the action requires and materializes any virtual arrays it needs to in order to provide that information. We can postpone some of those materializations by adding detailed type information—the Form—to virtual arrays, but then this information has to be propagated through any downstream actions that we also want to keep virtual. In this scheme, the complexity builds the longer we want to postpone materialization. Dask, on the other hand, knows nothing about the type of each of its delayed actions (or even if they will work) until the whole thing gets calculated, but that requires a user-visible `calculate()` method to say when the information is finally needed. Awkward Array wasn't designed to be that way because it wasn't designed to be a delayed evaluation formalism: if you ask for `ak.num`, you have to get the number of items in each list as soon as `ak.num` completes because there's no `calculate()` method for you to specify when you want that. The way forward on this, if more delayed evaluation is needed, is to get Awkward Array to work in Dask. (https://github.com/scikit-hep/awkward-1.0/issues/284#issuecomment-731434583)
