### ISSUE TITLE
Selecting a name within multiple records: array[["pt", "eta", "phi"], "nominal"]

### ISSUE THREAD

**Issue by maxgalli** [scikit-hep/awkward#618]
As discussed in https://github.com/scikit-hep/awkward-1.0/discussions/614, it would be nice to have a feature that allows to select a name within multiple columns (i.e., slice columns within columns).

Example:
considering a record of records of the following type:
```python
10 * {"eta": {"nominal": int64, "up": int64}, "phi": {"nominal": int64, "up": int64}}
``` 
the new feature would allow to use the syntax:
```python
my_array[["eta", "phi"], "up"]
```
to get a record of type
```python
10 * {"eta": int64, "phi": int64}
```
At the moment, this can be achieved with:
```python
ak.zip({field: my_array[field, "up"] for field in ak.fields(my_array) if "up" in ak.fields(my_array[field])})
```

**Comment by jpivarski** [comment]
As discussed in https://github.com/scikit-hep/awkward-1.0/discussions/614#discussioncomment-235312, this will need a deprecation cycle that starts by a phase of warnings against using `SliceFields` followed by `SliceField` or `SliceFields` now and the new feature would only be added after the deprecation cycle is over (because it uses the same syntax and there are no names to change).

We now have a [formal roadmap](https://github.com/scikit-hep/awkward-1.0#roadmap) (#617), so if this is going to go into 1.1.0 (Feb 1, 2021), then the warning has to be installed in a full release (1.0.2) _now_, before the break.

**Comment by jpivarski** [comment]
My intention was to quickly make a release with the deprecation warning, to give people as much time as possible to transition. I was first going to implement it and then switch it off, so that turning on this feature would be easier when the date arrived.

However, in the course of implementing it, I had a chance to think more deeply about it, particularly what the deprecation message was going to say. In so doing, I noticed that the old behavior is nonsensical: there is _no_ reason why anyone would want

```python
>>> array[["x", "y", "z"], "x"]
```

to select from the `["x", "y", "z"]` record they've just created, rather than looking for a sub-field `"x"` within each of the outer `"x"`, `"y"`, and `"z"` fields. In particular,

```python
>>> array["x", "y", "z"], "w"]
```

is guaranteed to be an error (in the old behavior) because you've just ensured that the outer record has only fields `"x"`, `"y"`, and `"z"`, so selecting `"w"` never makes sense. The same is true if the second field-selector was a list. The old behavior _only_ allows you to make subsets from the set you've just defined. Who would want that?

On the other hand, the new behavior of having the second field-selector look inside each of the objects created by the first field-selector has the application you described (@maxgalli) and it's more like what a tuple of row selectors does.

**So I hereby redefine the old behavior as a bug.** The new behavior is effective immediately (as soon as #619 enters a release).

If anyone was _relying_ on the old behavior, I'll point out that they can adapt by simply collapsing "`["x", "y", "z"], "x"`" into `"x"`. That works regardless of version; they weren't getting anything with this syntax's old behavior that they couldn't get with simpler syntax.
