### ISSUE TITLE
Unexpected results when using ak.from_arrow()

### ISSUE THREAD

**Issue by aminnj** [scikit-hep/awkward#624]
I'm getting a lot of mileage out of zero-copy (I think) conversions between awkward and Arrow. Thanks for all that functionality. However, when I introduce some slicing, I see some mismatches. Example below.

```python
import numpy as np # 1.19.0
import awkward as ak # 1.0.1
import pyarrow as pa # 2.0.0

np_arr = np.random.normal(0,1,10)
ak_arr = ak.Array(np_arr)
pa_arr = ak.to_arrow(ak_arr)
```

These are all identical, as expected.
```python

>>> print(np_arr)
[ 0.12213336  0.07918481 -0.02079451  0.52849207  0.56343541  0.08746807
  0.56490973 -0.47526351  0.295584    0.27810744]
>>> print(ak_arr)
[0.122, 0.0792, -0.0208, 0.528, 0.563, 0.0875, 0.565, -0.475, 0.296, 0.278]
>>> print(pa_arr)
[
  0.122133,
  0.0791848,
  -0.0207945,
  0.528492,
  0.563435,
  0.0874681,
  0.56491,
  -0.475264,
  0.295584,
  0.278107
]
```

I would expect to see the same values here, but it looks like awkward is going to the beginning of the array.
```python
>>> print(pa_arr[5:])
[
  0.0874681,
  0.56491,
  -0.475264,
  0.295584,
  0.278107
]
>>> print(ak.from_arrow(pa_arr[5:]))
[0.122, 0.0792, -0.0208, 0.528, 0.563]
```

**Comment by aminnj** [comment]
I actually discovered this with jagged arrays, but put the minimal flattened example above.
```python
>>> a = ak.to_arrow(ak.Array([[1],[],[2,3,4],[5]]))
>>> a
<pyarrow.lib.ListArray object at 0x18fe05288>
[
  [
    1
  ],
  [],
  [
    2,
    3,
    4
  ],
  [
    5
  ]
]

>>> ak.from_arrow(a[2:])
<Array [[1], []] type='2 * option[var * ?int64]'>
```

My use case is putting jagged arrays into pandas dataframes without copying (or making list of lists) by converting awkward to Arrow and then using pyarrow's [fletcher](https://github.com/xhochy/fletcher) pandas ExtensionArray to get stuff like this:

|    | Jet_pt                                                            |   MET_pt |
|---:|:------------------------------------------------------------------|---------:|
|  0 | [39.65625  29.9375   23.09375  18.0625   17.6875   15.609375]     |  46.0749 |
|  1 | [76.75      61.84375   58.875     52.0625    22.171875  17.28125  |  29.7964 |
|    |  17.09375   15.453125  15.2578125]                                |          |
|  2 | [23.109375  16.453125  15.5703125]                                |  82.0033 |
|  3 | [59.8125    45.3125    35.21875   22.03125   19.046875  15.796875 |  77.7026 |
|    |  15.6328125]                                                      |          |
|  4 | [55.71875   47.84375   44.46875   42.875     25.578125  22.953125 |  29.9007 |
|    |  20.890625  19.5       15.8671875]                                |          |

And slicing on this gives me the expected Arrow arrays, but converting back to awkward in order to actually compute things, fails:
```python
>>> ak.from_arrow(df.iloc[2:]["Jet_pt"].values.data)
<Array [[39.7, 29.9, 23.1, ... 16.5, 15.6]] type='3 * option[var * ?float32]'>
```

**Comment by jpivarski** [comment]
From @trickarcher:

> Hey Jim, I was going through the Issue #624 and it was related to `ak.from_arrow`.  I was able to reproduce the issue. I tried forming sliced array from buffers in the pyarrow ecosystem, and got a similar failure.

```python
 >>> import awkward as ak
 >>> import pyarrow as pa
 >>> pa_arr=pa.array([1,2,3,4,5,6,7,8,9,10])
 >>> pa_arr
 <pyarrow.lib.Int64Array object at 0x7f3a0d009b20>
 [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10
 ]
 >>> pa_arr.buffers()
 [None, <pyarrow.lib.Buffer object at 0x7f3a05b960f0>]
 >>> pa_arr[5:].buffers()
 [None, <pyarrow.lib.Buffer object at 0x7f3a05b8cd70>]
 >>> import numpy as np
 >>> pa.Array.from_buffers(pa.from_numpy_dtype(np.int64), 5, pa_arr[5:].buffers())
 <pyarrow.lib.Int64Array object at 0x7f3a05b95700>
 [
   1,
   2,
   3,
   4,
   5
 ]
```

> However, the sliced buffers are totally different from the original buffers. How can we debug further from here?

Actually, this example and @aminnj's are both showing the same thing: pyarrow's buffers are defined by a pointer, a length, and an offset (much like ours in Awkward, which we call `ptr`, `length`, and `offset` in C++). When you and I wrote `from_arrow`, we assumed that pyarrow's `buffers()` was giving offset-adjusted pointers (like our `data()`), but apparently it was giving non-adjusted pointers (like our `ptr`).

That's why `pa.array(np.arange(10))[6:]` is being turned into `ak.Array([0, 1, 2, 3])` instead of `ak.Array([6, 7, 8, 9])`. It has the right buffer and the right length (4), but it should be starting at 6, not starting at 0.

So the problem is that we're interpreting the output of pyarrow's `buffers()` incorrectly—we additionally need to get an offset number from somewhere. I don't know where that is, but the way to search for it is to open this up interactively and call `dir` on things. It's a number that would be 6 (items) or 48 (bytes) in the example above, possibly on the pyarrow object, possibly on the Python buffer returned by `buffers()`, possibly somewhere else, but accessible from the pyarrow object.

We'll have to check this on pyarrow arrays with missing values, since they do this with a bitmask, which can't be sliced at non-byte boundaries. (In practice, we'd have to build the Awkward Array node with a `length + offset`, then slice the Awkward node by the `offset`. We'd only want to do that if the offset is non-zero, since that would force a conversion of the BitMaskArray into a ByteMaskArray to be able to cut it at arbitrary places, and that's pointless when the place is zero.)

We didn't notice it before because we weren't slicing pyarrow arrays before converting them. This is just another illustration of how inadequate even 100% test coverage is! (Remember how I added a bunch of tests to make sure that every line of code on the function is tested? That doesn't help if the thing we're missing is a value, like this offset not being zero!)

I'm not in a good position to investigate this now, but let me know here if you find something. Thanks!

**Comment by jpivarski** [comment]
I got a chance to look at it on my computer, and I can confirm:

```python
>>> array = pa.array(np.arange(10))[6:]
>>> array
<pyarrow.lib.Int64Array object at 0x7fcc999f4280>
[
  6,
  7,
  8,
  9
]
>>> mask, content = array.buffers()
>>> mask
>>> content
<pyarrow.lib.Buffer object at 0x7fcc99d053b0>
>>> np.frombuffer(content, dtype=np.int64)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

The Python buffer object returned by `array.buffers()` hides Arrow's equivalent of an "offset" parameter. It also hides the "length"; we must be getting that from `len(array)` (which is `4`).

**Comment by jpivarski** [comment]
Here it is: it's an attribute called `offset`, which is attached to the pyarrow array itself:

```python
>>> array.offset
6
>>> pa.array(np.arange(10)).offset
0
>>> pa.array(np.arange(10))[6:].offset
6
>>> pa.array(np.arange(10))[2:].offset
2
```

**Comment by aminnj** [comment]
Hi Jim, thanks for such a fast response. I was playing a bit more yesterday and for flat arrays, found I could do
```python
>>> import pyarrow as pa
>>> import awkward1 as ak
>>> import numpy as np
>>> orig = pa.Array.from_pandas([1,2,3,4,5])
>>> a = orig[2:4]
>>> _, buffer = a.buffers()
>>> np.frombuffer(buffer, dtype=int)
array([1, 2, 3, 4, 5])
>>> np.frombuffer(buffer.slice(a.offset * a.type.bit_width//8), dtype=int)[:len(a)]
array([3, 4, 5])
```
but I can see how it's not trivial when there's a mask or jaggedness. 

Anyway, as a solution in my current code, I put
```python
        if array_arrow.offset != 0:
            array_arrow = array_arrow.take(np.arange(len(array_arrow)))
```
before I try to convert an arrow array into awkward.

**Comment by jpivarski** [comment]
The tests haven't been added yet, but PR #625 now correctly handles these `offsets`:

```python
>>> arrow_array = ak.to_arrow(ak.Array(np.arange(10)))
>>> ak.from_arrow(arrow_array[6:])
<Array [6, 7, 8, 9] type='4 * int64'>

>>> arrow_array = ak.to_arrow(ak.Array([[0, 1, 2], [], [3, 4], [5], [6, 7, 8, 9]]))
>>> ak.from_arrow(arrow_array[2:])
<Array [[3, 4], [5], [6, 7, 8, 9]] type='3 * var * int64'>
```

**Comment by jpivarski** [comment]
> Anyway, as a solution in my current code, I put
> 
> ```python
>         if array_arrow.offset != 0:
>             array_arrow = array_arrow.take(np.arange(len(array_arrow)))
> ```
> 
> before I try to convert an arrow array into awkward.

I think you're relying on the fact that the `take` copies the data into a new array that has `offset=0`. If the zero-copy aspect was valuable, you'll want this fix.

Thanks for pointing it out, though! Seeing the wrong answers come out of a function (as opposed to an error or something) is the most disturbing kind of bug.

**Comment by aminnj** [comment]
Great, I'll follow that PR so I can eventually switch to a truly zero-copy solution! :)

**Comment by raymondEhlers** [comment]
I saw this in the release notes, but I'm having some trouble understanding the full impact on my analysis code. Does this also impact analyses which convert to/from parquet files too? And is it only for slices? (ie. does it also impact masking?). Thanks!

**Comment by jpivarski** [comment]
It's worth testing your analysis code on the newly released version. This is a bug that can give you the wrong values when converting an Arrow array to an Awkward Array, and the chain Parquet → Arrow → Awkward goes through Arrow.

However, you only get the wrong values if the Arrow arrays have been sliced in `pyarrow`. That's because the zero-copy buffers that `pyarrow` gives us for, say

```python
>>> import pyarrow as pa
>>> array = pa.array([0, 1, 2, 3, 4, 5])
>>> sliced = array[2:]
>>> sliced
<pyarrow.lib.Int64Array object at 0x7fdb92cc6ca0>
[
  2,
  3,
  4,
  5
]
```

do not explicitly exclude the sliced-off parts. That is,

```python
>>> _, raw_data = sliced.buffers()
>>> np.frombuffer(raw_data, np.int64)
array([0, 1, 2, 3, 4, 5])
```

starts with `0` even though `sliced` is supposed to start with `2`. In the Arrow → Awkward conversion, we should have been looking at the

```python
>>> sliced.offset
2
```

to find the right part of `raw_data` to consider as part of the Awkward Array. With the PR, that "wrong answer bug" has been fixed.

Now that I've written this up in a scary way, I _doubt_ it affects conversions from Parquet through Arrow to Awkward Array because I _doubt_ that `pyarrow` arrays get sliced after the conversion from Parquet and before the conversion to Awkward. That's how this bug survived so long: nobody was doing any non-trivial work on the Arrow arrays, so the assumption that `offset == 0` always held. But that's my assumption of how the Parquet → Arrow conversion works, and I didn't write that code, so it remains only a guess.

**Comment by raymondEhlers** [comment]
Thanks for the explanation - now it's clear. I'll run a quick test to check and report back if something changed in my analysis with the new version, but I suspect that you're right that it shouldn't be an issue for me
