### ISSUE TITLE
Adding a `__delitem__``` method to awkward arrays

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#663]
We can add to a highlevel array with a record, e.g.
```python
a = ak.Array({"x": [1, 2, 3], "y": [4, 5, 6]})
a["z"] = [7, 8, 9]
```
but we can't delete:
```python
del a["z"]  # AttributeError
a["z"] = None  # makes a numpy object array
```

**Comment by jpivarski** [comment]
That's true, `ak.Array.__delitem__` does not exist.

If the array is a record at top-level, this is all you'd need:

```python
>>> a[[x for x in ak.fields(a) if x != "z"]]
<Array [{x: 1, y: 4}, ... y: 5}, {x: 3, y: 6}] type='3 * {"x": int64, "y": int64}'>
```

Though this has a few issues. One is that an empty list does the wrong thing because we don't know that it's supposed to be a list of strings:

```python
>>> a[[]]
<Array [] type='0 * {"x": int64, "y": int64, "z": int64}'>
```

There doesn't seem to be a way to make this output have type `3 * {}`, like this:

```python
>>> ak.Array(ak.layout.RecordArray([], [], 3))
<Array [{}, {}, {}] type='3 * {}'>
```

~~The other issue is that this doesn't apply at the level where the record actually is; it applies at top-level.~~

Nope! Turns out, that's okay. It's hard to remember all of these rules. With a jagged array of records `b`,

```python
>>> b = ak.unflatten(a, [2, 0, 1])
>>> print(b)
[[{x: 1, y: 4, z: 7}, {x: 2, y: 5, z: 8}], [], [{x: 3, y: 6, z: 9}]]
>>> ak.type(b)
3 * var * {"x": int64, "y": int64, "z": int64}
```

applying the slice procedure maintains the jagged array structure above the record.

```python
>>> b[[x for x in ak.fields(b) if x != "z"]]
<Array [[{x: 1, y: 4}, ... {x: 3, y: 6}]] type='3 * var * {"x": int64, "y": int64}'>
```

The only thing that keeps the definition of `ak.Array.__delitem__` from being a one-liner is handling the case in which there's only one field and that's the one being removed. To do that right, `getitem_fields` should be exposed to the Python layout level through [content_methods](https://github.com/scikit-hep/awkward-1.0/blob/b5503c5e606fc594fabdc2e352c9432aa767e160/src/python/content.cpp#L1145-L1503) and then `ak.Array.__delitem__` can pass its reduced list of keys directly to that function, rather than as a slice (where there's the ambiguity about an empty list being a list of strings).

**Comment by nsmith-** [comment]
Thoughts about `a["z"] = None` ? Should `None` be a special case (create a fully masked array?) or should we broadcast a numpy object array of None? This is somewhat tangential to delitem, I guess.

**Comment by jpivarski** [comment]
`a["z"] = None` is not what I'd expect to remove a field. I'd expect `ak.Array.__delitem__` to do that. There are cases where we want special handling of None, rather than casting it as an array (whatever _that_ turns out to be), such as #487, in which we really do expect `ar != None` to give a boolean array with True everywhere that the option-type `ar` has a missing value.

Actually, I might think that `a["z"] = None` would make `"z"` a new field (or replace one that was already there) consisting entirely of missing values. Like this:

```python
>>> ak.Array(
...     ak.layout.IndexedOptionArray32(
...         ak.layout.Index32(np.full(1000, -1, np.int32)),
...         ak.layout.EmptyArray()
...     )
... )
<Array [None, None, None, ... None, None, None] type='1000 * ?unknown'>
```

Maybe if `"z"` preexisted and it's assigned to be None, maybe then it would pick up the original type of `a["z"]` (by putting it in the `content` instead of the EmptyArray).

**Comment by nsmith-** [comment]
> a["z"] = None is not what I'd expect to remove a field.

Yeah I realized that shortly after typing, and just wanted to highlight its current behavior is a bit troublesome (causes some error)
