### ISSUE TITLE
Inconsistent dimensionality when slicing muiltple axes

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#689]
Example
```python
>>> import numpy as np
>>> import awkward as ak
>>> ak.Array([[1,2],[3,4]])[[True, False], 0].ndim
1
>>> ak.Array([[1,2],[3,4]])[[False, False], 0].ndim
2
>>> ak.Array([[1,2],[3,4]])[[False, False]][:, 0].ndim
1
>>> np.array([[1,2],[3,4]])[[False, False], 0].ndim
1
```
In this example the dimensionality of the result is 2 only in the second case, but in all others it's 1. I believe the dimensionality should be 1 in all cases. I can not see a reason why one would need to check if the mask for the first axis is zero everywhere and handle this case separately.
Tested on current git main (1.1.0rc1).

**Comment by jpivarski** [comment]
To fix this (PR #691), `__getitem__` has to pass down one more boolean in its recursive descent because there's a distinction between no advanced indexes (slicing with arrays of booleans or integers) and an advanced index with zero length. It doesn't make a different for any values, but it does matter for the type—thanks for catching this!
