### ISSUE TITLE
to_arrow() fails with IrregularlyPartitionedArrays

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#702]
This came up while using `uproot.lazy()`:

```python
>>> import awkward as ak
>>> ak.__version__
'1.0.2'
>>> import uproot
>>> ak.to_arrow(uproot.lazy('file.root'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/awkward/operations/convert.py", line 2226, in to_arrow
    return recurse(layout, None, False)
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/awkward/operations/convert.py", line 2221, in recurse
    raise TypeError(
TypeError: unrecognized array type: <IrregularlyPartitionedArray>
```

**Comment by jpivarski** [comment]
Thanks!

I've been finding and fixing a lot of bugs related to PartitionedArrays (the first commit of #699 goes down the line, making it have all the same methods and properties as `Content` subclasses). I've been developing some tutorial examples with lazy Parquet files, so I'm running into them myself and fixing them whenever I see them.

In this one, I think it makes sense for Awkward PartitionedArrays to be turned into [Arrow ChunkedArrays](https://arrow.apache.org/docs/cpp/arrays.html#chunked-arrays). However, ChunkedArrays are not turned into PartitionedArrays when round-tripping back (they just get concatenated, since the advantage of laziness is gone after round-tripping through Arrow). I might have to revisit that.
