### ISSUE TITLE
Slicing awkward array does not work correctly with Python 2.7

### ISSUE THREAD

**Issue by ast0815** [scikit-hep/awkward#705]
Hello, I think there is a bug when trying to slice an awkward array with python 2.7:

```python
>>> import awkward as ak
>>> ak.__version__
u'1.0.2'
>>> a = ak.Array([[1,2],[3]])
>>> a
<Array [[1, 2], [3]] type='2 * var * int64'>
>>> a[...]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/koch/Projekte/histoprint/env27/local/lib/python2.7/site-packages/awkward/highlevel.py", line 1005, in __getitem__
    return ak._util.wrap(self._layout[where], self._behavior)
ValueError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`), and integer or boolean arrays (possibly jagged) are valid indices

(https://github.com/scikit-hep/awkward-1.0/blob/1.0.2/src/python/content.cpp#L666)
```

When I try the same with Python 3.7 it works:

```python
>>> a[...]
<Array [[1, 2], [3]] type='2 * var * int64'>
```

Other slices work, so I suspect it does not like the ellipsis.

**Comment by jpivarski** [comment]
Not exactly a bug; when I wrote that, it wasn't actually possible to identify an ellipsis in Python 2.7 with pybind11:

https://github.com/scikit-hep/awkward-1.0/blob/ef3587f2aed1e8e8e0b13d863b96885cc08d7156/src/python/content.cpp#L459-L463

but since then, the situation has changed:

https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#ellipsis

Awkward builds against pybind11 2.6.2, so we can use ellipsis now! PR #707.
