### ISSUE TITLE
ak.from_iter should accept NumPy scalars as numbers

### ISSUE THREAD

**Issue by mariogeiger** [scikit-hep/awkward#740]
Hi,

```python
ak.from_iter([np.array(1.)])
```

To be honest I don't know if it should work or not but the error message is cryptic.

```
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Comment by jpivarski** [comment]
You found a bug. In general, we use only two exception types in Awkward Array: ValueErrors for user errors (i.e. you have to provide different input) and RuntimeErrors for internal errors. (There aren't many equivalences between C++ exceptions and Python exceptions, but there were these two, and so we choose to use them to make this distinction. The most important thing for you to know is whether it's your error or ours.) So, basically, if it ever says RuntimeError, please report it! (Maybe I should go through the code and add some text like that every single instance of RuntimeError. unfortunately, though, that's a practice that would have to be maintained manually.)

For this one in particular, I don't recognize the message, it could be coming from pybind11, rather than our own code. Nevertheless, we should support it because NumPy scalars can look just like ordinary numbers, and raising an error like this can be confusing.
