### ISSUE TITLE
ak.unflatten raises ValueError if counts end with 0

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#742]
```python
import awkward as ak
ak.unflatten(ak.Array([0,0,0]), ak.Array([1,2,0]))
```
Raises `ValueError: structure imposed by 'counts' does not fit in the array or partition at axis=0`

**Comment by jpivarski** [comment]
When unflattening at `axis>0` or in a PartitionedArray (two recent new features), it's a free choice where to put the zeros: inside the larger structure on the left or on the right. By choosing to put them on the left, I missed this case where you're unflattening at `axis=0` without any partitions: then it's not sensible to put them on the left because there's nothing on the right to take them. (That would also apply to the last list in `axis>0` or the last partition in a PartitionedArray.) So this choice isn't so arbitrary after all: they need to go on the left for the sensible thing to happen in a case like the above. Thanks for pointing this out.
