### ISSUE TITLE
Union of indexed arrays loses its record type

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#770]
If I define a simple mixin class and create a union array that can be an instance:
```python
import awkward as ak


@ak.mixin_class(ak.behavior)
class Blah:
    @property
    def blah(self):
        return self["x"]


a = ak.zip({"x": [[1, 2], [3]], "y": [[4, 5], [6]]})
b = ak.zip({"x": [[-1, -2, -3], [-4]], "z": [[-4, -5, -6], [-7]]})
c = ak.with_name(ak.concatenate([a, b], axis=1), "Blah")
```
then, as expected, `c.blah` returns `<Array [[1, 2, -1, -2, -3], [3, -4]] type='2 * var * union[int64, int64]'>` (it would be nice if it simplified, that's #714).
But if I first filter `a` and `b` (i.e. turning them into indexed arrays):
```python
a2 = a[a.x % 2 == 0]
b2 = b[b.x % 2 == 0]
c2 = ak.with_name(ak.concatenate([a2, b2], axis=1), "Blah")
```
the same `c2.blah` now raises an `AttributeError`. One also sees that `c2.layout.purelist_parameter("__record__")` is empty.

With ak version `1.2.0rc2`.

**Comment by nsmith-** [comment]
This looks very similar to #815 and still seems to be broken with `1.2.2-1-g9ef4b7bc`

**Comment by agoose77** [comment]
Where we end up with a `Union`, perhaps we should propagate the `__record__` iff. the contents of the union share the same `__record__`?

**Comment by jpivarski** [comment]
Maybe the new rule could be,

   1. if the UnionArray has a parameter with a given name, `purelist_parameter(name)` should return its value;
   2. if the UnionArray does not have this parameter, but every one of its contents has that parameter with the same value, then `purelist_parameter(none)` should return that common value.

None of the error cases that raised this issue are still errors, though. In all of those cases, it was wrong for the UnionArray to have existed: a `simplifiy_uniontype` call was missing. The above rule would make UnionArrays transparent to common parameters, but maybe that's bad because then we'd be less likely to catch missing `simplifiy_uniontype` calls, since that's a common symptom.

Are there any legitimate cases in which you'd have a UnionArray with all contents having the same parameter? I can think of one corner-case: you have an array of records that are all Lorentz vectors (`"__record__": "Momentum4D"`), but some of them have auxiliary data, like `"charge"` because they're electrons, while others don't. Then you'd want the record name to be visible above the UnionArray.

**Comment by nsmith-** [comment]
This bug was found by someone that wanted to concatenate electrons and muons into leptons, which share 4-vector and charge attributes, but may have other differing attributes. It would be nice to still do vector math with the leptons collection.

**Comment by jpivarski** [comment]
If the electrons and muons have different `__record__` values, then this wouldn't fix it because the UnionArray wouldn't be able to report a single answer for `purelist_parameter("__record__")`. There are a few ways that could be addressed:

   * Set the `__record__` of both the electrons and muons to `"Momentum4D"`, though they can have different attributes beyond the kinematic ones. Since they have different attributes, they wouldn't get merged—they'd still be a UnionArray—but the new rule described above would note that they're all labeled `"Momentum4D"` and report that for `purelist_parameter("__record__")`. However, that means that they can't have `__record__` names like `"Electron"` or `"Muon"` because that spot is taken by `"Momentum4D"`. If you wanted to have another specialized method that applies only to muons or is a different function for electrons and muons, you'd be out of luck.
   * Do the above and add yet another rule that interprets a _list_ of strings from `__record__` as a method resolution order. (Remember that parameters can be any JSON, not just strings.) Then the two union contents could be `["Electron", "Momentum4D"]` and `["Muon", "Momentum4D"]`, resolving particle-specific behaviors first, then Lorentz vector ones if not overridden. This would be a more flexible way than class inheritance way to do class inheritance. (Actually, more similar to Haskell's type classes.)
   * Maybe this would also be needed for the above, but it could be done independently: when attempting to call a method on an array containing unions that have a method with that name defined on all contents of the union, call the method independently on each content and make a union of the result. This will be tricky if the union is not a top-level, if it's nested in some list. If the first two bullet points are not implemented but this one is, it would solve the problem: `"Electron"` and `"Muon"` both have a method named `pt`, so they're both called, a union is built from the result, and that union would likely simplify to a non-union array. If the first two bullet points are implemented along with this one, it would solve the problem in a slicker way: `"Electron"` and `"Muon"` don't have to independently implement `pt`, it can be one of the inherited methods from `"Momentum4D"`, while they maintain their independent type names.

So many possibilities, so little time. Maybe we should start collecting these ideas into PIP/NEP like documents.

**Comment by nsmith-** [comment]
> If the electrons and muons have different __record__ values

They have the same record value: "Candidate" (4-vector plus charge)

**Comment by jpivarski** [comment]
Then only the new rule described in https://github.com/scikit-hep/awkward-1.0/issues/770#issuecomment-861867937 would be needed (which is good, because that's the easiest thing out of everything described above). I'll turn that comment into an issue.

**Comment by jpivarski** [comment]
As it turns out, the policy described in https://github.com/scikit-hep/awkward-1.0/issues/770#issuecomment-861867937 _is_ the policy that UnionArray _already has_. That's why @nsmith-'s example `c` worked. His example `c2` didn't work because it was incorrectly implemented: all of the UnionArray's `contents` are supposed to have the same `purelist_parameter`, but it was implemented checking their direct `parameters` (for all but `contents[0]`).
