### ISSUE TITLE
Constructing Array with different length columns should raise error

### ISSUE THREAD

**Issue by Dominic-Stafford** [scikit-hep/awkward#771]
Creating an awkward Array from different length columns currently (in v1.1.1) just truncates to the length of the shortest column:
```
>>> ak.Array({"a": [1, 2], "b": [1, 2, 3]})
<Array [{a: 1, b: 1}, {a: 2, b: 2}] type='2 * {"a": int64, "b": int64}'>
```
I'm not sure if this is intended behaviour, but I personally would expect this to fail with an exception (for instance pandas gives a `ValueError: arrays must all be same length`). If there is a reason to have this as the behaviour, could it be included in the documentation, please?

**Comment by jpivarski** [comment]
That's a good point. The RecordArray that this makes should allow different-lengthed contents (so that they can be filled non-atomically), users of this constructor are probably intending them to line up. The fact that Pandas raises an error and this constructor was introduced to emulate Pandas only clinches it.

It's interesting that the original test for the Pandas-style constructor had unequal length arrays and had to be modified by this PR.

**Comment by Dominic-Stafford** [comment]
Thank you!
