### ISSUE TITLE
`ak.from_parquet` loads wrong data with `lazy=True` for ListOffsetArray of nested records

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#783]
In some situations i get the wrong result when loading parquet files with `lazy=True` - the simplest example i could come up with is this ListOffsetArray of a nested record:

```pycon
>>> array = ak.Array([[], [{"a" : [{"x" : 17, "y" : 42}]}]])
>>> ak.to_parquet(array, "array.parquet")
>>> ak.from_parquet("array.parquet").tolist()
[[], [{'a': [{'x': 17, 'y': 42}]}]]
>>> ak.from_parquet("array.parquet", lazy=True).tolist()
[[], [{'a': []}]]
```

```pycon
>>> import awkward as ak
>>> ak.__version__
'1.2.0rc2'

```

But otherwise, pretty nice that lazy reading of columns from nested parquet files is possible now in principle!

**Comment by jpivarski** [comment]
There's a bug here, but your "simplest example" was very lucky—all of the variations that I tried did not reproduce this error. You actually need a list-of-record-of-list-of-record to do it (though record doesn't have to have two fields):

```python
>>> array = ak.Array([[], [{"x": [{"y": 1}]}]])
>>> ak.to_parquet(array, "array.parquet")
>>> ak.from_parquet("array.parquet").tolist()
[[], [{'x': [{'y': 1}]}]]
>>> ak.from_parquet("array.parquet", lazy=True).tolist()
[[], [{'x': []}]]
```

Moreover, you need the first entry to be an empty list. Here is the same type/form, but without starting with an empty list, the problem isn't visible:

```python
>>> array = ak.Array([[{"x": [{"y": 1}]}]])
>>> ak.to_parquet(array, "array.parquet")
>>> ak.from_parquet("array.parquet").tolist()
[[{'x': [{'y': 1}]}]]
>>> ak.from_parquet("array.parquet", lazy=True).tolist()
[[{'x': [{'y': 1}]}]]
```

I tried putting the empty list in the inner dimension, and encountered another, possibly related, error:

```python
>>> array = ak.Array([[{"x": []}, {"x": [{"y": 1}]}]])
>>> ak.to_parquet(array, "array.parquet")
>>> ak.from_parquet("array.parquet").tolist()
[[{'x': []}, {'x': [{'y': 1}]}]]
>>> ak.from_parquet("array.parquet", lazy=True).tolist()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/awkward-1.0/awkward/highlevel.py", line 439, in tolist
    return ak.operations.convert.to_list(self)
  File "/home/jpivarski/irishep/awkward-1.0/awkward/operations/convert.py", line 943, in to_list
    return [to_list(x) for x in array]
  File "/home/jpivarski/irishep/awkward-1.0/awkward/operations/convert.py", line 943, in <listcomp>
    return [to_list(x) for x in array]
  File "/home/jpivarski/irishep/awkward-1.0/awkward/operations/convert.py", line 943, in to_list
    return [to_list(x) for x in array]
  File "/home/jpivarski/irishep/awkward-1.0/awkward/operations/convert.py", line 943, in <listcomp>
    return [to_list(x) for x in array]
  File "/home/jpivarski/irishep/awkward-1.0/awkward/operations/convert.py", line 946, in to_list
    return to_list(array.layout)
  File "/home/jpivarski/irishep/awkward-1.0/awkward/operations/convert.py", line 955, in to_list
    return {n: to_list(x) for n, x in array.fielditems()}
ValueError: generated array does not have sufficient length: expected2 but generated 1

(https://github.com/scikit-hep/awkward-1.0/blob/1.2.0rc2/src/libawkward/virtual/ArrayGenerator.cpp#L39)
```

so it has something to do with empty lists. Putting an empty list between two good values is also symptomatic (for the value _after_ the empty list):

```python
>>> array = ak.Array([[{"x": [{"y": 1}]}], [], [{"x": [{"y": 2}]}]])
>>> ak.to_parquet(array, "array.parquet")
>>> ak.from_parquet("array.parquet").tolist()
[[{'x': [{'y': 1}]}], [], [{'x': [{'y': 2}]}]]
>>> ak.from_parquet("array.parquet", lazy=True).tolist()
[[{'x': [{'y': 1}]}], [], [{'x': []}]]
```

Explicitly materializing the lazy version gives a hint of what's going on: the outer list offsets are wrongfully applied to the inner list.

```python
>>> not_lazy = ak.from_parquet("array.parquet")
>>> from_lazy = ak.materialized(ak.from_parquet("array.parquet", lazy=True))
>>> not_lazy.tolist()
[[{'x': [{'y': 1}]}], [], [{'x': [{'y': 2}]}]]
>>> from_lazy.tolist()
[[{'x': [{'y': 1}]}], [], [{'x': []}]]

>>> not_lazy.layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 1 1 2]" offset="0" length="4" at="0x7fdc0dc00140"/></offsets>
    <content><RecordArray length="2">
        <field index="0" key="x">
            <ListOffsetArray64>
                <offsets><Index64 i="[0 1 2]" offset="0" length="3" at="0x7fdc0dc001c0"/></offsets>
                <content><RecordArray length="2">
                    <field index="0" key="y">
                        <NumpyArray format="l" shape="2" data="1 2" at="0x7fdc0dc00080"/>
                    </field>
                </RecordArray></content>
            </ListOffsetArray64>
        </field>
    </RecordArray></content>
</ListOffsetArray64>

>>> from_lazy.layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 1 1 2]" offset="0" length="4" at="0x7fdc0d800140"/></offsets>
    <content><RecordArray length="2">
        <field index="0" key="x">
            <ListOffsetArray64>
                <offsets><Index64 i="[0 1 1 2]" offset="0" length="4" at="0x7fdc0d800140"/></offsets>
                <content><RecordArray length="2">
                    <field index="0" key="y">
                        <NumpyArray format="l" shape="2" data="1 2" at="0x7fdc0d400080"/>
                    </field>
                </RecordArray></content>
            </ListOffsetArray64>
        </field>
    </RecordArray></content>
</ListOffsetArray64>
```

The inner list is not just `[0 1 1 2]` when it's supposed to be `[0 1 2]`, but it also has the same pointer: `0x7fdc0d800140`. That's definitely not right.

This could explain why examples without two levels of lists didn't exhibit the symptom, and records might be needed because the virtual-reading stops at each level of record arrays.

I'll try to figure out what is happening here. Thanks for reporting!

**Comment by jpivarski** [comment]
PR #784 fixes all of the examples above.

Fundamentally, it's because Parquet doesn't have the offsets array/content array distinction that Awkward Array and Arrow have—instead, it only saves the deepest leaf-nodes with [a single indexing scheme](https://blog.twitter.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet.html) to indicate offsets at all levels above it. To lazily produce offsets arrays anyway, we have to pick a field from the record (the first, though that's an implementation detail) and read that deepest content to get its indexes and make offsets.

In your case, there were two offsets arrays above the content. I had considered that and "unpacked" it to make the right offsets at each level, but they had the same cache key. So that's why we ended up with identically the same offsets for both levels: when it should have been fetching the second one, it found the first one in the cache and couldn't distinguish it. The essential correction was this:

```diff
-                samplekey = "{0}:off:{1}[{2}]".format(
-                    lazy_cache_key, sampleform.form_key[4:], row_group
+                samplekey = "{0}:off:{1}:{2}[{3}]".format(
+                    lazy_cache_key,
+                    sampleform.form_key[4:],
+                    ".".join("" if x is None else x for x in unpack),
+                    row_group,
                )
```

I just had to put a bit more information into that cache key so that the two levels of offsets don't look the same. Unfortunately, that meant fixing a lot of tests that were hard-coded against the original cache keys. (The point of those tests was to verify that lazy reading reads the right thing at the right time, but to do so, I looked at which keys were in the cache.)
