### ISSUE TITLE
Differing behavior depending on placement of ak.with_field

### ISSUE THREAD

**Issue by mat-adamec** [scikit-hep/awkward#788]
### Motivation
I'm updating my coffea analysis up to 0.7 (with awkward 1.1.2), and loving the new awkward1 features! I have, however, found some behavior that I'd consider to be odd. In part of the analysis, it's far easier to stack muons and electrons into a single array while preserving flavor. I found that this can be accomplished easily by a combination of `ak.with_field` to add a flavor tag and `ak.concatenate`, using `ak.with_name` to label the array as `PtEtaPhiMCandidate` to preserve functions like delta_r().

### Behavior
And here lies the discrepancy: if I add the flavor at the very beginning, the array doesn't seem to retain any name I put on it. In other words:

```
import awkward as ak
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

file = 'root://hcc-stash.unl.edu:1094//osgconnect/public/dweitzel/coffea-casa/38E83594-51BD-7D46-B96D-620DD60078A7.root'
events = NanoEventsFactory.from_root(file).events()

muons = ak.with_field(events.Muon, 0, 'flavor')
electrons = ak.with_field(events.Electron, 1, 'flavor')

loose_muons = muons[muons.pt > 5]
loose_electrons = electrons[electrons.pt > 5]

loose_leptons = ak.with_name(ak.concatenate([loose_muons, loose_electrons], axis=1), 'PtEtaPhiMCandidate')
```

Results in a loose_leptons array that appears as:
`<Array [[{dxy: 0.000454, ... flavor: 1}]] type='614400 * var * union[struct[["dx...'>)`

But if I add the flavor after all cuts on the muons/electrons have been made, then it all works just fine:
```
import awkward as ak
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

file = 'root://hcc-stash.unl.edu:1094//osgconnect/public/dweitzel/coffea-casa/38E83594-51BD-7D46-B96D-620DD60078A7.root'
events = NanoEventsFactory.from_root(file).events()

muons = events.Muon
electrons = events.Electron

loose_muons = muons[muons.pt > 5]
loose_muons = ak.with_field(loose_muons, 0, 'flavor')

loose_electrons = electrons[electrons.pt > 5]
loose_electrons = ak.with_field(loose_electrons, 1, 'flavor')

loose_leptons = ak.with_name(ak.concatenate([loose_muons, loose_electrons], axis=1), 'PtEtaPhiMCandidate')
```

This results in loose_leptons appearing as (as intended):
`<PtEtaPhiMCandidateArray [[{charge: -1, ... flavor: 1}]] type='614400 * var * un...'>)`

After further investigation, it seems like altering the array after adding a field onto it breaks how `ak.with_name` behaves. However, I don't see any other changes in behavior or any differences in content for loose_leptons between the two examples, so this seems like a bug.

**Comment by jpivarski** [comment]
You're right; this is a bug. The reason this happened goes pretty deep, too. Most operations on Awkward Arrays only rewrite indexes; they don't have to modify data in the tree structure down to the leaves. Exceptions to this are called "carrying" because the first application (in the implementation of slices) looked to me like carrying a digit in arithmetic, except that it was carrying a whole array. Naturally, carrying is more expensive than not carrying.

Almost a year ago now, @ianna put in an important optimization that replaced carrying of RecordArrays with creating an [IndexedArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedArray.html) node above the RecordArray. Carrying a RecordArray is especially expensive because it might have a lot of fields—you'd have to rewrite every one of those fields. Moreover, some of those fields might be unread data on disk (NanoEvents is lazy), so carrying every field in a RecordArray might initiate a lot of extra disk-reading. @ianna's optimization instead creates a new IndexedArray that _represents_ its content in a different order without actually changing the order of its content. This optimization couldn't be applied in all cases, but it could be applied in some.

However, there was one tiny mistake:

```diff
# src/libawkward/array/RecordArray.cpp
@@ -941,7 +941,7 @@ namespace awkward {
    }
    if (allow_lazy) {
      return std::make_shared<IndexedArray64>(identities,
-                                             parameters_,
+                                             util::Parameters(),
                                              carry,
                                              shallow_copy());
    }
```

The RecordArray's parameters (e.g. it's name) was being copied from the RecordArray to the new IndexedArray node, so the name now appeared in two places. When you call `ak.with_name`, you _are_ replacing the RecordArray's name, but it's hidden under the IndexedArray that still has the old name.

That's why you see a difference depending on whether the array has been modified or not. The modified array would formally require a carry operation, and an IndexedArray is inserted instead. The unmodifed array doesn't even formally require a carry.

Before:

```python
>>> one = ak.Array([[{"x": 1}], [], [{"x": 2}]], with_name="One")
>>> two = ak.Array([[{"x": 1.1}], [], [{"x": 2.2}]], with_name="Two")
>>> ak.with_name(ak.concatenate([one, two], axis=1), "All").type          # record name change is visible
3 * var * union[All["x": int64], All["x": float64]]
>>> ak.with_name(ak.concatenate([one[1:], two[1:]], axis=1), "All").type  # record name change is hidden
2 * var * union[One["x": int64], Two["x": float64]]
```

After:

```python
>>> ak.with_name(ak.concatenate([one, two], axis=1), "All").type
3 * var * union[All["x": int64], All["x": float64]]
>>> ak.with_name(ak.concatenate([one[1:], two[1:]], axis=1), "All").type
2 * var * union[All["x": int64], All["x": float64]]
```

That was one fix, and it might be the only one that's relevant to your case because electrons and muons might be unmergeable. (They might have to be a UnionArray of two RecordArrays, rather than a single RecordArray.) That's not the case in my minimal example, though: the `"x"` fields can be merged to a single `float64` field. So in PR #789, I also added a second pass to `ak.with_name` to check for instances where unions can be merged.

```python
>>> ak.with_name(ak.concatenate([one, two], axis=1), "All").type
3 * var * All["x": float64]
>>> ak.with_name(ak.concatenate([one[1:], two[1:]], axis=1), "All").type
2 * var * All["x": float64]
```

If it's possible to remove UnionArrays like this, it's better to do so because some features don't work with UnionArrays (Numba and JAX integration, for example). If your electrons and muons have different sets of fields, preventing their merger, you can select a common subset of fields like this:

```python
>>> my_electrons = electrons[["pt", "eta", "phi", "charge"]]
```

to make them mergeable. Records with the same field names pointing to mergeable field types _and_ the same record name are mergeable; the "union" should go away. (On the other hand, if you don't use any features that don't work for UnionArrays, don't worry about this step.)
