### ISSUE TITLE
Invalid dimensionality from cartesian with zero length input

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#794]
To reproduce
```python
import awkward as ak
data = ak.layout.NumpyArray([1, 2, 3])
data = ak.layout.ListArray64(ak.layout.Index64([0]), ak.layout.Index64([3]), data)
data = ak.layout.IndexedArray64(ak.layout.Index64([]), data)
cart = ak.cartesian([data, data])
print(cart.type)
```
This prints `0 * var * (1 * int64, int64)`. I think it should be `0 * var * (int64, int64)`.
If you compare this to the case that the index of the `IndexedArray64` has one entry, you nicely get `1 * var * (int64, int64)`.
I run into invalid array shapes with this behavior, as `ak.unzip(cart)[0]` suddenly is 3 dimensional (in case of 0 length input) instead of 2 dimensional.

Tested on latest git main (awkward-1.2.0rc4)

**Comment by jpivarski** [comment]
Thanks for the report!

I believe that the correct place to catch and fix this edge-case is in PR #795: we should let the size-1 RegularArray go through the calculation (that's how `ak.cartesian` works—by broadcasting) but if the result is all zero-length because one of the arrays in the Cartesian product was, then the size-1 RegularArrays that would have been broadcasted if they weren't empty should then be reduced to empty arrays. It works for your example (before and after collapsing the dimensions with `nested=False`) and works for all other tested cases. As a change, it applies in a very limited set of cases.
