### ISSUE TITLE
Override 'ak.sum' for custom types (expected in Vector)

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/awkward#824]
sorry for opening another issue :-/ , i'm just trying things out and cross-checking with my expectations 

Starting with the same examplle
```
data = [
    {"px": 1., "py": 1.1, "pz": 0.1, 'E': 3.3},
    {"px": 2., "py": 2.2, "pz": 0.2, 'E': 3.3}
]

arr = vc.awk(data)
```
gives

```
<MomentumArray4D [{x: 1, y: 1.1, z: 0.1, ... t: 3.3}] type='2 * Momentum4D["x": ...'>
```

but two (i would think) identical ways to add them yield the same data

```python
>>> print(ak.to_list(arr[0] +  arr[1]))
... print(ak.to_list(ak.sum(arr,axis=-1)))
{'x': 3.0, 'y': 3.3000000000000003, 'z': 0.30000000000000004, 't': 6.6}
{'x': 3.0, 'y': 3.3000000000000003, 'z': 0.30000000000000004, 't': 6.6}
```

but different types

```python
>>> print(ak.type(arr[0] +  arr[1]))
... print(ak.type(ak.sum(arr,axis=-1)))
Momentum4D["x": float64, "y": float64, "z": float64, "t": float64]
{"x": float64, "y": float64, "z": float64, "t": float64}
```

trying to fix things up manually gets the type right

```python
>>> print(ak.type(ak.Record(ak.sum(arr,axis=-1),with_name = 'Momentum4D')))
Momentum4D["x": float64, "y": float64, "z": float64, "t": float64]
```

but the bahavior is broken (trying to get the mass)

```python
>>>  ak.Record(ak.sum(arr,axis=-1),with_name = 'Momentum4D').mass

   1799                 raise AttributeError(
   1800                     "no field named {0}".format(repr(where))
-> 1801                     + ak._util.exception_suffix(__file__)
   1802                 )
   1803 

AttributeError: no field named 'mass'
```

while on the other type of summing it works

```python
>>> (arr[0] +  arr[1]).mass
4.8559242168715935
```

**Comment by lukasheinrich** [comment]
Thanks for the prompt answer @jpivarski! Is there a reason why the "manual" fix above (wrapping it in `ak.Record(.., with_name = ...)` didn't make the `.mass` property available? - happy to transfer this to awkward

**Comment by lukasheinrich** [comment]
(though I notice `np.sum` is not preserving the type either) but I guess it's a ufunc vs non-ufunc issue)


```
>>> np.sum(arr,axis=-1)
<Record {x: 3, y: 3.3, z: 0.3, t: 6.6} type='{"x": float64, "y": float64, "z": f...'>
```

**Comment by jpivarski** [comment]
> Thanks for the prompt answer @jpivarski! Is there a reason why the "manual" fix above (wrapping it in `ak.Record(.., with_name = ...)` didn't make the `.mass` property available?

Because of a long-standing but until now, never-noticed bug in `ak.behavior` handling for Records. Look at this thing: https://github.com/scikit-hep/awkward-1.0/pull/825/commits/3b694d6d35098ebd2db2615cfa7eb7e38aea2990 ! Assigning the name and updating the class have been out of order for maybe a year at least.

> (though I notice `np.sum` is not preserving the type either) but I guess it's a ufunc vs non-ufunc issue)
> 
> ```
> >>> np.sum(arr,axis=-1)
> <Record {x: 3, y: 3.3, z: 0.3, t: 6.6} type='{"x": float64, "y": float64, "z": f...'>
> ```

`np.sum` and `ak.sum` are the same thing; we use [NEP 18](https://numpy.org/neps/nep-0018-array-function-protocol.html) to override `np.sum` with our own, when there are any Awkward Arrays in the arguments. But `ak.sum` doesn't pass through the parameters, including the record name, because it reduces a dimension—what had been XYZ probably doesn't exist now.

Especially if the `axis` is not `-1`:

<img src="https://user-images.githubusercontent.com/1852447/114474503-01208f00-9bbc-11eb-9542-5bb244d8690f.png" width="400">

That mixes values from very different places.

```python
>>> array = ak.Array([[2, 3, 5], [], [None, 7], [11]])
>>> ak.prod(array, axis=-1)
<Array [30, 1, 7, 11] type='4 * int64'>
>>> ak.prod(array, axis=-2)
<Array [22, 21, 5] type='3 * int64'>
```

**Comment by nsmith-** [comment]
I'm not sure if I made an issue, but the way I dealt with it in coffea vectors was to add a mixin method specifically to do the axis=-1 reduction: https://github.com/CoffeaTeam/coffea/blob/fca8e13faa8c8dac51ec4216abf9f83a9b0405c4/coffea/nanoevents/methods/vector.py#L512-L524
