### ISSUE TITLE
`np.matmul` produces wrong result with NumPy RHS

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#846]
The following multiplication produces a result with too few entries in the underlying contents, leading to errors when accessing items:
```python
transform = ak.Array(
    [
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
    ]
)

vector = ak.Array(
    np.r_[4,5,6].reshape(3, 1)    
)

result = np.matmul(transform, vector)
result[0]
```

This does not happen if I create the `vector` Array by hand:
```python
vector = ak.Array(
    [
        [4],
        [5],
        [6]
    ]
)
result = np.matmul(transform, vector)
result[0]
```

This is also true of `transpose(vector) @ transform`

```python
>>> import awkward as ak
>>> ak.__version__
'1.2.2'
```

**Comment by agoose77** [comment]
The tests are failing on platforms without numba, because the `__matmul__` indirectly depends upon `numba`. Do you have any suggestions here? I could add 
```
numba = pytest.importorskip("numba")
```
to manually register the numba dependency, but this won't scale as more features have numbafied implementations.

**Comment by jpivarski** [comment]
`pytest.importorskip("numba")` is a good thing to add (without the assignment because flake8 would complain about the variable not being used).

There are a lot of tests that only work if Numba exists. Matrix multiplication is the only feature in which that is hidden—users don't have to manually import Numba to use it, so failures due to the lack of Numba could be a surprise—but if this is a popular feature, it should be ported to the C++ layer, anyway.

(This feature was originally written to answer an email. I didn't want to put a lot of time into something without knowing that it would be needed for analysis. Yours is the first use-case that I know about.)

**Comment by agoose77** [comment]
OK, I'll modify the test accordingly. I should have put this comment in the PR, but it's been a long day :weary: 

I understand that the feature is not really a "production one", and I can see why it makes sense to keep things high level unless required. I'm not personally going to advocate for that yet, so once this issue is closed all is fine by me!
