### ISSUE TITLE
Very slow ufuncs, especially when masked

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#852]
The ufunc in awkward seem to be too slow for what they are actually doing. Compared to the Numpy equivalent, there is a difference of a few magnitudes of order. I have studied this with `np.logical_not` on a simple one dimensional array. Other ufuncs appeared to have similar behavior.
![awkward_performance](https://user-images.githubusercontent.com/30041073/116428889-a175e500-a845-11eb-8360-ad8ebd7a0a19.png)

  <details>
    <summary>Python script to produce the plot</summary>
    

```python
#!/usr/bin/env python3

import numpy as np
import numpy.ma as ma
import awkward as ak
import matplotlib.pyplot as plt
from timeit import Timer

def timeit(func, number=100):
    return Timer(func).timeit(number=number)

testsizes = np.logspace(0, 6, 20).astype(int)

numpy_time = []
for size in testsizes:
    a = np.full(size, True)
    numpy_time.append(timeit(lambda: np.logical_not(a)))

numpymask_time = []
for size in testsizes:
    a = ma.masked_array(np.full(size, True), mask=[True] * size)
    numpymask_time.append(timeit(lambda: np.logical_not(a)))

awkward_time = []
for size in testsizes:
    a = ak.Array(np.full(size, True))
    awkward_time.append(timeit(lambda: np.logical_not(a)))

awkwardmask_time = []
for size in testsizes:
    a = ak.Array(np.full(size, True)).mask[[True] * size]
    awkwardmask_time.append(timeit(lambda: np.logical_not(a)))

plt.plot(testsizes, numpy_time, label="Numpy", color="C0", linestyle="--")
plt.plot(testsizes, numpymask_time, label="Numpy masked", color="C1", linestyle="--")
plt.plot(testsizes, awkward_time, label="Awkward", color="C0")
plt.plot(testsizes, awkwardmask_time, label="Awkward masked", color="C1")
plt.xscale("log")
plt.yscale("log")
plt.xlabel("Array length")
plt.ylabel("Time per 100 iterations in s")
plt.legend(title="Logical not with", loc="upper left")
plt.show()
```
  </details>

In https://github.com/scikit-hep/awkward-1.0/issues/442#issuecomment-689669226 the plot shows that the numpy and awkward execution times for large inputs becomes equal. However, I do not see this in my case. In above plot the blue lines might line up for input sizes far outside of what I am using, and the orange ones do not look like they will line up at all.

I think this is important because of this example timing I got from line_profiler using it on some of my code, `data` and `mask` are simple one dimensional awkward arrays with no further layout other than that they might use an OptionArray, times are in µs:
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   130     34668    6706606.0    193.5      2.5              a = ak.is_none(data)
   131     34668   22385934.0    645.7      8.2              b = ~a
   132     34668  190116583.0   5483.9     69.9              mask = mask & b
```
and comepare this to
```
   130     35939   12825258.0    356.9     21.6              a = np.asarray(ak.is_none(data))
   131     35939     172479.0      4.8      0.3              b = ~a
   132     35939    4658937.0    129.6      7.8              c = np.asarray(mask)
   133     35938     108790.0      3.0      0.2              mask = c & b
```

This is all using awkward 1.2.2

**Comment by jpivarski** [comment]
Okay, but the part that's slower is the constant-time part. (The lines are horizontal with respect to array size.) This would only be an issue if the ufuncs were being called many times on small arrays, which is the pattern we recommend against. (By "columnar," we mean that a single invocation of the function scales well with the size of the array.) By the time it starts to have a linear rise, the slope seems to be about the same as NumPy's slope—which would only make sense, since it's NumPy that's actually running the ufunc on flattened data.

The performance goals are to have a good slope for the _O(n)_ part and for the _O(1)_ part be short on human timescales (well under 1 second), for interactivity. More build-up and tear-down has to be done before and after actually running the ufunc in order to streamline the ufunc itself: the _O(1)_ time is worse than it would be in a for-loop style implementation, for the sake of streamlining the _O(n)_ part. This will work badly for scripts that try to do tight loops that a ufunc many times, but that's an anti-pattern in NumPy, too.

If the algorithm can't be expressed in a columnar way, we recommend using Numba for that part. The implementation of Awkward Array access in Numba is completely different from the ufunc implementation, minimizing the build-up and tear-down of each iteration because this _is_ expected to be used in hot loops.

**Comment by jrueb** [comment]
Thanks for the reply. I now understand what your goal is performance wise. The big difference between the constant times Numpy and Awkward have made me a bit worried, but I also think I need to improve my code.

But there is still one thing: I don't think the slopes in case of masked arrays agree. Maybe I'm mistaken, but isn't there a factor of 10 between Numpy and Awkward here? For example for a length of 10**9 Awkward needs 17 s while Numpy only needs 1.3 s. These 15 s difference can't be just build-up and tear-down, or are they?
```
for i in [10, 10**4, 10**6, 10**7, 10**8, 10**9]:
    a = ak.Array(np.full(i, True)).mask[np.full(i, True)]
    %timeit ~a

381 µs ± 4.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
419 µs ± 929 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
4.9 ms ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
131 ms ± 660 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.42 s ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
16.9 s ± 443 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


for i in [10, 10**4, 10**6, 10**7, 10**8, 10**9]:
    a = ma.masked_array(np.full(i, True), mask=np.full(i, True))
    %timeit ~a

26.6 µs ± 2.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
26.5 µs ± 205 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
166 µs ± 718 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.47 ms ± 7.79 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
133 ms ± 711 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.34 s ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by jpivarski** [comment]
Ah, I was eyeballing it from the plot. Yes, the masked arrays are scaling differently because the constant-time part is 0.05 seconds.

One thing that `ak.Array(np.full(i, True)).mask[np.full(i, True)]` does that `ma.masked_array(np.full(i, True), mask=np.full(i, True))` doesn't do when a ufunc is applied is that the Awkward version projects the non-masked-out data into a new array of only good values, applies the ufunc, and then un-projects back to the original shape. This prevents the ufunc from being executed on masked-out values. The NumPy version applies the ufunc to all data, whether masked-out or not.

Projecting accounts for half the execution time, as shown below. Presumably, un-projecting accounts for the other half. (I don't remember, offhand, how to do that from Python.)

```python
>>> starttime = time.time(); tmp = ~a; print(time.time() - starttime)
0.8057053089141846
>>> starttime = time.time(); tmp = a.layout.project(); print(time.time() - starttime)
0.4267578125
```

This wasn't done for performance; it was done because an operation might fail to run on invalid values, though I was thinking about operations that fail for structural reasons when I instituted that policy. (For example, suppose you are doing a slice that takes the first element of each list, and have masked out all the empty lists. You wouldn't want it to fail with an error message saying, "You can't get the first element of an empty list" when your array _looks like_ it has no empty lists, the empties being hidden by a mask.) Ufuncs are a little different because failure to compute a function like `np.sqrt` returns `nan`, possibly with a warning. If we let ufuncs get executed on masked-out values, the worst that would happen is that you'd see a warning saying "invalid value encountered" when there are no invalid values in the _logical_ array (they're hidden behind a mask).

Suppose we do that—suppose we skip the projection and un-projection for ufuncs (only) in [BitMaskedArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.BitMaskedArray.html) and [ByteMaskedArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.ByteMaskedArray.html), but not [IndexedOptionArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedOptionArray.html), which have to project for structural reasons. (IndexedOptionArrays are the most common way to implement missing values, but `.mask` makes ByteMaskedArrays, which are equivalent to NumPy's masked arrays.)

That's PR #853, and you _do_ get that order of magnitude back.

```python
>>> starttime = time.time(); tmp = ~a; print(time.time() - starttime)   # Awkward
0.07140612602233887
>>> starttime = time.time(); tmp = ~b; print(time.time() - starttime)   # NumPy
0.08176493644714355
```

However, I'm still on the fence about allowing it because it will lead to "invalid value encountered" warnings for arrays that don't look like they have any invalid values. For instance,

```python
>>> array = ak.Array([1.1, -2.2, 3.3, -4.4, 5.5])

>>> array.mask[array >= 0]
<Array [1.1, None, 3.3, None, 5.5] type='5 * ?float64'>

>>> np.sqrt(array.mask[array >= 0])
/home/jpivarski/irishep/awkward-1.0/awkward/_connect/_numpy.py:160: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(
<Array [1.05, None, 1.82, None, 2.35] type='5 * ?float64'>
```

That will be hard to explain. It's also difficult to make this performance optimization opt-in because it's not a method you're calling that you can pass an additional argument to, it's `~`.

**Comment by jrueb** [comment]
This indeed not an easy decision. I'm a bit in favor of raising warnings instead of copying the data, but I also see the downsides.
Is there a way to keep only the projected version of the array plus its mask? Basically a special case of the IndexedOptionArray. If the masked array was represented this way, one could avoid this issue. But maybe that has downsides as well.

**Comment by jpivarski** [comment]
Well, it would likely be slower with IndexedOptionArrays, especially for ufuncs with more than one option-type argument (e.g. if it was `logical_and` instead of `logical_not`) because then the projection must _always_ be applied to ensure that the contents of both IndexedOptionArrays line up. At least with masking (by bits or bytes), the content has the same order as the logical array.

Maybe there's a shortcut that's not quite as fast as the above but still avoids the most complicated gymnastics if all of the option-type arrays are (bit or byte) masked arrays.

No, it puts almost all of the time back:

```python
>>> starttime = time.time(); tmp = ~a; print(time.time() - starttime)
0.48636579513549805
```

It's really the projection that takes all that time, specifically this:

https://github.com/scikit-hep/awkward-1.0/blob/6d33c18815ac39b9436ffddc493f7ab12b498858/src/awkward/_util.py#L744-L747

NumPy's masked arrays are faster because they don't do that.

```python
>>> array = np.ma.masked_array([1.1, -2.2, 3.3, -4.4, 5.5], mask=[False, True, False, True, False])
>>> array
masked_array(data=[1.1, --, 3.3, --, 5.5],
             mask=[False,  True, False,  True, False],
       fill_value=1e+20)
>>> np.sqrt(array)
<stdin>:1: RuntimeWarning: invalid value encountered in sqrt
masked_array(data=[1.0488088481701516, --, 1.816590212458495, --,
                   2.345207879911715],
             mask=[False,  True, False,  True, False],
       fill_value=1e+20)
```

So that's the trade-off. NumPy's masked arrays are simple enough that if you encounter something like the above, you can pretty quickly figure out why you get the warning. Awkward Arrays are more complex, so the warning would be more mysterious. You might not know, for instance, whether you have a ByteMaskedArray (and would therefore get the warning) or an IndexedOptionArray (and would not).

**Comment by jpivarski** [comment]
After some thought, I'm leaning strongly toward not including this optimization. Awkward missing values are different from NumPy masked arrays: they have extra features that NumPy does not (e.g. preventing calculation on invalid quantities). That feature comes with a performance cost. Apart from hardware accelerators, like the future GPU support, Awkward Array won't be faster than NumPy (and with GPU support, it won't be faster than CuPy). In some cases, it may be as fast as NumPy (or CuPy), if it doesn't provide any features beyond NumPy. In this case, it does, and that's why you're seeing slower performance.

If you have rectilinear data and want to give up the "don't calculate on invalid values" feature for performance, then switching to NumPy for that part of the calculation would be a good thing to do. If you don't have rectilinear data but want to control the loop for performance, that's what the Numba interface is for. The performance goals for the Awkward Numba extension were very different from the ufunc extension: as you've seen, the ufunc extension freely makes new arrays to ensure that operations are not performed on invalid data (which includes more complex cases than masked values in a masked array), but the Numba extension reduces an Awkward Array into a minimalist pointer called ArrayView and hard-codes data access by type in Numba's JIT-compilation.

It seems wrong to partially give up a feature—preventing calculation on invalid values in Bit/ByteMaskedArrays, but not, for instance, slicing values from empty lists—introducing surprising (and wrong) warning messages for the sake of performance when there's another way to get that performance. Unless you have strong objections, I'll be closing PR #853 and this issue.
