### ISSUE TITLE
Missing operators

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/awkward#854]
awkward version 1.2.2.

The inplace bitwise-and operator is missing.

```py
a &= b
``` 

Error excerpt from my code:
```
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'bitwise_and'>, '__call__', <Array [False, False, False, ... False, False] type='3460644 * bool'>, <Array [True, True, True, ... True, True, True] type='3460644 * bool'>, out=(<Array [False, False, False, ... False, False] type='3460644 * bool'>,)): 'Array', 'Array', 'Array'
```

**Comment by HDembinski** [comment]
This and the other inplace operators are very important because they avoid creating temporaries.

**Comment by jpivarski** [comment]
Awkward Arrays are not mutable: #529. At least, the functions provided in the `awkward` package do not change arrays in place, but if an array is viewing memory owned elsewhere, by NumPy, for instance, then NumPy can change that memory in place ([docs](https://awkward-array.org/how-to-convert-numpy.html#mutability-of-awkward-arrays-from-numpy)).

Given that long-standing design choice, it would not be appropriate to implement any in-place operators, unless it is to override the error message.

Also, if the array has non-trivial structure (the reason you'd be using Awkward Array and not NumPy), it's not just one temporary array that's being created. In general, you can't control the number of temporary arrays at this level because the temporaries that need to be created depends on the exact layout of the array and the operation to perform. The way to control memory and CPU more tightly is to use Numba. When an Awkward Array is passed to Numba, no new arrays are created that you don't make yourself in the JIT'ed function, just a pointer to the existing arrays.

I haven't been able to find the issue number, but we also talked about doing `np.asarray` inside a JIT'ed function to mutate it in-place, and I remember that the resolution of that was that it worked. Yes, just verified it:

```python
>>> import awkward as ak
>>> import numpy as np
>>> import numba as nb
>>> @nb.njit
... def f(array):
...   for subarray in array:
...     asnumpy = np.asarray(subarray)
...     for i in range(len(asnumpy)):
...       asnumpy[i] += 10
... 
>>> array = ak.Array([[1, 2, 3], [], [4, 5]])
>>> f(array)
>>> array
<Array [[11, 12, 13], [], [14, 15]] type='3 * var * int64'>
```

In conclusion: implementing `&=` would go against a fundamental design choice that we've talked about several time before, but if you want to wrap Awkward Arrays with an interface that supports all the in-place operators and depends on Numba, you're free to do so. Such a package would have a different design philosophy than Awkward Array, since the JIT'ed functions you'd have to generate for each data structure is a very different kind of implementation than Awkward's implementation. Instead of making new buffers to build new array-tree structures with structural sharing, you'd be keeping the same buffers and array-tree structure and changing the values. The former does not require JIT; the latter does require JIT if it's going to be implemented for an infinite set of data types (e.g. the monoid generated by arbitrarily many levels of jaggedness).

**Comment by HDembinski** [comment]
Considering that the only awkward arrays that I am using are jagged arrays which have a very simple structure, it is very difficult to accept this argument. Why make arrays immutable? Why not differe tiate between arrays that must be immutable and allow others to be mutable? Your design choice collides with reality...

**Comment by jpivarski** [comment]
Because most users don't use only simple jagged arrays, and introducing an exception would be confusing. But if you're only using one-level jagged arrays, then providing that functionality with a wrapper becomes even simpler—you don't have to generate code to JIT-compile; the function I wrote above would be sufficient (well, one for each operator).

Mainly, though, we've talked about this multiple times. Mutability becomes confusing to _use_ (it's an _interface_ problem, not implementation) when all data types are considered. That's why, after experimenting with mutability in early versions, I concluded that it would bring more pain to include it. What you want is something specialized that clashes with the general library, so you can write it! You can make mutable jagged arrays a subclass of `ak.Array`, give it all the `__iadd__`, etc. methods, say

```python
ak.behavior["mutable-jagged"] = MutableJaggedArray
```

and set the `"__array__"` parameter of the ListArray/ListOffsetArray to `"mutable-jagged"`. Then, every time it's instantiated, it will have `MutableJaggedArray` type and have all the `__iadd__`, etc. methods.

Don't keep asking me to put things in the general library that I've already found to be troublesome. (We've talked about it before, but by "troublesome," I mean that users can't easily determine whether something is a view or a copy because, unlike a NumPy array, which is either all-view or all-copy, an Awkward Array is a tree of nodes, some of which may be views while others are copies. It gets complicated very quickly. That wouldn't happen if you only had simple jagged arrays, but most users have more complex arrays. I regularly work with people who have wide records, subrecords (usually representing systematic variations), index pointers, multiple levels of jaggedness, the four different option-types, and some people even use union-types, though I recommend against union types, if they're possible to avoid. And a back-door exception, like scikit-hep/awkward-0.x/pull/167, muddies the water too much: I had to keep explaining why this case worked and others didn't. "No mutability in the general library" is an easy enough rule that most people accept when they hear about it. _Especially_ since it's possible to wrap it with that functionality: casting as NumPy is a back door to mutability that can be built into a convenience library, if you limit the interface to data types in which mutability is not confusing.)
