### ISSUE TITLE
Replicated issue using np.newaxis on array of bools

### ISSUE THREAD

**Issue by HenryDayHall** [scikit-hep/awkward#859]
So we were chatting about a possible issue using `np.newaxis` to save arrays of bools on [stackoverflow](https://stackoverflow.com/questions/67436879/awkward1-how-to-set-array-dimension-as-variable/67439610?noredirect=1#comment119232107_67439610).

I did manage to replicate this in a docker; https://hub.docker.com/r/henrydayhall/awkward_issue_replication

When I run this I get;
```
$ sudo docker run -ti awkwarddoc1
Please run python3 ~/problem.py
root@eee2b4b23af5:/# python3 ~/problem.py
Awkward version 1.2.2
Save success
Traceback (most recent call last):
  File "/root/problem.py", line 12, in <module>
    ak.to_parquet(zipped, 'test.parquet')
  File "/usr/local/lib/python3.8/dist-packages/awkward/operations/convert.py", line 2960, in to_parquet
    first = next(iterator)
  File "/usr/local/lib/python3.8/dist-packages/awkward/operations/convert.py", line 2939, in batch_iterator
    to_arrow(
  File "/usr/local/lib/python3.8/dist-packages/awkward/operations/convert.py", line 2466, in to_arrow
    return recurse(layout, None, False)
  File "/usr/local/lib/python3.8/dist-packages/awkward/operations/convert.py", line 1999, in recurse
    ready_to_pack[: len(numpy_arr)] = numpy_arr
ValueError: could not broadcast input array from shape (3,) into shape (1,)
```
In the Docker I install awkward with pip, on my own system I'm using conda, and both give me the same behaviour.

Seeing as I can replicate this locally too I'd be happy to try and fix it? On the other hand it could be some issue with how I am importing things or something, which would probably be apparent in the [Dockerfile](https://github.com/HenryDayHall/awkward_docker/blob/master/Dockerfile)?

**Comment by jpivarski** [comment]
I see the error in the Docker environment, but not in my local setup. There's something going on here with versions.

   * I noticed that there were a lot of developments since the last Awkward release (new 1.x versions are regularly released every two months, but in between that they're ad-hoc. So I triggered another release, which should be available on PyPI in less than an hour.
   * I noticed that Arrow updated their major release number _again_, from 3.0.0 to 4.0.0. (They've adopted a very rapid versioning scheme!) Since this involves Parquet writing (which goes through Arrow), that's relevant.

I could test the second point right away by updating my pyarrow package from 3.0.0 to 4.0.0 (I should be testing the latest, anyway). There were no problems there.

This new Awkward release ([1.3.0rc4](https://github.com/scikit-hep/awkward-1.0/releases/tag/1.3.0rc4) includes a fix to the handling of regular dimensions in boolean arrays (#837). You might have independently discovered this same bug. If so, the new release should fix it, or [installing Awkward from GitHub](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/). I'm trying the latter in the Docker container right now.

**Comment by jpivarski** [comment]
It works in the Docker container if the latest Awkward is installed.

```
root@3701fd712778:/# python3 -m pip install git+https://github.com/scikit-hep/awkward-1.0.git
Collecting git+https://github.com/scikit-hep/awkward-1.0.git
  Cloning https://github.com/scikit-hep/awkward-1.0.git to /tmp/pip-req-build-6ga7pmxl
  Running command git clone -q https://github.com/scikit-hep/awkward-1.0.git /tmp/pip-req-build-6ga7pmxl
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13.1 in /usr/local/lib/python3.8/dist-packages (from awkward==1.3.0rc4) (1.20.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from awkward==1.3.0rc4) (45.2.0)
Building wheels for collected packages: awkward
  Building wheel for awkward (PEP 517) ... done
  Created wheel for awkward: filename=awkward-1.3.0rc4-cp38-cp38-linux_x86_64.whl size=8107834 sha256=d35368e8761cb11683aa05a028065fa9d43e7f7a92e0d12c22df06dd4d288079
  Stored in directory: /tmp/pip-ephem-wheel-cache-ffnf6_da/wheels/1d/0a/7d/c67b26366bf441e34371c6b286943132d3d8bb628ee67511c1
Successfully built awkward
Installing collected packages: awkward
  Attempting uninstall: awkward
    Found existing installation: awkward 1.2.2
    Uninstalling awkward-1.2.2:
      Successfully uninstalled awkward-1.2.2
Successfully installed awkward-1.3.0rc4
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
root@3701fd712778:/# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import awkward as ak
>>> ak.__version__
'1.3.0rc4'
>>> 
root@3701fd712778:/# python3 ~/problem.py 
Awkward version 1.3.0rc4
Save success
```

The second check would be to see if 1.3.0rc4 also solves the issue. ([See progress toward deployment here.](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=6362&view=results))

I've decided that the numbering of pre-releases and bug-fix releases between the every-two-months release is confusing: pre-releases are numbered 1.3.0rcX, whereas bug-fixes are numbered 1.2.Y. After 1.3.0, I'll start numbering the pre-releases as 1.3.1rcX so that version number order will be chronological order.

(The reason I need to do pre-candidates is because real releases have to be kept forever, since someone might pin to them, but pre-releases can be deleted. Storage space in PyPI is limited. However, since this regular-dimension, boolean array bug in `ak.to_arrow` was discovered twice, maybe this `1.3.0rc4 should also be released as 1.2.3, after you confirm that it fixes the error.)

**Comment by jpivarski** [comment]
[Awkward 1.3.0rc4 has been released](https://pypi.org/project/awkward/1.3.0rc4/).

**Comment by HenryDayHall** [comment]
Can confirm, this issue is fixed in the new release. Many thanks!
