### ISSUE TITLE
Have elements of an `Array` of strings be instances of `str`

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#873]
In numpy, the elements of an `np.ndarray` of strings are `np.str_`, which is a subclass of `str`:

```python
>>> import numpy as np
>>> np.array(['asdf'])[0]
'asdf'
>>> type(np.array(['asdf'])[0])
<class 'numpy.str_'>
>>> isinstance(np.array(['asdf'])[0], str)
True
```

In awkward, the elements come up as `awkward.behaviors.string.CharBehavior`, which is not a `str`:

```python
>>> import awkward as ak
>>> ak.__version__
'1.2.3'
>>> ak.Array(['asdf'])[0]
'asdf'
>>> type(ak.Array(['asdf'])[0])
<class 'awkward.behaviors.string.CharBehavior'>
>>> isinstance(ak.Array(['asdf'])[0], str)
False
```

This makes it inconvenient to pass these values to functions that depend on `isinstance(input, str)` to detect strings in their arguments. Getting around this is straightforward (just wrap with `str()`), but is it possible to make the default behavior an instance of `str`?

I guess the same would go for `awkward.behaviors.string.ByteBehavior` and `bytes`, but that issue would never come up in any of my use cases.

**Comment by jpivarski** [comment]
Well, I'm not sure. For one thing, ByteBehavior and CharBehavior can't be subclasses of bytes and str, respectively, because Python doesn't allow it (bytes and str are not normal classes and they have a different memory layout than Awkward Arrays; their methods wouldn't work). However, we can catch the output of `ak.Array.__getitem__`, `ak.Record.__getitem__`, and `ak.ArrayBuilder.__getitem__` to turn it into bytes and str.

On the one hand, this breaks the notion that Awkward types "`byte`" and "`char`" are just one-dimensional arrays of `uint8` with special behaviors. It also introduces extra copying: the bytes and str objects have a copy of the underlying data, rather than a view. That's more than a performance thing, it's a semantics difference if somebody was relying on the mutability of the underlying data.

On the other hand, having actual bytes and str objects is super-convenient. If "`byte`" and "`char`" are thought of as fundamental types like numbers, this is as natural as having `__getitem__` return Python int and float (which is what it does). On that last point, it's going backward from what @lukasheinrich wanted: to have `__getitem__` return a zero-dimensional object with `ak.Array` type, just as NumPy numbers are (sometimes!) zero-dimensional arrays. (This is something our approach to JAX integration needed, but we might be taking a different approach.) Finally, this is what happens in Numba-compiled functions: "`byte`" and "`char`" are returned as (lowered) bytes and str.

Actually, this should only ever be relevant for small-sampling, in which you're extracting a single string, rather than performing a vectorized operation.

Even if the PR passes all tests, I'm going to leave this open for discussion for a while. I'm not sure it's the right thing to do, but I'm convinceable.

**Comment by masonproffitt** [comment]
Yeah, handling this in `__getitem__` as in the PR seems reasonable to me. This is also consistent with the current behavior of `__iter__`, which *does* yield `str` (despite `__getitem__` not doing so) for reasons I don't entirely understand...

**Comment by jpivarski** [comment]
Actually, the fact that `__iter__` does makes the case stronger. (It's because `__iter__` is a non-recursive version of `tolist`—that was the training there.)
