### ISSUE TITLE
More issues with null typed columns to_arrow_table conversion & lazy loading from parquet

### ISSUE THREAD

**Issue by drahnreb** [scikit-hep/awkward#875]
I might have finally reproduced another problem in awkward that is linked to nullable columns in arrow tables (#828) and affects #865.

Environment specs:
```sh
# install latest awkward from @main to include newest lazy loading changes:
pip install git+https://github.com/scikit-hep/awkward-1.0.git@3dbf8c87d78d98332b6629607841d8610dcca072
```
```python
>>> import awkward as ak
>>> import pyarrow as pa
>>> ak.__version__, pa.__version__
(1.2.3, 4.0.0)
```
Consider the following table with a null typed column:

```python
>>> null_table = pa.Table.from_pydict({'null_col': pa.array([None])})
>>> null_table
pyarrow.Table
null_col: null
# as expected with #828
>>> null_array = ak.from_arrow(null_table)
>>> null_array
<Array [{null_col: None}] type='1 * {"null_col": ?unknown}'>
# alternatively:
>>> null_array = ak.Array({'null_col': [None]})
<Array [{null_col: None}] type='1 * {"null_col": ?unknown}'>
```

**Issue 1** - conversion to arrow results in a double typed column
```python
>>> ak.to_arrow_table(null_array)
pyarrow.Table
null_col: double
```

**Issue 2** - lazy read a nullable column fails with ValueError
```python
# we have to write via external lib e.g. pyarrow to avoid type conversion and save null typed column on disk
pq.write_table(null_table, 'null_typed_table.parquet')
pq.read_table('null_typed_table.parquet')
pyarrow.Table
null_col: null

ak.from_parquet('null_typed_table.parquet', lazy=True)
ValueError: cannot convert NumPy dtype with kind O into a NumpyForm

(https://github.com/scikit-hep/awkward-1.0/blob/1.2.3/src/libawkward/Content.cpp#L232)

# this works as expected
>>> ak.from_parquet('null_typed_table.parquet')
<Array [{null_col: None}] type='1 * {"null_col": ?unknown}'>
```

Without looking into the relevant lines yet, I guess definitely null typed columns should have its own routine for building Forms  (not `maybe_nullable()`; something reversed to #828)?

I didn't think of kind O typed numpy arrays when reasoning about a valid, non-temporary test case for #867 - but actually this ValueError should not be raised ever when loading from parquet because awkward should be compliant with both arrow and parquet (on-disk) columnar memory formats and none of them does support flexible/python objects as valid column types.

**Comment by jpivarski** [comment]
On issue 1, `ak.layout.EmptyArray` converts to a `float64` array because empty NumPy arrays are assumed to be `float64`. This logic is reproduced in the `to_arrow` function, but it doesn't have to be:

https://github.com/scikit-hep/awkward-1.0/blob/3dbf8c87d78d98332b6629607841d8610dcca072/src/awkward/operations/convert.py#L2033-L2034

Can we instead make a length-zero `pyarrow.Array` with null type? Is this appropriate?

```python
>>> pyarrow.Array.from_buffers(pyarrow.null(), 0, [pyarrow.py_buffer(np.array([]))])
<pyarrow.lib.NullArray object at 0x7fe7bae72700>
0 nulls
```

Or this?

```python
>>> pyarrow.Array.from_buffers(pyarrow.null(), 0, [None])
<pyarrow.lib.NullArray object at 0x7fe7bae819a0>
0 nulls
```

Probably the latter, because

```python
>>> null_table.to_batches()[0].column(0).buffers()
[None]
```

---------------------------

On issue 2, it's because an `arrow_type` of `DataType(null)` gets converted into a NumPy kind `"O"` dtype with

```python
>>> arrow_type = pq.ParquetFile("null_typed_table.parquet").schema_arrow.field("null_col").type
>>> arrow_type
DataType(null)
>>> arrow_type.to_pandas_dtype()
<class 'numpy.object_'>
```

https://github.com/scikit-hep/awkward-1.0/blob/3dbf8c87d78d98332b6629607841d8610dcca072/src/awkward/operations/convert.py#L3178-L3180

This null is an exceptional case that apparently shouldn't be checked through `to_pandas_dtype`. This works:

```python
>>> arrow_type == pyarrow.null()
True
```

**Comment by jpivarski** [comment]
I'll fix 'em.

**Comment by jpivarski** [comment]
PR #878 does it: see the tests. Cheers!
