### ISSUE TITLE
`broadcast_arrays()` loses information when broadcasting `None`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#882]
When broadcasting an array with an `option` array, the option leaks into the non-option array, e.g.
```python
>>> np.broadcast_arrays(ak.Array([[1,2,3],[4]]), [None, 6])
>>> [<Array [None, [4]] type='2 * option[var * int64]'>,
 <Array [None, [6]] type='2 * option[var * int64]'>]
```

I understand that some options need to propagate the `None` e.g. NumPy ufuncs. But, for broadcasting, do you think it's acceptable that the result should instead be:
```python
 [<Array [[1,2,3], [4]] type='2 * var * int64]'>,
 <Array [None, [6]] type='2 * option[var * int64]'>]
```
I.e. [lines 758-766](https://github.com/scikit-hep/awkward-1.0/blob/22501ba218646dc24dc515c4394eb22f126d340d/src/awkward/_util.py#L758-L766) might not be required (in addition to some other change of course. 
```python
>>> import awkward as ak
>>> ak.__version__
'1.2.3'
```

**Comment by jpivarski** [comment]
Or it needs to be

```python
 [<Array [[1,2,3], [4]] type='2 * var * int64]'>,
 <Array [[None, None, None], [6]] type='2 * var * ?int64'>]
```

**Comment by agoose77** [comment]
> Or it needs to be
> 
> ```python
>  [<Array [[1,2,3], [4]] type='2 * var * int64]'>,
>  <Array [[None, None, None], [6]] type='2 * var * ?int64'>]
> ```



Yes, I suppose if the option doesn't take precedence then it needs to be like this.

**Comment by jpivarski** [comment]
I was looking at this with the intention of fixing it, but instead, I became convinced that the current behavior is correct.

The purpose of broadcasting is to put N arrays into the same form so that some operation can be computed on them, such as (but not limited to) applying a ufunc. NumPy doesn't have missing values above the numeric level (and even then, `np.ma.MaskedArrays` are not super-standard), so NumPy doesn't provide guidance and we can choose a behavior that is suited to our needs.

Broadcasting these two arrays lets the None in the right array knock out a whole list in the left array:

```python
>>> ak.broadcast_arrays(ak.Array([[1, 2, 3], [4]]), ak.Array([None, 6]))
[<Array [None, [4]] type='2 * option[var * int64]'>,
 <Array [None, [6]] type='2 * option[var * int64]'>]
```

but that's because combining them in an operation like `+` (binary ufunc) would have no information for the whole first list on the left.

```python
>>> ak.Array([[1, 2, 3], [4]]) + ak.Array([None, 6])
<Array [None, [10]] type='2 * option[var * int64]'>
```

Alternative answers like `[[None, None, None], [10]]` don't really make sense (the None on the right is in the position of the whole first list—I don't see why it should be "exploded down" one level).

Given that broadcasting is to support N-array operations, the current behavior is correct. I suppose you were thinking that broadcasting should leave at least one of the arrays intact, but I don't see why that should be a constraint (and it might not be compatible with the intention of supporting N-array operations).
