### ISSUE TITLE
Implement ptp

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#889]
Is there a precedent for implementing functions that improve API parity with NumPy?

E.g. a naive `ptp` is something like two lines of code:
```python
@ak._connect._numpy.implements("ptp")
def ptp(arr, axis=None, keepdims=False, initial=None, mask_identity=True):
    """Return the range of values along a given axis."""
    return ak.max(
        arr, axis=axis, keepdims=keepdims, initial=initial, mask_identity=mask_identity
    ) - ak.min(
        arr, axis=axis, keepdims=keepdims, initial=initial, mask_identity=mask_identity
    )
```

But it's not an *essential* function. I'd vote in favour of implementing it (in https://github.com/scikit-hep/awkward-1.0/blob/main/src/awkward/operations/reducers.py) because `np.ptp` is more concise and quite widely used.

**Comment by jpivarski** [comment]
Improving feature parity with NumPy is definitely desirable, and I'd be grateful for any contributions like the above.

Since you already have an implementation, I'll just tell you where it goes: it's a reducer, so it belongs in `src/awkward/operations/reducers py`, immediately after `min` and `max`. The order of functions in the file matters because it determines the order of functions in the side-bar of the documentation. Like looking for books in a library, a user might be looking for `ak.min` and `ak.max`, but see `ak.ptp` right next to it and go for that.

You already know about the `implements` decorator that works make `ak.ptp` override `np.ptp`, so that's good.

You can copy most of the docstring from `min`, weigh gives a standard explanation of the reducer arguments. If you want to add an example illustrating that this is a difference and mention that "ptp" stands for "peak to peak," that would be helpful. Seen someone clicks on the documentation for `ak.ptp`, it will be the only thing on the page—they won't also be seeing the other reducers for context.

It should also have a test, numbered fit this issue or the PR, that includes comparisons of flat `ak.Arrays` with their corresponding `np.ndarrays`, since they have to behave the same when they coincide. You should make sure that the results are the same for all `axis` values, since `axis != -1` cuts across nested arrays in surprising ways.

**Comment by agoose77** [comment]
Thanks Jim. Let me know if these "discussion issues" are better done after creating a PR in future :)

**Comment by jpivarski** [comment]
No, this is exactly right: an issue labeled "feature" is the first step in adding a feature. I'd also accept an appropriate PR without the feature request issue, but raising the issue first gives us a chance to talk it over first, so that you don't put a lot of effort into a PR and then find out that I can't accept it for some reason.

Also, I gave all the details in my previous response though I know you're aware of some of them because someone else might discover this thread in the future when they want to add a feature. It's hard to get exactly the right information into the documentation or CONTRIBUTING.md that each person would need, but if I get enough information out there in the form of answering specific questions like this one, the chances are better that someone who needs it will find it.

**Comment by agoose77** [comment]
> No, this is exactly right: an issue labeled "feature" is the first step in adding a feature. I'd also accept an appropriate PR without the feature request issue, but raising the issue first gives us a chance to talk it over first, so that you don't put a lot of effort into a PR and then find out that I can't accept it for some reason.

This was my line of reasoning, too. Good to know :)

> Also, I gave all the details in my previous response though I know you're aware of some of them because someone else might discover this thread in the future when they want to add a feature. It's hard to get exactly the right information into the documentation or CONTRIBUTING.md that each person would need, but if I get enough information out there in the form of answering specific questions like this one, the chances are better that someone who needs it will find it.

Makes complete sense to me - there's nothing better than as-it-happened documention imo.

---

One issue with my above `ptp` implementation is that there is no "zero-overhead" way to implement an `initial` value. Although NumPy doesn't implement such a parameter for `ptp`, I think it makes more sense for Awkward where sub-arrays can be empty. We can't pull the identity out of the calls to `min` and `max` without setting `mask_identity=True`, and then running `fill_none`. Do you think it's reasonable for a reducer to call `fill_none` internally to fulfil this case?

**Comment by jpivarski** [comment]
Well, if `np.ptp` doesn't have an `initial` parameter, we don't _need_ to add one. Maybe they don't have one because it doesn't make a lot of sense in this case.

As for performance, this is already doing the `min` and `max` as separate passes, which could be more efficient as a single pass, though that would involve a whole new Reducer (C++ class), which is a lot of boilerplate.

We can't get guidance from NumPy about what to do with empty lists. By default (just subtracting) `min` and `max`, they'd be None. If it makes more sense for them to be zero, then adding a third pass with `fill_none` would be the right thing to do. It's fine for a first implementation of a feature to be less efficient than possible. If a faster version is needed, we establish the interface with this implementation and revamp it later with a specialized Reducer in the future.

**Comment by agoose77** [comment]
On the performance, the initial implementation can be *slower*, after all, `np.ptp` is also a simple difference IIRC.

This is what the above would look like:

```python
ptp = ak.max(
    arr, axis=axis, keepdims=keepdims
) - ak.min(
    arr, axis=axis, keepdims=keepdims
)
if not mask_identity:
    return ak.fill_none(ptp, initial=initial)
return ptp
```

Is it reasonable to just let `initial=0` in the `ptp` function signature?

**Comment by jpivarski** [comment]
The idea of `initial` is different from the idea of a `fill_value`. `initial` limits what min and max values `ak.min` and `ak.max` can "see"; it's literally

```python
initial = ???
for x in data:
    if x < initial:
        minimum = x
return minimum
```

So a data range can get truncated to an `initial` value even if it's not empty; if all of the values are greater than the `initial` (for `ak.min`, for instance). The `fill_value` only applies if `len(data)` is actually `0`. So the above implementation is fine, but it probably shouldn't be called `initial`. Perhaps it should be called `fill_value`, or maybe it should not even be configurable. For a "peak to peak" difference of no data, only None or zero make sense. (Zero wouldn't distinguish `len(data) == 0` from `len(data) == 1`; the latter would always have a peak-to-peak of zero.)

My preference would be to not have it be configurable. If `mask_identity` is True, then you get Nones, otherwise, you get zeros.

**Comment by agoose77** [comment]
Ah my mistake - I had thought that it was an override-able identity.  I was leaning towards letting it be non-configurable, so I'll take your preference on board.
