### ISSUE TITLE
Numba retrieves wrong value for buffers with strides

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#903]
This is a little tricky to reproduce late on a Friday. There is definitely a simpler example hiding in here somewhere
```python
@nb.njit
def get_11(record):
    return record[1].u


def test(order):
    # Create an array with either strided or contiguous columns
    table = np.zeros((2, 2), order=order)
    table[:] = np.arange(2  * 2).reshape(table.shape)

    record = ak.zip({"u": table[..., 0]})

    r1 = record[1].u
    r2 = get_11(record)

    assert r1 == r2, (r1, r2)


test(order="F")
test(order="C")
```

**Comment by agoose77** [comment]
It looks like the issue is probably the `NumpyArray` has both strides set and an already-strided copy of the data:
```pycon
>>> layout = ak.from_numpy(table[..., 0], highlevel=False)
>>> layout
<NumpyArray format="d" shape="2" strides="16" data="0 2" at="0x0000055575d0"/>
```
Perhaps this is just a wild goose chase, though; the data repr might just be wrong. Especially given that this *only* fails inside Numba.

**Comment by agoose77** [comment]
The `strides` value does not agree inside the numba function vs outside.

**Comment by agoose77** [comment]
The line in question is https://github.com/scikit-hep/awkward-1.0/blob/cb24e1b0a9c6ab6c10199f1db40035e55c35c7ab/src/awkward/_connect/_numba/arrayview.py#L1231-L1235, just need to work out what's going on here :)

**Comment by agoose77** [comment]
@jpivarski I think I've hit a wall with how much I understand about Numba + Awkward Numba. I'm not entirely clear whose responsibility it is to pass in the strides; I think we might need to add a `strides` field to the ArrayViewType, but I'm not confident on that!

**Comment by jpivarski** [comment]
You're right: the strides are assumed to be C-contiguous, which makes the for-loop steps constant for compiler optimization. But it went bad because they were just _assumed_ to be contiguous, not forced to be. Here's a simpler test case:

```python
    @numba.njit
    def f1(x):
        return x[0], x[1]

    array = ak.Array(np.arange(4).reshape(2, 2)[:, 0])

    assert f1.py_func(array) == (0, 2)
    assert f1(array) == (0, 2)   # would be (0, 1) with the bug
```

The spot that you located is in the lowering of the `np.asarray` function: changing that would only affect that one function (and the actual strides are not known at that point in the code!). That wouldn't have done it.

Instead, we should use `nplike.ascontiguousarray` instead of `nplike.asarray` when the array is converted into an ArrayView. This happens only once and is cached. Performance will be better for C-contiguous arrays because other arrays have to be converted into C-contiguous, but most arrays are C-contiguous, and we get to apply this compiler optimization (constant strides).

Thanks for looking into it! The Numba lowering is admittedly hard to read because it was so heavily optimized (e.g. all that pointer arithmetic).
