### ISSUE TITLE
`ak.values_astype` could support dtype specifier `np.datetime64` to convert `?int` or `?float` typed unix timestamps to `datetime`

### ISSUE THREAD

**Issue by drahnreb** [scikit-hep/awkward#909]
(Possible extension to #835)

While this works:
```python
>>> arr = ak.Array(['2019-09-02T09:30:00',  None])
>>> ak.strings_astype(arr, np.datetime64)
<Array [2019-09-02T09:30:00.000, None] type='2 * ?datetime'>
```

`ak.values_astype` **could** be extended to convert values not only to new numeric but also datetime type (if I remember correctly, that function is originally not meant for anything else than numeric values).
```python
ak.values_astype(ak.Array([1567416600000]), np.datetime64)
```

**Comment by ianna** [comment]
@jpivarski - I'll have a look - it shouldn't be too difficult to implement.

**Comment by ianna** [comment]
@drahnreb and @jpivarski - It looks like most packages I looked at have a default unit for an integer value since epoch - `pyarrow`, for example uses `ms`, `pandas` - `ns`. If **no unit** is passed to a function, it is assumed that the integer value is given in these default units. 

`np.datetime64` is ambiguous. We should be able to specify units. Please, let me know if you have any suggestions?

**Comment by jpivarski** [comment]
Quick note on Arrow, since I looked into it yesterday: they have a different default unit depending on whether the type is 32-bit or 64-bit!

```python
>>> pyarrow.date32()
DataType(date32[day])
>>> pyarrow.date64()
DataType(date64[ms])
```

NumPy's datetime/timedelta dtypes have units, the corresponding Python type does not.

```python
>>> np.dtype("M8[s]")
dtype('<M8[s]')
>>> np.dtype("M8[s]").type
<class 'numpy.datetime64'>

>>> np.dtype("M8[ns]")
dtype('<M8[ns]')
>>> np.dtype("M8[ns]").type
<class 'numpy.datetime64'>
```

As a Python type (`np.datetime64`), the unit information is stored in the Python _value_, rather than the type.

```python
>>> np.datetime64(5, "s")
numpy.datetime64('1970-01-01T00:00:05')
>>> np.datetime64(5, "ns")
numpy.datetime64('1970-01-01T00:00:00.000000005')
```

But that's not possible for arrays of values (and you'd want it to be constant across an array), so there has to be this dtype/type distinction.

When a user passes something (string, type, whatever) to the argument of `ak.values_astype`, it gets converted into a NumPy dtype, partly to ensure that that's possible before getting too deep into the code. After that regularization step, the object is a dtype and must have a unit.

Ah, I see: this is the problem.

```python
>>> np.dtype(np.datetime64)
dtype('<M8')
```

Simply passing the type to the dtype constructor doesn't give it a unit. Still, there must be some unit assumed. Let me see...

```python
>>> np.array([1, 2, 3], dtype=np.dtype(np.datetime64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Converting an integer to a NumPy datetime requires a specified unit
>>> np.array([1, 2, 3], dtype=np.datetime64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Converting an integer to a NumPy datetime requires a specified unit
>>> dir(np.dtype(np.datetime64))
```

I was going to try to learn the unit from some examples, but NumPy isn't letting me construct examples. As such, we can refuse to admit datetime/timedelta dtypes without units for the same reasons.

When you use NumPy's `astype` with a datetime without units, it just doesn't change the units.

```python
>>> np.array([1, 2, 3], "M8[D]")
array(['1970-01-02', '1970-01-03', '1970-01-04'], dtype='datetime64[D]')
>>> np.array([1, 2, 3], "M8[D]").astype("M8[s]")
array(['1970-01-02T00:00:00', '1970-01-03T00:00:00',
       '1970-01-04T00:00:00'], dtype='datetime64[s]')
>>> np.array([1, 2, 3], "M8[D]").astype("M8")
array(['1970-01-02', '1970-01-03', '1970-01-04'], dtype='datetime64[D]')
>>> np.array([1, 2, 3], "M8[D]").astype(np.datetime64)
array(['1970-01-02', '1970-01-03', '1970-01-04'], dtype='datetime64[D]')
```

We can't do that because we don't know how deep it's going to be, unless we implement this logic in the NumpyArray class (in C++). That's the only place where we'd know what the current unit is, in order to not change it.

```python
>>> np.array([1, 2, 3]).astype("M8[D]")
array(['1970-01-02', '1970-01-03', '1970-01-04'], dtype='datetime64[D]')
>>> np.array([1, 2, 3]).astype("M8")
ValueError: Cannot convert a NumPy datetime value other than NaT with generic units
>>> np.array([1, 2, 3]).astype(np.datetime64)
ValueError: Cannot convert a NumPy datetime value other than NaT with generic units
```

Yeah, the only valid case where a unitless datetime/timedelta (I haven't explicitly checked the timedeltas!) is when you're changing a type that is already a datetime/timedelta, which is to say, when it's not changing at all. That's not a very interesting/useful case. We can require the dtypes to have units.

**Comment by drahnreb** [comment]
Yes, a datetime coercion would need to include units but the python type objects `np.datetime64` are unitless (generic datetimes that only work on `NaT` e.g. `np.array('NaT', dtype=np.datetime64)`) until further specified as numpy dtypes.
Numpy stores this time unit in the metadata (in the original [PEP 4](https://numpy.org/neps/nep-0004-datetime-proposal3.html) it used to be implemented in the metadata property of a `np.dtype('m8[ns]').metadata` that is `None` in my case and moved to the .name/.str props...) to complement datetime dtypes in their expressiveness without changing the underlying structure.

Both short string notations ought to default to `[us]` as unit:
`M{m}8` is equivalent to `M{m}8[us]`.

Additionally, you can set the units of datetimes/timedeltas with the _long string notation_ (I use `'timedelta64[ns]'` here, but they have coherent behavior in numpy):
```python
>>> np.dtype('m8[ns]').name
'timedelta64[ns]'
>>> np.dtype('timedelta64[ns]')
dtype('<m8[ns]')
>>> type(np.dtype('<m8[ns]')) is type(np.dtype('m8[ns]')) is type(np.dtype('timedelta64[ns]'))
True

# np.core._multiarray_umath.DATETIMEUNITS  # NULL PyCapsule obj, unfortunately the C++ enum doesn't get broadcasted into python space
# business days 'B' are deprecated:
>>> np_base_units = ("Y", "M", "W", "D", "h", "m", "s", "ms", "us", "ns", "ps", "fs", "as")
>>> [np.array([1]).astype(f'timedelta64[{unit}]') for unit in np_base_units]
[array([1], dtype='timedelta64[Y]'),
 array([1], dtype='timedelta64[M]'),
 array([1], dtype='timedelta64[W]'),
 array([1], dtype='timedelta64[D]'),
 array([1], dtype='timedelta64[h]'),
 array([1], dtype='timedelta64[m]'),
 array([1], dtype='timedelta64[s]'),
 array([1], dtype='timedelta64[ms]'),
 array([1], dtype='timedelta64[us]'),
 array([1], dtype='timedelta64[ns]'),
 array([1], dtype='timedelta64[ps]'),
 array([1], dtype='timedelta64[fs]'),
 array([1], dtype='timedelta64[as]')]

>>> [np.array([1]).astype(f'datetime64[{unit}]') for unit in np_base_units]
[array(['1971'], dtype='datetime64[Y]'),
 array(['1970-02'], dtype='datetime64[M]'),
 array(['1970-01-08'], dtype='datetime64[W]'),
 array(['1970-01-02'], dtype='datetime64[D]'),
 array(['1970-01-01T01'], dtype='datetime64[h]'),
 array(['1970-01-01T00:01'], dtype='datetime64[m]'),
 array(['1970-01-01T00:00:01'], dtype='datetime64[s]'),
 array(['1970-01-01T00:00:00.001'], dtype='datetime64[ms]'),
 array(['1970-01-01T00:00:00.000001'], dtype='datetime64[us]'),
 array(['1970-01-01T00:00:00.000000001'], dtype='datetime64[ns]'),
 array(['1970-01-01T00:00:00.000000000001'], dtype='datetime64[ps]'),
 array(['1970-01-01T00:00:00.000000000000001'], dtype='datetime64[fs]'),
 array(['1970-01-01T00:00:00.000000000000000001'], dtype='datetime64[as]')]
```

As a side note (I barely used it): modulo event-units  can also be combined with any derived units and both dtypes in long and short notation:
```python
>>> np.array([1]).astype('m8[10s/2]')
array([1], dtype='timedelta64[5000ms]')
>>> np.array([1]).astype('datetime64[100as/1]')
array(['1970-01-01T00:00:00.000000000000000100'],
      dtype='datetime64[100as]')

```

**Comment by ianna** [comment]
@drahnreb - Could you, please, check https://github.com/scikit-hep/awkward-1.0/pull/916? Thanks.

**Comment by drahnreb** [comment]
> @drahnreb - Could you, please, check #916? Thanks.

Great, lgtm. Thanks, @ianna!
