### ISSUE TITLE
Merging list-types unnecessarily changes layout

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#939]
This issue has been refiled as I've understood the cause better.

The list types simplify the act of merging by simplifying to the most generic type (`ListArray64`). Not only is it more generic, it also supports different contents, which means we don't need to check whether contents are mergeable (although this is subsequently done to simplify the type).

This behaviour has implications for operations that expect / require the layout types to remain identical for "compatible" layouts e.g. `ak.partitioned`.

In theory, it should be possible to first try and merge the contents. If this works, then we should be able to retain the same family of list type. 

What I would like is something more like this:
```python3
def merge_list_offset(this, that):
    this = this.toListOffsetArray64(True)
    that = that.toListOffsetArray64(True)

    content = merge(this.content[: len(this)], that.content[: len(that)])
    index = ak.layout.Index64(
        np.concatenate(
            (
                np.asarray(this.offsets),
                np.asarray(this.offsets)[-1] + np.asarray(that.offsets),
            )
        )
    )
    return ak.layout.ListOffsetArray64(index, content)

def merge_regular(this, that):
    if this.size == that.size:
        content = merge(this.content, that.content)
        return ak.layout.RegularArray(content, this.size)

    return merge(this, that)

def merge_record(this, that):
    new_content = [merge(a, b) for a, b in zip(this.contents, that.contents)]
    return ak.layout.RecordArray(new_content, this.recordlookup, len(this))

SYMMETRIC_TABLE = {
    ak.layout.ListOffsetArray64: merge_list_offset,
    ak.layout.RegularArray: merge_regular,
    ak.layout.NumpyArray: lambda this, that: this.merge(that),
    ak.layout.RecordArray: merge_record,
}

def merge(this, that):
    this = ak.packed(this, highlevel=False)
    that = ak.packed(that, highlevel=False)

    assert this.mergeable(that)
    if (merge_symmetric := SYMMETRIC_TABLE.get(type(this))) and isinstance(
        that, type(this)
    ):
        return merge_symmetric(this, that)

    raise NotImplementedError(f"merge({type(this)}, {type(that)}")
```

Is this something that we're planning on moving to the Python layer anyway?

**Comment by jpivarski** [comment]
Partitions don't have to have the same form, but they do have to have the same type. If one partition is a ListOffsetArray same the next is a ListArray, that ought to be okay for everything downstream. Mixing either of these list node types with RegularArray is not okay, and if it was doing that, that would be a bug.

A lot of the PartitionedArray code is already in Python, largely because it was true last to be written. It does have a C++ part, but the C++ part is used minimally, almost all of the operations (including repartition,I think) is implemented in src/awkward/partition.py.

**Comment by agoose77** [comment]
> Positions don't have to have the same form, but they do have to have the same type. If one partition is a ListOffsetArray same the next is a ListArray, that ought to be okay for everything downstream. Mixing either of these list node types with RegularArray is not okay, and if it was doing that, that would be a bug.


I'll check the finer grained cases here and report back.

> It does have a C++ part, but the C++ part is used minimally, almost all of the operations (including repartition,I think) is implemented in src/awkward/partition.py.

Right I observed the same. So, is the plan to lift existing C++ layouts into the Python layer and leave just the kernels at the C++ level?

**Comment by jpivarski** [comment]
> Right I observed the same. So, is the plan to lift existing C++ layouts into the Python layer and leave just the kernels at the C++ level?

That's exactly right, though I would refer to the kernels level as "mostly C" because the ABI is `extern C` and the only C++ feature they use is function templates for integer specialization (something that could have been a C macro, but it's safer as a template). So the current 3-layer structure is C → C++ → Python and the Awkward 2.0 structure is C → Python → Python. Since both of the last two levels are Python, they may merge, losing their distinctive identity.

The conceptual distinction between the middle and high layers (currently C++ and Python) is weak, especially for partitioned arrays. The original intention was for the high-level layer to be a thin wrapper around the middle layer, but it was so much effort to add C++ methods that we added a lot of functionality in the Python layer directly, especially for partitioned arrays. Instead of translating the C++ `ak._ext.PartitionedArray` and `ak._ext.IrregularlyPartitionedArray` classes to Python, we'll just merge their functionality (which isn't much) directly into the Python `ak.partition.PartitionedArray` and `ak.partition.IrregularlyPartitionedArray`. Partitioning is decoupled from everything else because they are (deliberately) not subclasses of Content, so we have more freedom to make them strictly two-level: C → Python. That can even happen independently of or before the general Awkward 2.0 transition.

**Comment by agoose77** [comment]
This was really informative. Thanks Jim, things are clearer now.

**Comment by jpivarski** [comment]
This is moot because PartitionedArray won't be ported to v2.
