### ISSUE TITLE
`_packed` negative axes aren't handled properly for unions

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#969]
When `_packed` is given a negative axis for a layout that doesn't return a positive value in `wrap_axis_if_negative`, it actually bails early:
https://github.com/scikit-hep/awkward-1.0/blob/bec1a0d240f0e590a835a0ef70e3687624c96be5/src/awkward/operations/structure.py#L2122-L2123

What we are trying to catch here is whether the current depth is past the terminal depth, i.e. if we have gone past the deepest level we wish to operate on. This doesn't mean that deeper layouts aren't modified; the parent layout can simplify the child, but the child itself will not be simplified beyond this. 

Because this routine bails whenever `posaxis` is negative, it is "broken" for unions.

This bug is only triggered by the public API if we try to `unflatten` an array containing unions using a negative axis.

**Comment by agoose77** [comment]
@jpivarski I think the fix for this should look like

```python3
    def is_below_axis(layout, depth, axis):
        if axis >= 0:
            # Depth starts at 1
            return depth-1 > axis
        else:
            # We only consider ourselves to have passed the union depth 
            # if we cannot process any union members, i.e.
            # if `abs(axis)` is farther than the farthest leaf
            min_depth, max_depth = layout.minmax_depth
            return max_depth + axis < 0
        
    def apply(layout, depth, posaxis):
        if posaxis is not None:
            # If a particular axis was given, do not proceed past that axis
            if is_below_axis(layout, depth, posaxis):
                return layout
 ```

This is fiddly stuff, does it look right to you? The only problem here is that we don't handle the case where the initial layout is not deep enough; `is_below_axis` (by design) returns `True` (and doesn't raise an `Exception`) for any axis ~ ∞. I could add a check outside of the recursion that axis does not exceed the `max_depth` of the outer layout.

Alternatively, we drop the `axis` parameter. I don't know whether this is a good idea - the fix doesn't seem complicated, and I think we might benefit from not over simplifying. But, perhaps simpler is better?

**Comment by agoose77** [comment]
To explain the above modified code snippet, consider this example:
```python3
layout = ak.layout.ListOffsetArray64(
    ak.layout.Index64(np.r_[1, 3]),
    ak.layout.UnionArray8_64(
        ak.layout.Index8(np.r_[0, 1, 0, 1]),
        ak.layout.Index64(np.r_[0, 0, 1, 1]),
        [
            ak.layout.ListOffsetArray64(
                ak.layout.Index64(np.r_[1, 4, 8]), ak.layout.NumpyArray(np.arange(128))
            ),
            ak.layout.ListOffsetArray64(
                ak.layout.Index64(np.r_[1, 3, 5]),
                ak.layout.ListOffsetArray64(
                    ak.layout.Index64(np.r_[1, 3, 6, 9, 12, 16, 18, 25]),
                    ak.layout.NumpyArray(np.arange(64) - 32),
                ),
            ),
        ],
    ),
)
```
For `axis=2`, the effective depth is actually `depth=3`. When walking the tree, we wait until we hit that depth

* `ListOffsetArray64(depth=1)`
   * `UnionArray8_64(depth=2)` 
   * `ListOffsetArray64(depth=2)`
      * `NumpyArray(depth=3)`
   * `ListOffsetArray64(depth=2)`
      * `ListOffsetArray64(depth=3)`
         * ~~`NumpyArray(depth=4)`~~
      
and then stop processing. This means that the final `NumpyArray(depth=4)` is not processed.
For negative axes, the behaviour is different - we work backwards from the leaves. This means that for `axis=-2` we see:
* `ListOffsetArray64(depth=1, neg_depth=?)`
   * `UnionArray8_64(depth=2, neg_depth=?)` 
   * `ListOffsetArray64(depth=2, neg_depth=-2)`
      * ~~`NumpyArray(depth=3, neg_depth=-1)`~~
   * `ListOffsetArray64(depth=2, neg_depth=-3)`
      * `ListOffsetArray64(depth=3, neg_depth=-2)`
         * ~~`NumpyArray(depth=4, neg_depth=-1)`~~

i.e. we don't process the leaves at `neg_depth=-1`.

**Comment by jpivarski** [comment]
(I'm thinking this through; chances are I'm saying stuff you already know or have already figured out...)

`ak.packed` doesn't have an `axis` for simplicity—because of what the function does, I don't think anyone would ever want to pack only one dimension. So this is only about the internal `_packed`, which is used by `ak.unflatten`.

An `axis` shouldn't be considered valid on a UnionArray unless it can be used in some way by every `content` in that union. Your examples have a list-type in the first `content` and a list-list-type in the second `content`, so the second should be able to take one more possible negative `axis` than the first. That is, if the `axis` of the function refers to a numeric level, the first could take `axis=-1` and `axis=-2` and the second could take `axis=-1`, `axis=-2`, and `axis=-3`. If the function's `axis` refers to a point between dimensions, like where to put the new counts in `ak.unflatten`, then it would be just `axis=-1` for the first and `axis=-1` or `axis=-2` for the second.

The `depth` counts up from the bottom, so `depth` is either equal to the negation of a negative `axis` or off by one (consistently). Since `minmax_depth` gives you both the minimum and maximum and the UnionArray has to work for _all_ `content` branches, I think it's the _minimum_ that you want to compare against a negated `axis`, not the maximum, as in your code example. When you ask for `minmax_depth` of a UnionArray, the minimum is the one that's more restrictive in what negative axes are allowed.

I'll try drawing one of these diagrams, too:

```
                               min max depth   allowed axis?
------------------------------------------------------------
list-type                      3   4           0 (only)
│
└── union-type                 2   3           none!
    │
    ├── list-type              2   2           1, -2
    │   └── numeric-type       1   1           2, -1
    │
    └── list-type              3   3           1, -3
        └── list-type          2   2           2, -2
            └── numeric-type   1   1           3, -1
```

I'm confident about the `minmax_depth` values because I computed them in a terminal. That's just what you get when you call the function. I'm uncertain about the "allowed axis?" column—what I've written is my intuition about what should happen, but it could be different for different kinds of functions (some apply _at_ a dimension and others apply _above_ a dimension) and I couldn't find any examples of functions that work! UnionArrays break a lot of functionality. If there is some function that successfully passes an `axis` through a UnionArray, I don't know offhand which it is. RecordArrays and negative `axis` generally work.

But anyway, the "allowed axis?" column represents the theory: negative `axis` should count up from the bottom and as such, it can be different in different branches of a UnionArray or RecordArray (the only two layout types that can have more than one `content`). If it's ever ambiguous, it's not allowed, so a negative axis can't be applied above a split-point with different depths.

I'm starting to remember—it might have been an across-the-board decision to make negative `axis` never work through UnionArrays. Unions are different from records because in a RecordArray, every element of the array has all branches, but in a UnionArray, each array element has one of the possible branches. I think that the decision was that interpreting `axis` differently on an array element-by-array element basis was too subtle/not understandable enough to be a good policy. Maybe you shouldn't work so hard to get this one to accept negative `axis`.

**Comment by agoose77** [comment]
Thanks for the detailed reply, the diagram is much clearer than mine. You're correct that this *does not* matter for `ak.packed`, only `ak.unflatten` (because we choose to optimise the case).

This entire issue is really about the fact that neither positive nor negative axes are well defined for layouts with unions containing differing numbers of list type layouts. I made a decision in the original implementation & this issue. In my mind, there are really two separate problems:

## What negative axes "mean" (in general)
I wasn't aware that we deliberately disallow ambiguous allowed axes. This makes sense, and changes the interpretation of `minmax`. I was using `max_depth` because we are using negative depths whilst traversing the tree from the root. In this way, I interpret the meaning of negative axes for `_packed` to be 

> pack each layout until we reach the given axis, and then stop. 

With this interpretation, we expect any layout which contains some `content` that has sufficient depth (`max_depth`) to be visited, which is why I use `max_depth` in the condition.

The question is whether this interpretation is valid. Effectively, unions with (`min != max`) contents require us to choose whether out-of-bounds axes (e.g. an `axis` which is too large for one union content, but is valid for another, or an `axis` which is too negative for one content, but not the other) are legal or not. In the case of `_packed`, I think this is an oversight of mine - I arbitrarily chose negative depths to be interpreted in terms of the deepest branch, but one could equally take the minimum. 
Perhaps it is better to consider only the minimum, in the same way that one treats the positive case (as you suggest).

## How `_packed` should be fixed
`_packed` takes an axis so that it can prepare an array for `unflatten`. This function is different to many of the other Awkward functions that take axes, because it operates *above* the given axis, which makes the above ambiguity a problem. 

What we *want* to happen is that each layout is packed as it is visited on our way to unflattening at a given depth. Then we defer the meaning of `axis` to that which is defined for `unflatten`. I think this is the right solution. Either we move the recursion from `_packed` into `packed`, and have `_packed` perform a single packing operation, or we replace `axis` with `depth`, which defines the recursion depth. I think the latter is actually going to be simpler than having to implement the recursion in `packed`.

**Comment by jpivarski** [comment]
What you propose sounds like the right solution, to the extent that you need to make `ak.unflatten` work not just for data with unions, but with different list-depth unions. ("Sounds like" to the degree that I've understood it.)

If you don't have an explicit need for this case and if the solution would be hard to understand even when it works, then it may not be worthwhile. If you do decide that it's not worthwhile, at least it should raise a good error message.

**Comment by agoose77** [comment]
I think we're on the same page. Having taken a step back, unpacking above a depth really only makes sense for root-defined axes (aka depths) rather than allowing negative axes, so removing that feature isn't really a problem from a doing-it-the-right-way perspective.
