### ISSUE TITLE
Meta: use GitHub Issue Forms

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#986]
GitHub now provides the ability to define Issue Forms, which establish a structured, validated form for creating Issues.

[Here](https://github.com/agoose77/test-issue-syntax/issues/new?assignees=&labels=bug+%28unverified%29&template=bug-report.yaml&title=Bug) is an example form for Awkward.

Do you think this would be a useful addition?

**Comment by jpivarski** [comment]
Possibly. I've been thinking that since I saw a form on another repo. Some of our issue templates have text for the user to read, which must be deleted when writing the actual issue. A form would separate that text from the text box where the user writes, and trust would be somewhat cleaner, probably easier to read.

**Comment by henryiii** [comment]
It also allows you to add the triple tick marks and language highlighting or traceback highlighting automatically. :)

**Comment by agoose77** [comment]
It also adds drop downs!

**Comment by henryiii** [comment]
The textbox with the `pytb` setting actually uses a monospace font, very nice attention to detail.
